import { useEffect, useId, useState } from "react";
import { createPortal } from "react-dom";
import type { Sketch } from "@nexus/core";
import { Button } from "@nexus/ui";

import { strings } from "./strings.js";
import { useFocusTrap } from "./useFocusTrap.js";

export interface ElecSketchDialogProps {
  /** Generated by the renderer for this preview; main regenerates its own before writing. */
  sketch: Sketch;
  /** How many `error`-severity findings the checks panel is showing right now. */
  errors: number;
  busy: boolean;
  /** Opens the native save dialog. Absent from a refusal, which has no file to write. */
  onSave: () => void;
  onClose: () => void;
}

/**
 * The generated Arduino sketch, on screen before it is on disk (ADR-085 E4).
 *
 * **The preview and the file are generated by two different processes, on
 * purpose.** `generateSketch` is pure and lives in `@nexus/core`, so the
 * renderer calls it to show this and main calls it again to write the `.ino` —
 * the renderer never hands main a string to save, because a file on the user's
 * machine should be the circuit as stored rather than as a renderer described
 * it (SEC-EL, and the reason `elec:export-sketch` takes an id and nothing
 * else). The two agree because they are the same function over the same rows.
 *
 * **A refusal opens the dialog too.** „There is no board in this circuit" is a
 * true and useful sentence, and a disabled button with no explanation is the
 * one thing worse than saying it: the user cannot tell a considered refusal
 * from a broken control. What the refusal removes is the save button, not the
 * dialog.
 *
 * **The wiring table comes before the code,** and is what `Sketch.connections`
 * exists for. The same rows are in the file's header comment, but a person
 * holding a jumper wants „D10 → HC-SR04 · TRIG" as a row of a table, not as a
 * line they have to find inside a C comment.
 *
 * Same house recipe as the shortcuts reference — backdrop and panel as
 * siblings, Escape and the backdrop close, focus trapped and handed back, and
 * the body scrolls rather than the panel growing past the window.
 */
export function ElecSketchDialog({
  sketch,
  errors,
  busy,
  onSave,
  onClose,
}: ElecSketchDialogProps) {
  const s = strings.electronics.sketch;
  const titleId = useId();
  const [copied, setCopied] = useState(false);

  const panelRef = useFocusTrap<HTMLDivElement>({ open: true });

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        onClose();
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [onClose]);

  async function copy(): Promise<void> {
    if (sketch.kind !== "sketch") return;
    try {
      await navigator.clipboard.writeText(sketch.source);
      setCopied(true);
    } catch (error) {
      console.error("Nexus: failed to copy the sketch:", error);
    }
  }

  return createPortal(
    <div className="recur-dialog__overlay">
      <div className="recur-dialog__backdrop" onClick={onClose} />
      <div
        ref={panelRef}
        className="recur-dialog__panel elec-sketch__panel"
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
      >
        <h2 id={titleId} className="recur-dialog__title">
          {s.dialogTitle}
        </h2>

        {sketch.kind === "refused" ? (
          <p className="elec-sketch__refused">{s.refused[sketch.reason]}</p>
        ) : (
          <div className="elec-sketch__body">
            <p className="elec-sketch__description">{s.description}</p>

            {sketch.libraries.length > 0 && (
              <section className="elec-sketch__section">
                <h3 className="nx-eyebrow elec-sketch__heading">{s.librariesHeading}</h3>
                <ul className="elec-sketch__libraries">
                  {sketch.libraries.map((library) => (
                    <li key={library} className="elec-sketch__library">
                      {library}
                    </li>
                  ))}
                </ul>
                <p className="elec-sketch__hint">{s.librariesHint}</p>
              </section>
            )}

            {sketch.connections.length > 0 && (
              <section className="elec-sketch__section">
                <h3 className="nx-eyebrow elec-sketch__heading">{s.wiringHeading}</h3>
                <table className="elec-sketch__table">
                  <thead>
                    <tr>
                      <th scope="col" className="nx-eyebrow">
                        {s.wiringPin}
                      </th>
                      <th scope="col" className="nx-eyebrow">
                        {s.wiringPart}
                      </th>
                      <th scope="col" className="nx-eyebrow">
                        {s.wiringConstant}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {sketch.connections.map((row, index) => (
                      // The index IS the identity: these are the rows of one
                      // generated table in the order it generated them, and a
                      // connection has no id of its own. (No `eslint-disable` —
                      // `react/no-array-index-key` belongs to a plugin this repo
                      // does not register, and ESLint 9 treats a directive naming
                      // an unknown rule as a hard error.)
                      <tr key={index}>
                        <th scope="row" className="elec-sketch__mono">
                          {row.boardPin}
                        </th>
                        <td>
                          {row.part} · {row.partPin}
                        </td>
                        <td className="elec-sketch__mono">{row.constant ?? s.wiringUnnamed}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {sketch.connections.some((row) => row.constant === undefined) && (
                  <p className="elec-sketch__hint">{s.wiringHint}</p>
                )}
              </section>
            )}

            <section className="elec-sketch__section">
              <h3 className="nx-eyebrow elec-sketch__heading">
                {s.sourceHeading}
                <span className="elec-sketch__filename">{sketch.filename}</span>
              </h3>
              {errors > 0 && (
                <p className="elec-sketch__warning" role="status">
                  {s.hasErrors}
                </p>
              )}
              <pre className="elec-sketch__source">{sketch.source}</pre>
            </section>
          </div>
        )}

        <div className="recur-dialog__actions">
          <Button className="recur-dialog__cancel" onClick={onClose}>
            {s.close}
          </Button>
          {sketch.kind === "sketch" && (
            <>
              <Button onClick={() => void copy()}>{copied ? s.copied : s.copy}</Button>
              <Button variant="primary" disabled={busy} onClick={onSave}>
                {s.saveAs}
              </Button>
            </>
          )}
        </div>
      </div>
    </div>,
    document.body,
  );
}
