import { useEffect, useId, useState } from "react";
import { createPortal } from "react-dom";
import type { GeneratedCode, RosPackage, Sketch } from "@nexus/core";
import { Button } from "@nexus/ui";

import { strings } from "./strings.js";
import { useFocusTrap } from "./useFocusTrap.js";

export interface ElecCodeDialogProps {
  /** Generated by the renderer for this preview; main regenerates its own before writing. */
  code: GeneratedCode;
  /**
   * Whether the circuit has a machine on it (ADR-085 E4c) — the FACT, not what
   * it means for the artefact. A ROS 2 package answers that from `robot` and
   * needs no prop; a sketch has no model to carry and has to say so.
   */
  hasMachine: boolean;
  /** How many `error`-severity findings the checks panel is showing right now. */
  errors: number;
  busy: boolean;
  /** Opens the native dialog. Absent from a refusal, which has nothing to write. */
  onSave: () => void;
  onClose: () => void;
}

/**
 * The generated code, on screen before it is on disk (ADR-085 E4).
 *
 * **The preview and the file are generated by two different processes, on
 * purpose.** `generateCode` is pure and lives in `@nexus/core`, so the renderer
 * calls it to show this and main calls it again to write — the renderer never
 * hands main a string to save, because a file on the user's machine should be
 * the circuit as stored rather than as a renderer described it (SEC-EL, and the
 * reason `elec:export-code` takes an id and nothing else). The two agree
 * because they are the same function over the same rows.
 *
 * **One dialog for two artefacts, and no branch above this file.** Which one a
 * circuit gets is a fact about its board, so the page opens „Kod" and this
 * switches on `code.kind`. The chrome, the actions and the refusal copy are
 * shared because they are the same in both; only the tables differ, because the
 * artefacts do.
 *
 * **A refusal opens the dialog too.** „There is no board in this circuit" is a
 * true and useful sentence, and a disabled button with no explanation is the
 * one thing worse than saying it: the user cannot tell a considered refusal
 * from a broken control. What the refusal removes is the save button, not the
 * dialog.
 *
 * Same house recipe as the shortcuts reference — backdrop and panel as
 * siblings, Escape and the backdrop close, focus trapped and handed back, and
 * the body scrolls rather than the panel growing past the window.
 */
export function ElecCodeDialog({
  code,
  hasMachine,
  errors,
  busy,
  onSave,
  onClose,
}: ElecCodeDialogProps) {
  const s = strings.electronics.code;
  const titleId = useId();
  const [copied, setCopied] = useState(false);

  const panelRef = useFocusTrap<HTMLDivElement>({ open: true });

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        onClose();
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [onClose]);

  const source = sourceOf(code);

  async function copy(): Promise<void> {
    if (source === null) return;
    try {
      await navigator.clipboard.writeText(source);
      setCopied(true);
    } catch (error) {
      console.error("Nexus: failed to copy the generated code:", error);
    }
  }

  return createPortal(
    <div className="recur-dialog__overlay">
      <div className="recur-dialog__backdrop" onClick={onClose} />
      <div
        ref={panelRef}
        className={`recur-dialog__panel elec-code__panel${
          code.kind === "package" ? " elec-code__panel--wide" : ""
        }`}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
      >
        <h2 id={titleId} className="recur-dialog__title">
          {titleFor(code)}
        </h2>

        {code.kind === "refused" ? (
          <p className="nx-hint nx-hint--prose">{s.refused[code.reason]}</p>
        ) : (
          <div className="elec-code__body">
            {code.kind === "sketch" ? (
              <SketchBody sketch={code} hasMachine={hasMachine} errors={errors} />
            ) : (
              <PackageBody rospkg={code} errors={errors} />
            )}
          </div>
        )}

        <div className="recur-dialog__actions">
          <Button className="recur-dialog__cancel" onClick={onClose}>
            {s.close}
          </Button>
          {code.kind !== "refused" && (
            <>
              <Button onClick={() => void copy()}>{copied ? s.copied : s.copy}</Button>
              <Button variant="primary" disabled={busy} onClick={onSave}>
                {s.saveAs}
              </Button>
            </>
          )}
        </div>
      </div>
    </div>,
    document.body,
  );
}

/**
 * The dialog's heading, which names the ARTEFACT — and cannot, for a refusal.
 *
 * A refusal falls back to the button's own word rather than to either artefact
 * name: „U kolu je više ploča" under the heading „Arduino skica" is a heading
 * about a file that does not exist, and on a circuit holding two Raspberry Pis
 * it is a heading about the wrong toolchain as well.
 */
function titleFor(code: GeneratedCode): string {
  const s = strings.electronics.code;
  if (code.kind === "sketch") return s.sketch.dialogTitle;
  if (code.kind === "package") return s.ros.dialogTitle;
  return s.open;
}

/**
 * The text „Kopiraj" puts on the clipboard.
 *
 * For a package that is the NODE and not the eight files concatenated: the
 * other seven are the ament shape, they mean nothing pasted into a chat, and
 * the one a person wants to show someone is `wiring.py`. `null` for a refusal,
 * which never renders the button at all, and — belt and braces — for a package
 * with no node in it, which `renderPackage` cannot produce.
 */
function sourceOf(code: GeneratedCode): string | null {
  if (code.kind === "sketch") return code.source;
  if (code.kind === "refused") return null;
  return code.files.find((file) => file.path.endsWith("/wiring.py"))?.contents ?? null;
}

/** The warning above the code, shared because it is about the CIRCUIT either way. */
function ErrorsNotice({ errors }: { errors: number }) {
  if (errors === 0) return null;
  return (
    <p className="elec-code__warning" role="status">
      {strings.electronics.code.hasErrors}
    </p>
  );
}

function SketchBody({
  sketch,
  hasMachine,
  errors,
}: {
  sketch: Extract<Sketch, { kind: "sketch" }>;
  hasMachine: boolean;
  errors: number;
}) {
  const s = strings.electronics.code.sketch;
  return (
    <>
      <p className="nx-hint nx-hint--prose">{s.description}</p>

      {sketch.libraries.length > 0 && (
        <section className="elec-code__section">
          <h3 className="nx-eyebrow elec-code__heading">{s.librariesHeading}</h3>
          <ul className="elec-code__libraries">
            {sketch.libraries.map((library) => (
              <li key={library} className="elec-code__library">
                {library}
              </li>
            ))}
          </ul>
          <p className="elec-code__hint">{s.librariesHint}</p>
        </section>
      )}

      {sketch.connections.length > 0 && (
        <section className="elec-code__section">
          <h3 className="nx-eyebrow elec-code__heading">{s.wiringHeading}</h3>
          <table className="elec-code__table">
            <thead>
              <tr>
                <th scope="col" className="nx-eyebrow">
                  {s.wiringPin}
                </th>
                <th scope="col" className="nx-eyebrow">
                  {s.wiringPart}
                </th>
                <th scope="col" className="nx-eyebrow">
                  {s.wiringConstant}
                </th>
              </tr>
            </thead>
            <tbody>
              {sketch.connections.map((row, index) => (
                // The index IS the identity: these are the rows of one generated
                // table in the order it generated them, and a connection has no
                // id of its own. (No `eslint-disable` — `react/no-array-index-key`
                // belongs to a plugin this repo does not register, and ESLint 9
                // treats a directive naming an unknown rule as a hard error.)
                <tr key={index}>
                  <th scope="row" className="elec-code__mono">
                    {row.boardPin}
                  </th>
                  <td className="elec-code__wrap">
                    {row.part} · {row.partPin}
                  </td>
                  <td className="elec-code__mono">{row.constant ?? s.wiringUnnamed}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {sketch.connections.some((row) => row.constant === undefined) && (
            <p className="elec-code__hint">{s.wiringHint}</p>
          )}
        </section>
      )}

      {/*
        The machine, when there is one and this artefact cannot carry it
        (ADR-085 E4c). The model is a FILE OF THE ROS 2 PACKAGE, so a board that
        gets a sketch gets no model — and the chassis form has already told the
        user their numbers go into one. Printed here rather than left to be
        noticed by its absence, which is the same reason the package prints its
        own refusal instead of hiding the section.
      */}
      {hasMachine && (
        <section className="elec-code__section">
          <h3 className="nx-eyebrow elec-code__heading">{s.machineHeading}</h3>
          <p className="elec-code__hint">{s.machineNone}</p>
        </section>
      )}

      <section className="elec-code__section">
        <h3 className="nx-eyebrow elec-code__heading">
          {s.sourceHeading}
          <span className="elec-code__filename">{sketch.filename}</span>
        </h3>
        <ErrorsNotice errors={errors} />
        <pre className="elec-code__source">{sketch.source}</pre>
      </section>
    </>
  );
}

function PackageBody({
  rospkg,
  errors,
}: {
  rospkg: Extract<RosPackage, { kind: "package" }>;
  errors: number;
}) {
  const s = strings.electronics.code.ros;
  const node = rospkg.files.find((file) => file.path.endsWith("/wiring.py"));
  const rest = rospkg.files.filter((file) => file !== node);

  return (
    <>
      <p className="nx-hint nx-hint--prose">{s.description}</p>

      {rospkg.pins.length > 0 && (
        <section className="elec-code__section">
          <h3 className="nx-eyebrow elec-code__heading">{s.topicsHeading}</h3>
          <div className="elec-code__scroll">
            <table className="elec-code__table">
              <thead>
                <tr>
                  <th scope="col" className="nx-eyebrow">
                    {s.topicTopic}
                  </th>
                  <th scope="col" className="nx-eyebrow">
                    {s.topicMessage}
                  </th>
                  <th scope="col" className="nx-eyebrow">
                    {s.topicRole}
                  </th>
                  <th scope="col" className="nx-eyebrow">
                    {s.topicPin}
                  </th>
                  <th scope="col" className="nx-eyebrow">
                    {s.topicPart}
                  </th>
                </tr>
              </thead>
              <tbody>
                {rospkg.pins.map((pin) => (
                  <tr key={pin.topic}>
                    <th scope="row" className="elec-code__mono">
                      ~/{pin.topic}
                    </th>
                    <td className="elec-code__mono">{pin.message}</td>
                    <td>{s.roles[pin.role]}</td>
                    <td className="elec-code__mono">{pin.boardPin}</td>
                    <td className="elec-code__wrap">
                      {pin.part} · {pin.partPin}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {rospkg.skipped.length > 0 && (
        <section className="elec-code__section">
          <h3 className="nx-eyebrow elec-code__heading">{s.skippedHeading}</h3>
          <p className="elec-code__hint">{s.skippedIntro}</p>
          <table className="elec-code__table">
            <thead>
              <tr>
                <th scope="col" className="nx-eyebrow">
                  {s.topicPin}
                </th>
                <th scope="col" className="nx-eyebrow">
                  {s.topicPart}
                </th>
                <th scope="col" className="nx-eyebrow">
                  {s.skippedReason}
                </th>
              </tr>
            </thead>
            <tbody>
              {rospkg.skipped.map((row, index) => (
                // The same argument as the sketch's table above: one generated
                // list, in the order it was generated, with no id of its own.
                <tr key={index}>
                  <th scope="row" className="elec-code__mono">
                    {row.boardPin}
                  </th>
                  <td className="elec-code__wrap">
                    {row.part} · {row.partPin}
                  </td>
                  <td>{s.reasons[row.reason]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {/*
        The model of the machine (ADR-085 E4c). It is a section of this dialog
        rather than one of its own because it is a FILE OF THIS PACKAGE — the
        URDF ships inside it and colcon installs it — so a second dialog would
        be a second place to look for one artefact.

        The refusal is printed rather than the section hidden. „This circuit has
        no machine" is the reason the package has no model, and it is the only
        place that reason is said before the user opens the folder and finds no
        `urdf/`.
      */}
      <section className="elec-code__section">
        <h3 className="nx-eyebrow elec-code__heading">{s.urdfHeading}</h3>
        {rospkg.robot.kind === "refused" ? (
          <p className="elec-code__hint">{s.urdfNone}</p>
        ) : (
          <>
            <p className="nx-hint nx-hint--prose">{s.urdfIntro}</p>
            {rospkg.robot.sensors.length > 0 && (
              <>
                <h4 className="nx-eyebrow elec-code__heading">{s.urdfSensorsHeading}</h4>
                <table className="elec-code__table">
                  <thead>
                    <tr>
                      <th scope="col" className="nx-eyebrow">
                        {s.urdfSensorPart}
                      </th>
                      <th scope="col" className="nx-eyebrow">
                        {s.urdfSensorMount}
                      </th>
                      <th scope="col" className="nx-eyebrow">
                        {s.urdfSensorTopic}
                      </th>
                      <th scope="col" className="nx-eyebrow">
                        {s.urdfSensorMessage}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {rospkg.robot.sensors.map((sensor) => (
                      <tr key={sensor.link}>
                        <th scope="row" className="elec-code__wrap">
                          {sensor.part}
                        </th>
                        <td>{strings.electronics.chassis.mounts[sensor.mount]}</td>
                        <td className="elec-code__mono">~/{sensor.topic}</td>
                        <td className="elec-code__mono">{sensor.message}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                <p className="elec-code__hint">{s.urdfTopicsHint}</p>
              </>
            )}
            {rospkg.robot.skipped.length > 0 && (
              <>
                <h4 className="nx-eyebrow elec-code__heading">{s.urdfSkippedHeading}</h4>
                <table className="elec-code__table">
                  <thead>
                    <tr>
                      <th scope="col" className="nx-eyebrow">
                        {s.topicPart}
                      </th>
                      <th scope="col" className="nx-eyebrow">
                        {s.urdfSkippedReason}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {rospkg.robot.skipped.map((row, index) => (
                      // One generated list in the order it was generated, with
                      // no id of its own — the two tables above, exactly.
                      <tr key={index}>
                        <th scope="row" className="elec-code__wrap">
                          {row.part}
                        </th>
                        <td>{s.urdfReasons[row.reason]}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}
          </>
        )}
      </section>

      {node !== undefined && (
        <section className="elec-code__section">
          <h3 className="nx-eyebrow elec-code__heading">
            {s.sourceHeading}
            <span className="elec-code__filename">{node.path}</span>
          </h3>
          <ErrorsNotice errors={errors} />
          <pre className="elec-code__source">{node.contents}</pre>
          <p className="elec-code__hint">
            {s.filesRest}{" "}
            {rest.map((file) => file.path).join(" · ")}
          </p>
        </section>
      )}
    </>
  );
}
