import type { CaseFormat, RegexPartKind } from "@nexus/core/devtools/text";

/**
 * „Tekst" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 *
 * `regex.parts` and `caseConvert.formats` are each typed `satisfies
 * Record<…, string>` against the core module's own id union
 * (`RegexPartKind`, `CaseFormat`) — the core module exports those ids
 * specifically so this table can be checked exhaustive against them: a kind
 * added there and forgotten here is a compile error, not a silent blank row.
 */
export const DEVTOOLS_TEXT_SR = {
  diff: {
    left: "Levo",
    right: "Desno",
    leftPlaceholder: "Nalepi prvi tekst",
    rightPlaceholder: "Nalepi drugi tekst",
    level: "Nivo poređenja",
    levelLines: "Redovi",
    levelWords: "Reči",
    ignoreTrailing: "Zanemari razmake na kraju reda",
    ignoreAll: "Zanemari sve razmake",
    ignoreCase: "Zanemari velika i mala slova",
    context: "Redova konteksta",
    view: "Prikaz",
    viewSideBySide: "Uporedo",
    viewUnified: "Unified diff",
    added: "Dodato",
    removed: "Uklonjeno",
    identical: "Tekstovi su identični.",
    noTrailingNewline: "Poslednji red nema prelom na kraju.",
  },
  "markdown-table": {
    grid: "Tabela",
    markdown: "Markdown",
    markdownPlaceholder: "…ili nalepi Markdown tabelu ovde",
    headerPlaceholder: "Zaglavlje",
    addRow: "Dodaj red",
    addColumn: "Dodaj kolonu",
    removeRow: "Ukloni red",
    removeColumn: "Ukloni kolonu",
    align: "Poravnanje",
    alignNone: "Bez poravnanja",
    alignLeft: "Levo",
    alignCenter: "Sredina",
    alignRight: "Desno",
    lineBreakInCell:
      "Ćelija {row}·{column} sadrži prelom reda — Markdown tabela ne ume da ga zapiše.",
    extraCells: "Red {row} ima više ćelija nego zaglavlje.",
    notATable: "Ovo nije Markdown tabela.",
    edgeSpaceNote: "Razmaci na početku i kraju ćelije ne preživljavaju Markdown.",
  },
  lorem: {
    unit: "Jedinica",
    unitWords: "Reči",
    unitSentences: "Rečenice",
    unitParagraphs: "Pasusi",
    count: "Koliko",
    vocabulary: "Rečnik",
    vocabularyLatin: "Latinski",
    vocabularySerbian: "Srpski",
    classicOpening: "Počni klasičnim „Lorem ipsum“",
    classicOpeningNote:
      "Važi samo za latinski — srpski nema ustaljen početak i ne izmišljamo ga.",
    regenerate: "Osveži",
    invalidCount: "Unesi ceo broj veći od nule.",
  },
  slug: {
    input: "Tekst",
    inputPlaceholder: "npr. Đorđe Petrović",
    result: "Slug",
    transliterated: "Preslovljeno",
    separator: "Razdvajač",
    lowercase: "Sve malim slovima",
    maxLength: "Najviše znakova",
    maxLengthHint: "0 znači bez ograničenja",
    invalidMaxLength: "Unesi ceo broj nula ili veći",
    collapse: "Spoji uzastopne razdvajače",
    wordKeptWhole: "Prva reč se ne preseca, pa je rezultat duži od ograničenja.",
    empty: "Nema šta da se pretvori",
  },
  "case-convert": {
    input: "Naziv",
    inputPlaceholder: "npr. parseURLFrom2ndAPI",
    tokens: "Reči",
    tokensHint: "Ovako je naziv rastavljen pre pretvaranja",
    format: "Oblik",
    value: "Vrednost",
    formats: {
      camel: "camelCase",
      pascal: "PascalCase",
      snake: "snake_case",
      screamingSnake: "SCREAMING_SNAKE",
      kebab: "kebab-case",
      train: "Train-Case",
      dot: "dot.case",
      path: "path/case",
      sentence: "Rečenica",
      title: "Naslov",
    } satisfies Record<CaseFormat, string>,
    acronymNote: "Skraćenice se ne čuvaju velikim slovima — oblik važi za svaku reč.",
  },
  "line-tools": {
    input: "Ulaz",
    inputPlaceholder: "Nalepi redove",
    cleanupTitle: "Čišćenje",
    removeBlank: "Ukloni prazne redove",
    trim: "Skrati razmake",
    trimNone: "Ne diraj",
    trimBoth: "Sa obe strane",
    trimStart: "S početka",
    trimEnd: "S kraja",
    dedupeTitle: "Duplikati",
    dedupe: "Ukloni duplikate",
    adjacentOnly: "Samo susedne",
    caseSensitive: "Razlikuj velika i mala slova",
    orderTitle: "Redosled",
    order: "Redosled",
    orderNone: "Bez promene",
    orderSort: "Sortiraj",
    orderReverse: "Obrni",
    orderShuffle: "Izmešaj",
    sortMode: "Način",
    sortLexicographic: "Po znakovima",
    sortNatural: "Prirodno (broj kao broj)",
    sortLength: "Po dužini",
    sortCollated: "Srpski redosled",
    descending: "Opadajuće",
    numberTitle: "Numerisanje",
    number: "Numeriši",
    numberStart: "Počni od",
    numberSeparator: "Razdvajač",
    pad: "Poravnaj brojeve",
    affixTitle: "Dodaci",
    prefix: "Prefiks",
    suffix: "Sufiks",
    wrapTitle: "Prelom",
    wrap: "Prelomi",
    wrapWidth: "Širina",
    wrapNote: "Duža reč od širine ostaje cela.",
    invalidStart: "Unesi ceo broj",
    invalidWidth: "Unesi ceo broj veći od nule",
  },
  regex: {
    pattern: "Šablon",
    patternPlaceholder: "npr. (?<god>\\d{4})-(?<mes>\\d{2})",
    flags: "Zastavice",
    text: "Tekst",
    textPlaceholder: "Nalepi tekst za proveru",
    matches: "Poklapanja",
    noMatches: "Nema poklapanja.",
    index: "Pozicija",
    length: "Dužina",
    match: "Poklapanje",
    groups: "Grupe",
    namedGroups: "Imenovane grupe",
    unmatchedGroup: "nije se poklopila",
    replacement: "Zamena",
    replacementPlaceholder: "$1 · $<ime> · $&",
    preview: "Pregled",
    replacedCount: "Broj zamena",
    globalNote: "Bez zastavice g menja se samo prvo poklapanje.",
    explain: "Objašnjenje šablona",
    explainPart: "Deo",
    explainMeaning: "Značenje",
    invalid: "Šablon nije ispravan: {message}",
    nestedQuantifier:
      "Odbijeno na znaku {at}: ponavljanje grupe koja i sama ponavlja " +
      "može da zablokira aplikaciju.",
    nestedQuantifierNote:
      "Ovaj šablon ima ugnježdeno ponavljanje i može zablokirati aplikaciju (znak {at}).",
    allowAnyway: "Ipak pokreni",
    matchCap: "Prikazano prvih {count} poklapanja.",
    timeBudget: "Prekinuto — šablon je predugo tražio.",
    quantifierExact: "tačno {min} puta",
    quantifierAtLeast: "najmanje {min} puta",
    quantifierRange: "od {min} do {max} puta",
    quantifierLazy: "najkraće moguće",
    parts: {
      "anchor-start": "početak teksta",
      "anchor-end": "kraj teksta",
      "word-boundary": "granica reči",
      "not-word-boundary": "nije granica reči",
      "group-open": "grupa {group}",
      "named-group-open": "imenovana grupa „{name}“",
      "non-capturing-group-open": "grupa bez hvatanja",
      lookahead: "iza ovoga sledi",
      "negative-lookahead": "iza ovoga ne sledi",
      lookbehind: "ispred ovoga stoji",
      "negative-lookbehind": "ispred ovoga ne stoji",
      "group-close": "kraj grupe",
      alternation: "ili",
      class: "jedan znak iz skupa",
      "negated-class": "jedan znak van skupa",
      any: "bilo koji znak",
      digit: "cifra",
      "not-digit": "nije cifra",
      "word-char": "slovo, cifra ili donja crta",
      "not-word-char": "nije slovo, cifra ni donja crta",
      whitespace: "razmak",
      "not-whitespace": "nije razmak",
      backreference: "isto što je uhvatila ranija grupa",
      literal: "doslovni tekst",
      quantifier: "ponavlja se",
    } satisfies Record<RegexPartKind, string>,
  },
} as const;
