/**
 * „Strukturirani podaci" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 *
 * `position` and `errors` are hoisted OUT of the six tools below them, rather
 * than repeated inside each: four of the six (`jsonEditor`, `yamlEditor`,
 * `xmlEditor`, `dataFormat`) read a `StructuredError` from
 * `@nexus/core/devtools/*`, and every one of those carries the same
 * `{code, expected, found, line, column}` shape. The 81 codes are already
 * namespaced by their module prefix (`json.`, `path.`, `yaml.`, `xml.`,
 * `xpath.`, `toml.`, `csv.`, `convert.`) so one flat table holds all of them
 * without collision — and the one code that genuinely crosses tools
 * (`convert.yaml-multiple-documents`, raised by both the YAML editor reading a
 * multi-document stream and the format converter) is translated once instead
 * of twice.
 */
export const DEVTOOLS_DATA_EN = {
  indent: "Indentation",
  indentTab: "Tab",

  /** The words `data.tsx`'s `formatStructuredError` composes a sentence from. */
  position: {
    expected: "expected",
    found: "found",
    line: "line",
    column: "column",
  },

  /** Every `StructuredErrorCode` / `YamlErrorCode` / `XmlErrorCode` — see the header. */
  errors: {
    "json.unexpected-end": "The document ends before it is complete",
    "json.unexpected-char": "Unexpected character",
    "json.trailing-content": "Trailing content after the value",
    "json.leading-zero": "A number may not start with zero",
    "json.missing-fraction": "Missing digits after the decimal point",
    "json.missing-exponent": "Missing exponent",
    "json.unterminated-string": "Unterminated string",
    "json.bad-escape": "Unknown escape sequence",
    "json.bad-unicode-escape": "Invalid \\u escape",
    "json.control-char": "A control character must be escaped",
    "json.duplicate-key": "Duplicate key",
    "json.number-not-exact": "The number would be rounded — write it as a string",
    "json.no-nan": "JSON has no representation for NaN or infinity",
    "path.expected-root": "The path must start with $",
    "path.expected-segment": "Expected a name",
    "path.unexpected-char": "Unexpected character in the path",
    "path.unterminated-quote": "Unterminated string in the path",
    "path.unsupported": "This part of JSONPath is not supported",
    "yaml.tab-indent": "Tab in the indentation — YAML allows spaces only",
    "yaml.directive": "Directives (%YAML, %TAG) are not supported",
    "yaml.anchor": "Anchors (&) are not supported",
    "yaml.alias": "Aliases (*) are not supported",
    "yaml.tag": "Explicit tags (!!) are not supported",
    "yaml.complex-key": "Complex keys (?) are not supported",
    "yaml.nested-flow": "Nested flow style is not supported",
    "yaml.unterminated-flow": "Unterminated flow collection",
    "yaml.bad-indent": "Wrong indentation",
    "yaml.expected-key": "Expected a key",
    "yaml.duplicate-key": "Duplicate key",
    "yaml.unterminated-quote": "Unterminated string",
    "yaml.bad-escape": "Unknown escape sequence",
    "yaml.trailing-content": "Trailing content after the value",
    "yaml.multiline-plain-scalar":
      "Multi-line text without quotes — use quotes or a | block",
    "yaml.bad-block-header": "Invalid block header",
    "yaml.number-not-exact": "The number would be rounded — write it as a string",
    "xml.unexpected-char": "Unexpected character — < in text must be &lt;",
    "xml.bad-name": "Invalid name",
    "xml.unclosed-tag": "Tag not closed",
    "xml.mismatched-close": "Closing the wrong tag",
    "xml.stray-close": "A closing tag with no opening",
    "xml.duplicate-attribute": "Duplicate attribute",
    "xml.unterminated-comment": "Unterminated comment",
    "xml.unterminated-cdata": "Unterminated CDATA block",
    "xml.unterminated-instruction": "Unterminated instruction",
    "xml.unterminated-doctype": "Unterminated DOCTYPE",
    "xml.unterminated-tag": "Unterminated tag",
    "xml.unterminated-attribute": "Unterminated attribute value",
    "xpath.expected-absolute": "The path must start with /",
    "xpath.expected-name": "Expected an element name",
    "xpath.unexpected-char": "Unexpected character in the path",
    "xpath.unterminated-quote": "Unterminated string in the path",
    "xpath.unsupported": "This part of XPath is not supported",
    "toml.unexpected-char": "Unexpected character",
    "toml.expected-equals": "Expected =",
    "toml.bad-key": "Invalid key",
    "toml.bad-value": "Invalid value",
    "toml.bad-number": "Invalid number",
    "toml.number-not-exact": "The number would be rounded — write it as a string",
    "toml.unterminated-string": "Unterminated string",
    "toml.bad-escape": "Unknown escape sequence",
    "toml.unterminated-array": "Unterminated array",
    "toml.unterminated-header": "Unterminated table header",
    "toml.duplicate-key": "Duplicate key",
    "toml.redefined-table": "The table is already defined",
    "toml.inline-table-unsupported": "Inline tables ({ }) are not supported",
    "toml.datetime-unsupported": "Dates and times are not supported",
    "toml.trailing-content": "Trailing content in the row",
    "csv.unterminated-quote": "Unterminated string",
    "csv.text-after-quote": "Text after the closing quote",
    "csv.ragged-row": "The row has a different number of fields than the header",
    "csv.duplicate-header": "Duplicate column name",
    "csv.no-rows": "No rows at all",
    "convert.csv-needs-rows": "CSV needs an array of rows",
    "convert.csv-nesting": "CSV cannot hold a nested value",
    "convert.csv-null": "CSV has no null — turn on “empty field instead of null” if that suits",
    "convert.csv-ragged-object": "The objects do not have the same columns",
    "convert.toml-root-not-table": "A TOML root must be a table",
    "convert.toml-null": "TOML has no null",
    "convert.toml-mixed-array": "The array mixes tables and plain values",
    "convert.toml-object-in-array": "A table inside an array is not supported",
    "convert.yaml-multiple-documents": "The stream has several documents — choose one",
  },

  jsonEditor: {
    title: "JSON",
    source: "Source",
    sourcePlaceholder: "Paste JSON…",
    format: "Format",
    minify: "Minify",
    sortKeys: "Tidy keys",
    validate: "Validate",
    valid: "The JSON is valid.",
    pathTitle: "JSONPath",
    path: "Path",
    pathPlaceholder: "$.items[*].name",
    hits: "Matches",
    noHits: "No matches.",
    hitIndex: "#",
    hitValue: "Value",
  },

  yamlEditor: {
    title: "YAML",
    source: "Source",
    sourcePlaceholder: "Paste YAML…",
    viewJson: "As JSON",
    viewYaml: "As YAML",
    sortKeys: "Sort keys",
    document: "Document",
    documents: "Documents",
  },

  xmlEditor: {
    title: "XML",
    source: "Source",
    sourcePlaceholder: "Paste XML or HTML…",
    format: "Format",
    minify: "Minify",
    validate: "Validate",
    valid: "The markup is valid.",
    pathTitle: "XPath",
    path: "Path",
    pathPlaceholder: "//item[@id='a']",
    hits: "Matches",
    noHits: "No matches.",
    element: "Element",
    attributes: "Attributes",
    text: "Text",
  },

  dataFormat: {
    title: "Format conversion",
    source: "Source",
    sourcePlaceholder: "Paste content…",
    from: "From",
    to: "To",
    swap: "Swap sides",
    limitsTitle: "What is not carried over",
    outputOptions: "Output options",
    sortKeys: "Sort keys",
    csvOptions: "CSV options",
    delimiter: "Separator",
    header: "The first row is the header",
    nullAsEmpty: "Empty field instead of null",
    formats: {
      json: "JSON",
      yaml: "YAML",
      toml: "TOML",
      csv: "CSV",
    },
    limits: {
      "limit.comments-lost": "Comments are lost",
      "limit.csv-flat-only": "CSV holds a flat table only — nesting does not survive",
      "limit.csv-text-only": "Everything from CSV is text — numbers are not guessed",
      "limit.csv-no-null": "CSV has no null — an empty field reads as empty text",
      "limit.toml-root-table": "A TOML root must be a table, not an array",
      "limit.toml-no-null": "TOML has no null",
      "limit.toml-no-datetime": "Dates and times are not supported",
      "limit.json-no-nan": "JSON has no NaN or infinity",
      "limit.yaml-no-anchors": "Anchors and aliases are not supported",
    },
  },

  jsonToTypes: {
    title: "JSON to types",
    source: "JSON sample",
    sourcePlaceholder: "Paste JSON…",
    targetLabel: {
      interface: "TypeScript interface",
      type: "TypeScript type",
      zod: "Zod schema",
    },
    rootName: "Root type name",
    rootNamePlaceholder: "Root",
    options: "Settings",
    readonly: "readonly fields",
    inlineSingleUse: "Inline types used once",
    optionalStyle: "Optional fields",
    optionalQuestion: "field?",
    optionalUndefined: "| undefined",
    output: "Declarations",
    typesCount: "Number of types",
    errors: {
      empty: "Enter a JSON sample.",
      syntax: "Not valid JSON.",
      too_deep: "The sample is nested too deeply to process.",
    },
  },

  uuid: {
    generateTitle: "Generation",
    genV4: "UUID v4",
    genV7: "UUID v7",
    genUlid: "ULID",
    generateEmpty: "Choose an identifier kind.",
    inspectTitle: "Inspection",
    inspectLabel: "Identifier",
    inspectPlaceholder: "Paste a UUID or ULID…",
    invalid: "This is not a valid UUID or ULID.",
    canonical: "Canonical form",
    variant: "Variant",
    variantLabel: {
      ncs: "NCS",
      rfc4122: "RFC 9562",
      microsoft: "Microsoft",
      future: "Reserved",
    },
    version: "Version",
    special: "Special form",
    specialLabel: {
      nil: "Nil UUID (all zeros)",
      max: "Max UUID (all ones)",
    },
    timestamp: "Time (ms)",
    timestampIso: "Time (ISO 8601)",
    randomness: "Randomness (hex)",
  },
} as const;
