import type { CaseFormat, RegexPartKind } from "@nexus/core/devtools/text";

/**
 * „Tekst" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 *
 * `regex.parts` and `caseConvert.formats` are each typed `satisfies
 * Record<…, string>` against the core module's own id union
 * (`RegexPartKind`, `CaseFormat`) — the core module exports those ids
 * specifically so this table can be checked exhaustive against them: a kind
 * added there and forgotten here is a compile error, not a silent blank row.
 */
export const DEVTOOLS_TEXT_EN = {
  diff: {
    left: "Left",
    right: "Right",
    leftPlaceholder: "Paste the first text",
    rightPlaceholder: "Paste the second text",
    level: "Comparison level",
    levelLines: "Lines",
    levelWords: "Words",
    ignoreTrailing: "Ignore trailing whitespace",
    ignoreAll: "Ignore all whitespace",
    ignoreCase: "Ignore case",
    context: "Lines of context",
    view: "View",
    viewSideBySide: "Side by side",
    viewUnified: "Unified diff",
    added: "Added",
    removed: "Removed",
    identical: "The texts are identical.",
    noTrailingNewline: "The last line has no newline at the end.",
  },
  "markdown-table": {
    grid: "Table",
    markdown: "Markdown",
    markdownPlaceholder: "…or paste a Markdown table here",
    headerPlaceholder: "Header",
    addRow: "Add row",
    addColumn: "Add column",
    removeRow: "Remove row",
    removeColumn: "Remove column",
    align: "Alignment",
    alignNone: "No alignment",
    alignLeft: "Left",
    alignCenter: "Centre",
    alignRight: "Right",
    lineBreakInCell:
      "Cell {row}·{column} contains a line break — a Markdown table cannot express it.",
    extraCells: "Row {row} has more cells than the header.",
    notATable: "This is not a Markdown table.",
    edgeSpaceNote: "Spaces at the start and end of a cell do not survive Markdown.",
  },
  lorem: {
    unit: "Unit",
    unitWords: "Words",
    unitSentences: "Sentences",
    unitParagraphs: "Paragraphs",
    count: "How many",
    vocabulary: "Word list",
    vocabularyLatin: "Latin",
    vocabularySerbian: "Serbian",
    classicOpening: "Start with classic “Lorem ipsum”",
    classicOpeningNote:
      "Applies to Latin only — Serbian has no established opening and we do not invent one.",
    regenerate: "Refresh",
    invalidCount: "Enter a whole number greater than zero.",
  },
  slug: {
    input: "Text",
    inputPlaceholder: "e.g. Ada Lovelace",
    result: "Slug",
    transliterated: "Transliterated",
    separator: "Separator",
    lowercase: "All lowercase",
    maxLength: "Maximum characters",
    maxLengthHint: "0 means no limit",
    invalidMaxLength: "Enter a whole number of zero or greater",
    collapse: "Collapse consecutive separators",
    wordKeptWhole: "The first word is not cut, so the result is longer than the limit.",
    empty: "Nothing to convert",
  },
  "case-convert": {
    input: "Name",
    inputPlaceholder: "e.g. parseURLFrom2ndAPI",
    tokens: "Words",
    tokensHint: "This is how the name is split before conversion",
    format: "Form",
    value: "Value",
    formats: {
      camel: "camelCase",
      pascal: "PascalCase",
      snake: "snake_case",
      screamingSnake: "SCREAMING_SNAKE",
      kebab: "kebab-case",
      train: "Train-Case",
      dot: "dot.case",
      path: "path/case",
      sentence: "Sentence case",
      title: "Title Case",
    } satisfies Record<CaseFormat, string>,
    acronymNote: "Acronyms are not kept uppercase — the form applies to every word.",
  },
  "line-tools": {
    input: "Input",
    inputPlaceholder: "Paste lines",
    cleanupTitle: "Cleaning",
    removeBlank: "Remove empty lines",
    trim: "Trim whitespace",
    trimNone: "Leave alone",
    trimBoth: "Both sides",
    trimStart: "From the start",
    trimEnd: "From the end",
    dedupeTitle: "Duplicates",
    dedupe: "Remove duplicates",
    adjacentOnly: "Adjacent only",
    caseSensitive: "Case-sensitive",
    orderTitle: "Order",
    order: "Order",
    orderNone: "Unchanged",
    orderSort: "Sort",
    orderReverse: "Reverse",
    orderShuffle: "Shuffle",
    sortMode: "Mode",
    sortLexicographic: "By characters",
    sortNatural: "Natural (a number as a number)",
    sortLength: "By length",
    sortCollated: "Serbian order",
    descending: "Descending",
    numberTitle: "Numbering",
    number: "Number",
    numberStart: "Start at",
    numberSeparator: "Separator",
    pad: "Align numbers",
    affixTitle: "Affixes",
    prefix: "Prefix",
    suffix: "Suffix",
    wrapTitle: "Wrap",
    wrap: "Wrap",
    wrapWidth: "Width",
    wrapNote: "A word longer than the width stays whole.",
    invalidStart: "Enter a whole number",
    invalidWidth: "Enter a whole number greater than zero",
  },
  regex: {
    pattern: "Pattern",
    patternPlaceholder: "e.g. (?<year>\\d{4})-(?<month>\\d{2})",
    flags: "Flags",
    text: "Text",
    textPlaceholder: "Paste text to test",
    matches: "Matches",
    noMatches: "No matches.",
    index: "Position",
    length: "Length",
    match: "Match",
    groups: "Groups",
    namedGroups: "Named groups",
    unmatchedGroup: "did not match",
    replacement: "Replacement",
    replacementPlaceholder: "$1 · $<name> · $&",
    preview: "Preview",
    replacedCount: "Number of replacements",
    globalNote: "Without the g flag only the first match is replaced.",
    explain: "Pattern explanation",
    explainPart: "Part",
    explainMeaning: "Meaning",
    invalid: "The pattern is not valid: {message}",
    nestedQuantifier:
      "Rejected at character {at}: repeating a group that itself repeats can freeze the application.",
    nestedQuantifierNote:
      "This pattern has nested repetition and can freeze the application (character {at}).",
    allowAnyway: "Run anyway",
    matchCap: "Showing the first {count} matches.",
    timeBudget: "Aborted — the pattern searched for too long.",
    quantifierExact: "exactly {min} times",
    quantifierAtLeast: "at least {min} times",
    quantifierRange: "{min} to {max} times",
    quantifierLazy: "as short as possible",
    parts: {
      "anchor-start": "start of text",
      "anchor-end": "end of text",
      "word-boundary": "word boundary",
      "not-word-boundary": "not a word boundary",
      "group-open": "group {group}",
      "named-group-open": "named group “{name}”",
      "non-capturing-group-open": "non-capturing group",
      lookahead: "followed by",
      "negative-lookahead": "not followed by",
      lookbehind: "preceded by",
      "negative-lookbehind": "not preceded by",
      "group-close": "end of group",
      alternation: "or",
      class: "one character from the set",
      "negated-class": "one character not in the set",
      any: "any character",
      digit: "digit",
      "not-digit": "not a digit",
      "word-char": "letter, digit or underscore",
      "not-word-char": "not a letter, digit or underscore",
      whitespace: "whitespace",
      "not-whitespace": "not whitespace",
      backreference: "the same as an earlier group captured",
      literal: "literal text",
      quantifier: "repeated",
    } satisfies Record<RegexPartKind, string>,
  },
} as const;
