/**
 * „Kriptografija" — the English copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.en.ts`, because
 * the drawer's rail needs them before any surface is opened.
 *
 * `shared` holds the two sentences every ASYNC tool in this file can need and
 * none owns alone: the button's label while a WebCrypto call is in flight, and
 * the one fallback for a promise that rejected instead of answering with a
 * typed failure (`@nexus/core/devtools/cryptoTools` never throws for bad user
 * input — a rejection here means the platform itself refused, which none of
 * the eight tools can put a more specific sentence on).
 */
export const DEVTOOLS_CRYPTO_EN = {
  shared: {
    working: "Working…",
    webCryptoFailure: "The WebCrypto operation failed for an unknown reason.",
  },

  "token-gen": {
    length: "Length",
    alphabet: "Alphabet",
    alphabetHex: "Hexadecimal",
    alphabetBase64Url: "Base64url",
    alphabetBase58: "Base58",
    alphabetAlphanumeric: "Letters and digits",
    alphabetCustom: "Custom",
    customAlphabet: "Alphabet characters",
    customPlaceholder: "e.g. ABCDEF123456",
    count: "Number of tokens",
    generate: "Generate",
    copyAll: "Copy all",
    tokenColumn: "Token",
    entropy: "Entropy",
    entropyValue: "{bits} bits per token",
    entropyFrom: "from an alphabet of {size} characters",
    errLength: "Length must be between 1 and {limit}.",
    errCount: "At most {limit} tokens at once.",
    errAlphabetSmall: "The alphabet must have at least two different characters.",
    errAlphabetLarge: "The alphabet may not have more than {limit} characters.",
    errAlphabetRepeats: "The alphabet repeats a character — remove the duplicates.",
    errRandom: "The random number generator did not produce a usable result.",
  },

  "password-gen": {
    modePassword: "Password",
    modePassphrase: "Passphrase",
    modeLabel: "Password kind",
    classesLabel: "Character groups",
    length: "Length",
    lower: "Lowercase",
    upper: "Uppercase",
    digit: "Digits",
    symbol: "Symbols",
    excludeAmbiguous: "No similar characters ({chars})",
    requireEachClass: "At least one from each group",
    words: "Number of words",
    list: "Word list",
    listSr: "Serbian",
    listEn: "English",
    separator: "Separator",
    capitalize: "Capitalise each word",
    generate: "Generate",
    regenerate: "Regenerate",
    entropy: "Entropy",
    entropyValue: "{bits} bits",
    entropyNote: "Computed from an alphabet of {size} characters and the length, not from how the password looks.",
    entropyNoteWords: "Computed from a word list of {size} words, not from the number of characters.",
    errLength: "Length must be between 1 and {limit}.",
    errNoClasses: "Choose at least one character group.",
    errTooShort: "All the chosen groups together need at least {limit} characters.",
    errWords: "The number of words must be between 1 and {limit}.",
    errRandom: "Could not satisfy the given condition — try a longer length.",
  },

  jwt: {
    token: "Token",
    tokenPlaceholder: "Paste a JWT…",
    header: "Header",
    payload: "Payload",
    signature: "Signature",
    claims: "Claims",
    claimName: "Name",
    claimValue: "Value",
    claimInstant: "Instant",
    registered: "Standard",
    algorithm: "Algorithm",
    valid: "Valid (at this instant)",
    expired: "Expired",
    notYetValid: "Not yet valid",
    unbounded: "No deadline — neither exp nor nbf",
    unreadable: "Unreadable time: {claims}",
    verify: "Verify signature",
    keyKind: "Key kind",
    keySecret: "Shared secret",
    keyPem: "Public key (PEM)",
    keyJwk: "Public key (JWK)",
    secretPlaceholder: "Secret key…",
    jwkPlaceholder: "Paste a JWK…",
    signatureValid: "The signature is valid",
    signatureInvalid: "The signature is not valid",
    registeredClaimNames: {
      iss: "Issuer",
      sub: "Subject",
      aud: "Audience",
      exp: "Expires",
      nbf: "Valid from",
      iat: "Issued",
      jti: "Token ID",
    },
    errMalformed: "The token does not have three dot-separated parts.",
    errNotBase64Url:
      "The “{subject}” part is not valid base64url — JWS does not use “=” padding.",
    errNotJson: "The “{subject}” part is not a JSON object.",
    errAlgNone:
      "alg: none means “no signature”. Nexus does not accept it under any circumstances — accepting it is the classic JWT vulnerability.",
    errAlgMissing: "The header has no alg.",
    errAlgUnsupported: "Algorithm {subject} is not supported.",
    errKeyMismatch: "{subject} needs a different kind of key.",
    errKeyImport: "The key could not be loaded.",
    errKeyPrivate: "This is a private key — verification needs the public one.",
    errPem: "The PEM block is not valid.",
    errPemLabel: "A different key was expected — this is “{subject}”.",
  },

  hashing: {
    inputPlaceholder: "Text to hash…",
    algorithm: "Algorithm",
    hmacOn: "HMAC",
    hmacKey: "HMAC key",
    hmacKeyPlaceholder: "Secret key…",
    compute: "Compute",
    hex: "Hex",
    base64: "Base64",
    errUnavailable:
      "{subject} is not available: WebCrypto does not have it, and Nexus does not write its own implementation of an algorithm that was broken long ago.",
  },

  aes: {
    encrypt: "Encrypt",
    decrypt: "Decrypt",
    direction: "Direction",
    plaintext: "Text",
    plaintextPlaceholder: "Text to encrypt…",
    envelope: "Envelope",
    envelopePlaceholder: "Paste an envelope…",
    mode: "Mode",
    keyBits: "Key length",
    keySource: "Key",
    keyRaw: "Direct key",
    keyPassphrase: "Password",
    keyValue: "Key value",
    passphrase: "Passphrase",
    encoding: "Key encoding",
    encodingHex: "Hex",
    encodingBase64: "Base64",
    iterations: "PBKDF2 iterations",
    copyEnvelope: "Copy envelope",
    ivNote:
      "The IV is made anew for every encryption and travels in the envelope — a repeated IV under GCM breaks both secrecy and authenticity.",
    errInvalidHex: "The key is not valid hex.",
    errInvalidBase64: "The key is not valid base64.",
    errKeyLength: "This length needs {limit} bytes, {actual} entered.",
    errIterationsShape: "Write the iteration count as a whole number — digits only, no spaces.",
    errIterations:
      "At least {limit} iterations — fewer would make the password weaker than it looks.",
    errAuth: "The integrity check failed — the key or the ciphertext is not valid.",
    errDecrypt:
      "Decryption failed. CBC has no integrity check, so it cannot tell a wrong key from damaged data.",
    errNotUtf8: "The result is not text.",
    errEnvelope: "The envelope is not valid.",
    errKeyMismatch: "The envelope needs a different kind of key.",
  },

  "rsa-keygen": {
    sectionRsa: "RSA",
    sectionEc: "EC",
    scheme: "Purpose",
    schemeOaep: "RSA-OAEP (encryption)",
    schemePss: "RSA-PSS (signature)",
    modulus: "Key length",
    hash: "Hash",
    curve: "Curve",
    generate: "Generate pair",
    generateEc: "Generate EC pair",
    privateKey: "Private key (PKCS#8)",
    publicKey: "Public key (SPKI)",
    copyPrivate: "Copy private key",
    copyPublic: "Copy public key",
    warning: "The private key exists only here — Nexus does not store it or send it anywhere.",
    working: "Generating 4096 bits can take a few seconds.",
    errUnsupported: "{subject} is not an offered value.",
  },

  "rsa-crypt": {
    direction: "Direction",
    encrypt: "Encrypt",
    decrypt: "Decrypt",
    publicKey: "Public key (PEM)",
    privateKey: "Private key (PEM)",
    plaintext: "Text",
    ciphertext: "Ciphertext (base64)",
    hash: "OAEP hash",
    usedLabel: "Used",
    used: "{actual} of {limit} bytes",
    errTooLong:
      "The message has {actual} bytes and the key carries at most {limit}. For longer content, encrypt with an AES key, then encrypt only that key with RSA.",
    errPemLabel: "A different key was expected — this is “{subject}”.",
    errPem: "The PEM block is not valid.",
    errKeyImport: "The key could not be loaded.",
    errDecrypt: "Decryption failed — wrong key or damaged ciphertext.",
    errInvalidBase64: "The ciphertext is not valid base64.",
    errNotUtf8: "The result is not text.",
  },

  signature: {
    action: "Action",
    sign: "Sign",
    verify: "Verify",
    algorithm: "Algorithm",
    message: "Message",
    privateKey: "Private key (PEM)",
    publicKey: "Public key (PEM)",
    signatureValue: "Signature",
    encoding: "Encoding",
    encodingHex: "Hex",
    encodingBase64: "Base64",
    saltLength: "Salt length (PSS)",
    saltHint: "Empty = the default length for the chosen hash.",
    errSaltShape: "Write the salt length as a whole number of bytes, or leave it empty.",
    hash: "Hash",
    generateEc: "Generate EC pair",
    copySignature: "Copy signature",
    hex: "Hex",
    base64: "Base64",
    valid: "The signature is valid",
    invalid: "The signature is not valid",
    ecdsaNote:
      "An ECDSA signature is the raw pair r and s (P1363), not DER — OpenSSL produces DER by default and the two encodings do not verify against each other.",
    errUnsupported: "Algorithm {subject} is not supported.",
    errPem: "The PEM block is not valid.",
    errKeyImport: "The key does not match the chosen algorithm.",
    errInvalidHex: "The signature is not valid hex.",
    errInvalidBase64: "The signature is not valid base64.",
    errSign: "Signing failed — check the salt length.",
  },
} as const;
