/**
 * „Brojevi i formati" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 */
export const DEVTOOLS_NUMBERS_SR = {
  "number-base": {
    input: "Broj",
    inputPlaceholder: "npr. 0xFF, 1111_0000, -2a",
    from: "Iz osnove",
    to: "U osnovu",
    prefixHint: "Prefiks 0x/0b/0o mora odgovarati izabranoj osnovi.",
    group: "Grupiši cifre",
    uppercase: "Velika slova",
    result: "Rezultat",
    others: "Ostale osnove",
    baseColumn: "Osnova",
    valueColumn: "Vrednost",
    invalid: "Ovo nije ispravan zapis broja u izabranoj osnovi.",
    tooLong: "Predugačak unos — najviše 4096 znakova.",
  },
  "integer-inspector": {
    value: "Vrednost",
    valuePlaceholder: "npr. -1, 200, 0xFFFFFFFF",
    inputBase: "Osnova unosa",
    prefixHint: "Prefiks 0x/0b/0o mora odgovarati izabranoj osnovi.",
    type: "Tip",
    range: "Opseg",
    decimal: "Decimalno",
    hex: "Heksadecimalno",
    binary: "Binarno",
    doesNotFit: "Ne staje",
    smallest: "Najmanji tip koji staje",
    noneFits: "Nijedan tip ovde nije dovoljno širok.",
    byteOrder: "Redosled bajtova",
    width: "Širina",
    bigEndian: "Big-endian",
    littleEndian: "Little-endian",
    invalid: "Ovo nije ceo broj u izabranoj osnovi unosa.",
    noWidthFit: "Vrednost ne staje ni u jedan tip ove širine.",
  },
  bitwise: {
    width: "Širina",
    operandBase: "Osnova unosa",
    prefixHint: "Prefiks 0x/0b/0o mora odgovarati izabranoj osnovi.",
    operation: "Operacija",
    operandA: "A",
    operandB: "B",
    amount: "Pomeraj (broj mesta)",
    result: "Rezultat",
    hex: "Heksadecimalno",
    unsigned: "Bez znaka",
    signed: "Sa znakom",
    popcount: "Broj jedinica",
    leadingZeros: "Vodeće nule",
    trailingZeros: "Prateće nule",
    parity: "Parnost",
    parityOdd: "neparna",
    parityEven: "parna",
    invalid: "Ovo nije validan broj u izabranoj osnovi.",
    invalidAmount: "Pomeraj mora biti ceo broj, nula ili veći.",
    ops: {
      and: "I (AND)",
      or: "ILI (OR)",
      xor: "Isključivo ILI (XOR)",
      nand: "NI (NAND)",
      nor: "NILI (NOR)",
      xnor: "XNOR",
      not: "Negacija (NOT)",
      shl: "Pomeraj levo",
      shr: "Logički pomeraj desno",
      sar: "Aritmetički pomeraj desno",
      rol: "Rotacija levo",
      ror: "Rotacija desno",
    },
  },
  "data-unit": {
    value: "Vrednost",
    valuePlaceholder: "npr. 1,5",
    from: "Iz",
    to: "U",
    ladder: "Sve jedinice",
    unitColumn: "Jedinica",
    valueColumn: "Vrednost",
    convention: "Konvencija",
    conventionDecimal: "Decimalna (1000)",
    conventionBinary: "Binarna (1024)",
    best: "Najprirodnija jedinica",
    invalid: "Ovo nije validan broj.",
    overflow: "Rezultat je prevelik da bi se prikazao.",
    note: "kB nije KiB: 1 kB je 1000 B, a 1 KiB je 1024 B.",
    units: {
      byte: "Bajt (B)",
      "kb-dec": "Kilobajt — decimalno (kB)",
      "mb-dec": "Megabajt — decimalno (MB)",
      "gb-dec": "Gigabajt — decimalno (GB)",
      "tb-dec": "Terabajt — decimalno (TB)",
      "pb-dec": "Petabajt — decimalno (PB)",
      kib: "Kibibajt — binarno (KiB)",
      mib: "Mebibajt — binarno (MiB)",
      gib: "Gibibajt — binarno (GiB)",
      tib: "Tebibajt — binarno (TiB)",
      pib: "Pebibajt — binarno (PiB)",
      bit: "Bit (b)",
      kbit: "Kilobit (kbit)",
      mbit: "Megabit (Mbit)",
      gbit: "Gigabit (Gbit)",
    },
  },
  "float-convert": {
    modeLabel: "Način unosa",
    modeDecimal: "Decimalno",
    modeBits: "Bitovi",
    format: "Format",
    rounding: "Zaokruživanje",
    valueLabel: "Vrednost",
    bitsLabel: "Bitovi",
    valuePlaceholder: "npr. 0,1, -3,4e38, inf, nan",
    bitsPlaceholder: "npr. 0x3DCCCCCD",
    invalid: "Ovo nije čitljiv decimalni broj.",
    invalidBits: "Ovo nije čitljiv zapis bita za izabrani format.",
    bits: "Bitovi",
    classLabel: "Klasa",
    classes: {
      zero: "Nula",
      subnormal: "Subnormalan",
      normal: "Normalan",
      infinity: "Beskonačno",
      nan: "NaN",
    },
    exact: "Tačna vrednost",
    roundingApplied: "Zaokruživanje",
    roundingExact: "Bez zaokruživanja (tačna vrednost)",
    flags: "Napomene",
    overflow: "Preliv",
    underflow: "Potkoračenje",
    signLost: "Znak izgubljen",
    allFormats: "Svi formati",
    value: "Vrednost",
    sourceBadge: "Izvor",
    rounded: "Zaokruženo",
    roundingModes: {
      "nearest-even": "Najbliže, na parno",
      "nearest-away": "Najbliže, dalje od nule",
      "toward-zero": "Ka nuli",
      "toward-positive": "Ka +∞",
      "toward-negative": "Ka −∞",
    },
  },
  "mx-block": {
    element: "Format elementa",
    extended: "(nije u OCP specifikaciji)",
    rounding: "Zaokruživanje",
    values: "Vrednosti",
    valuesPlaceholder: "npr. 1, 2,5, -0,03, 100",
    valuesHint: "Odvoji zarezom, razmakom ili novim redom — najviše 32 vrednosti.",
    tooManyValues: "Blok prima najviše 32 vrednosti.",
    invalidValue: "Bar jedna vrednost nije čitljiv broj.",
    scale: "Deljena skala",
    scaleNaN: "Skala je NaN — bar jedna vrednost je NaN ili beskonačna, blok je neupotrebljiv.",
    scaleClamped: "Idealna skala je van opsega E8M0 — blok je zasićen na granicu.",
    index: "#",
    input: "Uneto",
    elementBits: "Bitovi elementa",
    decodedValue: "Dekodirana vrednost",
    notes: "Napomene",
    inexact: "Netačno",
    saturated: "Zasićeno",
    underflowed: "Potkoračenje",
    padded: "Preostali elementi bloka su popunjeni nulama do punog bloka od 32.",
    bitsPerValue: "Bita po vrednosti",
    blockBits: "Ukupno bita u bloku",
    roundingModes: {
      "nearest-even": "Najbliže, na parno",
      "nearest-away": "Najbliže, dalje od nule",
      "toward-zero": "Ka nuli",
      "toward-positive": "Ka +∞",
      "toward-negative": "Ka −∞",
    },
  },
} as const;
