/**
 * „Brojevi i formati" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 */
export const DEVTOOLS_NUMBERS_EN = {
  "number-base": {
    input: "Number",
    inputPlaceholder: "e.g. 0xFF, 1111_0000, -2a",
    from: "From base",
    to: "To base",
    prefixHint: "The 0x/0b/0o prefix must match the chosen base.",
    group: "Group digits",
    uppercase: "Uppercase",
    result: "Result",
    others: "Other bases",
    baseColumn: "Base",
    valueColumn: "Value",
    invalid: "This is not a valid number in the chosen base.",
    tooLong: "Input too long — at most 4096 characters.",
  },
  "integer-inspector": {
    value: "Value",
    valuePlaceholder: "e.g. -1, 200, 0xFFFFFFFF",
    inputBase: "Input base",
    prefixHint: "The 0x/0b/0o prefix must match the chosen base.",
    type: "Type",
    range: "Range",
    decimal: "Decimal",
    hex: "Hexadecimal",
    binary: "Binary",
    doesNotFit: "Does not fit",
    smallest: "Smallest type that fits",
    noneFits: "No type here is wide enough.",
    byteOrder: "Byte order",
    width: "Width",
    bigEndian: "Big-endian",
    littleEndian: "Little-endian",
    invalid: "This is not a whole number in the chosen input base.",
    noWidthFit: "The value does not fit any type of this width.",
  },
  bitwise: {
    width: "Width",
    operandBase: "Input base",
    prefixHint: "The 0x/0b/0o prefix must match the chosen base.",
    operation: "Operation",
    operandA: "A",
    operandB: "B",
    amount: "Shift (number of places)",
    result: "Result",
    hex: "Hexadecimal",
    unsigned: "Unsigned",
    signed: "Signed",
    popcount: "Number of ones",
    leadingZeros: "Leading zeros",
    trailingZeros: "Trailing zeros",
    parity: "Parity",
    parityOdd: "odd",
    parityEven: "even",
    invalid: "This is not a valid number in the chosen base.",
    invalidAmount: "The shift must be a whole number, zero or greater.",
    ops: {
      and: "AND",
      or: "OR",
      xor: "Exclusive OR (XOR)",
      nand: "NAND",
      nor: "NOR",
      xnor: "XNOR",
      not: "NOT",
      shl: "Shift left",
      shr: "Logical shift right",
      sar: "Arithmetic shift right",
      rol: "Rotate left",
      ror: "Rotate right",
    },
  },
  "data-unit": {
    value: "Value",
    valuePlaceholder: "e.g. 1.5",
    from: "From",
    to: "To",
    ladder: "All units",
    unitColumn: "Unit",
    valueColumn: "Value",
    convention: "Convention",
    conventionDecimal: "Decimal (1000)",
    conventionBinary: "Binary (1024)",
    best: "Most natural unit",
    invalid: "This is not a valid number.",
    overflow: "The result is too large to display.",
    note: "kB is not KiB: 1 kB is 1000 B, and 1 KiB is 1024 B.",
    units: {
      byte: "Byte (B)",
      "kb-dec": "Kilobyte — decimal (kB)",
      "mb-dec": "Megabyte — decimal (MB)",
      "gb-dec": "Gigabyte — decimal (GB)",
      "tb-dec": "Terabyte — decimal (TB)",
      "pb-dec": "Petabyte — decimal (PB)",
      kib: "Kibibyte — binary (KiB)",
      mib: "Mebibyte — binary (MiB)",
      gib: "Gibibyte — binary (GiB)",
      tib: "Tebibyte — binary (TiB)",
      pib: "Pebibyte — binary (PiB)",
      bit: "Bit (b)",
      kbit: "Kilobit (kbit)",
      mbit: "Megabit (Mbit)",
      gbit: "Gigabit (Gbit)",
    },
  },
  "float-convert": {
    modeLabel: "Input mode",
    modeDecimal: "Decimal",
    modeBits: "Bits",
    format: "Format",
    rounding: "Rounding",
    valueLabel: "Value",
    bitsLabel: "Bits",
    valuePlaceholder: "e.g. 0.1, -3.4e38, inf, nan",
    bitsPlaceholder: "e.g. 0x3DCCCCCD",
    invalid: "This is not a readable decimal number.",
    invalidBits: "This is not a readable bit pattern for the chosen format.",
    bits: "Bits",
    classLabel: "Class",
    classes: {
      zero: "Zero",
      subnormal: "Subnormal",
      normal: "Normal",
      infinity: "Infinity",
      nan: "NaN",
    },
    exact: "Exact value",
    roundingApplied: "Rounding",
    roundingExact: "No rounding (exact value)",
    flags: "Notes",
    overflow: "Overflow",
    underflow: "Underflow",
    signLost: "Sign lost",
    allFormats: "All formats",
    value: "Value",
    sourceBadge: "Source",
    rounded: "Rounded",
    roundingModes: {
      "nearest-even": "Nearest, ties to even",
      "nearest-away": "Nearest, away from zero",
      "toward-zero": "Toward zero",
      "toward-positive": "Toward +∞",
      "toward-negative": "Toward −∞",
    },
  },
  "mx-block": {
    element: "Element format",
    extended: "(not in the OCP specification)",
    rounding: "Rounding",
    values: "Values",
    valuesPlaceholder: "e.g. 1, 2.5, -0.03, 100",
    valuesHint: "Separate with a comma, a space or a new line — at most 32 values.",
    tooManyValues: "A block takes at most 32 values.",
    invalidValue: "At least one value is not a readable number.",
    scale: "Shared scale",
    scaleNaN: "The scale is NaN — at least one value is NaN or infinite, so the block is unusable.",
    scaleClamped: "The ideal scale is outside the E8M0 range — the block is saturated at the limit.",
    index: "#",
    input: "Entered",
    elementBits: "Element bits",
    decodedValue: "Decoded value",
    notes: "Notes",
    inexact: "Inexact",
    saturated: "Saturated",
    underflowed: "Underflow",
    padded: "The remaining elements of the block are padded with zeros to the full block of 32.",
    bitsPerValue: "Bits per value",
    blockBits: "Total bits in the block",
    roundingModes: {
      "nearest-even": "Nearest, ties to even",
      "nearest-away": "Nearest, away from zero",
      "toward-zero": "Toward zero",
      "toward-positive": "Toward +∞",
      "toward-negative": "Toward −∞",
    },
  },
} as const;
