/**
 * „Kriptografija" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 *
 * `shared` holds the two sentences every ASYNC tool in this file can need and
 * none owns alone: the button's label while a WebCrypto call is in flight, and
 * the one fallback for a promise that rejected instead of answering with a
 * typed failure (`@nexus/core/devtools/cryptoTools` never throws for bad user
 * input — a rejection here means the platform itself refused, which none of
 * the eight tools can put a more specific sentence on).
 */
export const DEVTOOLS_CRYPTO_SR = {
  shared: {
    working: "Radi…",
    webCryptoFailure: "WebCrypto operacija nije uspela iz nepoznatog razloga.",
  },

  "token-gen": {
    length: "Dužina",
    alphabet: "Azbuka",
    alphabetHex: "Heksadecimalno",
    alphabetBase64Url: "Base64url",
    alphabetBase58: "Base58",
    alphabetAlphanumeric: "Slova i cifre",
    alphabetCustom: "Sopstvena",
    customAlphabet: "Znakovi azbuke",
    customPlaceholder: "npr. ABCDEF123456",
    count: "Broj tokena",
    generate: "Generiši",
    copyAll: "Kopiraj sve",
    tokenColumn: "Token",
    entropy: "Entropija",
    entropyValue: "{bits} bita po tokenu",
    entropyFrom: "iz azbuke od {size} znakova",
    errLength: "Dužina mora biti između 1 i {limit}.",
    errCount: "Najviše {limit} tokena odjednom.",
    errAlphabetSmall: "Azbuka mora imati bar dva različita znaka.",
    errAlphabetLarge: "Azbuka ne sme imati više od {limit} znakova.",
    errAlphabetRepeats: "Azbuka ponavlja znak — ukloni duplikate.",
    errRandom: "Generator slučajnih brojeva nije dao upotrebljiv rezultat.",
  },

  "password-gen": {
    modePassword: "Lozinka",
    modePassphrase: "Fraza",
    modeLabel: "Vrsta lozinke",
    classesLabel: "Grupe znakova",
    length: "Dužina",
    lower: "Mala slova",
    upper: "Velika slova",
    digit: "Cifre",
    symbol: "Simboli",
    excludeAmbiguous: "Bez sličnih znakova ({chars})",
    requireEachClass: "Bar po jedan iz svake grupe",
    words: "Broj reči",
    list: "Rečnik",
    listSr: "Srpski",
    listEn: "Engleski",
    separator: "Razdvajač",
    capitalize: "Velika početna slova",
    generate: "Generiši",
    regenerate: "Iznova",
    entropy: "Entropija",
    entropyValue: "{bits} bita",
    entropyNote: "Računato iz azbuke od {size} znakova i dužine, ne iz izgleda lozinke.",
    entropyNoteWords: "Računato iz rečnika od {size} reči, ne iz broja znakova.",
    errLength: "Dužina mora biti između 1 i {limit}.",
    errNoClasses: "Izaberi bar jednu grupu znakova.",
    errTooShort: "Za sve izabrane grupe treba bar {limit} znakova.",
    errWords: "Broj reči mora biti između 1 i {limit}.",
    errRandom: "Nije uspelo da se ispuni zadati uslov — probaj veću dužinu.",
  },

  jwt: {
    token: "Token",
    tokenPlaceholder: "Nalepi JWT…",
    header: "Zaglavlje",
    payload: "Sadržaj",
    signature: "Potpis",
    claims: "Tvrdnje",
    claimName: "Naziv",
    claimValue: "Vrednost",
    claimInstant: "Trenutak",
    registered: "Standardna",
    algorithm: "Algoritam",
    valid: "Važi (u ovom trenutku)",
    expired: "Istekao",
    notYetValid: "Još ne važi",
    unbounded: "Bez roka — nema ni exp ni nbf",
    unreadable: "Vreme koje se ne može pročitati: {claims}",
    verify: "Proveri potpis",
    keyKind: "Vrsta ključa",
    keySecret: "Zajednička tajna",
    keyPem: "Javni ključ (PEM)",
    keyJwk: "Javni ključ (JWK)",
    secretPlaceholder: "Tajni ključ…",
    jwkPlaceholder: "Nalepi JWK…",
    signatureValid: "Potpis je ispravan",
    signatureInvalid: "Potpis nije ispravan",
    registeredClaimNames: {
      iss: "Izdavalac",
      sub: "Nosilac",
      aud: "Primalac",
      exp: "Ističe",
      nbf: "Važi od",
      iat: "Izdato",
      jti: "ID tokena",
    },
    errMalformed: "Token nema tri dela razdvojena tačkom.",
    errNotBase64Url:
      "Deo „{subject}“ nije ispravan base64url — JWS ne koristi dopunu znakom jednakosti.",
    errNotJson: "Deo „{subject}“ nije JSON objekat.",
    errAlgNone:
      "alg: none znači „bez potpisa“. Nexus to ne prihvata ni pod jednim uslovom — " +
      "prihvatanje je klasična JWT ranjivost.",
    errAlgMissing: "Zaglavlje nema alg.",
    errAlgUnsupported: "Algoritam {subject} nije podržan.",
    errKeyMismatch: "Za {subject} treba druga vrsta ključa.",
    errKeyImport: "Ključ nije mogao da se učita.",
    errKeyPrivate: "Ovo je privatni ključ — za proveru treba javni.",
    errPem: "PEM blok nije ispravan.",
    errPemLabel: "Očekivan je drugi ključ — ovo je „{subject}“.",
  },

  hashing: {
    inputPlaceholder: "Tekst za heširanje…",
    algorithm: "Algoritam",
    hmacOn: "HMAC",
    hmacKey: "HMAC ključ",
    hmacKeyPlaceholder: "Tajni ključ…",
    compute: "Izračunaj",
    hex: "Hex",
    base64: "Base64",
    errUnavailable:
      "{subject} nije dostupan: WebCrypto ga nema, a Nexus ne piše sopstvenu " +
      "implementaciju algoritma koji je odavno slomljen.",
  },

  aes: {
    encrypt: "Šifruj",
    decrypt: "Dešifruj",
    direction: "Smer",
    plaintext: "Tekst",
    plaintextPlaceholder: "Tekst koji se šifruje…",
    envelope: "Koverta",
    envelopePlaceholder: "Nalepi kovertu…",
    mode: "Režim",
    keyBits: "Dužina ključa",
    keySource: "Ključ",
    keyRaw: "Direktan ključ",
    keyPassphrase: "Lozinka",
    keyValue: "Vrednost ključa",
    passphrase: "Lozinka",
    encoding: "Zapis ključa",
    encodingHex: "Hex",
    encodingBase64: "Base64",
    iterations: "PBKDF2 iteracije",
    copyEnvelope: "Kopiraj kovertu",
    ivNote:
      "IV se pravi iznova pri svakom šifrovanju i putuje u koverti — ponovljen IV pod " +
      "GCM-om ruši i tajnost i potpis.",
    errInvalidHex: "Ključ nije ispravan hex.",
    errInvalidBase64: "Ključ nije ispravan base64.",
    errKeyLength: "Za ovu dužinu treba {limit} bajtova, uneto {actual}.",
    errIterationsShape: "Broj iteracija upiši kao ceo broj — samo cifre, bez razmaka.",
    errIterations:
      "Najmanje {limit} iteracija — manje bi lozinku učinilo slabijom nego što izgleda.",
    errAuth: "Provera integriteta nije prošla — ključ ili šifrat nisu ispravni.",
    errDecrypt:
      "Dešifrovanje nije uspelo. CBC nema proveru integriteta, pa ne može da razlikuje " +
      "pogrešan ključ od oštećenih podataka.",
    errNotUtf8: "Rezultat nije tekst.",
    errEnvelope: "Koverta nije ispravna.",
    errKeyMismatch: "Koverta traži drugu vrstu ključa.",
  },

  "rsa-keygen": {
    sectionRsa: "RSA",
    sectionEc: "EC",
    scheme: "Namena",
    schemeOaep: "RSA-OAEP (šifrovanje)",
    schemePss: "RSA-PSS (potpis)",
    modulus: "Dužina ključa",
    hash: "Heš",
    curve: "Kriva",
    generate: "Generiši par",
    generateEc: "Generiši EC par",
    privateKey: "Privatni ključ (PKCS#8)",
    publicKey: "Javni ključ (SPKI)",
    copyPrivate: "Kopiraj privatni",
    copyPublic: "Kopiraj javni",
    warning: "Privatni ključ postoji samo ovde — Nexus ga ne čuva i ne šalje nigde.",
    working: "Generisanje 4096 bita ume da potraje nekoliko sekundi.",
    errUnsupported: "{subject} nije ponuđena vrednost.",
  },

  "rsa-crypt": {
    direction: "Smer",
    encrypt: "Šifruj",
    decrypt: "Dešifruj",
    publicKey: "Javni ključ (PEM)",
    privateKey: "Privatni ključ (PEM)",
    plaintext: "Tekst",
    ciphertext: "Šifrat (base64)",
    hash: "OAEP heš",
    usedLabel: "Iskorišćeno",
    used: "{actual} od {limit} bajtova",
    errTooLong:
      "Poruka ima {actual} bajtova, a ključ nosi najviše {limit}. Za duži sadržaj šifruj " +
      "AES ključem, pa RSA-om samo taj ključ.",
    errPemLabel: "Očekivan je drugi ključ — ovo je „{subject}“.",
    errPem: "PEM blok nije ispravan.",
    errKeyImport: "Ključ nije mogao da se učita.",
    errDecrypt: "Dešifrovanje nije uspelo — pogrešan ključ ili oštećen šifrat.",
    errInvalidBase64: "Šifrat nije ispravan base64.",
    errNotUtf8: "Rezultat nije tekst.",
  },

  signature: {
    action: "Radnja",
    sign: "Potpiši",
    verify: "Proveri",
    algorithm: "Algoritam",
    message: "Poruka",
    privateKey: "Privatni ključ (PEM)",
    publicKey: "Javni ključ (PEM)",
    signatureValue: "Potpis",
    encoding: "Zapis",
    encodingHex: "Hex",
    encodingBase64: "Base64",
    saltLength: "Dužina soli (PSS)",
    saltHint: "Prazno = podrazumevana dužina za izabrani heš.",
    errSaltShape: "Dužinu soli upiši kao ceo broj bajtova ili ostavi prazno.",
    hash: "Heš",
    generateEc: "Generiši EC par",
    copySignature: "Kopiraj potpis",
    hex: "Hex",
    base64: "Base64",
    valid: "Potpis je ispravan",
    invalid: "Potpis nije ispravan",
    ecdsaNote:
      "ECDSA potpis je sirovi par r i s (P1363), ne DER — OpenSSL podrazumevano pravi " +
      "DER i ta dva zapisa se ne proveravaju međusobno.",
    errUnsupported: "Algoritam {subject} nije podržan.",
    errPem: "PEM blok nije ispravan.",
    errKeyImport: "Ključ ne odgovara izabranom algoritmu.",
    errInvalidHex: "Potpis nije ispravan hex.",
    errInvalidBase64: "Potpis nije ispravan base64.",
    errSign: "Potpisivanje nije uspelo — proveri dužinu soli.",
  },
} as const;
