/**
 * „Strukturirani podaci" — the Serbian copy of this category's tool surfaces.
 *
 * One entry per tool id, keyed exactly as the registration in
 * `shared/modules.ts` spells it. The tool's NAME and its one-line blurb are not
 * here: those live in the `name` and `blurb` tables of `./devtools.ts`, because
 * the drawer's rail needs them before any surface is opened.
 *
 * `position` and `errors` are hoisted OUT of the six tools below them, rather
 * than repeated inside each: four of the six (`jsonEditor`, `yamlEditor`,
 * `xmlEditor`, `dataFormat`) read a `StructuredError` from
 * `@nexus/core/devtools/*`, and every one of those carries the same
 * `{code, expected, found, line, column}` shape. The 81 codes are already
 * namespaced by their module prefix (`json.`, `path.`, `yaml.`, `xml.`,
 * `xpath.`, `toml.`, `csv.`, `convert.`) so one flat table holds all of them
 * without collision — and the one code that genuinely crosses tools
 * (`convert.yaml-multiple-documents`, raised by both the YAML editor reading a
 * multi-document stream and the format converter) is translated once instead
 * of twice.
 */
export const DEVTOOLS_DATA_SR = {
  indent: "Uvlačenje",
  indentTab: "Tabulator",

  /** The words `data.tsx`'s `formatStructuredError` composes a sentence from. */
  position: {
    expected: "očekivano",
    found: "pronađeno",
    line: "red",
    column: "kolona",
  },

  /** Every `StructuredErrorCode` / `YamlErrorCode` / `XmlErrorCode` — see the header. */
  errors: {
    "json.unexpected-end": "Dokument se prekida pre kraja",
    "json.unexpected-char": "Neočekivan znak",
    "json.trailing-content": "Suvišan sadržaj posle vrednosti",
    "json.leading-zero": "Broj ne sme počinjati nulom",
    "json.missing-fraction": "Nedostaju decimale posle tačke",
    "json.missing-exponent": "Nedostaje eksponent",
    "json.unterminated-string": "Nezatvoren navodnik",
    "json.bad-escape": "Nepoznata escape sekvenca",
    "json.bad-unicode-escape": "Neispravan \\u zapis",
    "json.control-char": "Kontrolni znak mora biti escape-ovan",
    "json.duplicate-key": "Ključ se ponavlja",
    "json.number-not-exact": "Broj bi bio zaokružen — zapiši ga kao tekst",
    "json.no-nan": "JSON nema zapis za NaN ni za beskonačno",
    "path.expected-root": "Putanja mora počinjati sa $",
    "path.expected-segment": "Očekivan naziv",
    "path.unexpected-char": "Neočekivan znak u putanji",
    "path.unterminated-quote": "Nezatvoren navodnik u putanji",
    "path.unsupported": "Ovaj deo JSONPath-a nije podržan",
    "yaml.tab-indent": "Tabulator u uvlačenju — YAML dozvoljava samo razmake",
    "yaml.directive": "Direktive (%YAML, %TAG) nisu podržane",
    "yaml.anchor": "Sidra (&) nisu podržana",
    "yaml.alias": "Alijasi (*) nisu podržani",
    "yaml.tag": "Eksplicitne oznake (!!) nisu podržane",
    "yaml.complex-key": "Složeni ključevi (?) nisu podržani",
    "yaml.nested-flow": "Ugnježdeni flow zapis nije podržan",
    "yaml.unterminated-flow": "Nezatvorena flow kolekcija",
    "yaml.bad-indent": "Pogrešno uvlačenje",
    "yaml.expected-key": "Očekivan ključ",
    "yaml.duplicate-key": "Ključ se ponavlja",
    "yaml.unterminated-quote": "Nezatvoren navodnik",
    "yaml.bad-escape": "Nepoznata escape sekvenca",
    "yaml.trailing-content": "Suvišan sadržaj posle vrednosti",
    "yaml.multiline-plain-scalar":
      "Tekst u više redova bez navodnika — koristi navodnike ili | blok",
    "yaml.bad-block-header": "Neispravno zaglavlje bloka",
    "yaml.number-not-exact": "Broj bi bio zaokružen — zapiši ga kao tekst",
    "xml.unexpected-char": "Neočekivan znak — < u tekstu mora biti &lt;",
    "xml.bad-name": "Neispravan naziv",
    "xml.unclosed-tag": "Tag nije zatvoren",
    "xml.mismatched-close": "Zatvara se pogrešan tag",
    "xml.stray-close": "Zatvaranje bez otvaranja",
    "xml.duplicate-attribute": "Atribut se ponavlja",
    "xml.unterminated-comment": "Nezatvoren komentar",
    "xml.unterminated-cdata": "Nezatvoren CDATA blok",
    "xml.unterminated-instruction": "Nezatvorena instrukcija",
    "xml.unterminated-doctype": "Nezatvoren DOCTYPE",
    "xml.unterminated-tag": "Nezatvoren tag",
    "xml.unterminated-attribute": "Nezatvorena vrednost atributa",
    "xpath.expected-absolute": "Putanja mora počinjati sa /",
    "xpath.expected-name": "Očekivan naziv elementa",
    "xpath.unexpected-char": "Neočekivan znak u putanji",
    "xpath.unterminated-quote": "Nezatvoren navodnik u putanji",
    "xpath.unsupported": "Ovaj deo XPath-a nije podržan",
    "toml.unexpected-char": "Neočekivan znak",
    "toml.expected-equals": "Očekivano =",
    "toml.bad-key": "Neispravan ključ",
    "toml.bad-value": "Neispravna vrednost",
    "toml.bad-number": "Neispravan broj",
    "toml.number-not-exact": "Broj bi bio zaokružen — zapiši ga kao tekst",
    "toml.unterminated-string": "Nezatvoren navodnik",
    "toml.bad-escape": "Nepoznata escape sekvenca",
    "toml.unterminated-array": "Nezatvoren niz",
    "toml.unterminated-header": "Nezatvoreno zaglavlje tabele",
    "toml.duplicate-key": "Ključ se ponavlja",
    "toml.redefined-table": "Tabela je već definisana",
    "toml.inline-table-unsupported": "Inline tabele ({ }) nisu podržane",
    "toml.datetime-unsupported": "Datumi i vremena nisu podržani",
    "toml.trailing-content": "Suvišan sadržaj u redu",
    "csv.unterminated-quote": "Nezatvoren navodnik",
    "csv.text-after-quote": "Tekst posle zatvorenog navodnika",
    "csv.ragged-row": "Red nema isti broj polja kao zaglavlje",
    "csv.duplicate-header": "Naziv kolone se ponavlja",
    "csv.no-rows": "Nema nijednog reda",
    "convert.csv-needs-rows": "Za CSV je potreban niz redova",
    "convert.csv-nesting": "CSV ne može da drži ugnježdenu vrednost",
    "convert.csv-null": "CSV nema null — uključi „prazno polje umesto null\" ako odgovara",
    "convert.csv-ragged-object": "Objekti nemaju iste kolone",
    "convert.toml-root-not-table": "TOML koren mora biti tabela",
    "convert.toml-null": "TOML nema null",
    "convert.toml-mixed-array": "Niz meša tabele i obične vrednosti",
    "convert.toml-object-in-array": "Tabela unutar niza nije podržana",
    "convert.yaml-multiple-documents": "Tok ima više dokumenata — izaberi jedan",
  },

  jsonEditor: {
    title: "JSON",
    source: "Izvor",
    sourcePlaceholder: "Nalepi JSON…",
    format: "Formatiraj",
    minify: "Minifikuj",
    sortKeys: "Sredi ključeve",
    validate: "Proveri",
    valid: "JSON je ispravan.",
    pathTitle: "JSONPath",
    path: "Putanja",
    pathPlaceholder: "$.stavke[*].naziv",
    hits: "Pogodaka",
    noHits: "Nema pogodaka.",
    hitIndex: "#",
    hitValue: "Vrednost",
  },

  yamlEditor: {
    title: "YAML",
    source: "Izvor",
    sourcePlaceholder: "Nalepi YAML…",
    viewJson: "Kao JSON",
    viewYaml: "Kao YAML",
    sortKeys: "Sortiraj ključeve",
    document: "Dokument",
    documents: "Dokumenata",
  },

  xmlEditor: {
    title: "XML",
    source: "Izvor",
    sourcePlaceholder: "Nalepi XML ili HTML…",
    format: "Formatiraj",
    minify: "Minifikuj",
    validate: "Proveri",
    valid: "Markup je ispravan.",
    pathTitle: "XPath",
    path: "Putanja",
    pathPlaceholder: "//stavka[@id='a']",
    hits: "Pogodaka",
    noHits: "Nema pogodaka.",
    element: "Element",
    attributes: "Atributi",
    text: "Tekst",
  },

  dataFormat: {
    title: "Konverzija formata",
    source: "Izvor",
    sourcePlaceholder: "Nalepi sadržaj…",
    from: "Iz",
    to: "U",
    swap: "Zameni strane",
    limitsTitle: "Šta se ne prenosi",
    outputOptions: "Izlazne opcije",
    sortKeys: "Sortiraj ključeve",
    csvOptions: "CSV opcije",
    delimiter: "Razdvajač",
    header: "Prvi red je zaglavlje",
    nullAsEmpty: "Prazno polje umesto null",
    formats: {
      json: "JSON",
      yaml: "YAML",
      toml: "TOML",
      csv: "CSV",
    },
    limits: {
      "limit.comments-lost": "Komentari se gube",
      "limit.csv-flat-only": "CSV drži samo ravnu tabelu — ugnježdavanje ne prolazi",
      "limit.csv-text-only": "Iz CSV-a je sve tekst — brojevi se ne pogađaju",
      "limit.csv-no-null": "CSV nema null — prazno polje se čita kao prazan tekst",
      "limit.toml-root-table": "TOML koren mora biti tabela, ne niz",
      "limit.toml-no-null": "TOML nema null",
      "limit.toml-no-datetime": "Datumi i vremena nisu podržani",
      "limit.json-no-nan": "JSON nema NaN ni beskonačno",
      "limit.yaml-no-anchors": "Sidra i alijasi nisu podržani",
    },
  },

  jsonToTypes: {
    title: "JSON u tipove",
    source: "JSON uzorak",
    sourcePlaceholder: "Nalepi JSON…",
    targetLabel: {
      interface: "TypeScript interface",
      type: "TypeScript type",
      zod: "Zod šema",
    },
    rootName: "Naziv korenskog tipa",
    rootNamePlaceholder: "Root",
    options: "Podešavanja",
    readonly: "readonly polja",
    inlineSingleUse: "Ugradi tipove korišćene jednom",
    optionalStyle: "Opciona polja",
    optionalQuestion: "polje?",
    optionalUndefined: "| undefined",
    output: "Deklaracije",
    typesCount: "Broj tipova",
    errors: {
      empty: "Unesi JSON uzorak.",
      syntax: "Nije validan JSON.",
      too_deep: "Uzorak je ugnježden previše duboko za obradu.",
    },
  },

  uuid: {
    generateTitle: "Generisanje",
    genV4: "UUID v4",
    genV7: "UUID v7",
    genUlid: "ULID",
    generateEmpty: "Izaberi vrstu identifikatora.",
    inspectTitle: "Inspekcija",
    inspectLabel: "Identifikator",
    inspectPlaceholder: "Nalepi UUID ili ULID…",
    invalid: "Ovo nije ispravan UUID ni ULID.",
    canonical: "Kanonski oblik",
    variant: "Varijanta",
    variantLabel: {
      ncs: "NCS",
      rfc4122: "RFC 9562",
      microsoft: "Microsoft",
      future: "Rezervisano",
    },
    version: "Verzija",
    special: "Poseban oblik",
    specialLabel: {
      nil: "Nil UUID (sve nule)",
      max: "Max UUID (sve jedinice)",
    },
    timestamp: "Vreme (ms)",
    timestampIso: "Vreme (ISO 8601)",
    randomness: "Nasumičnost (heks)",
  },
} as const;
