/**
 * „Agro" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. The tool's NAME and its one-line blurb are not here: those
 * live in `./pro.ts`'s `name`/`blurb` tables, because the drawer's rail needs
 * them before any surface is opened.
 *
 * **A unit is copy, not a constant** — written here rather than concatenated
 * in a component, so a translator can find it and `check:strings` can see it.
 *
 * **Nothing in here judges.** `fertiliser-nutrient-blend`, `sprayer-calibration`
 * and `tank-mix-dose` are `life-safety`: their copy may name a quantity and
 * the user's own limit, and never says what the two mean together.
 */
export const PRO_AGRO_SR = {
  "bale-count-storage": {
    shape: "Oblik bale",
    shapeRound: "Rolo (valjak)",
    shapeSquare: "Kvadratna (kvadar)",
    diameterM: "Prečnik role",
    diameterMHint: "U metrima, 0,5 do 2,5 m.",
    roundWidthM: "Širina role",
    roundOrientation: "Orijentacija pri slaganju",
    orientationOnEnd: "Na čelo (stoji)",
    orientationOnSide: "Na obod (leži)",
    orientationFootprint: "Stopa d × š",
    orientationOnLengthFace: "Na uzdužnu stranu",
    orientationOnWidthFace: "Na bočnu stranu",
    lengthM: "Dužina bale",
    squareWidthM: "Širina bale",
    heightM: "Visina bale",
    massMode: "Način zadavanja mase",
    massModeMeasured: "Izmerena masa bale",
    massModeDensity: "Gustina bale",
    measuredMassKg: "Masa jedne bale",
    densityKgM3: "Gustina bale",
    densityKgM3Hint:
      "Izmerena za konkretan materijal i presu, 30 do 400 kg/m³. Nexus je ne pretpostavlja.",
    quantityMode: "Način zadavanja prinosa",
    quantityModeYield: "Prinos po hektaru",
    quantityModeTotal: "Ukupna masa",
    yieldTHa: "Prinos",
    totalMassT: "Ukupna masa",
    areaHa: "Površina",
    areaHaHint:
      "Obavezno pri prinosu po hektaru; opciono pri ukupnoj masi, za broj bala po hektaru.",
    balingLossPercent: "Gubitak pri baliranju",
    storage: "Skladište (opciono)",
    storageLengthM: "Dužina skladišta",
    storageWidthM: "Širina skladišta",
    storageHeightM: "Korisna visina slaganja",
    storageHeightMHint:
      "Tvoj unos — Nexus je ne određuje i ne proverava nosivost ni stabilnost slaganja.",

    results: "Rezultat",
    baleVolume: "Zapremina jedne bale",
    baleMass: "Masa jedne bale",
    totalMassAfterLoss: "Ukupna masa posle gubitka",
    countExact: "Broj bala (tačno)",
    countCeil: "Broj bala (zaokruženo naviše)",
    totalVolume: "Ukupna zapremina bala",
    balesPerHa: "Bala po hektaru",
    storageResults: "Slaganje u skladištu",
    storageOrientation: "Orijentacija u skladištu",
    storagePerRow: "Bala u redu",
    storagePerColumn: "Bala u koloni",
    storagePerLayer: "Bala po sloju",
    storageLayers: "Broj slojeva",
    storageCapacity: "Kapacitet",
    storageCapacityTonnes: "Kapacitet",
    unusedLength: "Neiskorišćena dužina",
    unusedWidth: "Neiskorišćena širina",
    shortfall: "Potrebno naspram kapaciteta (razlika)",
    stackingNote:
      "Samo geometrijsko slaganje po unetim merama. Stabilnost slaganja, opterećenje poda i " +
      "dozvoljena visina nisu deo ovog računa. Šestougaono (piramidalno) slaganje rolo bala se " +
      "ne računa.",

    inputs: "Uneseno",
    formula:
      "V = π·(D/2)²·B (rolo) ili d·š·v (kvadratna)     n = M / m_b     kapacitet = po_sloju × " +
      "slojeva",

    errorShape: "Unesi dimenzije za izabrani oblik bale.",
    errorDiameterM: "Prečnik role mora biti između 0,5 i 2,5 m.",
    errorWidthM: "Širina mora biti u dozvoljenom opsegu za izabrani oblik bale.",
    errorLengthM: "Dužina bale mora biti između 0,3 i 3 m.",
    errorHeightM: "Visina bale mora biti između 0,3 i 3 m.",
    errorMeasuredMassKg: "Izmerena masa bale mora biti veća od nule.",
    errorDensityKgM3: "Gustina bale mora biti između 30 i 400 kg/m³.",
    errorBaleMassKg: "Masa bale ispada nula ili manje — proveri unetu masu ili gustinu.",
    errorBalingLossPercent: "Gubitak pri baliranju je između 0 i 30 %.",
    errorAreaHa: "Površina mora biti veća od nule.",
    errorYieldTHa: "Prinos mora biti veći od nule.",
    errorTotalMassT: "Ukupna masa mora biti veća od nule.",
    errorStorageLengthM: "Dužina skladišta mora biti veća od nule.",
    errorStorageWidthM: "Širina skladišta mora biti veća od nule.",
    errorUsableHeightM: "Korisna visina slaganja mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM: "m",
    unitM3: "m³",
    unitKg: "kg",
    unitT: "t",
    unitHa: "ha",
    unitPercent: "%",
  },

  "bee-syrup-mix": {
    preset: "Odnos šećer:voda",
    presetCustom: "Proizvoljan",
    ratioA: "Šećer (deo odnosa)",
    ratioHint: "Po masi — 1 l vode je 1 kg, pa se osnova po masi i po zapremini poklapaju.",
    ratioB: "Voda (deo odnosa)",
    given: "Šta se zadaje",
    givenTargetVolume: "Ciljana zapremina sirupa",
    givenTargetMass: "Ciljana masa sirupa",
    givenAvailableSugar: "Raspoloživa masa šećera",
    value: "Zadata vrednost",
    valueHint: "Litara za ciljanu zapreminu, kilograma za ciljanu masu ili raspoloživi šećer.",
    hiveCount: "Broj košnica",
    literPerHive: "Količina po košnici",
    bagMassKg: "Masa vreće šećera",

    results: "Rezultat",
    sugarKg: "Masa šećera",
    waterVolumeL: "Zapremina vode",
    waterMassKg: "Masa vode",
    syrupMassKg: "Masa sirupa",
    syrupVolumeL: "Zapremina sirupa",
    densityKgL: "Gustina sirupa",
    densityEstimated: "izračunato",
    densityNote:
      "Izračunata iz prividne zapremine rastvorene saharoze (0,63 l/kg), ne izmerena. Vrednosti " +
      "važe za oko 20 °C.",
    concentrationPercent: "Koncentracija (maseni %)",
    bagsExact: "Broj vreća (tačno)",
    bagsCeil: "Broj vreća (zaokruženo naviše)",
    hivesCovered: "Pokriveno košnica",
    hivesRemainderL: "Ostatak sirupa",
    apiary: "Za ceo pčelinjak",
    apiaryVolumeL: "Ukupna zapremina",
    apiarySugarKg: "Ukupno šećera",
    apiaryBagsCeil: "Broj vreća",

    inputs: "Uneseno",
    ratio: "Odnos",
    formula: "V_v = V/(1 + 0,63r)     S = r·V_v     V = V_v + 0,63·S     ρ = M/V",

    errorRatioA: "Deo odnosa za šećer mora biti veći od nule.",
    errorRatioB: "Deo odnosa za vodu mora biti veći od nule.",
    errorValue: "Zadata vrednost mora biti veća od nule.",
    errorBagMassKg: "Masa vreće šećera mora biti veća od nule.",
    errorHiveCount: "Broj košnica mora biti veći od nule.",
    errorLiterPerHive: "Količina po košnici mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitKg: "kg",
    unitL: "l",
    unitKgL: "kg/l",
    unitPercent: "%",
  },

  "cadastral-area-units": {
    value: "Vrednost",
    fromUnit: "Polazna jedinica",
    jutroM2Override: "Vrednost katastarskog jutra u m² (opciono)",
    jutroM2OverrideHint:
      "Stariji listovi nepokretnosti u Srbiji nekad nose lokalno jutro drugačije veličine. " +
      "Prazno polje koristi objavljenih 5754,6425 m².",

    results: "Rezultat",
    resultM2: "Kvadratni metri",
    resultAr: "Ari",
    resultHa: "Hektari",
    resultHvat2: "Kvadratni hvati",
    resultJutro: "Katastarska jutra",
    jutroUsed: "Upotrebljena vrednost jutra",
    sourceNote:
      "Austrougarska metrikacija (Austrija: zakon iz 1871, u primeni od 1876): 1 bečki hvat = " +
      "1,896484 m, 1 katastarsko jutro = 1600 kvadratnih hvati = 5754,6425 m².",

    inputs: "Uneseno",
    formula:
      "sve preko m²: m² = vrednost × faktor(jedinica); rezultat = m² ÷ faktor(ciljana jedinica)",

    errorValue: "Vrednost mora biti nula ili veća, i ne veća od 1×10¹² m².",
    errorJutroM2Override: "Vrednost katastarskog jutra u m² mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM2: "m²",
    unitAr: "ar",
    unitHa: "ha",
    unitHvat2: "kvadratni hvat",
    unitJutro: "katastarsko jutro",
  },

  "fertiliser-nutrient-blend": {
    direction: "Smer računa",
    directionForward: "Iz hraniva u đubrivo",
    directionReverse: "Iz đubriva u hraniva",
    targetForm: "Ciljevi za P i K zadati kao",
    targetFormOxide: "Oksid (P₂O₅, K₂O)",
    targetFormElement: "Element (P, K)",
    targetN: "Ciljana količina azota (N)",
    targetHint:
      "Iz preporuke na osnovu analize zemljišta ili propisanog ograničenja unosa. Tvoj unos.",
    targetP2o5: "Ciljana količina P₂O₅",
    targetK2o: "Ciljana količina K₂O",
    targetPElement: "Ciljana količina P",
    targetKElement: "Ciljana količina K",
    primary: "Osnovno đubrivo",
    secondary: "Dopunsko đubrivo (opciono)",
    composition: "Sastav đubriva",
    compositionN: "N (%)",
    compositionP2o5: "P₂O₅ (%)",
    compositionK2o: "K₂O (%)",
    lead: "Vodeće hranivo",
    leadN: "N",
    leadP2o5: "P₂O₅",
    leadK2o: "K₂O",
    leadNone: "Nema dopunskog đubriva",
    doseKgHa: "Doza đubriva",
    areaHa: "Površina",
    bagMassKg: "Masa vreće",

    results: "Rezultat",
    line: "Đubrivo",
    totalKg: "Ukupno za površinu",
    bagsExact: "Broj vreća (tačno)",
    bagsCeil: "Broj vreća (zaokruženo naviše)",
    actualDoseKgHa: "Stvarna doza (posle zaokruženja vreća)",
    delivered: "Šta unetа đubriva donose po hektaru",
    deliveredN: "N",
    deliveredP2o5: "P₂O₅",
    deliveredK2o: "K₂O",
    deliveredPElement: "P (element)",
    deliveredKElement: "K (element)",
    totalDeliveredN: "Ukupno N za površinu",
    totalDeliveredP2o5: "Ukupno P₂O₅ za površinu",
    totalDeliveredK2o: "Ukupno K₂O za površinu",
    balance: "Cilj naspram isporučenog",
    targetMinusDeliveredN: "Cilj − isporučeno (N)",
    targetMinusDeliveredP2o5: "Cilj − isporučeno (P₂O₅)",
    targetMinusDeliveredK2o: "Cilj − isporučeno (K₂O)",
    userInputNote:
      "Ciljane količine i sastav đubriva su tvoj unos sa deklaracije i preporuke. Nexus ih ne " +
      "poznaje, ne pamti i ne predlaže.",

    inputs: "Uneseno",
    formula:
      "X = 100·cilj / procenat_vodećeg     isporučeno_j = X·procenat_j/100     cilj − isporučeno",

    errorAreaHa: "Površina mora biti veća od nule.",
    errorBagMassKg: "Masa vreće mora biti veća od nule.",
    errorComposition: "Sastav đubriva mora biti u opsegu 0–100 % po hranivu, sa zbirom do 100 %.",
    errorDoseKgHa: "Doza đubriva mora biti veća od nule.",
    errorTargetN: "Ciljana količina azota je između 0 i 500 kg/ha.",
    errorTargetP: "Ciljana količina fosfora je između 0 i 500 kg/ha.",
    errorTargetK: "Ciljana količina kalijuma je između 0 i 500 kg/ha.",
    errorPrimary:
      "Sastav osnovnog đubriva mora biti u opsegu 0–100 % po hranivu, sa zbirom do 100 %.",
    errorSecondary:
      "Sastav dopunskog đubriva mora biti u opsegu 0–100 % po hranivu, sa zbirom do 100 %.",
    errorPrimaryLead: "Izabrano vodeće hranivo osnovnog đubriva mora imati procenat veći od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitKg: "kg",
    unitKgHa: "kg/ha",
    unitHa: "ha",
  },

  "grain-moisture-shrink": {
    grossMassKg: "Bruto masa",
    measuredMoisturePercent: "Izmerena vlaga",
    targetMoisturePercent: "Ciljana (ugovorena) vlaga",
    targetMoisturePercentHint: "Iz ugovora o otkupu. Nexus ga ne zna i ne predlaže.",
    impuritiesPercent: "Primese",
    impuritiesFreeLimitPercent: "Primese bez odbitka",
    impuritiesFreeLimitPercentHint:
      "Iz ugovora o otkupu ili pravilnika otkupljivača. Nexus ga ne zna i ne predlaže.",
    order: "Redosled odbitaka",
    orderImpuritiesFirst: "Prvo primese pa vlaga",
    orderMoistureFirst: "Prvo vlaga pa primese",
    deductionMode: "Odbitak primesa",
    deductionModeExcessOnly: "Samo iznad dozvoljenog (jednosmerno)",
    deductionModeTwoSided: "I ispod dozvoljenog, kao dobitak (dvosmerno)",
    pricePerKg: "Cena po kilogramu",
    dryerEfficiencyPercent: "Korisna toplota sušare",

    results: "Rezultat",
    driedMassKg: "Masa posle sušenja (samo vlaga)",
    waterOutKg: "Izašla voda",
    shrinkPercent: "Kalo (od bruto mase)",
    shrinkPercentMassIndependent: "Kalo (kontrola, nezavisno od mase)",
    physicalModelNote:
      "Fizički model gubitka samo vode: bez gubitka suve materije i bez gubitka na manipulaciji " +
      "i prašini u sušari. Razlika prema kolskoj vagi može poticati odatle. Gornja masa i voda " +
      "su bazne vrednosti pri gubitku samo od vlage, bez primesa — stvarno izdvojena voda pri " +
      "sušenju je u granama ispod, po izabranom redosledu.",
    impuritiesFirst: "Prvo primese pa vlaga",
    moistureFirst: "Prvo vlaga pa primese",
    impurityDeductionKg: "Odbitak primesa",
    finalMassKg: "Konačna masa",
    selected: "Izabrani redosled",
    value: "Vrednost",
    grossValue: "Vrednost bruto mase",
    netValue: "Vrednost konačne mase",
    valueDifference: "Razlika",
    energy: "Energija sušenja",
    minimumEnergyMJ: "Teorijski minimum",
    minimumEnergyKWh: "Teorijski minimum",
    actualEnergyMJ: "Pri unetoj korisnoj toploti",
    actualEnergyKWh: "Pri unetoj korisnoj toploti",

    inputs: "Uneseno",
    formula:
      "m₂ = m₁·(100−w₁)/(100−w₂)     kalo % = (w₁−w₂)/(100−w₂)×100     odbitak = m·(p−p₀)/100",

    errorGrossMassKg: "Bruto masa mora biti veća od nule.",
    errorMeasuredMoisturePercent: "Izmerena vlaga je između 0 i 60 %.",
    errorTargetMoisturePercent: "Ciljana vlaga je između 0 i 60 % i mora biti manja od 100.",
    errorImpuritiesPercent: "Primese su između 0 i 50 %.",
    errorImpuritiesFreeLimitPercent: "Dozvoljeni procenat primesa je između 0 i 50 %.",
    errorPricePerKg: "Cena po kilogramu ne može biti negativna.",
    errorDryerEfficiencyPercent: "Korisna toplota sušare je između 1 i 100 %.",
    errorGeneric: "Proveri unete vrednosti.",

    unitKg: "kg",
    unitPercent: "%",
    unitRsd: "RSD",
    unitMj: "MJ",
    unitKwh: "kWh",
  },

  "growing-degree-days": {
    rowsText: "Dnevne temperature",
    rowsTextHint:
      "Nalepi jedan red po danu: datum;maksimalna °C;minimalna °C. Razdvajač je tabulator, " +
      "tačka-zarez ili zarez, datum u obliku DD.MM.GGGG.",
    baseTempC: "Bazna temperatura",
    baseTempCHint:
      "Tvoj izbor prema kulturi. Nexus ne bira kulturu i ne tvrdi da je 10 °C tačna za bilo koju.",
    upperLimitC: "Gornja granica (modifikovani metod)",
    targetSum: "Ciljana suma",
    averageWindowDays: "Period za prosek pri projekciji",

    results: "Rezultat",
    colDate: "Datum",
    colSimpleDaily: "Prosti (dan)",
    colSimpleCumulative: "Prosti (kumulativ)",
    colModifiedDaily: "Modifikovani (dan)",
    colModifiedCumulative: "Modifikovani (kumulativ)",
    totalSimple: "Ukupno, prosti metod",
    totalModified: "Ukupno, modifikovani metod",
    averageSimple: "Prosek za ceo period",
    averageSimpleRecent: "Prosek za poslednjih",
    days: "dana",
    zeroContributionDays: "Dana sa nultim doprinosom",
    projection: "Projekcija do cilja",
    remainingToTarget: "Preostalo do cilja",
    daysToTarget: "Dana pri prosečnom tempu",
    projectedDate: "Projektovani datum",
    projectionNote: "Linearna ekstrapolacija unetih temperatura, ne prognoza.",

    inputs: "Uneseno",
    rowCount: "Broj dana u nizu",
    formula:
      "prosti: max(0, (Tmax+Tmin)/2 − baza)     modifikovani: seče Tmin odozdo i Tmax odozgo pre " +
      "proseka",

    errorParse: "Nalepljeni red mora biti datum;maksimalna;minimalna, datum u obliku DD.MM.GGGG.",
    errorReadings: "Niz mora imati od 1 do 400 dana.",
    errorBaseTempC: "Bazna temperatura je između −10 i 30 °C.",
    errorUpperLimitC: "Gornja granica je između 10 i 45 °C i ne sme biti ispod bazne temperature.",
    errorTargetSum: "Ciljana suma mora biti veća od nule.",
    errorAverageWindowDays: "Period za prosek je ceo broj od 1 do 60 dana.",
    errorTMaxC: "Maksimalna temperatura je između −40 i 55 °C u svakom redu.",
    errorTMinC: "Minimalna temperatura je između −40 i 55 °C u svakom redu.",
    errorRowOrder: "Minimalna temperatura ne sme biti veća od maksimalne u istom redu.",
    errorDateOrder: "Datumi moraju biti rastući, bez ponavljanja.",
    errorGeneric: "Proveri unete vrednosti.",

    unitDeg: "°C",
  },

  "honey-mass-moisture": {
    quantityMode: "Način zadavanja količine",
    quantityModeGrossTare: "Izmerena bruto masa sa tarom",
    quantityModeVolume: "Zapremina posude",
    grossMassKg: "Bruto masa",
    tareKg: "Tara (masa prazne posude)",
    containerVolumeL: "Zapremina posude",
    densityKgL: "Gustina meda",
    densityKgLHint:
      "Izmerena, 1,35 do 1,50 kg/l — merenjem mase poznate zapremine ili iz tabele koju imaš. " +
      "Nije izvedena iz vlage.",
    sampleMassKg: "Merenje gustine: masa uzorka (opciono)",
    sampleHint: "Za nezavisnu proveru gustine — masa i zapremina uzorka zajedno.",
    sampleVolumeL: "Merenje gustine: zapremina uzorka",
    moisturePercent: "Vlaga (refraktometar)",
    targetMoisturePercent: "Ciljana vlaga posle sušenja",
    jarVolumeMl: "Zapremina tegle",
    jarDeclaredNetMassG: "Deklarisana neto masa tegle",
    jarToleranceG: "Dozvoljeno odstupanje po tegli",
    jarToleranceGHint: "Iz propisa ili dogovora sa kupcem. Nexus ga ne zna i ne predlaže.",
    pricePerKg: "Cena po kilogramu",

    results: "Rezultat",
    netMassKg: "Neto masa meda",
    volumeFromMassL: "Zapremina iz mase",
    measuredDensityKgL: "Gustina iz uzorka",
    independenceNote: "Gustina i vlaga se unose nezavisno — nijedna nije izvedena iz druge.",
    waterMassKg: "Masa vode",
    dryMatterMassKg: "Masa suve materije",
    drying: "Sušenje na ciljanu vlagu",
    driedMassKg: "Masa posle sušenja",
    waterRemovedKg: "Izašla voda",
    shrinkPercent: "Gubitak",
    jars: "Tegle",
    massPerJarKg: "Masa meda po tegli",
    massPerJarG: "Masa meda po tegli",
    fullJars: "Punih tegli",
    jarRemainderKg: "Ostatak",
    jarsFromDeclaredMass: "Broj tegli od deklarisane neto mase",
    fillMassVsDeclaredG: "Masa punjenja − deklarisana masa",
    value: "Vrednost",
    grossValue: "Vrednost neto mase",
    driedValue: "Vrednost posle sušenja",

    inputs: "Uneseno",
    formula: "m = bruto − tara (ili V·ρ)     voda = m·w/100     m₂ = m·(100−w₁)/(100−w₂)",

    errorGrossMassKg: "Bruto masa mora biti veća od nule.",
    errorTareKg: "Tara ne sme biti negativna.",
    errorNetMassKg: "Neto masa (bruto − tara) mora biti veća od nule.",
    errorContainerVolumeL: "Zapremina posude mora biti veća od nule.",
    errorDensityKgL: "Gustina meda mora biti između 1,35 i 1,50 kg/l.",
    errorSampleMassKg: "Masa uzorka za merenje gustine mora biti veća od nule.",
    errorSampleVolumeL: "Zapremina uzorka za merenje gustine mora biti veća od nule.",
    errorSampleDensity: "Gustina iz uzorka je van opsega 1,35 do 1,50 kg/l.",
    errorMoisturePercent: "Vlaga mora biti između 12 i 25 %.",
    errorTargetMoisturePercent: "Ciljana vlaga mora biti između 12 i 25 %.",
    errorJarVolumeMl: "Zapremina tegle mora biti veća od nule.",
    errorJarDeclaredNetMassG: "Deklarisana neto masa tegle mora biti veća od nule.",
    errorJarToleranceG: "Dozvoljeno odstupanje po tegli ne sme biti negativno.",
    errorPricePerKg: "Cena po kilogramu ne može biti negativna.",
    errorGeneric: "Proveri unete vrednosti.",

    unitKg: "kg",
    unitG: "g",
    unitL: "l",
    unitKgL: "kg/l",
    unitPercent: "%",
    unitRsd: "RSD",
  },

  "irrigation-depth-volume": {
    normMm: "Zalivna norma",
    normMmHint: "Tvoj unos, 0,5 do 200 mm. Nexus je ne predlaže.",
    areaHa: "Površina",
    efficiencyPercent: "Efikasnost sistema",
    efficiencyPercentHint: "Svojstvo konkretnog sistema, 30 do 100 %. Nexus je ne pretpostavlja.",
    flowUnit: "Jedinica raspoloživog protoka",
    flowUnitM3h: "m³/h",
    flowUnitLs: "l/s",
    flowValue: "Raspoloživ protok",
    method: "Način zalivanja",
    methodSprinkler: "Rasprskivači",
    methodDrip: "Kap po kap",
    spacingInRowM: "Razmak rasprskivača u redu",
    spacingBetweenRowsM: "Razmak redova rasprskivača",
    nozzleFlowUnit: "Jedinica protoka rasprskivača",
    nozzleFlowValue: "Protok jednog rasprskivača",
    dripsPerPlant: "Broj kapaljki po biljci",
    dripFlowLh: "Protok kapaljke",
    areaPerPlantM2: "Površina koja pripada jednoj biljci",
    hoursPerDay: "Broj sati rada dnevno",

    results: "Rezultat",
    netVolumeM3: "Neto zapremina",
    netVolumeL: "Neto zapremina",
    grossVolumeM3: "Bruto zapremina",
    flowM3h: "Protok",
    timeHours: "Vreme rada sistema",
    daysNeeded: "Broj dana",
    sprinklerResults: "Rasprskivači",
    intensityMmH: "Intenzitet kiše",
    netTimePerPositionH: "Vreme po poziciji (neto norma)",
    grossTimePerPositionH: "Vreme po poziciji (bruto norma)",
    positions: "Broj pozicija",
    positionsPerDay: "Pozicija dnevno",
    dripResults: "Kap po kap",
    netLitersPerPlant: "Litara po biljci (neto norma)",
    netDripDurationH: "Trajanje ciklusa (neto norma)",
    grossLitersPerPlant: "Litara po biljci (bruto norma)",
    grossDripDurationH: "Trajanje ciklusa (bruto norma)",

    inputs: "Uneseno",
    formula: "V_n = N·10·A     V_b = V_n/(η/100)     t = V_b/Q     I = q/(S_r·S_l)",

    errorNormMm: "Zalivna norma je između 0,5 i 200 mm.",
    errorAreaHa: "Površina mora biti veća od nule.",
    errorEfficiencyPercent: "Efikasnost sistema je između 30 i 100 %.",
    errorFlowValue: "Raspoloživ protok mora biti veći od nule.",
    errorHoursPerDay: "Broj sati rada dnevno je između 0,5 i 24.",
    errorSpacingInRowM: "Razmak rasprskivača u redu mora biti veći od nule.",
    errorSpacingBetweenRowsM: "Razmak redova rasprskivača mora biti veći od nule.",
    errorNozzleFlowLh: "Protok jednog rasprskivača mora biti veći od nule.",
    errorDripsPerPlant: "Broj kapaljki po biljci mora biti veći od nule.",
    errorDripFlowLh: "Protok kapaljke mora biti veći od nule.",
    errorAreaPerPlantM2: "Površina po biljci mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM3: "m³",
    unitL: "l",
    unitM3h: "m³/h",
    unitLh: "l/h",
    unitMm: "mm",
    unitMmH: "mm/h",
    unitHa: "ha",
    unitH: "h",
    unitMin: "min",
    unitPercent: "%",
  },

  "livestock-ration-dm": {
    headCount: "Broj grla",
    avgBodyMassKg: "Prosečna telesna masa",
    intakeMode: "Unos suve materije",
    intakeModePercent: "% telesne mase",
    intakeModeKg: "kg SM po grlu dnevno",
    intakeValue: "Vrednost unosa",
    intakeValueHint: "Tvoj izbor — Nexus ga ne predlaže.",
    feedsText: "Hraniva",
    feedsTextHint:
      "Nalepi jedan red po hranivu: naziv;sadržaj SM %;udeo u obroku po SM %;cena po kg sveže " +
      "mase (opciono);masa pakovanja u kg (opciono).",
    feedsTextPlaceholder: "silaža kukuruza;33;50;;250\nseno;86;20;;250\nsmeša;88;30;40;25",
    days: "Broj dana",
    wastePercent: "Gubitak (rastur) na jaslama",

    results: "Rezultat",
    dmPerHeadKgDay: "Suva materija po grlu",
    dmHerdKgDay: "Suva materija za stado",
    shareSumPercent: "Zbir unetih udela",
    colFeed: "Hranivo",
    colDmKgDay: "SM (kg/dan)",
    colFreshEaten: "Sveže, pojedeno (kg/dan)",
    colFreshIssued: "Sveže, izdato (kg/dan)",
    colPeriodIssued: "Izdato za period",
    colPackages: "Pakovanja",
    colCost: "Trošak/dan",
    freshIssuedKgPerDay: "izdato/dan",
    periodIssuedKg: "za period",
    packagesCeil: "pakovanja",
    totalFreshEatenKgDay: "Ukupno sveže, pojedeno",
    totalFreshIssuedKgDay: "Ukupno sveže, izdato",
    totalFreshEatenPerHeadKgDay: "Sveže po grlu",
    rationDmPercentAsIssued: "Sadržaj SM obroka kako se izdaje",
    cost: "Trošak",
    totalDailyCost: "Dnevni trošak",
    totalPeriodCost: "Trošak za period",

    inputs: "Uneseno",
    formula:
      "SM_grlo = masa·unos/100     SM_i = SM_stado·udeo/100     sveže = 100·SM_i/sadržaj_SM     " +
      "izdato = sveže/(1−rastur/100)",

    errorHeadCount: "Broj grla je ceo broj od 1 do 100000.",
    errorAvgBodyMassKg: "Prosečna telesna masa mora biti veća od nule.",
    errorIntakeValue:
      "Unos suve materije je 0,5 do 6 % telesne mase ili veći od nule u kg/grlu/dan.",
    errorFeeds: "Unesi od 1 do 20 hraniva.",
    errorDays: "Broj dana je ceo broj od 1 do 730.",
    errorWastePercent: "Gubitak na jaslama je između 0 i 30 %.",
    errorDmPercent: "Sadržaj suve materije hraniva je između 1 i 100 %.",
    errorShareOfDmPercent: "Udeo hraniva u obroku je između 0 i 100 %.",
    errorPricePerKgFresh: "Cena po kg sveže mase ne može biti negativna.",
    errorPackageMassKg: "Masa pakovanja mora biti veća od nule.",
    errorFeedParse:
      "Svaki red hraniva je naziv;sadržaj SM %;udeo %;cena (opciono);masa pakovanja (opciono).",
    errorGeneric: "Proveri unete vrednosti.",

    unitKg: "kg",
    unitPercent: "%",
    unitRsd: "RSD",
  },

  "machine-field-capacity": {
    nominalWidthM: "Radni zahvat",
    overlapPercent: "Preklop",
    speedKmh: "Radna brzina",
    utilizationPercent: "Iskorišćenje vremena",
    utilizationPercentHint:
      "Odnos čistog rada prema ukupnom vremenu, svojstvo konkretnog posla. Tvoj unos.",
    areaHa: "Površina",
    fuelLPerHour: "Potrošnja goriva",
    fuelPricePerL: "Cena goriva",
    hoursPerDay: "Radnih sati dnevno",
    turnSeconds: "Vreme jednog okretanja na uvratini",
    fieldLengthM: "Dužina parcele u pravcu rada",

    results: "Rezultat",
    actualWidthM: "Stvaran radni zahvat",
    theoreticalCapacityHaH: "Teorijski učinak",
    effectiveCapacityHaH: "Stvarni učinak",
    timeHours: "Vreme za celu površinu",
    daysNeeded: "Broj radnih dana",
    capacityPerDayHa: "Učinak po danu",
    lastDayHours: "Sati na poslednjem danu",
    fuel: "Gorivo",
    fuelLPerHa: "Gorivo po hektaru",
    fuelTotalL: "Gorivo ukupno",
    fuelCostPerHa: "Trošak goriva po hektaru",
    fuelCostTotal: "Trošak goriva ukupno",
    turns: "Okretanja",
    turnCount: "Broj okretanja",
    turnTimeHours: "Vreme okretanja",
    turnTimeSharePercent: "Udeo u radnom vremenu",

    inputs: "Uneseno",
    formula:
      "W = W_n·(1−preklop/100)     C_t = W·v/10     C_e = C_t·η     t = A/C_e     prohodi−1 " +
      "okretanja",

    errorNominalWidthM: "Radni zahvat je između 0,5 i 60 m.",
    errorOverlapPercent: "Preklop je između 0 i 30 %.",
    errorSpeedKmh: "Radna brzina je između 0,5 i 30 km/h.",
    errorUtilizationPercent: "Iskorišćenje vremena je između 30 i 100 %.",
    errorAreaHa: "Površina mora biti veća od nule.",
    errorHoursPerDay: "Radnih sati dnevno je između 0,5 i 24.",
    errorFuelLPerHour: "Potrošnja goriva mora biti veća od nule.",
    errorFuelPricePerL: "Cena goriva ne može biti negativna.",
    errorTurnSeconds: "Vreme okretanja je između 0 i 600 s.",
    errorFieldLengthM: "Dužina parcele mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM: "m",
    unitHa: "ha",
    unitHaH: "ha/h",
    unitH: "h",
    unitMin: "min",
    unitL: "l",
    unitLHa: "l/ha",
    unitKmh: "km/h",
    unitRsd: "RSD",
    unitPercent: "%",
  },

  "orchard-trellis-layout": {
    lengthM: "Dužina parcele (pravac redova)",
    widthM: "Širina parcele",
    rowSpacingM: "Razmak redova",
    headlandM: "Uvratina na svakom kraju reda",
    boundaryOffsetM: "Odstojanje prvog reda od međe",
    postSpacingM: "Razmak stubova u redu",
    postSpacingMHint: "Tvoj izbor — Nexus ga ne predlaže.",
    wireRows: "Broj redova žice",
    wireDiameterMm: "Prečnik žice",
    wireSlackPercent: "Dodatak na žicu za vezivanje i zatezanje",
    plantSpacingM: "Razmak sadnica u redu",
    anchorsPerEnd: "Sidara po kraju reda",
    coilLengthM: "Dužina koluta žice",
    coilLengthMHint: "Za broj koluta i kilograme po kolutu — žica se naručuje u kolutima.",
    plantAtBothEnds: "Sadnica na kraju reda",
    plantAtBothEndsYes: "Na oba kraja (floor + 1)",
    plantAtBothEndsNo: "Pomerena za pola razmaka (floor)",
    wireMassPerKmOverride: "Deklarisana masa žice po km (opciono)",
    wireMassPerKmOverrideHint:
      "Sa deklaracije pocinkovane žice — kada je uneta, koristi se umesto gustine čelika.",

    results: "Rezultat",
    rowsCount: "Broj redova",
    zeroRowsNote:
      "Uvratina ili odstojanje od međe su veći od raspoložive dužine ili širine — nema mesta ni " +
      "za jedan red.",
    rowLengthM: "Dužina jednog reda",
    totalRowLengthM: "Ukupna dužina redova",
    postsPerRow: "Stubova po redu",
    endPostsPerRow: "krajnjih",
    midPostsPerRow: "međustubova",
    actualPostSpacingM: "Stvaran razmak stubova",
    totalPosts: "Ukupno stubova",
    anchors: "Sidara",
    wireLengthM: "Dužina žice (sa dodatkom)",
    wireMassKg: "Masa žice",
    coilsCeil: "Broj koluta",
    kgPerCoil: "Kilograma po kolutu",
    plantsPerRow: "Sadnica po redu",
    totalPlants: "Ukupno sadnica",
    plotAreaHa: "Površina parcele",
    usedAreaHa: "Iskorišćena površina (redovi)",
    densityPerHa: "Stvarna gustina",
    theoreticalDensityPerHa: "Teorijska gustina",
    geometryNote:
      "Samo pravougaono slaganje po unetim merama. Šestougaono (piramidalno) slaganje se ne " +
      "računa; presek, dubina i nosivost stubova, žice i sidara nisu deo ovog računa.",

    inputs: "Uneseno",
    formula:
      "n_r = floor((W−2·e_b)/a)+1     stubova/red = ceil(L_r/p)+1     žica = " +
      "n_r·L_r·k·(1+dodatak/100)",

    errorLengthM: "Dužina parcele mora biti veća od nule.",
    errorWidthM: "Širina parcele mora biti veća od nule.",
    errorRowSpacingM: "Razmak redova je između 0,5 i 20 m.",
    errorHeadlandM: "Uvratina je između 0 i 30 m.",
    errorBoundaryOffsetM: "Odstojanje od međe je između 0 i 30 m.",
    errorPostSpacingM: "Razmak stubova u redu je između 2 i 15 m.",
    errorWireRows: "Broj redova žice je ceo broj od 1 do 8.",
    errorWireDiameterMm: "Prečnik žice je između 1,0 i 5,0 mm.",
    errorWireSlackPercent: "Dodatak na žicu je između 0 i 30 %.",
    errorPlantSpacingM: "Razmak sadnica u redu je između 0,3 i 10 m.",
    errorAnchorsPerEnd: "Sidara po kraju reda je ceo broj od 0 do 2.",
    errorCoilLengthM: "Dužina koluta žice mora biti veća od nule.",
    errorWireMassPerKmOverride: "Deklarisana masa žice po km mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM: "m",
    unitKg: "kg",
    unitHa: "ha",
  },

  "plant-spacing-density": {
    pattern: "Raspored",
    patternRectangular: "Pravougaoni (red × biljka)",
    patternTriangular: "Trougaoni (šahovski)",
    rowSpacingM: "Razmak redova",
    spacingM: "Razmak u redu",
    spacingMHint: "Kod trougaonog rasporeda — jedinstveno rastojanje između susednih biljaka.",
    lengthM: "Dužina parcele",
    widthM: "Širina parcele",
    headlandM: "Uvratina na kraju reda",
    boundaryOffsetM: "Odstojanje od bočne međe",
    desiredDensityPerHa: "Željeni sklop",

    results: "Rezultat",
    areaPerPlantM2: "Površina po biljci",
    theoreticalDensityPerHa: "Teorijska gustina",
    onParcel: "Na parceli",
    rowsCount: "Broj redova",
    rowLengthM: "Dužina jednog reda",
    plantsPerRow: "Biljaka po redu",
    totalPlants: "Ukupno sadnica",
    plotAreaHa: "Površina parcele",
    usedAreaHa: "Iskorišćena površina",
    actualDensityPerHa: "Stvarna gustina",
    triangularNote:
      "Broj sadnica na parceli se prikazuje samo za pravougaoni raspored — kod trougaonog svaki " +
      "drugi red je pomeren za pola razmaka, što ovaj račun ne modeluje.",
    reverse: "Obrnut račun (iz željenog sklopa)",
    requiredInRowSpacingM: "Potreban razmak u redu (tačno)",
    requiredSpacingRoundedM: "Zaokruženo na santimetar",
    densityAtRoundedSpacing: "Gustina pri zaokruženom razmaku",

    inputs: "Uneseno",
    formula: "S = a·b (pravougaoni) ili (√3/2)·d² (trougaoni)     gustina = 10000/S",

    errorRowSpacingM: "Razmak redova je između 0,05 i 50 m.",
    errorSpacingM: "Razmak u redu je između 0,05 i 50 m.",
    errorHeadlandM: "Uvratina je između 0 i 50 m.",
    errorBoundaryOffsetM: "Odstojanje od međe je između 0 i 50 m.",
    errorDesiredDensityPerHa:
      "Željeni sklop mora biti veći od nule i dostižan pri unetom razmaku redova.",
    errorLengthM: "Dužina parcele mora biti veća od nule.",
    errorWidthM: "Širina parcele mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM: "m",
    unitM2: "m²",
    unitHa: "ha",
  },

  "polygon-area": {
    verticesText: "Temena",
    verticesTextHint:
      "Nalepi jedno teme po redu, dve vrednosti razdvojene razmakom, tabulatorom ili " +
      "tačkom-zarezom (decimalni zarez je dozvoljen unutar broja). Od 3 do 512 temena.",
    columnOrder: "Redosled kolona",
    columnOrderYX: "Y, X (geodetski)",
    columnOrderXY: "X, Y (matematički)",
    unitDisplay: "Jedinica prikaza površine",
    unitDisplayAll: "Sve tri",

    results: "Rezultat",
    areaM2: "Površina",
    areaAr: "Površina",
    areaHa: "Površina",
    perimeterM: "Obim",
    centroid: "Težište",
    centroidUndefined: "Težište ne postoji — temena su kolinearna (površina je nula).",
    winding: "Smer obilaska",
    windingCcw: "Suprotno od kazaljke",
    windingCw: "U smeru kazaljke",
    colX: "X",
    colY: "Y",

    inputs: "Uneseno",
    vertexCount: "Broj temena",
    formula: "A = |Σ(xᵢ·yᵢ₊₁ − xᵢ₊₁·yᵢ)|/2     obim = Σ√((Δx)²+(Δy)²)",

    errorParse: "Svaki red su dve vrednosti razdvojene razmakom, tabulatorom ili tačkom-zarezom.",
    errorVertices: "Unesi od 3 do 512 temena, sve konačne vrednosti.",
    errorIntersect: "Dve nesusedne stranice poligona se seku — površina se ne prikazuje.",
    errorGeneric: "Proveri unete vrednosti.",

    unitM: "m",
    unitM2: "m²",
    unitAr: "ar",
    unitHa: "ha",
  },

  "seeding-rate": {
    standMode: "Jedinica željenog sklopa",
    standModePerM2: "biljaka/m²",
    standModePerHa: "biljaka/ha",
    standValue: "Željeni sklop",
    standValueHint: "Tvoj izbor prema kulturi i sorti. Nexus ga ne predlaže.",
    tkwGrams: "Masa 1000 zrna (TKW)",
    germinationPercent: "Klijavost",
    purityPercent: "Čistoća",
    fieldLossPercent: "Poljski gubitak",
    areaHa: "Površina za setvu",
    bagMassKg: "Masa vreće",
    rowSpacingCm: "Razmak redova",
    seedsPerUnit: "Broj zrna u setvenoj jedinici",
    priceMode: "Cena",
    priceModeNone: "Bez cene",
    priceModePerKg: "Po kilogramu",
    priceModePerUnit: "Po setvenoj jedinici",
    pricePerKg: "Cena po kilogramu",
    pricePerUnit: "Cena po setvenoj jedinici",

    results: "Rezultat",
    normKgHa: "Setvena norma",
    seedsPerM2: "Zrna po m²",
    seedsPerHa: "Zrna po hektaru",
    totalSeedKg: "Ukupno semena",
    bagsExact: "Broj vreća (tačno)",
    bagsCeil: "Broj vreća (zaokruženo naviše)",
    totalSeeds: "Ukupno zrna",
    unitsExact: "Setvenih jedinica (tačno)",
    unitsCeil: "Setvenih jedinica (zaokruženo naviše)",
    rowSetting: "Podešavanje sejalice",
    seedsPerLinearMeter: "Zrna po dužnom metru reda",
    spacingInRowCm: "Razmak zrna u redu",
    reverseStandCheckPerM2: "Kontrola: sklop iz izračunate norme",
    totalCost: "Ukupan trošak semena",

    inputs: "Uneseno",
    formula: "F = klijavost·čistoća·(1−gubitak/100)     N = sklop/F     norma = sklop·TKW/(100·F)",

    errorStandValue: "Željeni sklop mora biti u dozvoljenom opsegu za izabranu jedinicu.",
    errorTkwGrams: "Masa 1000 zrna je između 0,05 i 2000 g.",
    errorGerminationPercent:
      "Klijavost je procenat od 1 do 100 — vrednost ispod 1 se odbija kao verovatna greška.",
    errorPurityPercent: "Čistoća je procenat od 1 do 100.",
    errorFieldLossPercent: "Poljski gubitak je između 0 i 60 %.",
    errorAreaHa: "Površina za setvu mora biti veća od nule.",
    errorBagMassKg: "Masa vreće mora biti veća od nule.",
    errorRowSpacingCm: "Razmak redova mora biti veći od nule.",
    errorSeedsPerUnit: "Broj zrna u setvenoj jedinici mora biti veći od nule.",
    errorPricePerKg: "Cena po kilogramu ne može biti negativna.",
    errorPricePerUnit: "Cena po setvenoj jedinici ne može biti negativna.",
    errorGeneric:
      "Proveri unete vrednosti — jedan od činilaca (klijavost, čistoća, gubitak) daje nulu.",

    unitKg: "kg",
    unitKgHa: "kg/ha",
    unitG: "g",
    unitCm: "cm",
    unitHa: "ha",
    unitPercent: "%",
    unitRsd: "RSD",
  },

  "sprayer-calibration": {
    nozzleFlowMode: "Kako je izmeren protok dizne",
    nozzleFlowModeDirect: "Direktno očitan protok",
    nozzleFlowModeCatch: "Zahvaćena zapremina i vreme",
    flowLMin: "Protok jedne dizne",
    flowLMinHint: "Izmereno hvatanjem, ne iz kataloga.",
    catchVolumeMl: "Zahvaćena zapremina",
    catchTimeS: "Vreme hvatanja",
    nozzleSpacingM: "Razmak dizni na gredi",
    nozzleCount: "Broj dizni",
    workingWidthM: "Radni zahvat (izmeren)",
    workingWidthMHint:
      "Nezavisno izmeren zahvat — poredi se sa brojem dizni × razmakom, ne zamenjuje ga tiho.",
    speedKmh: "Brzina kretanja",
    targetRateLHa: "Ciljana norma prskanja (sa etikete)",
    limitHint: "Iz propisa koji primenjuješ. Nexus ne zna koji je to propis i ne nudi vrednost.",
    tankVolumeL: "Zapremina rezervoara",

    results: "Rezultat",
    nozzleFlowLMin: "Protok jedne dizne",
    rateFromSpacingLHa: "Norma prskanja (iz razmaka dizni)",
    boomCheck: "Provera preko cele grede",
    totalFlowLMin: "Ukupan protok grede",
    widthFromCountM: "Radni zahvat (iz broja dizni × razmaka)",
    widthDifferenceM: "Izmereni zahvat − iz broja dizni × razmaka",
    rateFromCountWidthLHa: "Norma prskanja (iz grede)",
    fromLabel: "Prema ciljanoj normi sa etikete",
    requiredNozzleFlowLMin: "Potreban protok dizne za ciljanu normu",
    expectedCatchVolumeMl: "Očekivana zahvaćena zapremina",
    ratio: "Izmereno ÷ ciljano",
    tank: "Rezervoar",
    coverageHaPerTank: "Površina po punom rezervoaru",
    distancePerTankM: "Dužina puta po punom rezervoaru",

    inputs: "Uneseno",
    formula: "Q = 600·q/(v·w)     q = (V/1000)·(60/t)     q_cilj = Q_cilj·v·w/600",

    errorNozzleSpacingM: "Razmak dizni na gredi je između 0,1 i 2 m.",
    errorSpeedKmh: "Brzina kretanja je između 0,5 i 30 km/h.",
    errorCatchTimeS: "Vreme hvatanja mora biti veće od nule.",
    errorNozzleCount: "Broj dizni je ceo broj od 1 do 200.",
    errorWorkingWidthM: "Radni zahvat mora biti veći od nule.",
    errorTargetRateLHa: "Ciljana norma prskanja je između 20 i 2000 l/ha.",
    errorTankVolumeL: "Zapremina rezervoara mora biti veća od nule.",
    errorNozzleFlowLMin: "Protok jedne dizne je između 0,05 i 20 l/min.",
    errorCatchVolumeMl: "Zahvaćena zapremina mora biti veća od nule.",
    errorGeneric: "Proveri unete vrednosti.",

    unitLMin: "l/min",
    unitLHa: "l/ha",
    unitM: "m",
    unitMl: "ml",
    unitHa: "ha",
    unitKmh: "km/h",
    unitPercent: "%",
  },

  "tank-mix-dose": {
    productsText: "Preparati u rezervoaru",
    productsTextHint:
      "Nalepi jedan preparat po redu: naziv;l ili kg;način doze (ha, % ili ml);vrednost. Način " +
      "„ha“ je doza po hektaru, „%“ je koncentracija u procentima, „ml“ je doza po litru " +
      "škropiva (ml ili g na litar). Do 10 preparata.",
    productsTextPlaceholder: "Preparat A;l;ha;1,5\nPreparat B;kg;%;0,625",
    sprayRateLHa: "Norma prskanja (utrošak vode)",
    limitHint: "Iz propisa koji primenjuješ. Nexus ne zna koji je to propis i ne nudi vrednost.",
    tankVolumeL: "Zapremina rezervoara",
    areaHa: "Površina za tretiranje",

    results: "Rezultat",
    colProduct: "Preparat",
    colDosePerHa: "Doza po hektaru",
    colPerTank: "Po punom rezervoaru",
    colTotal: "Ukupno za površinu",
    colRemainder: "U poslednjem (delimičnom) punjenju",
    colConcentration: "Koncentracija u rezervoaru",
    perFullTankAmount: "po punom rezervoaru",
    totalAmount: "ukupno",
    remainderAmount: "u ostatku",
    concentrationPercent: "koncentracija",
    basisVolumeVolume: "zapremina/zapremina",
    basisMassVolume: "masa/zapremina",
    fullTankAreaHa: "Površina po punom rezervoaru",
    totalSprayVolumeL: "Ukupna zapremina škropiva",
    fullFills: "Punih punjenja",
    remainderVolumeL: "Zapremina poslednjeg (delimičnog) punjenja",
    remainderAreaHa: "Površina poslednjeg (delimičnog) punjenja",
    fullTankCarrierL: "Vode po punom rezervoaru (posle dodavanja preparata)",
    totalCarrierL: "Ukupno vode za celu površinu",
    labelNote:
      "Škropivo je voda plus svi dodati preparati — zapremina vode je zapremina rezervoara " +
      "umanjena za tečne preparate koje sadrži, ne cela zapremina rezervoara. Dozu i normu " +
      "prskanja unosiš sa etikete preparata; Nexus ih ne poznaje, ne pamti i ne predlaže.",

    inputs: "Uneseno",
    productCount: "Broj preparata",
    formula:
      "A_r = V/Q     P_r = D·A_r     V_uk = Q·A     P_uk = D·A     n = V_uk/V     n_p = floor(n) " +
      "    V_o = V_uk − n_p·V     P_o = D·(V_o/Q)     voda = V_uk − P_uk (tečni preparati)",

    errorParse: "Svaki red preparata je naziv;l ili kg;ha, % ili ml;vrednost.",
    errorProducts: "Unesi od 1 do 10 preparata.",
    errorSprayRateLHa: "Norma prskanja (utrošak vode) je između 20 i 2000 l/ha.",
    errorTankVolumeL: "Zapremina rezervoara mora biti veća od nule.",
    errorAreaHa: "Površina za tretiranje mora biti veća od nule.",
    errorDose: "Doza preparata mora biti veća od nule, za svaki preparat u listi.",
    errorGeneric: "Proveri unete vrednosti.",

    unitL: "l",
    unitLHa: "l/ha",
    unitHa: "ha",
    unitPercent: "%",
    unitPerHaSuffix: "/ha",
  },

  "yield-estimate-samples": {
    method: "Metod uzorkovanja",
    methodSmallGrain: "Strna žita (klasovi × zrna × TKW)",
    methodRowCrop: "Okopavine (biljke × plodovi × zrna)",
    methodMeasuredArea: "Odmerena površina (masa uzorka)",
    samplesText: "Uzorci",
    samplesTextHintSmallGrain:
      "Nalepi jedan uzorak po redu: klasova po m²;zrna po klasu. Od 1 do 50 uzoraka.",
    samplesTextHintRowCrop:
      "Nalepi jedan uzorak po redu: biljaka po hektaru;klipova (plodova) po biljci;zrna po " +
      "klipu. Ako se zrna broje kao redovi × zrna u redu, unesi njihov proizvod kao treću " +
      "vrednost. Od 1 do 50 uzoraka.",
    samplesTextHintMeasuredArea:
      "Nalepi jedan uzorak po redu: površina uzorka u m²;masa požnjevenog uzorka u kg. Od 1 do " +
      "50 uzoraka.",
    tkwGrams: "Masa 1000 zrna (TKW)",
    tkwMoisturePercent: "Vlaga na kojoj je izmerena TKW",
    tkwMoisturePercentHint:
      "Vlaga uzorka zrna od kog je izmerena masa 1000 zrna — osnova sa koje preračun na " +
      "referentnu vlagu polazi za ovaj metod. Nije vlaga požnjevenog uzorka.",
    sampleMoisturePercent: "Vlaga u uzorku",
    sampleMoisturePercentHint:
      "Vlaga požnjevenog i izmerenog uzorka — osnova sa koje preračun na referentnu vlagu polazi " +
      "za ovaj metod.",
    referenceMoisturePercent: "Referentna vlaga za preračun",
    limitHint: "Iz ugovora o otkupu ili pravilnika otkupljivača. Nexus ga ne zna i ne predlaže.",
    harvestLossPercent: "Gubitak pri žetvi (opciono)",
    plotAreaHa: "Površina parcele",

    results: "Rezultat",
    colSample: "Uzorak",
    colYieldTHa: "Prinos",
    meanTHa: "Prosek uzoraka",
    minTHa: "Minimum",
    maxTHa: "Maksimum",
    stdDevTHa: "Standardna devijacija",
    standardErrorTHa: "Standardna greška proseka",
    coefficientOfVariationPercent: "Koeficijent varijacije",
    singleSampleNote: "Procena počiva na jednom uzorku — rasipanje se ne prikazuje.",
    meanAtReferenceMoistureTHa: "Prosek pri referentnoj vlazi",
    meanAfterLossTHa: "Prosek posle gubitka pri žetvi",
    totalYieldT: "Ukupan procenjen rod za parcelu",

    inputs: "Uneseno",
    sampleCount: "Broj uzoraka",
    formula:
      "strna žita: t/ha = K·Z·TKW/100000     okopavine: t/ha = " +
      "biljaka/ha·(plodova·zrna·TKW/1000)/1000000     odmerena površina: t/ha = masa/površina×10 " +
      "    x̄ = Σxᵢ/n     s = √(Σ(xᵢ−x̄)²/(n−1))     m_ref = m·(100−w₁)/(100−w₂)",

    errorParse: "Svaki red uzorka mora imati onoliko vrednosti koliko traži izabrani metod.",
    errorSamples: "Unesi od 1 do 50 uzoraka.",
    errorTkwGrams: "Masa 1000 zrna je između 0,05 i 2000 g.",
    errorTkwMoisturePercent: "Vlaga na kojoj je izmerena TKW je između 0 i 60 %.",
    errorSampleMoisturePercent: "Vlaga u uzorku je između 0 i 60 %.",
    errorReferenceMoisturePercent:
      "Referentna vlaga za preračun je između 0 i 60 % i ne sme biti jednaka 100.",
    errorHarvestLossPercent: "Gubitak pri žetvi je između 0 i 100 %.",
    errorPlotAreaHa: "Površina parcele mora biti veća od nule.",
    errorEarsPerM2: "Klasova po m² je između 1 i 2000, u svakom uzorku.",
    errorGrainsPerEar: "Zrna po klasu (ili klipu) je između 1 i 200, u svakom uzorku.",
    errorPlantsPerHa: "Biljaka po hektaru mora biti veće od nule, u svakom uzorku.",
    errorEarsPerPlant: "Klipova (plodova) po biljci mora biti veće od nule, u svakom uzorku.",
    errorSampleAreaM2: "Površina uzorka mora biti veća od nule, u svakom uzorku.",
    errorSampleMassKg: "Masa uzorka mora biti veća od nule, u svakom uzorku.",
    errorGeneric: "Proveri unete vrednosti.",

    unitTHa: "t/ha",
    unitT: "t",
    unitG: "g",
    unitHa: "ha",
    unitPercent: "%",
  },
} as const;
