/**
 * "Metalworking" - the English copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. Three of the pack's six tools carry `zanat`'s copy
 * (`tap-drill-size`, `sheet-metal-bend`, `weld-consumable`), because a pack is a
 * lens over the drawer and not a second copy of it.
 */
export const PRO_METAL_EN = {
  "cutting-speed": {
    diameter: "Tool or workpiece diameter",
    diameterHint: "In millimetres.",
    mode: "What is given",
    modeFromSpeed: "cutting speed",
    modeFromRpm: "spindle speed",
    cuttingSpeed: "Cutting speed v_c",
    cuttingSpeedHint: "From the tool catalogue and the material, in m/min.",
    spindleSpeed: "Spindle speed n",
    spindleSpeedHint: "In revolutions per minute.",
    results: "Result",
    resultSpeed: "Cutting speed v_c",
    resultRpm: "Spindle speed n",
    formula: "v_c = π·D·n / 1000     n = 1000·v_c / (π·D)",
    inputs: "Entered",
    errorDiameter: "The diameter is a number from 0 to 10 000 mm and above zero.",
    errorMode: "Choose what is given.",
    errorKnown: "Give exactly one - the cutting speed or the spindle speed.",
    errorSpeed: "The cutting speed is a number above zero.",
    errorRpm: "The spindle speed is a number above zero.",
    unitMm: "mm",
    unitMPerMin: "m/min",
    unitRpm: "rpm",
  },

  "feed-per-tooth": {
    teeth: "Number of teeth",
    teethHint: "The cutter's number of cutting edges.",
    spindleSpeed: "Spindle speed n",
    spindleSpeedHint: "In revolutions per minute.",
    mode: "What is given",
    modeFromPerTooth: "feed per tooth",
    modeFromFeedRate: "table feed",
    feedPerTooth: "Feed per tooth f_z",
    feedPerToothHint: "In millimetres.",
    feedRate: "Table feed v_f",
    feedRateHint: "In millimetres per minute.",
    results: "Result",
    resultPerTooth: "Feed per tooth f_z",
    resultPerRev: "Feed per revolution f",
    resultRate: "Table feed v_f",
    formula: "v_f = f_z · z · n     f_z = v_f / (z · n)",
    inputs: "Entered",
    errorTeeth: "The number of teeth is a whole number from 1 to 1000.",
    errorSpindle: "The spindle speed is a number above zero.",
    errorMode: "Choose what is given.",
    errorKnown: "Give exactly one - the feed per tooth or the table feed.",
    errorPerTooth: "The feed per tooth is a number above zero.",
    errorRate: "The table feed is a number above zero.",
    unitMm: "mm",
    unitMmPerTooth: "mm/tooth",
    unitMmPerRev: "mm/rev",
    unitMmPerMin: "mm/min",
    unitRpm: "rpm",
  },

  "metal-weight": {
    shape: "Section",
    shapeHint: "The shape of the material's cross-section.",
    shapeRound: "round bar",
    shapeSquare: "square bar",
    shapeHex: "hex bar",
    shapeRoundTube: "round tube",
    shapeBoxTube: "square tube",
    shapeRect: "plate or flat bar",
    size: "Dimension",
    sizeHint:
      "Diameter, side or width, in millimetres. Hex bar is measured across the flats.",
    secondSize: "Second dimension",
    secondSizeHint: "Height of the section, in millimetres - plate and flat bar only.",
    wall: "Wall thickness",
    wallHint: "In millimetres - tubes only.",
    length: "Length of the piece",
    lengthHint: "In metres.",
    pieces: "Number of pieces",
    density: "Density of the material",
    densityHint:
      "In kg/m³, from the mill certificate. The conventional value for steel is 7 850.",
    results: "Result",
    section: "Cross-section area",
    volume: "Volume per piece",
    massPerMetre: "Mass per metre",
    massPerPiece: "Mass per piece",
    totalMass: "Total mass",
    formula:
      "m = ρ·A·L     A: round π·D²/4, square a², hex (√3/2)·s², tube π/4·(D² − (D − 2t)²)",
    inputs: "Entered",
    errorShape: "Choose a section shape.",
    errorSize: "The dimension is a number above zero.",
    errorSecondSize: "The second dimension is a number above zero.",
    errorWall: "The wall has to be above zero and below half the dimension.",
    errorLength: "The length is a number above zero.",
    errorPieces: "The number of pieces is a whole number above zero.",
    errorDensity: "The density is a number above zero.",
    errorKnown: "This shape does not use every dimension - leave the others empty.",
    unitMm: "mm",
    unitMm2: "mm²",
    unitM: "m",
    unitM3: "m³",
    unitKg: "kg",
    unitKgPerM: "kg/m",
  },

  "weld-throat-leg": {
    measure: "What is given",
    measureLeg: "leg z",
    measureThroat: "throat a",
    leg: "Leg z₁",
    legHint: "The legs of an equal fillet, in millimetres.",
    leg2: "Leg z₂",
    leg2Hint: "The second leg, in millimetres - leave empty for an equal fillet.",
    throat: "Throat a",
    throatHint: "The throat wanted, in millimetres - yields an equal-legged fillet.",
    density: "Density of the weld metal",
    densityHint: "In kg/m³. Defaults to 7 850 for steel.",
    results: "Result",
    resultLeg: "Leg z₁",
    resultLeg2: "Leg z₂",
    resultThroat: "Throat a",
    resultArea: "Weld section per millimetre of length",
    resultMass: "Weld mass per metre",
    formula: "a = z₁·z₂ / √(z₁² + z₂²)     A = z₁·z₂ / 2",
    inputs: "Entered",
    errorMeasure: "Choose whether you are giving the leg or the throat.",
    errorLeg: "The leg is a number from 0,5 to 100 mm.",
    errorLeg2: "The second leg is a number from 0,5 to 100 mm.",
    errorThroat: "The throat is a number from 0,3 to 100 mm.",
    errorDensity: "The density is a number above zero.",
    errorKnown: "Give either the leg or the throat - not both.",
    unitMm: "mm",
    unitMm2: "mm²",
    unitKgPerM: "kg/m",
  },
} as const;
