/**
 * „Transport i logistika" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as the assignment spells it. The tool's
 * NAME and one-line blurb live in `./pro.ts`, not here.
 *
 * **Half of this pack is `life-safety`.** Its copy may name a quantity and the
 * user's own limit, and may never say what the pair means — no „zadovoljava",
 * no „bezbedno", no verdict word anywhere in these strings.
 */
export const PRO_TRANSPORT_SR = {
  "axle-load-distribution": {
    mode: "Režim",
    modeRigid: "Kruto vozilo",
    modeTractor: "Tegljač sa poluprikolicom",
    wheelbase: "Međuosovinsko rastojanje",
    tractorWheelbase: "Međuosovinsko rastojanje tegljača",
    wheelbaseHint: "Od prednje osovine do sredine zadnje osovinske grupe, u metrima.",
    emptyFront: "Prazna prednja osovina sa vage",
    emptyFrontTractor: "Prazna prednja osovina tegljača sa vage",
    emptyFrontHint: "Izmerena vrednost, ne procena.",
    emptyRear: "Prazna zadnja osovina (grupa) sa vage",
    emptyDrive: "Prazna pogonska osovina tegljača sa vage",
    emptyRearHint: "Izmerena vrednost, ne procena.",
    items: "Stavke tereta",
    itemsHint:
      "Jedan red po stavci: masa kg, rastojanje m. U režimu krutog vozila rastojanje se meri od " +
      "prednje osovine unazad (ispred prednje osovine je negativno). U režimu tegljača od kraljičnog " +
      "čepa unazad.",
    fifthWheel: "Rastojanje sedla od prednje osovine tegljača",
    kingpinToBogie: "Rastojanje kraljičnog čepa do sredine osovinske grupe poluprikolice",
    trailerTare: "Tara poluprikolice",
    trailerTareCentre: "Težište prazne poluprikolice od kraljičnog čepa",
    frontLimit: "Granica prednje osovine",
    limitHint: "Iz propisa koji primenjuješ i iz saobraćajne dozvole. Nexus ih ne zna i ne nudi vrednost.",
    rearLimit: "Granica zadnje osovine",
    driveLimit: "Granica pogonske osovine",
    bogieLimit: "Granica osovinske grupe poluprikolice",
    totalLimit: "Granica ukupne mase",

    results: "Rezultat",
    front: "Opterećenje prednje osovine",
    rear: "Opterećenje zadnje osovine",
    drive: "Opterećenje pogonske osovine",
    bogie: "Opterećenje osovinske grupe poluprikolice",
    total: "Ukupna masa",
    fifthWheelLoad: "Opterećenje sedla",
    ratio: "Odnos prema granici",
    diff: "Razlika (izračunato − granica)",
    payload: "Teret (Σ masa stavki)",
    totalByMasses: "Ukupna masa (proverom preko F0 + R0 + Σm)",
    colMass: "Masa",
    colDistance: "Rastojanje",
    colToFront: "Doprinos prednjoj / pogonskoj",
    colToRear: "Doprinos zadnjoj / grupi",
    colToBogie: "Doprinos osovinskoj grupi",
    colToDrive: "Doprinos pogonskoj (preko sedla)",

    formulaRigid: "Rt = Σ(mⱼ·xⱼ)/b     Ft = Σmⱼ − Rt     F = F0 + Ft     R = R0 + Rt",
    formulaTractor:
      "B = mt·c/s + Σ(mⱼ·dⱼ)/s     K = (mt + Σmⱼ) − B     D = R0 + K·u/btr     F = F0 + K·(1 − u/btr)",
    inputs: "Uneseno",

    targetTitle: "Obrnuti račun: rastojanje za ciljno opterećenje",
    targetHint:
      "Na kom rastojanju bi izabrana stavka dala ciljno opterećenje. Premeštanje jedne stavke menja " +
      "obe osovine (i sedlo u režimu tegljača) — izračunata vrednost je rastojanje, ne uputstvo šta " +
      "uraditi.",
    itemIndex: "Redni broj stavke koja se pomera",
    itemIndexHint: "Broj reda u spisku stavki tereta iznad, počev od 1.",
    targetRear: "Ciljno opterećenje zadnje osovine",
    targetBogie: "Ciljno opterećenje osovinske grupe poluprikolice",
    targetDistance: "Rastojanje stavke na cilju",
    targetShift: "Pomeraj u odnosu na sadašnje rastojanje",
    targetOutOfBounds: "Izračunato rastojanje je negativno ili veće od unetog raspona.",
    newFront: "Prednja osovina na cilju",
    newRear: "Zadnja osovina na cilju",
    newDrive: "Pogonska osovina na cilju",
    newBogie: "Osovinska grupa poluprikolice na cilju",
    newTotal: "Ukupna masa na cilju (provera)",
    targetFormula: "Sc = (cilj − R0)·b     xk = (Sc − Σⱼ≠ₖ mⱼ·xⱼ)/mk",

    errorWheelbase: "Međuosovinsko rastojanje je broj od 0,5 do 12 m.",
    errorEmptyFront: "Prazna prednja osovina je broj od 0 do 30000 kg.",
    errorEmptyRear: "Prazna zadnja ili pogonska osovina je broj od 0 do 40000 kg.",
    errorItems: "Unesi bar jedan red stavke tereta, do 100 redova, svaki „masa kg, rastojanje m\".",
    errorKingpinToBogie: "Rastojanje kraljičnog čepa do grupe je broj od 1 do 15 m.",
    errorTrailerTare: "Tara poluprikolice je broj od 0 do 20000 kg.",
    errorTrailerTareCentre: "Težište prazne poluprikolice je broj od 0 do 15 m.",
    errorFifthWheel: "Rastojanje sedla je broj od 0 do 12 m.",
    errorTarget: "Redni broj stavke mora postojati u spisku, a stavka mora imati masu veću od nule.",

    unitKg: "kg",
    unitKgm: "kg·m",
    unitM: "m",
  },

  "cargo-centre-of-gravity": {
    items: "Stavke",
    itemsHint:
      "Jedan red po komadu: masa kg, x m, y m, z m (bez dimenzija) ili masa kg, x m, y m, z m, " +
      "dužina m, širina m, visina m (sa dimenzijama). x je uzdužno od izabrane nule unazad, y bočno " +
      "od ose vozila (desno je plus), z visina težišta komada iznad poda.",
    zeroChoice: "Nula za x",
    zeroFront: "Prednja osovina",
    zeroWall: "Čeoni zid tovarnog prostora",
    zeroKingpin: "Kraljični čep",
    useDims: "Uzeti dimenzije komada umesto težišta",
    useDimsHint:
      "Kad je uključeno, redovi nose i dužinu, širinu i visinu komada, a težište se uzima u " +
      "geometrijskom središtu — pod pretpostavkom ravnomerne gustine unutar komada, računato od ugla " +
      "sa najmanjim x, y i z.",
    yes: "Da",
    no: "Ne",
    floorHeight: "Visina poda iznad tla",
    track: "Razmak točkova (trag)",
    innerWidth: "Unutrašnja širina tovarnog prostora",
    momentRef: "Referentna tačka za moment",
    vehicleMass: "Masa vozila ili prikolice",
    vehicleMassHint: "0 znači da se zajedničko težište sa vozilom ne računa.",
    vehicleCentre: "Težište vozila ili prikolice",
    vehicleCentreHint: "x m, y m, z m, odvojeno zapetama. z je već iznad tla, iz podatka proizvođača.",

    results: "Rezultat",
    totalMass: "Ukupna masa",
    x: "x̄ (uzdužno)",
    y: "ȳ (bočno)",
    z: "z̄ (iznad poda)",
    heightAboveGround: "Visina težišta iznad tla",
    lateralOffset: "Bočni pomak težišta",
    lateralShare: "Udeo poluširine tovarnog prostora",
    momentAboutReference: "Moment oko referentne tačke",
    geometricRatio: "(trag ÷ 2) ÷ visina težišta iznad tla",
    geometricRatioNote: "Odnos dve dužine. Alatka ga ne tumači i ne poredi ni sa čim.",
    combinedTitle: "Zajedničko težište tereta i vozila",

    formula:
      "x̄ = Σmᵢxᵢ/M     ȳ = Σmᵢyᵢ/M     z̄ = Σmᵢzᵢ/M     zg = z̄ + hp     G = (T/2)/zg",
    inputs: "Uneseno",

    errorItems: "Unesi bar jedan red stavke, do 200 redova, sa masom, x, y i z.",
    errorFloorHeight: "Visina poda je broj od 0 do 3 m.",
    errorTrack: "Razmak točkova je broj od 0,5 do 3,5 m.",
    errorInnerWidth: "Unutrašnja širina je broj od 0,5 do 4 m.",
    errorVehicleMass: "Masa vozila je broj od 0 do 60000 kg.",
    errorVehicleCentre: "Uz masu vozila mora biti uneto i njeno težište (x, y, z).",
    errorItemDimensions: "Uz uključene dimenzije svaki red mora imati dužinu, širinu i visinu.",

    unitKg: "kg",
    unitKgm: "kg·m",
    unitM: "m",
  },

  "chargeable-weight": {
    items: "Stavke pošiljke",
    itemsHint:
      "Jedan red po stavci: dužina cm, širina cm, visina cm, komada, masa po komadu kg, broj slojeva " +
      "u koje se stavka slaže (prazno ili 0 se čita kao 1).",
    divisor: "Delilac",
    divisorHint: "Broj iz ugovora sa prevoznikom u cm³/kg, npr. 4000, 5000 ili 6000. Alatka ga ne pretpostavlja.",
    densityDivisor: "Delilac zadat kao kg/m³",
    densityDivisorHint: "Alternativa deliocu iznad — koristi se ako je delilac u cm³/kg prazan.",
    ldmWidth: "Širina tovarnog prostora za tovarni metar",
    massPerLdm: "Masa po tovarnom metru",
    massPerLdmHint: "Broj iz ugovora u kg/ldm. Prazno ili 0 isključuje tu osnovicu.",
    massPerPalletSpace: "Masa po paletnom mestu",
    palletSpaces: "Broj paletnih mesta",
    roundingStep: "Korak zaokruživanja",
    rounding: "Zaokruživati",
    roundingPerItem: "Po komadu",
    roundingPerShipment: "Na celu pošiljku",
    pricePerKg: "Cena po kilogramu",

    results: "Rezultat",
    actualMass: "Stvarna masa",
    volumetricMass: "Zapreminska masa",
    loadingMetreMass: "Masa po tovarnim metrima",
    palletSpaceMass: "Masa po paletnim mestima",
    chargeableMass: "Obračunska masa (pre zaokruživanja)",
    roundedPerShipment: "Zaokruženo na celu pošiljku",
    roundedPerItem: "Zaokruženo po komadu, pa sabrano",
    billedMass: "Masa koja se fakturiše",
    amount: "Iznos fakture",
    currency: "RSD",
    volume: "Zapremina",
    loadingMetres: "Tovarni metri",
    basisActual: "stvarna masa",
    basisVolumetric: "zapreminska masa",
    basisLoadingMetre: "tovarni metar",
    basisPalletSpace: "paletno mesto",
    colVolume: "Zapremina",
    colActual: "Stvarna masa",
    colVolumetric: "Zapreminska masa",
    colLdm: "Tovarni metri",
    colChargeable: "Merodavno",

    formula: "mv = V/d     ldm = (L·W·q)/(10000·Bw·t)     obračunska = max(stvarna, mv, ldm·kldm, ...)",
    inputs: "Uneseno",

    errorItems: "Unesi bar jedan red stavke, do 200 redova.",
    errorLdmWidth: "Širina za tovarni metar je broj od 1 do 4 m.",
    errorRoundingStep: "Korak zaokruživanja je broj od 0,01 do 100 kg.",
    errorItemDimensions: "Dimenzije stavke su brojevi od 0 do 10000 cm.",
    errorItemQuantity: "Broj komada je ceo broj od 0 do 100000.",
    errorItemMass: "Masa po komadu je broj od 0 do 100000 kg.",

    unitKg: "kg",
    unitM: "m",
    unitM3: "m³",
    unitLdm: "ldm",
  },

  "cost-per-km-transport": {
    fixedAnnual: "Fiksni godišnji troškovi",
    fixedAnnualHint:
      "Zbir godišnjih fiksnih stavki koje sam sabereš van alatke: lizing ili amortizacija, osiguranje, " +
      "registracija, parking, knjigovodstvo, plata vozača, ostalo.",
    annualKm: "Pređeni kilometri godišnje",
    annualKmHint: "Planska pretpostavka, ne podatak alatke.",
    emptyShare: "Udeo praznog hoda",
    emptyShareHint: "Prazni kilometri ÷ ukupni kilometri, u procentima. Planska pretpostavka.",
    consumption: "Potrošnja goriva",
    fuelPrice: "Cena goriva",
    fuelPriceHint: "Tržišna cena koju alatka ne poznaje.",
    tyreSetPrice: "Cena kompleta guma",
    tyreLifeKm: "Vek kompleta guma",
    servicePrice: "Cena redovnog servisa",
    serviceIntervalKm: "Servisni interval",
    serviceIntervalKmHint: "Broj iz servisne knjižice konkretnog vozila.",
    repairsPerKm: "Rezerva za popravke",
    adBlueShare: "Potrošnja AdBlue kao udeo dizela",
    adBluePrice: "Cena AdBlue",
    adBluePriceHint: "Tržišna cena koju alatka ne poznaje.",
    marginOnPrice: "Ciljna marža na cenu",
    markupOnCost: "Ciljna marža na trošak (maržiranje)",
    workingDays: "Radnih dana godišnje",

    results: "Rezultat",
    fixedPerKm: "Fiksni trošak po kilometru",
    fuelPerKm: "Gorivo po kilometru",
    tyresPerKm: "Gume po kilometru",
    servicePerKm: "Servis po kilometru",
    adBluePerKm: "AdBlue po kilometru",
    variablePerKm: "Varijabilni trošak po kilometru",
    totalPerKm: "Ukupan trošak po kilometru",
    perLadenKm: "Trošak po kilometru pod teretom",
    annualCost: "Ukupan godišnji trošak",
    perWorkingDay: "Trošak po radnom danu",
    priceAtMargin: "Cena pri marži na cenu",
    priceAtMarkup: "Cena pri maržiranju troška",
    markupEquivalent: "Ekvivalentno maržiranje troška (%)",

    formula: "f = FIX/Kt     v = gorivo + gume + servis + popravke + AdBlue     c = f + v     cl = c/(1 − e)",
    inputs: "Uneseno",

    errorFixedAnnual: "Fiksni godišnji troškovi su broj od 0 do 1000000000 RSD.",
    errorAnnualKm: "Kilometri godišnje su broj od 1 do 1000000.",
    errorEmptyShare: "Udeo praznog hoda je broj od 0 do 99%.",
    errorWorkingDays: "Radnih dana godišnje je ceo broj od 1 do 366.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    currency: "RSD",
    currencyPerKm: "RSD/km",
    unitKm: "km",
  },

  "driving-hours-planner": {
    departure: "Vreme polaska (h:mm)",
    plannedDriving: "Planirana vožnja (h:mm)",
    plannedDrivingHint: "Ako je prazno, računa se iz rastojanja i prosečne brzine ispod.",
    distance: "Rastojanje",
    averageSpeed: "Prosečna brzina",
    continuousLimit: "Granica neprekidne vožnje (h:mm)",
    limitHint: "Granicu propisuju propisi o radnom vremenu vozača i menjaju je. Nexus je ne zna i ne nudi vrednost.",
    breakMinutes: "Trajanje pauze (min)",
    splitBreak: "Deljenje pauze na dva dela",
    yes: "Da",
    no: "Ne",
    firstBreakPart: "Prvi deo pauze (min)",
    drivingBeforeFirstPart: "Vožnja posle koje se uzima prvi deo (h:mm)",
    dailyLimit: "Granica dnevne vožnje (h:mm)",
    dailyRestMinutes: "Trajanje dnevnog odmora (h:mm)",
    drivenSinceBreak: "Već odvožena vožnja od poslednje pauze (h:mm)",
    drivenToday: "Već odvožena dnevna vožnja (h:mm)",
    otherWork: "Ostalo radno vreme",
    otherWorkHint: "Jedan red po unosu: minuti, posle koliko sati vožnje (h:mm). Do 20 redova.",

    results: "Raspored",
    colKind: "Vrsta",
    colStart: "Početak",
    colEnd: "Kraj",
    colMinutes: "Trajanje",
    colSinceBreak: "Vožnja od pauze",
    colToday: "Vožnja u danu",
    kindDrive: "Vožnja",
    kindBreak: "Pauza",
    kindDailyRest: "Dnevni odmor",
    kindOtherWork: "Ostalo radno vreme",
    arrival: "Dolazak",
    elapsedMinutes: "Ukupno proteklo vreme",
    drivingMinutes: "Vožnja ukupno",
    breakMinutesTotal: "Pauze ukupno",
    restMinutes: "Odmori ukupno",
    otherWorkMinutes: "Ostalo radno vreme ukupno",
    sinceBreak: "Vožnja od poslednje pauze",
    today: "Vožnja u tekućem danu",
    ratio: "Odnos prema granici",
    continuousLimitReachedAt: "Sat dostizanja granice neprekidne vožnje",
    dailyLimitReachedAt: "Sat dostizanja granice dnevne vožnje",
    truncatedNote: "Plan je duži od prikaza (dostignuto je 200 blokova) — prikazano je koliko je izračunato.",
    unplacedNote: "Neki unosi ostalog radnog vremena imaju prag veći od ukupne planirane vožnje i nisu ubačeni.",

    formula: "s = min(Rc, Rd, Dl, ...)     t += s     Rc −= s     Rd −= s",
    inputs: "Uneseno",

    errorDeparture: "Vreme polaska je h:mm između 00:00 i 23:59.",
    errorContinuousLimit: "Granica neprekidne vožnje je h:mm veće od 0.",
    errorBreakMinutes: "Trajanje pauze je broj minuta od 1 do 600.",
    errorDailyLimit: "Granica dnevne vožnje je h:mm veće od 0.",
    errorDailyRestMinutes: "Trajanje dnevnog odmora je h:mm veće od 0.",
    errorPlannedDriving: "Unesi planiranu vožnju ili rastojanje i prosečnu brzinu.",
    errorAverageSpeed: "Prosečna brzina je broj od 1 do 130 km/h.",
    errorFirstBreakPart: "Prvi deo pauze je broj minuta manji od ukupnog trajanja pauze.",
    errorDrivingBeforeFirstPart: "Vožnja posle koje se uzima prvi deo je h:mm veće od 0.",
    errorGeneric: "Proveri unete brojeve i vremena — neki je izvan dozvoljenog opsega.",
  },

  "eta-with-breaks": {
    distance: "Rastojanje",
    averageSpeed: "Prosečna brzina u vožnji",
    averageSpeedHint: "Planska pretpostavka korisnika — alatka ne poznaje ni put ni saobraćaj.",
    departure: "Vreme polaska (h:mm)",
    breaks: "Planirane pauze (min)",
    waiting: "Čekanje na granici i trajektu (min)",
    loading: "Utovar i istovar (min)",
    reserve: "Rezerva",
    targetTime: "Ciljno vreme dolaska (h:mm)",
    targetDayOffset: "Broj dana od polaska do ciljnog dolaska",
    targetDayOffsetHint: "0 znači isti dan kao polazak.",

    results: "Rezultat",
    drivingMinutes: "Čisto vreme vožnje",
    stopMinutes: "Zbir zastoja",
    totalMinutes: "Ukupno proteklo vreme (bez rezerve)",
    totalWithReserve: "Ukupno proteklo vreme (sa rezervom)",
    arrival: "Vreme dolaska",
    doorToDoorSpeed: "Prosečna brzina od vrata do vrata (sa rezervom)",
    doorToDoorSpeedNoReserve: "Prosečna brzina od vrata do vrata (bez rezerve)",
    targetTitle: "Prema ciljnom vremenu dolaska",
    latestDeparture: "Najkasniji polazak",
    available: "Raspoloživo vreme",
    minutesAvailableForDriving: "Vreme raspoloživo za vožnju",
    requiredSpeed: "Potrebna prosečna brzina u vožnji",
    noRequiredSpeed: "Pri unetim zastojima i rezervi, takva brzina ne postoji — zastoji premašuju raspoloživo vreme.",

    formula: "tv = 60·D/v     tuk = (tv + Z)·(1 + r)     dolazak = polazak + tuk",
    inputs: "Uneseno",

    errorDistance: "Rastojanje je broj od 0 do 20000 km.",
    errorAverageSpeed: "Prosečna brzina je broj od 1 do 130 km/h.",
    errorDeparture: "Vreme polaska je h:mm između 00:00 i 23:59.",
    errorReserve: "Rezerva je broj od 0 do 100%.",
    errorTargetTime: "Ciljno vreme dolaska je h:mm između 00:00 i 23:59.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitKm: "km",
    unitKmh: "km/h",
  },

  "fuel-consumption-cost": {
    distance: "Pređeni put",
    distanceHint: "Koristi se samo ako stanja kilometraže ispod nisu oba uneta.",
    odometerStart: "Stanje kilometraže na početku",
    odometerEnd: "Stanje kilometraže na kraju",
    litres: "Utrošeno gorivo",
    pricePerLitre: "Cena goriva",
    pricePerLitreHint: "Tržišna cena koju alatka ne poznaje i ne preuzima.",
    cargoTonnes: "Masa tereta",
    ladenDistance: "Put pod teretom",
    ladenDistanceHint: "Ako je prazno, uzima se ceo pređeni put.",
    fuelRemaining: "Preostalo gorivo u rezervoaru",

    results: "Rezultat",
    per100Km: "Potrošnja",
    kmPerLitre: "Ekonomičnost",
    mpgUs: "mpg (US)",
    mpgImperial: "mpg (imperijalni)",
    totalCost: "Ukupna cena goriva",
    costPerKm: "Cena po kilometru",
    tonneKmDistance: "Rastojanje ušlo u tona-kilometre",
    tonneKm: "Tona-kilometri",
    litresPer100TonneKm: "Litara na 100 tona-kilometara",
    costPerTonneKm: "Cena po tona-kilometru",
    range: "Domet pri istoj potrošnji",

    formula: "C100 = 100·L/D     E = D/L     T = L·P     TK = m·D     R = Lr·D/L",
    inputs: "Uneseno",

    errorOdometer: "Unesi oba stanja kilometraže ili nijedno; kraj mora biti veći od početka.",
    errorDistance: "Pređeni put je broj od 0,1 do 100000 km.",
    errorLitres: "Utrošeno gorivo je broj od 0,01 do 5000 l.",
    errorPricePerLitre: "Cena goriva je broj od 0 do 100000 RSD/l.",
    errorCargoTonnes: "Masa tereta je broj od 0 do 100 t.",
    errorFuelRemaining: "Preostalo gorivo je broj od 0 do 5000 l.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitKm: "km",
    unitL: "l",
    unitL100km: "l/100 km",
    unitKmL: "km/l",
    unitTkm: "t·km",
    unitL100tkm: "l/100 t·km",
    currency: "RSD",
    currencyPerKm: "RSD/km",
    currencyPerL: "RSD/l",
    currencyPerTkm: "RSD/t·km",
  },

  "gear-ratio-road-speed": {
    engineRpm: "Obrtaji motora",
    gearRatio: "Prenosni odnos stepena menjača",
    finalDrive: "Prenosni odnos zadnjeg mosta",
    transferRatio: "Prenosni odnos razdelnika ili reduktora",
    circumference: "Kotrljajni obim gume",
    circumferenceHint: "Iz alatke Odstupanje brzinomera, ili izmereno na sopstvenom vozilu.",
    gears: "Spisak stepena menjača",
    gearsHint: "Jedan prenosni odnos po redu, do 16 redova.",
    shiftRpm: "Obrtaji na kojima se menja stepen",
    desiredSpeed: "Željena brzina",

    results: "Rezultat",
    totalRatio: "Ukupan prenosni odnos",
    wheelRpm: "Obrtaji točka",
    speed: "Brzina vozila",
    speedNote: "Teorijska brzina bez proklizavanja pogonskog točka.",
    speedPer1000Rpm: "Brzina po 1000 obrtaja motora",
    rpmAtDesiredSpeed: "Obrtaji motora za željenu brzinu",
    colRatio: "Odnos stepena",
    colTotalRatio: "Ukupan odnos",
    colSpeed: "Brzina pri unetim obrtajima",
    colSpeedAtShift: "Brzina pri obrtajima promene",
    colRpmDrop: "Pad obrtaja pri prelasku",

    formula: "i = ig·if·ir     v = n·C·60/(i·1000000)     n = v·i·1000000/(60·C)",
    inputs: "Uneseno",

    errorEngineRpm: "Obrtaji motora su broj od 100 do 12000 o/min.",
    errorGearRatio: "Prenosni odnos stepena je broj od 0,3 do 20.",
    errorFinalDrive: "Prenosni odnos zadnjeg mosta je broj od 1 do 12.",
    errorTransferRatio: "Prenosni odnos razdelnika je broj od 0,3 do 10.",
    errorCircumference: "Kotrljajni obim je broj od 500 do 5000 mm.",
    errorGears: "Svaki odnos u spisku stepena je broj od 0,3 do 20, do 16 redova.",
    errorShiftRpm: "Obrtaji promene stepena su broj od 100 do 12000 o/min.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitKmh: "km/h",
    unitRpm: "o/min",
    unitMm: "mm",
  },

  "gvw-payload": {
    mode: "Režim",
    modeSingle: "Jedno vozilo",
    modeCombination: "Skup vozila",
    vehicleTare: "Tara vozila sa nadogradnjom",
    tareIncludes: "Tara već sadrži gorivo, AdBlue i posadu",
    tareIncludesHint:
      "Uključi ako je tara iz saobraćajne dozvole već masa u voznom stanju — tada se gorivo, AdBlue i " +
      "posada ne dodaju drugi put.",
    yes: "Da",
    no: "Ne",
    trailerTare: "Tara prikolice ili poluprikolice",
    fuelLitres: "Gorivo u rezervoaru",
    fuelDensity: "Gustina goriva",
    fuelDensityHint: "Važi na 15 °C. Unete litre su zapremina na temperaturi u rezervoaru — bez temperaturne korekcije.",
    adBlueLitres: "AdBlue u rezervoaru",
    adBlueDensity: "Gustina AdBlue",
    adBlueDensityHint: "Važi na 20 °C.",
    crew: "Vozač i posada",
    crewHint: "Unosi se stvarna izmerena masa, ne pretpostavka.",
    equipment: "Oprema, alat i lični prtljag",
    packaging: "Tara ambalaže i paleta",
    cargo: "Teret",
    vehicleLimit: "Granica ukupne mase vozila",
    limitHint: "Iz saobraćajne dozvole i propisa o masama. Nexus ih ne zna i ne nudi vrednost.",
    trailerLimit: "Granica mase prikolice ili poluprikolice",
    combinationLimit: "Granica mase skupa",

    results: "Rezultat",
    runningMass: "Masa u voznom stanju",
    combinationEmptyMass: "Masa praznog skupa (vučno vozilo + prikolica)",
    payloadMass: "Masa korisnog tereta (teret + ambalaža)",
    totalMass: "Ukupna masa",
    ratio: "Odnos prema granici",
    diff: "Razlika (izračunato − granica)",
    vehicleWithoutCargo: "Masa vučnog vozila (bez tereta)",
    trailerWithoutCargo: "Masa prikolice (bez tereta, sama tara)",
    payloadHeadroom: "Razlika do granice pri praznom teretu",
    headroomUsed: "Iskorišćenost te razlike teretom i ambalažom",
    minCargoHeadroom: "Najmanja preostala nosivost do bilo koje granice",
    densityNote:
      "Raspodela mase tereta na vučno vozilo i prikolicu ovde se ne pretpostavlja — za nju služi " +
      "alatka Osovinsko opterećenje.",

    formula: "Mv = tara + mg + ma + posada + oprema     Mt = teret + ambalaža     M = Mv + Mt",
    inputs: "Uneseno",

    errorVehicleTare: "Tara vozila je broj od 0 do 60000 kg.",
    errorFuelLitres: "Gorivo je broj od 0 do 2000 l.",
    errorFuelDensity: "Uz gorivo veće od nule, gustina goriva je broj od 0,7 do 1,1 kg/l.",
    errorAdBlueLitres: "AdBlue je broj od 0 do 200 l.",
    errorAdBlueDensity: "Uz AdBlue veći od nule, gustina AdBlue je broj od 1,0 do 1,2 kg/l.",
    errorCrew: "Vozač i posada su broj od 0 do 600 kg.",
    errorEquipment: "Oprema je broj od 0 do 5000 kg.",
    errorPackaging: "Ambalaža je broj od 0 do 20000 kg.",
    errorCargo: "Teret je broj od 0 do 60000 kg.",
    errorTrailerTare: "Tara prikolice je broj od 0 do 40000 kg.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitKg: "kg",
  },

  "load-lashing-force": {
    method: "Način obezbeđenja",
    methodTopOver: "Prekopreko (trenjem)",
    methodDirect: "Direktno (dijagonalno)",
    methodBlocking: "Blokiranje",
    mass: "Masa tereta",
    forwardC: "Koeficijent ubrzanja napred",
    coefficientHint: "Broj iz standarda obezbeđenja tereta koji primenjuješ. Nexus ga ne zna i ne nudi vrednost.",
    backwardC: "Koeficijent ubrzanja nazad",
    lateralC: "Koeficijent ubrzanja bočno",
    friction: "Koeficijent trenja μ",
    verticalAngle: "Vertikalni ugao vezice α",
    angleHint: "Meri se od poda tovarnog prostora.",
    horizontalAngle: "Horizontalni ugao vezice β",
    transferFactor: "Faktor prenosa zatezanja na drugu stranu k",
    stf: "STF sa etikete vezice",
    lc: "LC sa etikete vezice",
    lashings: "Broj vezica u postavci",

    results: "Rezultat",
    weight: "Težina tereta",
    frictionForce: "Trenje od sopstvene težine",
    verticalForce: "Vertikalna sila jedne vezice (Fv)",
    perLashing: "Sila po jednoj vezici",
    setForce: "Sila cele unete postavke",
    forward: "Napred",
    backward: "Nazad",
    lateral: "Bočno",
    drivingForce: "Sila u smeru (c·G)",
    remainingForce: "Preostala sila za obezbeđenje (Fp)",
    noRemainingForce: "Po ovom računu u ovom smeru ne preostaje sila za obezbeđenje.",
    quotient: "Količnik Fp / sila po vezici",
    setRatio: "Odnos unete postavke prema Fp",
    slidingOnlyNote: "Računa se isključivo ravnoteža klizanja, ne i prevrtanja tereta.",

    formulaTopOver: "Fv = STF·sinα·(1+k)     Fg = μ·Fv     Fp = (c−μ)·G     q = Fp/Fg",
    formulaDirect: "Fe = LC·(cosα·cosβ + μ·sinα)     Fp = (c−μ)·G     q = Fp/Fe",
    formulaBlocking: "Fp = (c−μ)·G",
    inputs: "Uneseno",

    errorMass: "Masa tereta je broj od 1 do 60000 kg.",
    errorCoefficient: "Koeficijent ubrzanja je broj od 0 do 2.",
    errorFriction: "Koeficijent trenja μ je broj od 0 do 1.",
    errorLashings: "Broj vezica je ceo broj od 0 do 50.",
    errorVerticalAngle: "Vertikalni ugao α je broj od 1 do 90°.",
    errorTransferFactor: "Faktor prenosa k je broj od 0 do 1.",
    errorStf: "STF je broj od 1 do 2000 daN.",
    errorHorizontalAngle: "Horizontalni ugao β je broj od 0 do 89°.",
    errorLc: "LC je broj od 1 do 20000 daN.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitKg: "kg",
    unitDaN: "daN",
    unitKn: "kN",
  },

  "loading-space-utilisation": {
    innerLength: "Unutrašnja dužina tovarnog prostora",
    innerWidth: "Unutrašnja širina",
    innerHeight: "Unutrašnja visina",
    items: "Stavke",
    itemsHint: "Jedan red po stavci: dužina m, širina m, visina m, komada, broj slojeva u koje se slaže.",
    ldmWidth: "Ugovorna širina za tovarni metar",
    ldmWidthHint: "Broj iz ugovora korisnika.",

    results: "Rezultat",
    availableVolume: "Raspoloživa zapremina",
    availableFloorArea: "Raspoloživa podna površina",
    availableLoadingMetres: "Raspoloživi tovarni metri",
    usedVolume: "Iskorišćena zapremina",
    usedFloorArea: "Iskorišćena podna površina",
    usedLoadingMetres: "Iskorišćeni tovarni metri",
    volumeShare: "Iskorišćenje po zapremini",
    floorShare: "Iskorišćenje po podnoj površini",
    loadingMetreShare: "Iskorišćenje po tovarnim metrima",
    remainingVolume: "Preostala zapremina",
    remainingFloorArea: "Preostala podna površina",
    remainingLoadingMetres: "Preostali tovarni metri",
    averageStackHeight: "Prosečna visina slaganja",
    stackHeightShare: "Udeo prosečne visine u unutrašnjoj visini",
    largestBasis: "Osnovica sa najvećim procentom",
    basisVolume: "zapremina",
    basisFloor: "podna površina",
    basisLoadingMetre: "tovarni metar",
    widerNote: "Bar jedna stavka je šira od unutrašnje širine tovarnog prostora — za nju izraz ne opisuje ništa što staje u prostor.",
    tallerNote: "Bar jedna stavka sa slaganjem prelazi unutrašnju visinu.",

    formula: "ηV = Vu/Vr     ηA = Au/Ar     ηLDM = LDMu/LDMr",
    inputs: "Uneseno",

    errorItems: "Unesi bar jedan red stavke, do 200 redova.",
    errorInnerLength: "Unutrašnja dužina je broj od 0,5 do 30 m.",
    errorInnerWidth: "Unutrašnja širina je broj od 0,5 do 4 m.",
    errorInnerHeight: "Unutrašnja visina je broj od 0,3 do 5 m.",
    errorLdmWidth: "Ugovorna širina je broj od 1 do 4 m.",
    errorItemDimensions: "Dimenzije stavke su brojevi od 0 do 100 m.",

    unitM: "m",
    unitM2: "m²",
    unitM3: "m³",
    unitLdm: "ldm",
  },

  "pallet-load-plan": {
    innerLength: "Unutrašnja dužina tovarnog prostora",
    innerWidth: "Unutrašnja širina",
    innerHeight: "Unutrašnja visina",
    palletType: "Tip palete",
    palletEur: "EUR 1200×800",
    palletIndustrial: "Industrijska 1200×1000",
    palletCustom: "Proizvoljna",
    customLength: "Proizvoljna dužina palete",
    customWidth: "Proizvoljna širina palete",
    loadedHeight: "Visina natovarene palete",
    loadedHeightHint: "Uključujući prepust tereta preko palete, ako ga ima.",
    stacking: "Slaganje u visinu dozvoljeno",
    yes: "Da",
    no: "Ne",
    maxLayers: "Najviše slojeva",
    rotationAllowed: "Okretanje paleta dozvoljeno",

    results: "Rezultat",
    geometryOnlyNote:
      "Alatka računa samo geometriju. Masa, raspored po osovinama, nosivost paleta i obezbeđenje " +
      "tereta su druge alatke i ovde se ne prikazuju — broj mesta nije tvrdnja da se toliko sme natovariti.",
    lengthwise: "Uzdužni raspored",
    crosswise: "Poprečni raspored",
    combined: "Najbolja kombinacija pojaseva",
    combinedBands: "Sastav kombinacije (uzdužnih + poprečnih pojaseva)",
    combinedNote:
      "Tačan maksimum je izračunat nad pojasnim rasporedima — svaki pojas jedne orijentacije. Mešane " +
      "orijentacije unutar jednog pojasa mogu dati više mesta, ali to ova alatka ne pretražuje.",
    perFloor: "Paleta po podu",
    usedLength: "Iskorišćena dužina",
    remainingLength: "Preostala dužina",
    places: "Paletnih mesta (sa slaganjem)",
    floorArea: "Zauzeta podna površina",
    freeFloorArea: "Slobodna podna površina",
    layers: "Slojeva po visini",
    zeroLayersNote: "Natovarena paleta ne prolazi po unutrašnjoj visini prostora.",

    formula: "n = floor(Wv/q)     r = floor(Lv/p)     N = n·r     t = min(najviše slojeva, floor(Hv/hn))",
    inputs: "Uneseno",

    errorInnerLength: "Unutrašnja dužina je broj od 0,5 do 30 m.",
    errorInnerWidth: "Unutrašnja širina je broj od 0,5 do 4 m.",
    errorInnerHeight: "Unutrašnja visina je broj od 0,3 do 5 m.",
    errorPalletLength: "Dužina palete je broj od 100 do 3000 mm.",
    errorPalletWidth: "Širina palete je broj od 100 do 3000 mm.",
    errorLoadedHeight: "Visina natovarene palete je broj od 50 do 3000 mm.",
    errorMaxLayers: "Najviše slojeva je ceo broj od 1 do 10.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitM: "m",
    unitMm: "mm",
    unitM2: "m²",
  },

  "reefer-fuel-consumption": {
    continuousHours: "Sati rada u neprekidnom režimu",
    continuousRate: "Potrošnja u neprekidnom režimu",
    rateHint: "Podatak iz uputstva konkretnog agregata ili iz sopstvenog merenja.",
    startStopHours: "Sati rada u start-stop režimu",
    startStopRate: "Potrošnja u start-stop režimu",
    pullDownHours: "Sati rada na spuštanju temperature",
    pullDownRate: "Potrošnja na spuštanju temperature",
    pricePerLitre: "Cena goriva",
    pricePerLitreHint: "Tržišna cena koju alatka ne poznaje.",
    tankLitres: "Gorivo u rezervoaru agregata",
    tractionLitres: "Gorivo utrošeno na vuču",
    pallets: "Broj paleta",
    days: "Trajanje ture",

    results: "Rezultat",
    litres: "Utrošeno gorivo agregata",
    hours: "Ukupni sati rada",
    modeContinuous: "neprekidni",
    modeStartStop: "start-stop",
    modePullDown: "spuštanje temperature",
    omittedNote: "Režim sa satima rada bez unete potrošnje nije ušao u zbir:",
    averageRate: "Prosečna potrošnja",
    cost: "Cena goriva",
    litresPerDay: "Potrošnja po danu",
    costPerDay: "Cena po danu",
    litresPerPallet: "Litara po paleti (cela tura)",
    costPerPallet: "Cena po paleti (cela tura)",
    litresPerPalletDay: "Litara po paleti i danu",
    costPerPalletDay: "Cena po paleti i danu",
    autonomyHours: "Količnik autonomije (rezervoar ÷ prosečna potrošnja)",
    autonomyDays: "Isto, u danima (pretpostavka neprekidnog rada, ÷24)",
    autonomyDaysAtTripRate: "Isto, u danima pri satima rada iz ove ture",
    autonomyContinuousHours: "Autonomija pri neprekidnom režimu",
    autonomyStartStopHours: "Autonomija pri start-stop režimu",
    autonomyPullDownHours: "Autonomija pri spuštanju temperature",
    shareOfTripFuel: "Udeo agregata u ukupnom gorivu ture",

    formula: "L = Σhᵢ·qᵢ     H = Σhᵢ     q̄ = L/H     T = L·P     A = Vr/q̄",
    inputs: "Uneseno",

    errorHours: "Sati rada su broj u dozvoljenom opsegu (0 do 2000, ili 0 do 200 za spuštanje temperature).",
    errorPricePerLitre: "Cena goriva je broj od 0 do 100000 RSD/l.",
    errorTankLitres: "Gorivo u rezervoaru agregata je broj od 0 do 1000 l.",
    errorTractionLitres: "Gorivo za vuču je broj od 0 do 5000 l.",
    errorPallets: "Broj paleta je ceo broj od 0 do 100.",
    errorDays: "Trajanje ture je broj od 0 do 90 dana.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitL: "l",
    unitLh: "l/h",
    unitH: "h",
    unitDays: "dana",
    currency: "RSD",
  },

  "service-interval-km-hours": {
    currentKm: "Trenutna kilometraža",
    lastServiceKm: "Kilometraža na poslednjem servisu",
    distanceInterval: "Interval po kilometrima",
    intervalHint: "Broj iz servisne knjižice konkretnog vozila. Prazno ili 0 isključuje tu osnovicu.",
    currentHours: "Trenutni motočasovi",
    lastServiceHours: "Motočasovi na poslednjem servisu",
    hoursInterval: "Interval po motočasovima",
    lastServiceDate: "Datum poslednjeg servisa (DD.MM.GGGG)",
    dateHint: "Bez ovog datuma mesečna osnovica se ne uključuje u poređenje.",
    monthsInterval: "Interval po mesecima",
    kmPerDay: "Prosečno kilometara dnevno",
    hoursPerDay: "Prosečno motočasova dnevno",
    today: "Današnji datum",

    results: "Rezultat",
    travelledKm: "Pređeno od poslednjeg servisa",
    travelledHours: "Pređeno od poslednjeg servisa (motočasovi)",
    basisDistance: "Kilometarska osnovica",
    basisHours: "Motočasovna osnovica",
    basisMonths: "Mesečna osnovica",
    remaining: "Preostalo do isteka",
    dueAt: "Apsolutno stanje isteka",
    date: "Procenjen datum isteka",
    first: "Prva ističe",
    daysToNext: "Razmak do naredne osnovice",
    kmPerEngineHour: "Kilometara po motočasu (prosek ovog vozila između dva servisa)",
    distanceIntervalInHours: "Kilometarski interval izražen u motočasovima",
    hoursIntervalInKm: "Motočasovni interval izražen u kilometrima",
    averagesNote:
      "Datumi su procena iz prosečnih dnevnih vrednosti koje si uneo, ne iz stvarnog rasporeda vožnje.",

    formula: "Δk = trenutna − poslednja     Rk = Ik − Δk     dana = Rk / km dnevno",
    inputs: "Uneseno",

    errorCurrentKm: "Trenutna kilometraža mora biti veća ili jednaka kilometraži na poslednjem servisu.",
    errorLastServiceKm: "Kilometraža na poslednjem servisu je broj od 0 do 9999999.",
    errorCurrentHours: "Trenutni motočasovi moraju biti veći ili jednaki motočasovima na poslednjem servisu.",
    errorKmPerDay: "Prosečno kilometara dnevno je broj od 0 do 3000.",
    errorHoursPerDay: "Prosečno motočasova dnevno je broj od 0 do 24.",
    errorLastServiceDate: "Datum poslednjeg servisa je ispravan datum u formatu DD.MM.GGGG.",
    errorMonthsInterval: "Interval po mesecima je ceo broj od 1 do 120.",
    errorGeneric: "Proveri unete brojeve i datume — neki je izvan dozvoljenog opsega.",

    unitKm: "km",
    unitH: "h",
    unitDays: "dana",
    unitKmh: "km/h",
  },

  "speedometer-tyre-deviation": {
    currentWidth: "Postojeća guma — širina (mm)",
    currentProfile: "Postojeća guma — profil (%)",
    currentRim: "Postojeća guma — felna (col)",
    replacementWidth: "Nova guma — širina (mm)",
    replacementProfile: "Nova guma — profil (%)",
    replacementRim: "Nova guma — felna (col)",
    measuredCurrent: "Izmereni kotrljajni obim postojeće",
    measuredHint: "0 znači da se obim računa iz dimenzije gume.",
    measuredReplacement: "Izmereni kotrljajni obim nove",
    deflection: "Faktor ugiba pod opterećenjem",
    deflectionHint: "1,000 je čista geometrija — natovarena guma se kotrlja kraće.",
    indicatedSpeed: "Brzina na brzinomeru",
    indicatedDistance: "Pređeno po putnom računaru",
    desiredTrueSpeed: "Željena stvarna brzina",
    characteristicCoefficient: "Karakteristični koeficijent w",
    characteristicCoefficientHint: "Tahografska konstanta odštampana na vozilu, ako postoji (imp/km).",

    results: "Rezultat",
    currentDiameter: "Spoljni prečnik postojeće",
    replacementDiameter: "Spoljni prečnik nove",
    currentCircumference: "Kotrljajni obim postojeće",
    replacementCircumference: "Kotrljajni obim nove",
    sourceMeasured: "izmereno",
    sourceGeometry: "iz geometrije",
    mixedSourceNote:
      "Jedan obim je izmeren a drugi iz geometrije — geometrijski obim je po pravilu veći za nekoliko " +
      "procenata, pa je odnos ispod mešavina dva izvora.",
    currentRevsPerKm: "Obrtaji na kilometar — postojeća",
    replacementRevsPerKm: "Obrtaji na kilometar — nova",
    circumferenceRatio: "Odnos obima (k = C₂/C₁)",
    diameterChange: "Promena prečnika",
    axleHeightChange: "Promena visine ose vozila",
    axleHeightNote: "Razlika slobodnih prečnika, bez promene ugiba pod opterećenjem.",
    trueSpeed: "Stvarna brzina",
    indicatedForDesired: "Pokazivanje brzinomera za željenu stvarnu brzinu",
    trueDistance: "Stvarno pređeni put",
    errorPer100Km: "Greška na 100 km",
    wOverRatio: "w ÷ k (aritmetika, ne baždarenje uređaja)",
    calibrationNote:
      "Ovo je razlika koju donosi promena dimenzije gume, ne apsolutna tačnost brzinomera u vozilu.",

    formula: "D = felna·25,4 + 2·širina·profil/100     C = π·D·f     k = C₂/C₁     vs = vp·k",
    inputs: "Uneseno",

    errorTyreWidth: "Širina gume je broj od 125 do 495 mm.",
    errorTyreProfile: "Profil gume je broj od 20 do 100%.",
    errorTyreRim: "Felna je broj od 8 do 26 cola.",
    errorDeflection: "Faktor ugiba je broj od 0,90 do 1,00.",
    errorIndicatedSpeed: "Brzina na brzinomeru je broj od 1 do 250 km/h.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitMm: "mm",
    unitKm: "km",
    unitKmh: "km/h",
  },

  "tank-volume-by-level": {
    shape: "Oblik rezervoara",
    shapeLying: "Ležeći cilindar",
    shapeStanding: "Uspravni cilindar",
    shapeBox: "Sanduk (kvadar)",
    diameter: "Prečnik",
    length: "Dužina",
    lengthHint: "Dužina cilindričnog dela, između dva mesta gde počinju kupe dna — bez samih kupa.",
    width: "Širina",
    height: "Visina",
    domeDepth: "Dubina kupe dna",
    domeDepthHint: "0 za ravno dno. Meri se za jedno dno; iznad polovine prečnika se ne uzima u obzir.",
    level: "Očitavanje mernog štapa",
    density: "Gustina tečnosti",
    densityHint: "Sa otpremnice, ne pretpostavljena vrednost.",
    pricePerLitre: "Cena po litru",
    targetVolume: "Ciljana zapremina",

    results: "Rezultat",
    volume: "Zapremina na očitanom nivou",
    volumeM3: "Zapremina na očitanom nivou (m³)",
    fullVolume: "Puna zapremina rezervoara",
    fillShare: "Popunjenost",
    emptySpace: "Prazan prostor do vrha",
    mass: "Masa sadržaja",
    value: "Vrednost sadržaja",
    sensitivity: "Osetljivost očitavanja",
    levelForTarget: "Nivo za ciljanu zapreminu",
    levelAboveCapacityNote: "Uneti nivo je iznad kapaciteta rezervoara — zapremina je ograničena na punu.",
    calibrationNote:
      "Gustina je na 15°C, bez korekcije za temperaturu tečnosti u rezervoaru.",

    formulaLying: "V = A(h)·L + Vkupe(h)     A(h) preseg kružnog odsečka",
    formulaOther: "V = A·h     A — poprečni presek, konstantan po visini",
    inputs: "Uneseno",

    errorLevel: "Očitavanje je broj od 0 do 5000 mm.",
    errorDiameter: "Prečnik je broj od 100 do 5000 mm.",
    errorLength: "Dužina je broj od 100 do 20000 mm.",
    errorDomeDepth: "Dubina kupe dna je broj od 0 do 1500 mm i ne veća od poluprečnika.",
    errorHeight: "Visina je broj od 100 do 5000 mm.",
    errorWidth: "Širina je broj od 100 do 5000 mm.",
    errorDensity: "Gustina je broj od 0,50 do 2,00 kg/l.",
    errorPricePerLitre: "Cena po litru je broj od 0 do 100000.",
    errorTargetVolume: "Ciljana zapremina je broj od 0 do 200000 l.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitL: "l",
    unitM3: "m³",
    unitKg: "kg",
    unitMm: "mm",
    unitLmm: "l/mm",
    unitKgL: "kg/l",
    currency: "RSD",
  },

  "trip-cost-quote": {
    ladenKm: "Kilometri pod teretom",
    emptyKm: "Prazni i pristupni kilometri",
    costPerKmKind: "Uneta stopa je po",
    costPerKmKindHint:
      "Ako je stopa preuzeta iz alatke „Trošak po kilometru\", proveri da li je to trošak po ukupnom " +
      "ili po kilometru pod teretom — pomnožena sa pogrešnom kilometražom, prazan hod se naplati dvaput.",
    costPerKmKindTotal: "ukupnom kilometru",
    costPerKmKindLaden: "kilometru pod teretom",
    costPerKm: "Trošak po kilometru",
    costPerKmHint: "Ne sme sadržati putarine, dnevnice ni čekanje ako se te stavke unose posebno ispod.",
    tolls: "Putarine",
    ferriesAndVignettes: "Trajekt, tunel, vinjeta",
    terminalCharges: "Naknade na utovaru i istovaru",
    waitingHours: "Sati čekanja",
    waitingRate: "Cena sata čekanja",
    days: "Broj dana na putu",
    perDiem: "Dnevnica",
    perDiemHint: "Iznos propisuje država i menja ga. Nexus ga ne zna i ne nudi vrednost.",
    nights: "Broj noćenja",
    nightRate: "Cena noćenja",
    otherCosts: "Ostali troškovi",
    marginMethod: "Način obračuna marže",
    marginMethodOnPrice: "Marža na cenu",
    marginMethodOnCost: "Maržiranje troška",
    marginOnPrice: "Marža na cenu",
    markupOnCost: "Marža na trošak (maržiranje)",
    vatRate: "Stopa PDV",
    vatRateHint: "Stopu propisuje država i menja je. Nexus je ne zna i ne nudi vrednost.",
    cargoTonnes: "Masa tereta",

    results: "Rezultat",
    doubleCountingNote:
      "Proveri stavku po stavku iznad — ako je bilo koji trošak sadržan i u ceni po kilometru i u " +
      "posebnom redu ovde, ta stavka je naplaćena dvaput.",
    totalKm: "Ukupna kilometraža",
    colGroup: "Grupa troška",
    colAmount: "Iznos",
    drivingCost: "Trošak vožnje",
    roadCost: "Putarine i naknade (uz čekanje i ostalo)",
    driverCost: "Dnevnice i noćenja",
    totalCost: "Ukupan trošak ture",
    colMarginMethod: "Način marže",
    colPrice: "Cena bez PDV",
    priceAtMargin: "Cena pri marži na cenu",
    priceAtMarkup: "Cena pri maržiranju troška",
    marginEquivalenceNote:
      "Ista stopa daje različitu cenu po ova dva načina — veza je u = m/(1 − m). Cena ispod je uvek " +
      "po odabranom načinu obračuna.",
    priceBeforeVat: "Cena bez PDV (odabrani način)",
    vat: "PDV",
    priceWithVat: "Cena sa PDV",
    breakEvenPrice: "Prag rentabilnosti (cena = trošak)",
    breakEvenPricePerKm: "Prag rentabilnosti po kilometru",
    profit: "Zarada ture",
    profitPerDay: "Zarada po danu",
    profitShareOfPrice: "Zarada kao udeo cene",
    profitShareOfCost: "Zarada kao udeo troška",
    pricePerKm: "Cena po kilometru",
    pricePerLadenKm: "Cena po kilometru pod teretom",
    pricePerTonne: "Cena po toni",
    regulatedFiguresNote:
      "Iznos dnevnice i stopa PDV su brojevi koje si uneo — Nexus ne tvrdi da je bilo koji iznos " +
      "poreski priznat niti da je stopa tačna.",

    formula:
      "C = Ku·c + (PUT+TRJ+NAK+hč·pč+OST) + (nd·Dn+nn·Pn)     Pb = C/(1−m) ili C·(1+u)     " +
      "Z = Pb−C     PDV = Pb·v     Ps = Pb·(1+v)",
    inputs: "Uneseno",

    errorLadenKm: "Kilometri pod teretom su broj od 0 do 20000.",
    errorEmptyKm: "Prazni kilometri su broj od 0 do 20000.",
    errorCostPerKm: "Trošak po kilometru je broj od 0 do 100000.",
    errorTolls: "Putarine su broj od 0 do 100000000.",
    errorFerriesAndVignettes: "Trajekt, tunel i vinjeta su broj od 0 do 100000000.",
    errorTerminalCharges: "Naknade na utovaru i istovaru su broj od 0 do 100000000.",
    errorWaitingHours: "Sati čekanja su broj od 0 do 500.",
    errorWaitingRate: "Cena sata čekanja je broj od 0 do 1000000.",
    errorDays: "Broj dana je ceo broj od 0 do 90.",
    errorPerDiem: "Dnevnica je broj od 0 do 1000000.",
    errorNights: "Broj noćenja je ceo broj od 0 do 90.",
    errorNightRate: "Cena noćenja je broj od 0 do 1000000.",
    errorOtherCosts: "Ostali troškovi su broj od 0 do 100000000.",
    errorCargoTonnes: "Masa tereta je broj od 0 do 100 t.",
    errorMarginOnPrice: "Marža na cenu je broj od 0 do 95%.",
    errorMarkupOnCost: "Marža na trošak je broj od 0 do 500%.",
    errorVatRate: "Stopa PDV je broj od 0 do 100%.",
    errorGeneric: "Proveri unete brojeve — neki je izvan dozvoljenog opsega.",

    unitKm: "km",
    unitRsdKm: "RSD/km",
    currency: "RSD",
  },
} as const;
