/**
 * „Transport i logistika" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as the assignment spells it. The tool's
 * NAME and one-line blurb live in `./pro.ts`, not here.
 *
 * **Half of this pack is `life-safety`.** Its copy may name a quantity and the
 * user's own limit, and may never say what the pair means — no „zadovoljava",
 * no „bezbedno", no verdict word anywhere in these strings.
 */
export const PRO_TRANSPORT_EN = {
  "axle-load-distribution": {
    mode: "Mode",
    modeRigid: "Rigid vehicle",
    modeTractor: "Tractor unit with semi-trailer",
    wheelbase: "Wheelbase",
    tractorWheelbase: "Tractor wheelbase",
    wheelbaseHint: "From the front axle to the centre of the rear axle group, in metres.",
    emptyFront: "Empty front axle from the weighbridge",
    emptyFrontTractor: "Empty tractor front axle from the weighbridge",
    emptyFrontHint: "A measured value, not an estimate.",
    emptyRear: "Empty rear axle (group) from the weighbridge",
    emptyDrive: "Empty tractor drive axle from the weighbridge",
    emptyRearHint: "A measured value, not an estimate.",
    items: "Load items",
    itemsHint:
      "One row per item: mass kg, distance m. In rigid-vehicle mode the distance is measured from the front axle backwards (in front of the front axle is negative). In tractor mode from the kingpin backwards.",
    fifthWheel: "Fifth-wheel distance from the tractor front axle",
    kingpinToBogie: "Kingpin distance to the centre of the semi-trailer's axle group",
    trailerTare: "Semi-trailer tare",
    trailerTareCentre: "Centre of gravity of the empty semi-trailer from the kingpin",
    frontLimit: "Front axle limit",
    limitHint:
      "From the regulation you apply and from the vehicle registration. Neagle does not know them and offers no value.",
    rearLimit: "Rear axle limit",
    driveLimit: "Drive axle limit",
    bogieLimit: "Semi-trailer axle-group limit",
    totalLimit: "Total mass limit",

    results: "Result",
    front: "Front axle load",
    rear: "Rear axle load",
    drive: "Drive axle load",
    bogie: "Semi-trailer axle-group load",
    total: "Total mass",
    fifthWheelLoad: "Fifth-wheel load",
    ratio: "Ratio to the limit",
    diff: "Difference (calculated − limit)",
    payload: "Load (Σ item masses)",
    totalByMasses: "Total mass (check via F0 + R0 + Σm)",
    colMass: "Mass",
    colDistance: "Distance",
    colToFront: "Contribution to the front / drive axle",
    colToRear: "Contribution to the rear / group",
    colToBogie: "Contribution to the axle group",
    colToDrive: "Contribution to the drive axle (via the fifth wheel)",

    formulaRigid: "Rt = Σ(mⱼ·xⱼ)/b     Ft = Σmⱼ − Rt     F = F0 + Ft     R = R0 + Rt",
    formulaTractor:
      "B = mt·c/s + Σ(mⱼ·dⱼ)/s     K = (mt + Σmⱼ) − B     D = R0 + K·u/btr     F = F0 + K·(1 − u/btr)",
    inputs: "Entered",

    targetTitle: "Reverse calculation: distance for a target load",
    targetHint:
      "At what distance the chosen item would give the target load. Moving one item changes both axles (and the fifth wheel in tractor mode) — the calculated value is a distance, not an instruction on what to do.",
    itemIndex: "Ordinal of the item being moved",
    itemIndexHint: "The row number in the list of load items above, starting from 1.",
    targetRear: "Target rear axle load",
    targetBogie: "Target semi-trailer axle-group load",
    targetDistance: "Item distance at the target",
    targetShift: "Shift relative to the current distance",
    targetOutOfBounds: "The calculated distance is negative or greater than the entered span.",
    newFront: "Front axle at the target",
    newRear: "Rear axle at the target",
    newDrive: "Drive axle at the target",
    newBogie: "Semi-trailer axle group at the target",
    newTotal: "Total mass at the target (check)",
    targetFormula: "Sc = (target − R0)·b     xk = (Sc − Σⱼ≠ₖ mⱼ·xⱼ)/mk",

    errorWheelbase: "The wheelbase is a number from 0.5 to 12 m.",
    errorEmptyFront: "The empty front axle is a number from 0 to 30000 kg.",
    errorEmptyRear: "The empty rear or drive axle is a number from 0 to 40000 kg.",
    errorItems: "Enter at least one load item row, up to 100 rows, each “mass kg, distance m”.",
    errorKingpinToBogie: "The kingpin-to-group distance is a number from 1 to 15 m.",
    errorTrailerTare: "The semi-trailer tare is a number from 0 to 20000 kg.",
    errorTrailerTareCentre: "The centre of gravity of the empty semi-trailer is a number from 0 to 15 m.",
    errorFifthWheel: "The fifth-wheel distance is a number from 0 to 12 m.",
    errorTarget:
      "The item ordinal must exist in the list, and the item must have a mass greater than zero.",

    unitKg: "kg",
    unitKgm: "kg·m",
    unitM: "m",
  },

  "cargo-centre-of-gravity": {
    items: "Items",
    itemsHint:
      "One row per item: mass kg, x m, y m, z m (without dimensions) or mass kg, x m, y m, z m, length m, width m, height m (with dimensions). x is longitudinal from the chosen zero backwards, y lateral from the vehicle axis (right is plus), z the height of the item's centre of gravity above the floor.",
    zeroChoice: "Zero for x",
    zeroFront: "Front axle",
    zeroWall: "Front wall of the cargo space",
    zeroKingpin: "Kingpin",
    useDims: "Take the item's dimensions instead of the centre of gravity",
    useDimsHint:
      "When on, the rows also carry the item's length, width and height, and the centre of gravity is taken at the geometric centre — assuming uniform density within the item, counted from the corner with the smallest x, y and z.",
    yes: "Yes",
    no: "No",
    floorHeight: "Floor height above the ground",
    track: "Track width",
    innerWidth: "Internal width of the cargo space",
    momentRef: "Reference point for the moment",
    vehicleMass: "Mass of the vehicle or trailer",
    vehicleMassHint: "0 means the combined centre of gravity with the vehicle is not calculated.",
    vehicleCentre: "Centre of gravity of the vehicle or trailer",
    vehicleCentreHint:
      "x m, y m, z m, separated by commas. z is already above the ground, from the manufacturer's data.",

    results: "Result",
    totalMass: "Total mass",
    x: "x̄ (longitudinal)",
    y: "ȳ (lateral)",
    z: "z̄ (above the floor)",
    heightAboveGround: "Height of the centre of gravity above the ground",
    lateralOffset: "Lateral offset of the centre of gravity",
    lateralShare: "Share of the half-width of the cargo space",
    momentAboutReference: "Moment about the reference point",
    geometricRatio: "(track ÷ 2) ÷ height of the centre of gravity above the ground",
    geometricRatioNote: "A ratio of two lengths. The tool does not interpret or compare it with anything.",
    combinedTitle: "Combined centre of gravity of the load and vehicle",

    formula:
      "x̄ = Σmᵢxᵢ/M     ȳ = Σmᵢyᵢ/M     z̄ = Σmᵢzᵢ/M     zg = z̄ + hp     G = (T/2)/zg",
    inputs: "Entered",

    errorItems: "Enter at least one item row, up to 200 rows, with mass, x, y and z.",
    errorFloorHeight: "The floor height is a number from 0 to 3 m.",
    errorTrack: "The track width is a number from 0.5 to 3.5 m.",
    errorInnerWidth: "The internal width is a number from 0.5 to 4 m.",
    errorVehicleMass: "The vehicle mass is a number from 0 to 60000 kg.",
    errorVehicleCentre: "With the vehicle mass, its centre of gravity (x, y, z) must also be entered.",
    errorItemDimensions: "With dimensions enabled every row must have a length, a width and a height.",

    unitKg: "kg",
    unitKgm: "kg·m",
    unitM: "m",
  },

  "chargeable-weight": {
    items: "Shipment items",
    itemsHint:
      "One row per item: length cm, width cm, height cm, count, mass per piece kg, number of layers the item stacks in (empty or 0 reads as 1).",
    divisor: "Divisor",
    divisorHint:
      "A number from the contract with the carrier in cm³/kg, e.g. 4000, 5000 or 6000. The tool does not assume it.",
    densityDivisor: "Divisor given as kg/m³",
    densityDivisorHint: "An alternative to the divisor above — used if the divisor in cm³/kg is empty.",
    ldmWidth: "Cargo-space width for the loading metre",
    massPerLdm: "Mass per loading metre",
    massPerLdmHint: "A number from the contract in kg/ldm. Empty or 0 excludes that basis.",
    massPerPalletSpace: "Mass per pallet place",
    palletSpaces: "Number of pallet places",
    roundingStep: "Rounding step",
    rounding: "Round",
    roundingPerItem: "Per piece",
    roundingPerShipment: "To the whole shipment",
    pricePerKg: "Price per kilogram",

    results: "Result",
    actualMass: "Actual mass",
    volumetricMass: "Volumetric mass",
    loadingMetreMass: "Mass by loading metres",
    palletSpaceMass: "Mass by pallet places",
    chargeableMass: "Chargeable mass (before rounding)",
    roundedPerShipment: "Rounded to the whole shipment",
    roundedPerItem: "Rounded per piece, then summed",
    billedMass: "Mass that is invoiced",
    amount: "Invoice amount",
    currency: "RSD",
    volume: "Volume",
    loadingMetres: "Loading metres",
    basisActual: "actual mass",
    basisVolumetric: "volumetric mass",
    basisLoadingMetre: "loading metre",
    basisPalletSpace: "pallet place",
    colVolume: "Volume",
    colActual: "Actual mass",
    colVolumetric: "Volumetric mass",
    colLdm: "Loading metres",
    colChargeable: "Applicable",

    formula:
      "mv = V/d     ldm = (L·W·q)/(10000·Bw·t)     chargeable = max(actual, mv, ldm·kldm, ...)",
    inputs: "Entered",

    errorItems: "Enter at least one item row, up to 200 rows.",
    errorLdmWidth: "The width for the loading metre is a number from 1 to 4 m.",
    errorRoundingStep: "The rounding step is a number from 0.01 to 100 kg.",
    errorItemDimensions: "An item's dimensions are numbers from 0 to 10000 cm.",
    errorItemQuantity: "The count is a whole number from 0 to 100000.",
    errorItemMass: "The mass per piece is a number from 0 to 100000 kg.",

    unitKg: "kg",
    unitM: "m",
    unitM3: "m³",
    unitLdm: "ldm",
  },

  "cost-per-km-transport": {
    fixedAnnual: "Fixed annual costs",
    fixedAnnualHint:
      "The sum of annual fixed items you add up outside the tool: leasing or depreciation, insurance, registration, parking, bookkeeping, driver's pay, other.",
    annualKm: "Kilometres driven per year",
    annualKmHint: "A planning assumption, not a datum from the tool.",
    emptyShare: "Empty-running share",
    emptyShareHint: "Empty kilometres ÷ total kilometres, in percent. A planning assumption.",
    consumption: "Fuel consumption",
    fuelPrice: "Fuel price",
    fuelPriceHint: "A market price the tool does not know.",
    tyreSetPrice: "Price of a set of tyres",
    tyreLifeKm: "Life of a set of tyres",
    servicePrice: "Price of a regular service",
    serviceIntervalKm: "Service interval",
    serviceIntervalKmHint: "A number from the specific vehicle's service book.",
    repairsPerKm: "Repair provision",
    adBlueShare: "AdBlue consumption as a share of diesel",
    adBluePrice: "AdBlue price",
    adBluePriceHint: "A market price the tool does not know.",
    marginOnPrice: "Target margin on the price",
    markupOnCost: "Target markup on the cost",
    workingDays: "Working days per year",

    results: "Result",
    fixedPerKm: "Fixed cost per kilometre",
    fuelPerKm: "Fuel per kilometre",
    tyresPerKm: "Tyres per kilometre",
    servicePerKm: "Service per kilometre",
    adBluePerKm: "AdBlue per kilometre",
    variablePerKm: "Variable cost per kilometre",
    totalPerKm: "Total cost per kilometre",
    perLadenKm: "Cost per kilometre under load",
    annualCost: "Total annual cost",
    perWorkingDay: "Cost per working day",
    priceAtMargin: "Price at a margin on the price",
    priceAtMarkup: "Price at a markup on the cost",
    markupEquivalent: "Equivalent markup on the cost (%)",

    formula:
      "f = FIX/Kt     v = fuel + tyres + service + repairs + AdBlue     c = f + v     cl = c/(1 − e)",
    inputs: "Entered",

    errorFixedAnnual: "The fixed annual costs are a number from 0 to 1000000000 RSD.",
    errorAnnualKm: "The kilometres per year are a number from 1 to 1000000.",
    errorEmptyShare: "The empty-running share is a number from 0 to 99%.",
    errorWorkingDays: "The working days per year is a whole number from 1 to 366.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    currency: "RSD",
    currencyPerKm: "RSD/km",
    unitKm: "km",
  },

  "driving-hours-planner": {
    departure: "Departure time (h:mm)",
    plannedDriving: "Planned driving (h:mm)",
    plannedDrivingHint: "If empty, it is calculated from the distance and average speed below.",
    distance: "Distance",
    averageSpeed: "Average speed",
    continuousLimit: "Continuous-driving limit (h:mm)",
    limitHint:
      "The limit is set by drivers' hours regulations and changes. Neagle does not know it and offers no value.",
    breakMinutes: "Break duration (min)",
    splitBreak: "Splitting the break into two parts",
    yes: "Yes",
    no: "No",
    firstBreakPart: "First part of the break (min)",
    drivingBeforeFirstPart: "Driving after which the first part is taken (h:mm)",
    dailyLimit: "Daily driving limit (h:mm)",
    dailyRestMinutes: "Daily rest duration (h:mm)",
    drivenSinceBreak: "Driving already done since the last break (h:mm)",
    drivenToday: "Daily driving already done (h:mm)",
    otherWork: "Other working time",
    otherWorkHint: "One row per entry: minutes, after how many hours of driving (h:mm). Up to 20 rows.",

    results: "Layout",
    colKind: "Kind",
    colStart: "Start",
    colEnd: "End",
    colMinutes: "Duration",
    colSinceBreak: "Driving since a break",
    colToday: "Driving in the day",
    kindDrive: "Driving",
    kindBreak: "Break",
    kindDailyRest: "Daily rest",
    kindOtherWork: "Other working time",
    arrival: "Arrival",
    elapsedMinutes: "Total elapsed time",
    drivingMinutes: "Driving total",
    breakMinutesTotal: "Breaks total",
    restMinutes: "Rests total",
    otherWorkMinutes: "Other working time total",
    sinceBreak: "Driving since the last break",
    today: "Driving in the current day",
    ratio: "Ratio to the limit",
    continuousLimitReachedAt: "Time of reaching the continuous-driving limit",
    dailyLimitReachedAt: "Time of reaching the daily driving limit",
    truncatedNote:
      "The plan is longer than the display (200 blocks reached) — as much as was calculated is shown.",
    unplacedNote:
      "Some other-working-time entries have a threshold greater than the total planned driving and were not inserted.",

    formula: "s = min(Rc, Rd, Dl, ...)     t += s     Rc −= s     Rd −= s",
    inputs: "Entered",

    errorDeparture: "The departure time is h:mm between 00:00 and 23:59.",
    errorContinuousLimit: "The continuous-driving limit is h:mm greater than 0.",
    errorBreakMinutes: "The break duration is a number of minutes from 1 to 600.",
    errorDailyLimit: "The daily driving limit is h:mm greater than 0.",
    errorDailyRestMinutes: "The daily rest duration is h:mm greater than 0.",
    errorPlannedDriving: "Enter the planned driving or the distance and average speed.",
    errorAverageSpeed: "The average speed is a number from 1 to 130 km/h.",
    errorFirstBreakPart: "The first part of the break is a number of minutes smaller than the total break duration.",
    errorDrivingBeforeFirstPart: "The driving after which the first part is taken is h:mm greater than 0.",
    errorGeneric: "Check the entered numbers and times — one is outside the allowed range.",
  },

  "eta-with-breaks": {
    distance: "Distance",
    averageSpeed: "Average driving speed",
    averageSpeedHint: "The user's planning assumption — the tool knows neither the route nor the traffic.",
    departure: "Departure time (h:mm)",
    breaks: "Planned breaks (min)",
    waiting: "Waiting at the border and ferry (min)",
    loading: "Loading and unloading (min)",
    reserve: "Reserve",
    targetTime: "Target arrival time (h:mm)",
    targetDayOffset: "Number of days from departure to the target arrival",
    targetDayOffsetHint: "0 means the same day as the departure.",

    results: "Result",
    drivingMinutes: "Pure driving time",
    stopMinutes: "Sum of stops",
    totalMinutes: "Total elapsed time (without reserve)",
    totalWithReserve: "Total elapsed time (with reserve)",
    arrival: "Arrival time",
    doorToDoorSpeed: "Door-to-door average speed (with reserve)",
    doorToDoorSpeedNoReserve: "Door-to-door average speed (without reserve)",
    targetTitle: "Against the target arrival time",
    latestDeparture: "Latest departure",
    available: "Available time",
    minutesAvailableForDriving: "Time available for driving",
    requiredSpeed: "Required average driving speed",
    noRequiredSpeed:
      "With the entered stops and reserve, such a speed does not exist — the stops exceed the available time.",

    formula: "tv = 60·D/v     tuk = (tv + Z)·(1 + r)     arrival = departure + tuk",
    inputs: "Entered",

    errorDistance: "The distance is a number from 0 to 20000 km.",
    errorAverageSpeed: "The average speed is a number from 1 to 130 km/h.",
    errorDeparture: "The departure time is h:mm between 00:00 and 23:59.",
    errorReserve: "The reserve is a number from 0 to 100%.",
    errorTargetTime: "The target arrival time is h:mm between 00:00 and 23:59.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitKm: "km",
    unitKmh: "km/h",
  },

  "fuel-consumption-cost": {
    distance: "Distance travelled",
    distanceHint: "Used only if the two odometer readings below are not both entered.",
    odometerStart: "Odometer reading at the start",
    odometerEnd: "Odometer reading at the end",
    litres: "Fuel used",
    pricePerLitre: "Fuel price",
    pricePerLitreHint: "A market price the tool does not know or take over.",
    cargoTonnes: "Load mass",
    ladenDistance: "Distance under load",
    ladenDistanceHint: "If empty, the whole distance travelled is used.",
    fuelRemaining: "Fuel remaining in the tank",

    results: "Result",
    per100Km: "Consumption",
    kmPerLitre: "Economy",
    mpgUs: "mpg (US)",
    mpgImperial: "mpg (imperial)",
    totalCost: "Total fuel cost",
    costPerKm: "Cost per kilometre",
    tonneKmDistance: "Distance used for tonne-kilometres",
    tonneKm: "Tonne-kilometres",
    litresPer100TonneKm: "Litres per 100 tonne-kilometres",
    costPerTonneKm: "Cost per tonne-kilometre",
    range: "Range at the same consumption",

    formula: "C100 = 100·L/D     E = D/L     T = L·P     TK = m·D     R = Lr·D/L",
    inputs: "Entered",

    errorOdometer: "Enter both odometer readings or neither; the end must be greater than the start.",
    errorDistance: "The distance travelled is a number from 0.1 to 100000 km.",
    errorLitres: "The fuel used is a number from 0.01 to 5000 l.",
    errorPricePerLitre: "The fuel price is a number from 0 to 100000 RSD/l.",
    errorCargoTonnes: "The load mass is a number from 0 to 100 t.",
    errorFuelRemaining: "The fuel remaining is a number from 0 to 5000 l.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitKm: "km",
    unitL: "l",
    unitL100km: "l/100 km",
    unitKmL: "km/l",
    unitTkm: "t·km",
    unitL100tkm: "l/100 t·km",
    currency: "RSD",
    currencyPerKm: "RSD/km",
    currencyPerL: "RSD/l",
    currencyPerTkm: "RSD/t·km",
  },

  "gear-ratio-road-speed": {
    engineRpm: "Engine speed",
    gearRatio: "Gearbox ratio",
    finalDrive: "Final-drive ratio",
    transferRatio: "Transfer or reduction ratio",
    circumference: "Tyre rolling circumference",
    circumferenceHint: "From the Speedometer error tool, or measured on your own vehicle.",
    gears: "List of gear ratios",
    gearsHint: "One gear ratio per row, up to 16 rows.",
    shiftRpm: "Engine speed at which the gear is changed",
    desiredSpeed: "Desired speed",

    results: "Result",
    totalRatio: "Total gear ratio",
    wheelRpm: "Wheel speed",
    speed: "Vehicle speed",
    speedNote: "Theoretical speed without drive-wheel slip.",
    speedPer1000Rpm: "Speed per 1000 engine rpm",
    rpmAtDesiredSpeed: "Engine speed for the desired speed",
    colRatio: "Gear ratio",
    colTotalRatio: "Total ratio",
    colSpeed: "Speed at the entered rpm",
    colSpeedAtShift: "Speed at the shift rpm",
    colRpmDrop: "Rpm drop on the shift",

    formula: "i = ig·if·ir     v = n·C·60/(i·1000000)     n = v·i·1000000/(60·C)",
    inputs: "Entered",

    errorEngineRpm: "The engine speed is a number from 100 to 12000 rpm.",
    errorGearRatio: "The gear ratio is a number from 0.3 to 20.",
    errorFinalDrive: "The final-drive ratio is a number from 1 to 12.",
    errorTransferRatio: "The transfer ratio is a number from 0.3 to 10.",
    errorCircumference: "The rolling circumference is a number from 500 to 5000 mm.",
    errorGears: "Every ratio in the gear list is a number from 0.3 to 20, up to 16 rows.",
    errorShiftRpm: "The shift rpm is a number from 100 to 12000 rpm.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitKmh: "km/h",
    unitRpm: "rpm",
    unitMm: "mm",
  },

  "gvw-payload": {
    mode: "Mode",
    modeSingle: "A single vehicle",
    modeCombination: "Vehicle combination",
    vehicleTare: "Tare of the vehicle with its body",
    tareIncludes: "The tare already includes fuel, AdBlue and crew",
    tareIncludesHint:
      "Turn on if the tare from the registration is already the kerb mass — then fuel, AdBlue and crew are not added a second time.",
    yes: "Yes",
    no: "No",
    trailerTare: "Tare of the trailer or semi-trailer",
    fuelLitres: "Fuel in the tank",
    fuelDensity: "Fuel density",
    fuelDensityHint:
      "Holds at 15 °C. The entered litres are the volume at the tank temperature — without temperature correction.",
    adBlueLitres: "AdBlue in the tank",
    adBlueDensity: "AdBlue density",
    adBlueDensityHint: "Holds at 20 °C.",
    crew: "Driver and crew",
    crewHint: "The actual measured mass is entered, not an assumption.",
    equipment: "Equipment, tools and personal luggage",
    packaging: "Tare of the packaging and pallets",
    cargo: "Load",
    vehicleLimit: "Total vehicle mass limit",
    limitHint: "From the registration and the weight regulations. Neagle does not know them and offers no value.",
    trailerLimit: "Trailer or semi-trailer mass limit",
    combinationLimit: "Combination mass limit",

    results: "Result",
    runningMass: "Kerb mass",
    combinationEmptyMass: "Mass of the empty combination (towing vehicle + trailer)",
    payloadMass: "Payload mass (load + packaging)",
    totalMass: "Total mass",
    ratio: "Ratio to the limit",
    diff: "Difference (calculated − limit)",
    vehicleWithoutCargo: "Mass of the towing vehicle (without load)",
    trailerWithoutCargo: "Mass of the trailer (without load, tare alone)",
    payloadHeadroom: "Difference to the limit with an empty load",
    headroomUsed: "Use of that difference by the load and packaging",
    minCargoHeadroom: "Smallest remaining payload to any limit",
    densityNote:
      "The distribution of the load mass between the towing vehicle and the trailer is not assumed here — the Axle load tool is for that.",

    formula: "Mv = tare + mg + ma + crew + equipment     Mt = load + packaging     M = Mv + Mt",
    inputs: "Entered",

    errorVehicleTare: "The vehicle tare is a number from 0 to 60000 kg.",
    errorFuelLitres: "The fuel is a number from 0 to 2000 l.",
    errorFuelDensity: "With fuel greater than zero, the fuel density is a number from 0.7 to 1.1 kg/l.",
    errorAdBlueLitres: "The AdBlue is a number from 0 to 200 l.",
    errorAdBlueDensity: "With AdBlue greater than zero, the AdBlue density is a number from 1.0 to 1.2 kg/l.",
    errorCrew: "The driver and crew are a number from 0 to 600 kg.",
    errorEquipment: "The equipment is a number from 0 to 5000 kg.",
    errorPackaging: "The packaging is a number from 0 to 20000 kg.",
    errorCargo: "The load is a number from 0 to 60000 kg.",
    errorTrailerTare: "The trailer tare is a number from 0 to 40000 kg.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitKg: "kg",
  },

  "load-lashing-force": {
    method: "Securing method",
    methodTopOver: "Over-the-top (friction)",
    methodDirect: "Direct (diagonal)",
    methodBlocking: "Blocking",
    mass: "Load mass",
    forwardC: "Forward acceleration coefficient",
    coefficientHint:
      "A number from the cargo-securing standard you apply. Neagle does not know it and offers no value.",
    backwardC: "Backward acceleration coefficient",
    lateralC: "Lateral acceleration coefficient",
    friction: "Friction coefficient μ",
    verticalAngle: "Vertical lashing angle α",
    angleHint: "Measured from the cargo-space floor.",
    horizontalAngle: "Horizontal lashing angle β",
    transferFactor: "Transmission factor of tension to the other side k",
    stf: "STF from the lashing's label",
    lc: "LC from the lashing's label",
    lashings: "Number of lashings in the arrangement",

    results: "Result",
    weight: "Load weight",
    frictionForce: "Friction from self-weight",
    verticalForce: "Vertical force of one lashing (Fv)",
    perLashing: "Force per lashing",
    setForce: "Force of the whole entered arrangement",
    forward: "Forwards",
    backward: "Backwards",
    lateral: "Lateral",
    drivingForce: "Force in the direction (c·G)",
    remainingForce: "Remaining force to secure (Fp)",
    noRemainingForce: "By this calculation no force remains to secure in this direction.",
    quotient: "Ratio Fp / force per lashing",
    setRatio: "Ratio of the entered arrangement to Fp",
    slidingOnlyNote: "Only sliding equilibrium is calculated, not the tipping of the load.",

    formulaTopOver: "Fv = STF·sinα·(1+k)     Fg = μ·Fv     Fp = (c−μ)·G     q = Fp/Fg",
    formulaDirect: "Fe = LC·(cosα·cosβ + μ·sinα)     Fp = (c−μ)·G     q = Fp/Fe",
    formulaBlocking: "Fp = (c−μ)·G",
    inputs: "Entered",

    errorMass: "The load mass is a number from 1 to 60000 kg.",
    errorCoefficient: "The acceleration coefficient is a number from 0 to 2.",
    errorFriction: "The friction coefficient μ is a number from 0 to 1.",
    errorLashings: "The number of lashings is a whole number from 0 to 50.",
    errorVerticalAngle: "The vertical angle α is a number from 1 to 90°.",
    errorTransferFactor: "The transmission factor k is a number from 0 to 1.",
    errorStf: "STF is a number from 1 to 2000 daN.",
    errorHorizontalAngle: "The horizontal angle β is a number from 0 to 89°.",
    errorLc: "LC is a number from 1 to 20000 daN.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitKg: "kg",
    unitDaN: "daN",
    unitKn: "kN",
  },

  "loading-space-utilisation": {
    innerLength: "Internal length of the cargo space",
    innerWidth: "Internal width",
    innerHeight: "Internal height",
    items: "Items",
    itemsHint:
      "One row per item: length m, width m, height m, count, number of layers it stacks in.",
    ldmWidth: "Contractual width for the loading metre",
    ldmWidthHint: "A number from the user's contract.",

    results: "Result",
    availableVolume: "Available volume",
    availableFloorArea: "Available floor area",
    availableLoadingMetres: "Available loading metres",
    usedVolume: "Volume used",
    usedFloorArea: "Floor area used",
    usedLoadingMetres: "Loading metres used",
    volumeShare: "Utilisation by volume",
    floorShare: "Utilisation by floor area",
    loadingMetreShare: "Utilisation by loading metres",
    remainingVolume: "Remaining volume",
    remainingFloorArea: "Remaining floor area",
    remainingLoadingMetres: "Remaining loading metres",
    averageStackHeight: "Average stacking height",
    stackHeightShare: "Share of the average height in the internal height",
    largestBasis: "Basis with the highest percentage",
    basisVolume: "volume",
    basisFloor: "floor area",
    basisLoadingMetre: "loading metre",
    widerNote:
      "At least one item is wider than the internal width of the cargo space — for it the expression describes nothing that fits in the space.",
    tallerNote: "At least one stacked item exceeds the internal height.",

    formula: "ηV = Vu/Vr     ηA = Au/Ar     ηLDM = LDMu/LDMr",
    inputs: "Entered",

    errorItems: "Enter at least one item row, up to 200 rows.",
    errorInnerLength: "The internal length is a number from 0.5 to 30 m.",
    errorInnerWidth: "The internal width is a number from 0.5 to 4 m.",
    errorInnerHeight: "The internal height is a number from 0.3 to 5 m.",
    errorLdmWidth: "The contractual width is a number from 1 to 4 m.",
    errorItemDimensions: "An item's dimensions are numbers from 0 to 100 m.",

    unitM: "m",
    unitM2: "m²",
    unitM3: "m³",
    unitLdm: "ldm",
  },

  "pallet-load-plan": {
    innerLength: "Internal length of the cargo space",
    innerWidth: "Internal width",
    innerHeight: "Internal height",
    palletType: "Pallet type",
    palletEur: "EUR 1200×800",
    palletIndustrial: "Industrial 1200×1000",
    palletCustom: "Custom",
    customLength: "Custom pallet length",
    customWidth: "Custom pallet width",
    loadedHeight: "Height of the loaded pallet",
    loadedHeightHint: "Including any overhang of the load beyond the pallet.",
    stacking: "Stacking in height allowed",
    yes: "Yes",
    no: "No",
    maxLayers: "Maximum layers",
    rotationAllowed: "Rotating pallets allowed",

    results: "Result",
    geometryOnlyNote:
      "The tool calculates geometry only. Mass, axle distribution, pallet load capacity and cargo securing are other tools and are not shown here — the number of places is not a claim that this many may be loaded.",
    lengthwise: "Longitudinal layout",
    crosswise: "Transverse layout",
    combined: "Best combination of strips",
    combinedBands: "Composition of the combination (longitudinal + transverse strips)",
    combinedNote:
      "The exact maximum is calculated over strip layouts — every strip one orientation. Mixed orientations within one strip can give more places, but this tool does not search that.",
    perFloor: "Pallets on the floor",
    usedLength: "Length used",
    remainingLength: "Remaining length",
    places: "Pallet places (with stacking)",
    floorArea: "Occupied floor area",
    freeFloorArea: "Free floor area",
    layers: "Layers by height",
    zeroLayersNote: "The loaded pallet does not pass the internal height of the space.",

    formula:
      "n = floor(Wv/q)     r = floor(Lv/p)     N = n·r     t = min(max layers, floor(Hv/hn))",
    inputs: "Entered",

    errorInnerLength: "The internal length is a number from 0.5 to 30 m.",
    errorInnerWidth: "The internal width is a number from 0.5 to 4 m.",
    errorInnerHeight: "The internal height is a number from 0.3 to 5 m.",
    errorPalletLength: "The pallet length is a number from 100 to 3000 mm.",
    errorPalletWidth: "The pallet width is a number from 100 to 3000 mm.",
    errorLoadedHeight: "The height of the loaded pallet is a number from 50 to 3000 mm.",
    errorMaxLayers: "The maximum layers is a whole number from 1 to 10.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitM: "m",
    unitMm: "mm",
    unitM2: "m²",
  },

  "reefer-fuel-consumption": {
    continuousHours: "Operating hours in continuous mode",
    continuousRate: "Consumption in continuous mode",
    rateHint: "A datum from the specific generator's manual or from your own measurement.",
    startStopHours: "Operating hours in start-stop mode",
    startStopRate: "Consumption in start-stop mode",
    pullDownHours: "Operating hours cooling down",
    pullDownRate: "Consumption cooling down",
    pricePerLitre: "Fuel price",
    pricePerLitreHint: "A market price the tool does not know.",
    tankLitres: "Fuel in the generator's tank",
    tractionLitres: "Fuel used for traction",
    pallets: "Number of pallets",
    days: "Tour duration",

    results: "Result",
    litres: "Fuel used by the generator",
    hours: "Total operating hours",
    modeContinuous: "continuous",
    modeStartStop: "start-stop",
    modePullDown: "cooling down",
    omittedNote: "A mode with operating hours but no entered consumption did not enter the total:",
    averageRate: "Average consumption",
    cost: "Fuel price",
    litresPerDay: "Consumption per day",
    costPerDay: "Cost per day",
    litresPerPallet: "Litres per pallet (whole tour)",
    costPerPallet: "Cost per pallet (whole tour)",
    litresPerPalletDay: "Litres per pallet and day",
    costPerPalletDay: "Cost per pallet and day",
    autonomyHours: "Autonomy ratio (tank ÷ average consumption)",
    autonomyDays: "Same, in days (assuming continuous operation, ÷24)",
    autonomyDaysAtTripRate: "Same, in days at the operating hours from this tour",
    autonomyContinuousHours: "Autonomy in continuous mode",
    autonomyStartStopHours: "Autonomy in start-stop mode",
    autonomyPullDownHours: "Autonomy while cooling down",
    shareOfTripFuel: "Generator's share of the tour's total fuel",

    formula: "L = Σhᵢ·qᵢ     H = Σhᵢ     q̄ = L/H     T = L·P     A = Vr/q̄",
    inputs: "Entered",

    errorHours:
      "The operating hours are a number in the allowed range (0 to 2000, or 0 to 200 for cooling down).",
    errorPricePerLitre: "The fuel price is a number from 0 to 100000 RSD/l.",
    errorTankLitres: "The fuel in the generator's tank is a number from 0 to 1000 l.",
    errorTractionLitres: "The fuel for traction is a number from 0 to 5000 l.",
    errorPallets: "The number of pallets is a whole number from 0 to 100.",
    errorDays: "The tour duration is a number from 0 to 90 days.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitL: "l",
    unitLh: "l/h",
    unitH: "h",
    unitDays: "days",
    currency: "RSD",
  },

  "service-interval-km-hours": {
    currentKm: "Current odometer",
    lastServiceKm: "Odometer at the last service",
    distanceInterval: "Interval by kilometres",
    intervalHint:
      "A number from the specific vehicle's service book. Empty or 0 excludes that basis.",
    currentHours: "Current engine hours",
    lastServiceHours: "Engine hours at the last service",
    hoursInterval: "Interval by engine hours",
    lastServiceDate: "Date of the last service (DD.MM.YYYY)",
    dateHint: "Without this date the monthly basis is not included in the comparison.",
    monthsInterval: "Interval by months",
    kmPerDay: "Average kilometres per day",
    hoursPerDay: "Average engine hours per day",
    today: "Today's date",

    results: "Result",
    travelledKm: "Covered since the last service",
    travelledHours: "Covered since the last service (engine hours)",
    basisDistance: "Kilometre basis",
    basisHours: "Engine-hour basis",
    basisMonths: "Monthly basis",
    remaining: "Remaining to expiry",
    dueAt: "Absolute expiry reading",
    date: "Estimated expiry date",
    first: "Expires first",
    daysToNext: "Gap to the next basis",
    kmPerEngineHour: "Kilometres per engine hour (this vehicle's average between two services)",
    distanceIntervalInHours: "Kilometre interval expressed in engine hours",
    hoursIntervalInKm: "Engine-hour interval expressed in kilometres",
    averagesNote:
      "The dates are an estimate from the average daily values you enter, not from the actual driving schedule.",

    formula: "Δk = current − last     Rk = Ik − Δk     days = Rk / km per day",
    inputs: "Entered",

    errorCurrentKm:
      "The current odometer must be greater than or equal to the odometer at the last service.",
    errorLastServiceKm: "The odometer at the last service is a number from 0 to 9999999.",
    errorCurrentHours:
      "The current engine hours must be greater than or equal to the engine hours at the last service.",
    errorKmPerDay: "The average kilometres per day is a number from 0 to 3000.",
    errorHoursPerDay: "The average engine hours per day is a number from 0 to 24.",
    errorLastServiceDate: "The date of the last service is a valid date in the format DD.MM.YYYY.",
    errorMonthsInterval: "The interval by months is a whole number from 1 to 120.",
    errorGeneric: "Check the entered numbers and dates — one is outside the allowed range.",

    unitKm: "km",
    unitH: "h",
    unitDays: "days",
    unitKmh: "km/h",
  },

  "speedometer-tyre-deviation": {
    currentWidth: "Existing tyre — width (mm)",
    currentProfile: "Existing tyre — profile (%)",
    currentRim: "Existing tyre — rim (in)",
    replacementWidth: "New tyre — width (mm)",
    replacementProfile: "New tyre — profile (%)",
    replacementRim: "New tyre — rim (in)",
    measuredCurrent: "Measured rolling circumference of the existing tyre",
    measuredHint: "0 means the circumference is calculated from the tyre size.",
    measuredReplacement: "Measured rolling circumference of the new tyre",
    deflection: "Deflection factor under load",
    deflectionHint: "1.000 is pure geometry — a loaded tyre rolls a shorter distance.",
    indicatedSpeed: "Speedometer reading",
    indicatedDistance: "Distance by the trip computer",
    desiredTrueSpeed: "Desired actual speed",
    characteristicCoefficient: "Characteristic coefficient w",
    characteristicCoefficientHint:
      "The tachograph constant printed on the vehicle, if present (imp/km).",

    results: "Result",
    currentDiameter: "Outer diameter of the existing tyre",
    replacementDiameter: "Outer diameter of the new tyre",
    currentCircumference: "Rolling circumference of the existing tyre",
    replacementCircumference: "Rolling circumference of the new tyre",
    sourceMeasured: "measured",
    sourceGeometry: "from geometry",
    mixedSourceNote:
      "One circumference is measured and the other from geometry — the geometric circumference is as a rule several percent larger, so the ratio below mixes two sources.",
    currentRevsPerKm: "Revolutions per kilometre — existing",
    replacementRevsPerKm: "Revolutions per kilometre — new",
    circumferenceRatio: "Circumference ratio (k = C₂/C₁)",
    diameterChange: "Change in diameter",
    axleHeightChange: "Change in the vehicle's axle height",
    axleHeightNote: "The difference in free diameters, without a change in deflection under load.",
    trueSpeed: "Actual speed",
    indicatedForDesired: "Speedometer reading for the desired actual speed",
    trueDistance: "Actual distance travelled",
    errorPer100Km: "Error per 100 km",
    wOverRatio: "w ÷ k (arithmetic, not calibration of the device)",
    calibrationNote:
      "This is the difference the tyre-size change brings, not the absolute accuracy of the vehicle's speedometer.",

    formula: "D = rim·25.4 + 2·width·profile/100     C = π·D·f     k = C₂/C₁     vs = vp·k",
    inputs: "Entered",

    errorTyreWidth: "The tyre width is a number from 125 to 495 mm.",
    errorTyreProfile: "The tyre profile is a number from 20 to 100%.",
    errorTyreRim: "The rim is a number from 8 to 26 inches.",
    errorDeflection: "The deflection factor is a number from 0.90 to 1.00.",
    errorIndicatedSpeed: "The speedometer reading is a number from 1 to 250 km/h.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitMm: "mm",
    unitKm: "km",
    unitKmh: "km/h",
  },

  "tank-volume-by-level": {
    shape: "Tank shape",
    shapeLying: "Horizontal cylinder",
    shapeStanding: "Vertical cylinder",
    shapeBox: "Box (cuboid)",
    diameter: "Diameter",
    length: "Length",
    lengthHint: "The length of the cylindrical part, between the two points where the end domes begin — without the domes themselves.",
    width: "Width",
    height: "Height",
    domeDepth: "Depth of the end dome",
    domeDepthHint:
      "0 for a flat end. Measured for one end; above half the diameter it is not taken into account.",
    level: "Dipstick reading",
    density: "Liquid density",
    densityHint: "From the delivery note, not an assumed value.",
    pricePerLitre: "Price per litre",
    targetVolume: "Target volume",

    results: "Result",
    volume: "Volume at the read level",
    volumeM3: "Volume at the read level (m³)",
    fullVolume: "Full tank volume",
    fillShare: "Occupancy",
    emptySpace: "Empty space to the top",
    mass: "Mass of the contents",
    value: "Value of the contents",
    sensitivity: "Sensitivity of the reading",
    levelForTarget: "Level for the target volume",
    levelAboveCapacityNote:
      "The entered level is above the tank's capacity — the volume is clamped to full.",
    calibrationNote:
      "The density is at 15 °C, without correction for the temperature of the liquid in the tank.",

    formulaLying: "V = A(h)·L + V_dome(h)     A(h) area of a circular segment",
    formulaOther: "V = A·h     A — cross-section, constant over the height",
    inputs: "Entered",

    errorLevel: "The reading is a number from 0 to 5000 mm.",
    errorDiameter: "The diameter is a number from 100 to 5000 mm.",
    errorLength: "The length is a number from 100 to 20000 mm.",
    errorDomeDepth: "The depth of the end dome is a number from 0 to 1500 mm and not greater than the radius.",
    errorHeight: "The height is a number from 100 to 5000 mm.",
    errorWidth: "The width is a number from 100 to 5000 mm.",
    errorDensity: "The density is a number from 0.50 to 2.00 kg/l.",
    errorPricePerLitre: "The price per litre is a number from 0 to 100000.",
    errorTargetVolume: "The target volume is a number from 0 to 200000 l.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitL: "l",
    unitM3: "m³",
    unitKg: "kg",
    unitMm: "mm",
    unitLmm: "l/mm",
    unitKgL: "kg/l",
    currency: "RSD",
  },

  "trip-cost-quote": {
    ladenKm: "Kilometres under load",
    emptyKm: "Empty and access kilometres",
    costPerKmKind: "The entered rate is per",
    costPerKmKindHint:
      "If the rate is taken from the Cost per kilometre tool, check whether it is a cost per total kilometre or per kilometre under load — multiplied by the wrong mileage, the empty run is charged twice.",
    costPerKmKindTotal: "total kilometre",
    costPerKmKindLaden: "kilometre under load",
    costPerKm: "Cost per kilometre",
    costPerKmHint:
      "It must not include tolls, per diems or waiting if those items are entered separately below.",
    tolls: "Tolls",
    ferriesAndVignettes: "Ferry, tunnel, vignette",
    terminalCharges: "Loading and unloading fees",
    waitingHours: "Hours of waiting",
    waitingRate: "Price per hour of waiting",
    days: "Number of days on the road",
    perDiem: "Per diem",
    perDiemHint: "The amount is set by the state and changes. Neagle does not know it and offers no value.",
    nights: "Number of overnight stays",
    nightRate: "Price per overnight stay",
    otherCosts: "Other costs",
    marginMethod: "Margin method",
    marginMethodOnPrice: "Margin on the price",
    marginMethodOnCost: "Markup on the cost",
    marginOnPrice: "Margin on the price",
    markupOnCost: "Margin on the cost (markup)",
    vatRate: "VAT rate",
    vatRateHint: "The rate is set by the state and changes. Neagle does not know it and offers no value.",
    cargoTonnes: "Load mass",

    results: "Result",
    doubleCountingNote:
      "Check item by item above — if any cost is included both in the cost per kilometre and in a separate row here, that item has been charged twice.",
    totalKm: "Total mileage",
    colGroup: "Cost group",
    colAmount: "Amount",
    drivingCost: "Driving cost",
    roadCost: "Tolls and fees (with waiting and other)",
    driverCost: "Per diems and overnight stays",
    totalCost: "Total tour cost",
    colMarginMethod: "Margin method",
    colPrice: "Price without VAT",
    priceAtMargin: "Price at a margin on the price",
    priceAtMarkup: "Price at a markup on the cost",
    marginEquivalenceNote:
      "The same rate gives a different price under these two methods — the relation is u = m/(1 − m). The price below is always by the chosen method.",
    priceBeforeVat: "Price without VAT (chosen method)",
    vat: "VAT",
    priceWithVat: "Price with VAT",
    breakEvenPrice: "Break-even point (price = cost)",
    breakEvenPricePerKm: "Break-even point per kilometre",
    profit: "Tour profit",
    profitPerDay: "Profit per day",
    profitShareOfPrice: "Profit as a share of the price",
    profitShareOfCost: "Profit as a share of the cost",
    pricePerKm: "Cost per kilometre",
    pricePerLadenKm: "Price per kilometre under load",
    pricePerTonne: "Price per tonne",
    regulatedFiguresNote:
      "The per-diem amount and the VAT rate are numbers you enter — Neagle does not claim that any amount is tax-deductible or that the rate is correct.",

    formula:
      "C = Ku·c + (PUT+TRJ+NAK+hw·pw+OTHER) + (nd·Dn+nn·Pn)     Pn = C/(1−m) or C·(1+u)     Z = Pn−C     VAT = Pn·v     Ps = Pn·(1+v)",
    inputs: "Entered",

    errorLadenKm: "The kilometres under load are a number from 0 to 20000.",
    errorEmptyKm: "The empty kilometres are a number from 0 to 20000.",
    errorCostPerKm: "The cost per kilometre is a number from 0 to 100000.",
    errorTolls: "The tolls are a number from 0 to 100000000.",
    errorFerriesAndVignettes: "The ferry, tunnel and vignette are a number from 0 to 100000000.",
    errorTerminalCharges: "The loading and unloading fees are a number from 0 to 100000000.",
    errorWaitingHours: "The hours of waiting are a number from 0 to 500.",
    errorWaitingRate: "The price per hour of waiting is a number from 0 to 1000000.",
    errorDays: "The number of days is a whole number from 0 to 90.",
    errorPerDiem: "The per diem is a number from 0 to 1000000.",
    errorNights: "The number of overnight stays is a whole number from 0 to 90.",
    errorNightRate: "The price per overnight stay is a number from 0 to 1000000.",
    errorOtherCosts: "The other costs are a number from 0 to 100000000.",
    errorCargoTonnes: "The load mass is a number from 0 to 100 t.",
    errorMarginOnPrice: "The margin on the price is a number from 0 to 95%.",
    errorMarkupOnCost: "The margin on the cost is a number from 0 to 500%.",
    errorVatRate: "The VAT rate is a number from 0 to 100%.",
    errorGeneric: "Check the entered numbers — one is outside the allowed range.",

    unitKm: "km",
    unitRsdKm: "RSD/km",
    currency: "RSD",
  },
} as const;
