/**
 * „Dizajn i priprema za štampu" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as the assignment spells it. The tool's
 * NAME and its one-line blurb are not here: those live in a table another
 * process owns.
 *
 * **Every tool in this pack is `riskClass: "none"`.** There is no regulatory
 * limit anywhere in it, so this file never writes a „tvoja granica" line —
 * that phrasing belongs to a pack that actually takes one.
 *
 * A unit is copy, not a constant: written out here rather than concatenated
 * in the surface.
 */
export const PRO_DIZAJN_EN = {
  "aspect-ratio-fit": {
    sourceWidth: "Source width",
    sourceHint: "In pixels or millimetres — the same unit for all inputs here.",
    sourceHeight: "Source height",
    mode: "Fit method",
    modeContain: "Fit (letterbox)",
    modeCover: "Fill (cropped)",
    modeExactWidth: "Exact width",
    modeExactHeight: "Exact height",
    modeStretch: "Stretch",
    targetWidth: "Frame width",
    targetHint: "Needed for all methods except “exact height”.",
    targetHeight: "Frame height",
    roundTo: "Rounding",
    roundToNone: "None",
    roundToPixel: "Whole pixel",

    results: "Result",
    ratioInteger: "Reduced ratio",
    noIntegerRatio: "No integer ratio (the source dimensions are not both whole numbers)",
    ratioDecimal: "Decimal ratio",
    scale: "Scale factor",
    scaleX: "Scale factor by width",
    scaleY: "Scale factor by height",
    distortion: "Distortion (sx ÷ sy)",
    outputWidth: "Resulting width",
    outputHeight: "Resulting height",
    displayWidth: "Displayed width (after rounding)",
    displayHeight: "Displayed height (after rounding)",
    displayRatioLabel: "Displayed size ratio",
    roundingRemainderWidth: "Rounding offset by width",
    roundingRemainderHeight: "Rounding offset by height",
    barWidth: "Bar by width (on each side)",
    barHeight: "Bar by height (on each side)",
    cropWidth: "Crop by width (each side, in frame units)",
    cropHeight: "Crop by height (each side, in frame units)",
    cropWidthSource: "Crop by width (in source units)",
    cropHeightSource: "Crop by height (in source units)",
    visibleSourceWidth: "Visible source width",
    visibleSourceHeight: "Visible source height",

    inputs: "Entered",
    formula:
      "fit: s = min(tw/w, th/h)   fill: s = max(tw/w, th/h)   exact width: s = tw/w   exact height: s = th/h   stretch: sx = tw/w, sy = th/h",

    errorSourceWidth: "The source width must be greater than zero.",
    errorSourceHeight: "The source height must be greater than zero.",
    errorTargetWidth: "The frame width is required for this fit method.",
    errorTargetHeight: "The frame height is required for this fit method.",
    errorRoundTo: "Invalid rounding mode.",
    errorMode: "Invalid fit method.",
  },

  "baseline-rhythm": {
    fontSize: "Letter case",
    lineHeight: "Leading",
    lineHeightHint: "Read as a multiplier or as pixels, according to the choice beside it.",
    lineHeightUnit: "Leading unit",
    unitMultiplier: "Multiplier",
    unitPx: "px",
    gridUnit: "Baseline grid unit",
    gridUnitHint: "Grid step in pixels. Default 8.",
    columnHeight: "Column height",
    columnHeightHint: "Optional — only if you also want the number of lines per column.",
    snapMode: "Snapping to the grid",
    snapUp: "Up",
    snapNearest: "To nearest",
    snapDown: "Down",

    results: "Result",
    lineHeightPx: "Leading in pixels",
    multiplier: "Leading as a multiplier",
    leading: "Gap (leading − font size)",
    halfLeading: "Half the gap",
    gridRemainder: "Remainder to the grid",
    onGrid: "Falls on the grid",
    yes: "Yes",
    no: "No",
    snapped: "Leading after snapping",
    snappedMultiplier: "Snapped leading as a multiplier",
    snappedLeading: "Gap after snapping",
    columnRaw: "Column — raw leading",
    lines: "Number of lines",
    used: "Occupied height",
    leftover: "Remainder",
    columnSnapped: "Column — snapped leading",

    inputs: "Entered",
    formula:
      "lh = multiplier×font size or px   remainder = lh mod grid (in thousandths of px)   snapped = up/nearest/down(lh/grid)×grid   lines = floor(columnHeight/lh)",

    errorFontSize: "The font size must be greater than zero.",
    errorLineHeight: "The leading must be greater than zero.",
    errorGridUnit: "The baseline grid unit must be greater than zero.",
    errorLineHeightUnit: "Invalid leading unit.",
    errorSnapMode: "Invalid snapping mode.",
    errorColumnHeight: "The column height must be greater than zero.",
  },

  "book-spine": {
    pageCount: "Number of pages",
    paperCaliper: "Sheet thickness (entered by hand)",
    paperCaliperHint:
      "In millimetres, measured with a micrometer on ONE sheet. Takes precedence over the other two sources.",
    grammage: "Paper weight",
    grammageHint: "Paper mass in g/m² — not a thickness.",
    bulk: "Bulk (cm³/g)",
    bulkHint:
      "A datum from the paper manufacturer — NOT a sheet thickness. If you enter a thickness here (e.g. 0.10 instead of 1.25), the spine comes out up to 12.5 times thinner: check the “Sheet thickness (from paper weight)” row below.",
    measuredStack: "Measured block height",
    measuredStackHint:
      "In millimetres, for the whole measured block — the third source of sheet thickness, if the first two are unknown.",
    coverCaliper: "Thickness of one cover",
    extraAllowance: "Allowance (glue, endpapers, boards)",
    extraAllowanceHint: "Everything the binding adds to the spine beyond the block and covers.",
    coverWidth: "Width of one cover",
    coverHeight: "Cover height",
    edgeWrap: "Cover turn-in (per edge)",
    edgeWrapHint:
      "For covers that wrap over the edge of the block — applied to all outer edges.",
    bindingStyle: "Binding type",
    bindingSoft: "Softcover",
    bindingHard: "Hardcover",
    hingeGroove: "Hinge (one, hardcover)",
    hingeGrooveHint:
      "Width of one hinge — applied only for a hardcover, on both sides of the spine.",

    results: "Result",
    leaves: "Number of sheets",
    caliper: "Sheet thickness (used)",
    sourceTyped: "entered by hand",
    sourceGrammage: "from paper weight and bulk",
    sourceMeasured: "from the measured block",
    block: "Block thickness",
    spine: "Spine",
    flatCoverWidth: "Developed cover width",
    flatCoverHeight: "Developed cover height",

    inputs: "Entered",
    formula:
      "sheets = ceil(pages/2)   sheetThickness = entered | paperWeight×bulk/1000 | measuredBlock/sheets   block = sheets×sheetThickness   spine = block + 2×cover + allowance   developedWidth = 2×coverWidth + spine + 2×turnIn (+ 2×hinge for hardcover)   developedHeight = coverHeight + 2×turnIn",

    errorPageCount: "The number of pages is a whole number from 1 to 20000.",
    errorCoverCaliper: "The cover thickness may not be negative.",
    errorExtraAllowance: "The allowance may not be negative.",
    errorEdgeWrap: "The cover turn-in may not be negative.",
    errorHingeGroove: "The hinge may not be negative.",
    errorBindingStyle: "Invalid binding type.",
    errorPaperCaliper: "The sheet thickness must be greater than zero.",
    errorGrammage: "The paper weight must be greater than zero.",
    errorBulk: "The bulk must be greater than zero.",
    errorMeasuredStack: "The measured block height must be greater than zero.",
    errorCaliper:
      "At least one source of sheet thickness is needed: an entered thickness, paper weight and bulk, or the measured block.",
    errorCoverWidth: "The cover width must be greater than zero.",
    errorCoverHeight: "The cover height must be greater than zero.",
  },

  "column-grid": {
    containerWidth: "Container width",
    columns: "Number of columns",
    gutter: "Gutter between columns",
    outerMargin: "Outer margin (on each side)",
    spanColumns: "Span of k columns",
    spanColumnsHint: "Optional — the width of a span of k adjacent columns.",
    minColumnWidth: "Minimum column width",
    minColumnWidthHint: "For the reverse question — how many columns of that width fit.",

    results: "Result",
    contentWidth: "Content width",
    columnWidth: "Column width",
    noGrid: "The grid does not fit — the gutters alone exceed the content. Required content width",
    columnPercent: "Column width (% of content)",
    span: "Requested span",
    colIndex: "k",
    colSpan: "Span(k)",
    colLeftEdge: "Left edge",
    maxColumns: "Most columns of that width",

    inputs: "Entered",
    formula:
      "content = container − 2×margin   column = (content − (n−1)×gutter)/n   span(k) = k×column + (k−1)×gutter   leftEdge(i) = margin + (i−1)×(column+gutter)   maxColumn = floor((content+gutter)/(min+gutter))",

    errorContainerWidth: "The container width must be greater than zero.",
    errorColumns: "The number of columns is a whole number from 1 to 24.",
    errorGutter: "The gutter may not be negative.",
    errorOuterMargin: "The margins are too large — the content width must stay greater than zero.",
    errorSpanColumns: "The span must be a whole number between 1 and the number of columns.",
    errorMinColumnWidth: "The minimum column width must be greater than zero.",
  },

  copyfitting: {
    characterCount: "Number of characters",
    charactersPerLine: "Characters per line",
    charactersPerLineHint:
      "Enter directly, or leave empty and fill in the column width and average character width below.",
    columnWidth: "Column width",
    averageCharacterWidth: "Average character width",
    averageCharacterWidthHint: "Measured on real typeset text, in millimetres.",
    linesPerColumn: "Lines per column",
    linesPerColumnHint: "Enter directly, or leave empty and fill in the column height and leading below.",
    columnHeight: "Column height",
    lineHeight: "Leading",
    columnsPerPage: "Columns per page",
    targetPages: "Target number of pages",
    targetPagesHint:
      "Optional — the reverse question: how many characters per line would fit the text into exactly this many pages.",
    paragraphs: "Number of paragraphs",
    paragraphsHint:
      "Optional — every paragraph after the first may leave up to one whole blank line at its break.",

    results: "Result",
    totalLines: "Total lines (lower bound)",
    totalLinesUpperBound: "Total lines (upper bound, with paragraphs)",
    linesPerPage: "Lines per page",
    pages: "Number of pages",
    lastPageLines: "Lines on the last page",
    lastPageFill: "Fill of the last page (%)",
    requiredCharactersPerLine: "Characters per line needed for the target page count",

    inputs: "Entered",
    formula:
      "cpl = entered or floor(columnWidth/averageCharWidth)   linesPerColumn = entered or floor(columnHeight/leading)   totalLines = ceil(characters/cpl)   upperBound = totalLines + paragraphs − 1   linesPerPage = linesPerColumn×columnsPerPage   pages = ceil(totalLines/linesPerPage)   neededCPL = ceil(characters/(targetPages×linesPerPage))",

    errorCharacterCount: "The number of characters is a whole number of 1 or more.",
    errorColumnsPerPage: "The number of columns per page is a whole number from 1 to 12.",
    errorCharactersPerLine:
      "Characters per line must be a whole number from 1 to 1000, or derive it from the column width and average character width.",
    errorColumnWidth: "The column width must be greater than zero.",
    errorAverageCharacterWidth: "The average character width must be greater than zero.",
    errorLinesPerColumn:
      "Lines per column must be a whole number from 1 to 1000, or derive it from the column height and leading.",
    errorColumnHeight: "The column height must be greater than zero.",
    errorLineHeight: "The leading must be greater than zero.",
    errorTargetPages: "The target number of pages is a whole number from 1 to 100000.",
    errorParagraphs: "The number of paragraphs is a whole number from 1 to a million.",
  },

  "css-typographic-units": {
    value: "Value",
    fromUnit: "From unit",
    rootFontSize: "Root size (rem)",
    parentFontSize: "Parent size (em)",
    deviceDpi: "Device density",
    deviceDpiHint: "Optional — the real screen or print density in dpi, for the device-pixel row.",
    assetScale: "Asset export",
    scale1x: "1x",
    scale2x: "2x",
    scale3x: "3x",

    results: "Result",
    rem: "rem",
    atRoot: "at a root of",
    em: "em",
    atParent: "at a parent of",
    devicePx: "Device pixels",
    atDensity: "at a density of",
    assetPx1x: "Export @1x",
    assetPx2x: "Export @2x",
    assetPx3x: "Export @3x",

    inputs: "Entered",
    formula:
      "in = px/96 = pt/72 = pc×12/72 = mm/25.4 = Q/101.6   rem = px/root   em = px/parent   devicePx = px×density/96   export = round(px×scale)",

    errorValue: "The value must be a finite number.",
    errorRootFontSize: "The root size must be greater than zero.",
    errorParentFontSize: "The parent size must be greater than zero.",
    errorAssetScale: "Invalid asset export.",
    errorDeviceDpi: "The device density must be greater than zero.",
    errorFromUnit: "Invalid source unit.",
  },

  "delta-e": {
    l1: "L* — standard",
    a1: "a* — standard",
    b1: "b* — standard",
    colour1Hint: "Colour 1 is the STANDARD/original — ΔE94 is asymmetric and is built from this colour.",
    l2: "L* — sample",
    a2: "a* — sample",
    b2: "b* — sample",
    colour2Hint: "Colour 2 is the SAMPLE/print being compared with the standard.",
    de94Application: "Application for ΔE94",
    applicationGraphicArts: "Graphic arts (K1 0.045, K2 0.015, kL 1)",
    applicationTextiles: "Textiles (K1 0.048, K2 0.014, kL 2)",
    kL: "kL (parametric, ΔE00 only)",
    kLHint: "Affects ΔE00 only. ΔE94 uses its own kL, locked by the application choice.",
    kC: "kC (parametric)",
    kH: "kH (parametric)",

    results: "Result",
    kL94Used: "kL used for ΔE94 (locked by the application)",
    colour1: "Colour 1 (standard)",
    colour2: "Colour 2 (sample)",

    inputs: "Entered",
    formula:
      "ΔE*ab = √(ΔL²+Δa²+Δb²)   ΔE94 = √((ΔL/kL94)² + (ΔC*/(kC·SC))² + (ΔH*/(kH·SH))²)   ΔE00 = √((ΔL'/(kL·SL))² + (ΔC'/(kC·SC))² + (ΔH'/(kH·SH))² + RT·termC·termH)",

    errorColour1: "L* must be between 0 and 100, and a* and b* must be finite numbers.",
    errorColour2: "L* must be between 0 and 100, and a* and b* must be finite numbers.",
    errorKL: "kL must be greater than zero.",
    errorKC: "kC must be greater than zero.",
    errorKH: "kH must be greater than zero.",
    errorDe94Application: "Invalid application for ΔE94.",
  },

  "ean-barcode": {
    digits: "Digits (without the check digit)",
    digitsHint: "Digits only: 12 for EAN-13, 7 for EAN-8, 11 for UPC-A. Leading zeros are kept.",
    symbology: "Symbology",
    xDimension: "X-dimension",
    xDimensionHint: "Module in millimetres. Enter this OR the magnification below, never both.",
    magnificationPercent: "Magnification (%)",
    magnificationHint:
      "A percentage of the nominal X-dimension of 0.33 mm. Enter this OR the X-dimension above, never both.",
    verifyDigits: "Code to check (with the check digit)",
    verifyDigitsHint: "The whole printed code — the length must match the chosen symbology.",

    results: "Result",
    checkDigit: "Check digit",
    code: "Whole code",
    weightedSum: "Weighted sum",
    xDimensionLabel: "X-dimension (used)",
    magnification: "Magnification (%)",
    totalModules: "Total modules",
    symbolWidth: "Symbol width (with quiet zones)",
    encodedWidth: "Width of the encoded bars",
    leftQuietZone: "Left quiet zone",
    rightQuietZone: "Right quiet zone",
    barHeight: "Bar height",
    totalHeight: "Total symbol height (with digits)",
    verifyComputed: "Calculated check digit",
    verifyTyped: "Entered check digit",
    verifyMatches: "They match",
    yes: "Yes",
    no: "No",

    inputs: "Entered",
    formula:
      "checkDigit: weight 3 on the rightmost digit, alternating 1,3,…   sum = Σ digit×weight   checkDigit = (10 − (sum mod 10)) mod 10   symbol = (encodedModules+leftQuiet+rightQuiet)×X   barHeight = nominalHeight×magnification/100",

    errorDigits:
      "The number of digits must exactly match the chosen symbology (12, 7 or 11), digits only.",
    errorXDimension: "The X-dimension must be greater than zero. Enter it or the magnification, not both.",
    errorMagnificationPercent:
      "The magnification must be greater than zero. Enter it or the X-dimension, not both.",
    errorVerifyDigits:
      "The code to check must contain only digits, in the length the chosen symbology requires (with the check digit).",
    errorSymbology: "Invalid symbology.",
  },

  "font-metrics-trim": {
    unitsPerEm: "Font unit (unitsPerEm)",
    ascender: "Ascender",
    descender: "Descender",
    descenderHint: "Usually stored negative in a font — here its absolute value is taken.",
    lineGap: "Line gap (lineGap)",
    lineGapHint:
      "In this tool it is trimmed from both offsets — it moves no margins, only the displayed content box.",
    capHeight: "Cap height (capHeight)",
    xHeight: "x-height (xHeight)",
    fontSize: "Letter case",
    lineHeight: "Leading (CSS line-height)",
    metricSource: "Metrics source",
    metricSourceHint:
      "Which font table you are entering — hhea, OS/2 sTypo or OS/2 usWin. It affects WHOSE result this is, not what a renderer will do.",
    sourceHhea: "hhea",
    sourceOs2Typo: "OS/2 sTypo",
    sourceOs2Win: "OS/2 usWin",

    results: "Result",
    unitScale: "Pixels per font unit",
    ascenderPx: "Ascender in pixels",
    descenderPx: "Descender in pixels",
    lineGapPx: "Line gap in pixels",
    capHeightPx: "Cap height in pixels",
    xHeightPx: "x-height in pixels",
    contentArea: "Content box",
    halfLeading: "Half-leading",
    trimTop: "Offset from the top",
    trimBottom: "Offset from the bottom",
    marginTop: "Top margin to apply",
    marginBottom: "Bottom margin to apply",
    metricSourceLabel: "Metrics source (of this result)",
    gapCancelsNote:
      "The line gap is trimmed from both offsets — two rival understandings of the content box give the same offset; only the displayed content box changes.",

    inputs: "Entered",
    formula:
      "s = size/fontUnit   contentBox = (ascender+|descender|+lineGap)×s   halfLeading = (leading−contentBox)/2   topOffset = halfLeading + lineGap×s/2 + (ascender−capHeight)×s   bottomOffset = halfLeading + lineGap×s/2 + |descender|×s",

    errorUnitsPerEm: "The font unit is a whole number from 1 to 16384.",
    errorAscender: "The ascender must be greater than zero.",
    errorDescender: "The descender must be a finite number other than zero.",
    errorLineGap: "The line gap may not be negative.",
    errorCapHeight: "The cap height must be greater than zero.",
    errorFontSize: "The font size must be greater than zero.",
    errorLineHeight: "The leading must be greater than zero.",
    errorMetricSource: "Invalid metrics source.",
    errorXHeight: "The x-height must be greater than zero.",
  },

  "iso-paper-sizes": {
    series: "Series",
    index: "Format index",
    targetSeries: "Target series",
    targetIndex: "Target index",
    targetIndexHint: "Optional — for the number of formats in a larger one and the copier percentage.",
    measuredWidth: "Measured width",
    measuredHint: "Optional — to identify the sheet in your hand.",
    measuredHeight: "Measured height",
    matchTolerance: "Identification tolerance",

    results: "Result",
    shortEdge: "Shorter edge",
    longEdge: "Longer edge",
    areaM2: "Area (m²)",
    areaCm2: "Area (cm²)",
    diagonal: "Diagonal",
    ratio: "Aspect ratio (actual)",
    nominalRatio: "√2 (nominal ratio)",
    envelopeFlat: "Envelope that takes it flat (C series)",
    envelopeFoldedOnce: "Envelope that takes it folded once (C series)",
    target: "Target format",
    nominalCount: "Nominal number of target formats in this one",
    copierScale: "Copier magnification (rounded / exact)",
    match: "Recognised format",
    noMatch: "No ISO format was recognised within the tolerance.",

    inputs: "Entered",
    formula:
      "short(n) = floor(long(n−1)/2), long(n) = short(n−1), starting from the series anchor   area = short×long/1e6   diagonal = √(short²+long²)   magnification = min(targetShort/short, targetLong/long)×100",

    errorSeries: "Invalid series.",
    errorIndex: "The format index is a whole number from 0 to 10.",
    errorMatchTolerance: "The tolerance is a number from 0 to 10 mm.",
    errorTargetIndex: "The target index is a whole number from 0 to 10.",
    errorTargetSeries: "Invalid target series.",
    errorMeasuredWidth: "The measured width must be greater than zero.",
    errorMeasuredHeight: "The measured height must be greater than zero.",
  },

  "modular-type-scale": {
    baseSize: "Base size",
    baseUnit: "Unit of the base size",
    ratio: "Ratio",
    ratioOctave: "Octave",
    ratioPerfectFifth: "Perfect fifth",
    ratioPerfectFourth: "Perfect fourth",
    ratioMajorThird: "Major third",
    ratioMinorThird: "Minor third",
    ratioCustomLabel: "Entered ratio",
    ratioHint: "A decimal number greater than 1.",
    stepsUp: "Steps up",
    stepsDown: "Steps down",
    rootFontSize: "Root size (for rem)",
    rounding: "Display rounding",
    roundingNone: "None",
    roundingHalf: "0.5 px",
    roundingPixel: "1 px",
    roundingFour: "To 4 px",

    results: "Result",
    basePx: "Base size in pixels",
    colStep: "Step",
    colPxRaw: "px (raw)",
    colPxRounded: "px (rounded)",
    colRem: "rem",
    colPt: "pt",

    inputs: "Entered",
    formula:
      "size(n) = basePx × ratio^n   rem = size/root   pt = size×0.75   rounding applies only to the displayed px column, never to the next step",

    errorBaseSize: "The base size must be greater than zero.",
    errorRatio: "The ratio must be a number greater than 1.",
    errorStepsUp: "Steps up is a whole number from 0 to 12.",
    errorStepsDown: "Steps down is a whole number from 0 to 12.",
    errorRootFontSize: "The root size must be greater than zero.",
    errorBaseUnit: "Invalid unit of the base size.",
    errorRounding: "Invalid rounding.",
  },

  "paper-weight": {
    grammage: "Paper weight",
    sheetWidth: "Sheet width",
    sheetHeight: "Sheet height",
    sheetCount: "Number of sheets",
    measuredMass: "Measured bundle mass",
    measuredMassHint: "Optional — for the reverse direction, the paper weight from the measured mass.",
    rollWidth: "Roll width",
    rollMass: "Roll mass (kg)",
    rollMassHint: "Optional, together with the roll width — for the roll length. It does not subtract the core mass.",

    results: "Result",
    areaM2: "Sheet area (m²)",
    sheetMass: "Mass of one sheet",
    totalMass: "Total mass (g)",
    totalMassKg: "Total mass (kg)",
    measuredGrammage: "Paper weight from the measured mass",
    rollLength: "Roll length",

    inputs: "Entered",
    formula:
      "area = width×height/1e6   sheetMass = paperWeight×area   totalMass = sheetMass×count   paperWeightFromMass = measuredMass/(count×area)   rollLength = rollMass[kg]×1e6/(paperWeight×rollWidth[mm])",

    errorGrammage: "The paper weight must be greater than zero.",
    errorSheetWidth: "The sheet width must be greater than zero.",
    errorSheetHeight: "The sheet height must be greater than zero.",
    errorSheetCount: "The number of sheets is a whole number of 1 or more.",
    errorMeasuredMass: "The measured mass must be greater than zero.",
    errorRollWidth: "The roll width must be greater than zero.",
    errorRollMass: "The roll mass must be greater than zero.",
  },

  "print-resolution": {
    direction: "Direction",
    directionPxToSize: "Pixels → size",
    directionSizeToPx: "Size → pixels",
    directionEffectivePpi: "Effective resolution",
    widthPx: "Width (px)",
    heightPx: "Height (px)",
    resolution: "Resolution (ppi)",
    resolutionHint: "Needed for both directions except “effective resolution”.",
    physicalWidth: "Physical width",
    physicalHeight: "Physical height",
    physicalUnit: "Unit of the physical size",
    bleed: "Bleed (per edge)",
    bleedHint: "In millimetres, applied to both edges of each axis.",
    scaleDenominator: "Scale denominator (1:s)",
    scaleDenominatorHint: "1 means actual size.",
    channels: "Number of channels",
    channelsHint: "1 greyscale, 3 RGB, 4 CMYK — or a free number for another combination.",
    bitsPerChannel: "Bits per channel",

    results: "Result",
    widthMm: "Width (mm)",
    heightMm: "Height (mm)",
    widthIn: "Width (in)",
    heightIn: "Height (in)",
    ppiWidth: "Resolution across the width",
    ppiHeight: "Resolution across the height",
    axesDisagree: "The axes do not agree (non-square pixels)",
    yes: "Yes",
    no: "No",
    artboardWidthMm: "Artwork — width (mm)",
    artboardHeightMm: "Artwork — height (mm)",
    artboardWidthPx: "Artwork — width (px)",
    artboardHeightPx: "Artwork — height (px)",
    finalWidthMm: "Final width at scale",
    finalHeightMm: "Final height at scale",
    finalPpiWidth: "Final resolution across the width",
    finalPpiHeight: "Final resolution across the height",
    megapixels: "Megapixels",
    bytes: "Bytes (raw)",
    mebibytes: "MiB (raw)",
    bytesNote:
      "Raw samples — without an alpha channel, ICC profile, layers or row padding. A saved file will always be larger than this number.",

    inputs: "Entered",
    formula:
      "mm = px×25.4/ppi   px = round(mm×ppi/25.4)   ppi = px×25.4/mm   artwork = image + 2×bleed (px rounded UP)   finalSize = image×s   bytes = width×height×channels×bitsPerChannel/8",

    errorBleed: "The bleed may not be negative.",
    errorScaleDenominator: "The scale denominator must be 1 or greater.",
    errorChannels: "The number of channels is a whole number from 1 to 8.",
    errorBitsPerChannel: "Bits per channel is 1, 8, 16 or 32.",
    errorPhysicalUnit: "Invalid unit of the physical size.",
    errorWidthPx: "The width in pixels is a whole number of 1 or more.",
    errorHeightPx: "The height in pixels is a whole number of 1 or more.",
    errorResolution: "The resolution must be greater than zero.",
    errorPhysicalWidth: "The physical width must be greater than zero.",
    errorPhysicalHeight: "The physical height must be greater than zero.",
    errorDirection: "Invalid direction.",
  },

  "roll-yield": {
    rollWidth: "Roll width",
    pieceWidth: "Piece width",
    pieceHeight: "Piece height",
    sideMargin: "Side margin (per edge of the roll)",
    gutter: "Spacing between pieces",
    leadTrailMargin: "Margin at the start and end of the job",
    quantity: "Print run",
    allowRotation: "Allow turning by 90°",
    yes: "Yes",
    no: "No",
    rollLength: "Length of one roll",
    rollLengthHint:
      "Optional — for the number of rolls needed. The number is built from whole rows per roll, never from a plain division of length.",
    pricePerMetre: "Price per running metre",

    results: "Result",
    usableWidth: "Usable width",
    upright: "Portrait",
    across: "Pieces across",
    leftoverWidth: "Unused width",
    rows: "Lines",
    lengthM: "Length used (m)",
    produced: "Actually produced",
    rolls: "Rolls needed",
    cost: "Material cost",
    rotated: "Turned",
    shorter: "Shorter arrangement",
    equal: "Equal",

    inputs: "Entered",
    formula:
      "across = floor((usable+gutter)/(piece+gutter))   rows = ceil(run/across)   length = rows×(height+gutter) − gutter + 2×startEndMargin   rowsPerRoll = floor((rollLength+gutter)/(height+gutter))   rolls = ceil(rows/rowsPerRoll)",

    errorRollWidth: "The roll width must be greater than zero.",
    errorPieceWidth: "The piece width must be greater than zero.",
    errorPieceHeight: "The piece height must be greater than zero.",
    errorSideMargin: "The side margin may not be negative.",
    errorGutter: "The gutter may not be negative.",
    errorLeadTrailMargin: "The start and end margin may not be negative.",
    errorQuantity: "The print run is a whole number of 1 or more.",
    errorRollLength: "The roll length must be greater than zero.",
    errorPricePerMetre: "The price per metre may not be negative.",
  },

  "saddle-stitch-imposition": {
    pageCount: "Number of pages",
    signatureSize: "Pages per signature",
    signatureSizeHint: "4 means a saddle-stitched booklet with no sections — every sheet is part of the same booklet.",
    startPage: "Number of the first page in the job",
    startPageHint: "Shifts every printed page number; the pairs stay the same.",

    results: "Result",
    paddedPages: "Pages after padding (a multiple of the signature)",
    blanks: "Blank pages",
    firstBlankPage: "First blank page",
    sheets: "Sheets",
    signatures: "Signatures",
    sheet: "Sheet",
    signature: "Signature",
    colSheet: "Sheet",
    colSignature: "Signature",
    colFrontLeft: "Front — left",
    colFrontRight: "Front — right",
    colBackLeft: "Back — left",
    colBackRight: "Back — right",

    inputs: "Entered",
    formula:
      "P4 = ceil(pages/4)×4   PS = ceil(P4/signature)×signature   blanks = PS−pages   sheet k: front = (PS−2k+2 | 2k−1), back = (2k | PS−2k+1), shifted by (firstPage−1)",

    errorPageCount: "The number of pages is a whole number from 1 to 4000.",
    errorSignatureSize: "Pages per signature is 4, 8, 16 or 32.",
    errorStartPage: "The number of the first page is a whole number from 1 to a million.",
  },

  "sheet-imposition": {
    sheetWidth: "Sheet width",
    sheetHeight: "Sheet height",
    pieceWidth: "Piece width",
    pieceHeight: "Piece height",
    marginTop: "Top margin",
    marginHint: "Gripper edge and similar margins — applied before the imposition.",
    marginBottom: "Bottom margin",
    marginLeft: "Left margin",
    marginRight: "Right margin",
    gutter: "Spacing between pieces",
    gutterHint: "Bleed plus cut width.",
    allowRotation: "Allow turning by 90°",
    yes: "Yes",
    no: "No",
    requiredQuantity: "Required print run",

    results: "Result",
    usableWidth: "Usable width",
    usableHeight: "Usable height",
    upright: "Portrait",
    across: "Pieces across",
    down: "Pieces vertically",
    count: "Pieces per sheet",
    leftoverWidth: "Unused width",
    leftoverHeight: "Unused height",
    rotated: "Turned",
    bestOrientation: "Better arrangement",
    either: "Either (equal)",
    best: "Pieces per sheet (better arrangement)",
    usedPercent: "Used (% of the whole sheet)",
    wastePercent: "Waste (% of the whole sheet)",
    usedPercentOfUsable: "Used (% of the usable area)",
    wastePercentOfUsable: "Waste (% of the usable area)",
    sheets: "Sheets needed",

    inputs: "Entered",
    formula:
      "usableWidth = sheet − left − right   usableHeight = sheet − top − bottom   across = floor((usableWidth+gutter)/(width+gutter))   down = floor((usableHeight+gutter)/(height+gutter))   waste% = (1 − pieces×pieceArea/sheetArea)×100",

    errorSheetWidth: "The sheet width must be greater than zero.",
    errorSheetHeight: "The sheet height must be greater than zero.",
    errorPieceWidth: "The piece width must be greater than zero.",
    errorPieceHeight: "The piece height must be greater than zero.",
    errorMarginTop: "The top margin may not be negative.",
    errorMarginBottom: "The bottom margin may not be negative.",
    errorMarginLeft: "The left margin may not be negative.",
    errorMarginRight: "The right margin may not be negative.",
    errorGutter: "The gutter may not be negative.",
    errorRequiredQuantity: "The required print run is a whole number of 1 or more.",
  },
} as const;
