/**
 * „Obrada metala" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. Three of the pack's six tools carry `zanat`'s copy (`tap-drill-size`,
 * `sheet-metal-bend`, `weld-consumable`), because a pack is a lens over the
 * drawer and not a second copy of it.
 *
 * **`metal-weight` is `life-safety`.** The mass it prints is what somebody lifts
 * and rigs, so its copy states what the number IS and never that the lift is
 * safe; the density is an input, with steel's conventional value named in the
 * hint and cited on the source line.
 */
export const PRO_METAL_SR = {
  "cutting-speed": {
    diameter: "Prečnik alata ili obratka",
    diameterHint: "U milimetrima.",
    mode: "Šta je zadato",
    modeFromSpeed: "brzina rezanja",
    modeFromRpm: "broj obrtaja",
    cuttingSpeed: "Brzina rezanja v_c",
    cuttingSpeedHint: "Iz kataloga alata i materijala, u m/min.",
    spindleSpeed: "Broj obrtaja n",
    spindleSpeedHint: "U obrtajima u minutu.",
    results: "Rezultat",
    resultSpeed: "Brzina rezanja v_c",
    resultRpm: "Broj obrtaja n",
    formula: "v_c = π·D·n / 1000     n = 1000·v_c / (π·D)",
    inputs: "Uneseno",
    errorDiameter: "Prečnik je broj od 0 do 10 000 mm i veći od nule.",
    errorMode: "Izaberi šta je zadato.",
    errorKnown: "Zadaj tačno jedno — brzinu rezanja ili broj obrtaja.",
    errorSpeed: "Brzina rezanja je broj veći od nule.",
    errorRpm: "Broj obrtaja je broj veći od nule.",
    unitMm: "mm",
    unitMPerMin: "m/min",
    unitRpm: "o/min",
  },

  "feed-per-tooth": {
    teeth: "Broj zuba",
    teethHint: "Broj reznih ivica glodala.",
    spindleSpeed: "Broj obrtaja n",
    spindleSpeedHint: "U obrtajima u minutu.",
    mode: "Šta je zadato",
    modeFromPerTooth: "pomak po zubu",
    modeFromFeedRate: "pomak tabele",
    feedPerTooth: "Pomak po zubu f_z",
    feedPerToothHint: "U milimetrima.",
    feedRate: "Pomak tabele v_f",
    feedRateHint: "U milimetrima u minutu.",
    results: "Rezultat",
    resultPerTooth: "Pomak po zubu f_z",
    resultPerRev: "Pomak po obrtaju f",
    resultRate: "Pomak tabele v_f",
    formula: "v_f = f_z · z · n     f_z = v_f / (z · n)",
    inputs: "Uneseno",
    errorTeeth: "Broj zuba je ceo broj od 1 do 1000.",
    errorSpindle: "Broj obrtaja je broj veći od nule.",
    errorMode: "Izaberi šta je zadato.",
    errorKnown: "Zadaj tačno jedno — pomak po zubu ili pomak tabele.",
    errorPerTooth: "Pomak po zubu je broj veći od nule.",
    errorRate: "Pomak tabele je broj veći od nule.",
    unitMm: "mm",
    unitMmPerTooth: "mm/zub",
    unitMmPerRev: "mm/o",
    unitMmPerMin: "mm/min",
    unitRpm: "o/min",
  },

  "metal-weight": {
    shape: "Presek",
    shapeHint: "Oblik poprečnog preseka materijala.",
    shapeRound: "okrugla šipka",
    shapeSquare: "kvadratna šipka",
    shapeHex: "šestougaona šipka",
    shapeRoundTube: "okrugla cev",
    shapeBoxTube: "kvadratna cev",
    shapeRect: "ploča ili flah",
    size: "Mera",
    sizeHint:
      "Prečnik, stranica ili širina, u milimetrima. Za šestougaonu šipku meri se preko " +
      "ključa (preko ravni).",
    secondSize: "Druga mera",
    secondSizeHint: "Visina preseka, u milimetrima — samo za ploču i flah.",
    wall: "Debljina zida",
    wallHint: "U milimetrima — samo za cevi.",
    length: "Dužina komada",
    lengthHint: "U metrima.",
    pieces: "Broj komada",
    density: "Gustina materijala",
    densityHint:
      "U kg/m³, iz sertifikata materijala. Konvencionalna vrednost za čelik je 7 850.",
    results: "Rezultat",
    section: "Površina preseka",
    volume: "Zapremina po komadu",
    massPerMetre: "Masa po metru",
    massPerPiece: "Masa po komadu",
    totalMass: "Ukupna masa",
    formula:
      "m = ρ·A·L     A: krug π·D²/4, kvadrat a², šestougao (√3/2)·s², cev π/4·(D² − (D − 2t)²)",
    inputs: "Uneseno",
    errorShape: "Izaberi oblik preseka.",
    errorSize: "Mera je broj veći od nule.",
    errorSecondSize: "Druga mera je broj veći od nule.",
    errorWall: "Debljina zida mora biti veća od nule i manja od polovine mere.",
    errorLength: "Dužina je broj veći od nule.",
    errorPieces: "Broj komada je ceo broj veći od nule.",
    errorDensity: "Gustina je broj veći od nule.",
    errorKnown: "Za ovaj presek neke mere se ne koriste — ostavi ih prazne.",
    unitMm: "mm",
    unitMm2: "mm²",
    unitM: "m",
    unitM3: "m³",
    unitKg: "kg",
    unitKgPerM: "kg/m",
  },

  "weld-throat-leg": {
    measure: "Šta je zadato",
    measureLeg: "krak z",
    measureThroat: "grlo a",
    leg: "Krak z₁",
    legHint: "Kraka jednakog šava, u milimetrima.",
    leg2: "Krak z₂",
    leg2Hint: "Drugi krak, u milimetrima — ostavi prazno za jednakokraki šav.",
    throat: "Grlo a",
    throatHint: "Potrebno grlo, u milimetrima — dobija se jednakokraki šav.",
    density: "Gustina metala šava",
    densityHint: "U kg/m³. Podrazumevano 7 850 za čelik.",
    results: "Rezultat",
    resultLeg: "Krak z₁",
    resultLeg2: "Krak z₂",
    resultThroat: "Grlo a",
    resultArea: "Presek šava po milimetru dužine",
    resultMass: "Masa šava po metru",
    formula: "a = z₁·z₂ / √(z₁² + z₂²)     A = z₁·z₂ / 2",
    inputs: "Uneseno",
    errorMeasure: "Izaberi da li zadaješ krak ili grlo.",
    errorLeg: "Krak je broj od 0,5 do 100 mm.",
    errorLeg2: "Drugi krak je broj od 0,5 do 100 mm.",
    errorThroat: "Grlo je broj od 0,3 do 100 mm.",
    errorDensity: "Gustina je broj veći od nule.",
    errorKnown: "Zadaj ili krak ili grlo — ne oba.",
    unitMm: "mm",
    unitMm2: "mm²",
    unitKgPerM: "kg/m",
  },
} as const;
