/**
 * „Agro" — the English copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. The tool's NAME and its one-line blurb are not here: those
 * live in `./pro.en.ts`'s `name`/`blurb` tables, because the drawer's rail needs
 * them before any surface is opened.
 *
 * **A unit is copy, not a constant** — written here rather than concatenated
 * in a component, so a translator can find it and `check:strings` can see it.
 *
 * **Nothing in here judges.** `fertiliser-nutrient-blend`, `sprayer-calibration`
 * and `tank-mix-dose` are `life-safety`: their copy may name a quantity and
 * the user's own limit, and never says what the two mean together.
 */
export const PRO_AGRO_EN = {
  "bale-count-storage": {
    shape: "Bale shape",
    shapeRound: "Round (cylinder)",
    shapeSquare: "Square (cuboid)",
    diameterM: "Roll diameter",
    diameterMHint: "In metres, 0.5 to 2.5 m.",
    roundWidthM: "Roll width",
    roundOrientation: "Orientation when stacking",
    orientationOnEnd: "On end (standing)",
    orientationOnSide: "On the side (lying)",
    orientationFootprint: "Footprint d × w",
    orientationOnLengthFace: "On the long side",
    orientationOnWidthFace: "On the short side",
    lengthM: "Bale length",
    squareWidthM: "Bale width",
    heightM: "Bale height",
    massMode: "Method of setting the mass",
    massModeMeasured: "Measured bale mass",
    massModeDensity: "Bale density",
    measuredMassKg: "Mass of one bale",
    densityKgM3: "Bale density",
    densityKgM3Hint:
      "Measured for a specific material and baler, 30 to 400 kg/m³. Nexus does not assume it.",
    quantityMode: "Method of setting the yield",
    quantityModeYield: "Yield per hectare",
    quantityModeTotal: "Total mass",
    yieldTHa: "Yield",
    totalMassT: "Total mass",
    areaHa: "Area",
    areaHaHint:
      "Required for yield per hectare; optional for total mass, for the bales per hectare.",
    balingLossPercent: "Baling loss",
    storage: "Store (optional)",
    storageLengthM: "Store length",
    storageWidthM: "Store width",
    storageHeightM: "Usable stacking height",
    storageHeightMHint:
      "Your input — Nexus does not determine it and does not check the load capacity or stacking stability.",

    results: "Result",
    baleVolume: "Volume of one bale",
    baleMass: "Mass of one bale",
    totalMassAfterLoss: "Total mass after loss",
    countExact: "Number of bales (exact)",
    countCeil: "Number of bales (rounded up)",
    totalVolume: "Total bale volume",
    balesPerHa: "Bales per hectare",
    storageResults: "Stacking in the store",
    storageOrientation: "Orientation in the store",
    storagePerRow: "Bales per row",
    storagePerColumn: "Bales per column",
    storagePerLayer: "Bales per layer",
    storageLayers: "Number of coats",
    storageCapacity: "Capacity",
    storageCapacityTonnes: "Capacity",
    unusedLength: "Unused length",
    unusedWidth: "Unused width",
    shortfall: "Needed versus capacity (difference)",
    stackingNote:
      "Geometric stacking by the entered dimensions only. Stacking stability, floor load and allowable height are not part of this calculation. Hexagonal (pyramidal) stacking of round bales is not calculated.",

    inputs: "Entered",
    formula:
      "V = π·(D/2)²·W (round) or l·w·h (square)     n = M / m_b     capacity = per_layer × layers",

    errorShape: "Enter the dimensions for the chosen bale shape.",
    errorDiameterM: "The roll diameter must be between 0.5 and 2.5 m.",
    errorWidthM: "The width must be within the allowed range for the chosen bale shape.",
    errorLengthM: "The bale length must be between 0.3 and 3 m.",
    errorHeightM: "The bale height must be between 0.3 and 3 m.",
    errorMeasuredMassKg: "The measured bale mass must be greater than zero.",
    errorDensityKgM3: "The bale density must be between 30 and 400 kg/m³.",
    errorBaleMassKg: "The bale mass comes out zero or less — check the entered mass or density.",
    errorBalingLossPercent: "Baling loss is between 0 and 30%.",
    errorAreaHa: "The area must be greater than zero.",
    errorYieldTHa: "The yield must be greater than zero.",
    errorTotalMassT: "The total mass must be greater than zero.",
    errorStorageLengthM: "The store length must be greater than zero.",
    errorStorageWidthM: "The store width must be greater than zero.",
    errorUsableHeightM: "The usable stacking height must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitM: "m",
    unitM3: "m³",
    unitKg: "kg",
    unitT: "t",
    unitHa: "ha",
    unitPercent: "%",
  },

  "bee-syrup-mix": {
    preset: "Sugar:water ratio",
    presetCustom: "Arbitrary",
    ratioA: "Sugar (ratio part)",
    ratioHint: "By mass — 1 l of water is 1 kg, so the mass and volume bases coincide.",
    ratioB: "Water (ratio part)",
    given: "What is set",
    givenTargetVolume: "Target syrup volume",
    givenTargetMass: "Target syrup mass",
    givenAvailableSugar: "Available sugar mass",
    value: "Given value",
    valueHint: "Litres for the target volume, kilograms for the target mass or the available sugar.",
    hiveCount: "Number of hives",
    literPerHive: "Quantity per hive",
    bagMassKg: "Mass of a sugar bag",

    results: "Result",
    sugarKg: "Mass of sugar",
    waterVolumeL: "Water volume",
    waterMassKg: "Mass of water",
    syrupMassKg: "Syrup mass",
    syrupVolumeL: "Syrup volume",
    densityKgL: "Syrup density",
    densityEstimated: "calculated",
    densityNote:
      "Calculated from the apparent volume of dissolved sucrose (0.63 l/kg), not measured. The values hold at about 20 °C.",
    concentrationPercent: "Concentration (mass %)",
    bagsExact: "Number of bags (exact)",
    bagsCeil: "Number of bags (rounded up)",
    hivesCovered: "Hives covered",
    hivesRemainderL: "Leftover syrup",
    apiary: "For the whole apiary",
    apiaryVolumeL: "Total volume",
    apiarySugarKg: "Total sugar",
    apiaryBagsCeil: "Number of bags",

    inputs: "Entered",
    ratio: "Ratio",
    formula: "V_w = V/(1 + 0.63r)     S = r·V_w     V = V_w + 0.63·S     ρ = M/V",

    errorRatioA: "The sugar ratio part must be greater than zero.",
    errorRatioB: "The water ratio part must be greater than zero.",
    errorValue: "The given value must be greater than zero.",
    errorBagMassKg: "The sugar bag mass must be greater than zero.",
    errorHiveCount: "The number of hives must be greater than zero.",
    errorLiterPerHive: "The quantity per hive must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitKg: "kg",
    unitL: "l",
    unitKgL: "kg/l",
    unitPercent: "%",
  },

  "cadastral-area-units": {
    value: "Value",
    fromUnit: "Source unit",
    jutroM2Override: "Value of a cadastral acre in m² (optional)",
    jutroM2OverrideHint:
      "Older land-register entries in Serbia sometimes carry a local acre of a different size. An empty field uses the published 5754.6425 m².",

    results: "Result",
    resultM2: "Square metres",
    resultAr: "Ares",
    resultHa: "Hectares",
    resultHvat2: "Square fathoms",
    resultJutro: "Cadastral acres",
    jutroUsed: "Acre value used",
    sourceNote:
      "Austro-Hungarian metrication (Austria: act of 1871, in force from 1876): 1 Viennese fathom = 1.896484 m, 1 cadastral acre = 1600 square fathoms = 5754.6425 m².",

    inputs: "Entered",
    formula:
      "everything via m²: m² = value × factor(unit); result = m² ÷ factor(target unit)",

    errorValue: "The value must be zero or greater, and not greater than 1×10¹² m².",
    errorJutroM2Override: "The value of a cadastral acre in m² must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitM2: "m²",
    unitAr: "ar",
    unitHa: "ha",
    unitHvat2: "square fathom",
    unitJutro: "cadastral acre",
  },

  "fertiliser-nutrient-blend": {
    direction: "Direction of calculation",
    directionForward: "From nutrients to fertiliser",
    directionReverse: "From fertiliser to nutrients",
    targetForm: "P and K targets given as",
    targetFormOxide: "Oxide (P₂O₅, K₂O)",
    targetFormElement: "Element (P, K)",
    targetN: "Target nitrogen (N)",
    targetHint:
      "From a recommendation based on a soil analysis or a prescribed input limit. Your input.",
    targetP2o5: "Target P₂O₅",
    targetK2o: "Target K₂O",
    targetPElement: "Target P",
    targetKElement: "Target K",
    primary: "Base fertiliser",
    secondary: "Supplementary fertiliser (optional)",
    composition: "Fertiliser composition",
    compositionN: "N (%)",
    compositionP2o5: "P₂O₅ (%)",
    compositionK2o: "K₂O (%)",
    lead: "Lead nutrient",
    leadN: "N",
    leadP2o5: "P₂O₅",
    leadK2o: "K₂O",
    leadNone: "No supplementary fertiliser",
    doseKgHa: "Fertiliser dose",
    areaHa: "Area",
    bagMassKg: "Bag mass",

    results: "Result",
    line: "Fertiliser",
    totalKg: "Total for the area",
    bagsExact: "Number of bags (exact)",
    bagsCeil: "Number of bags (rounded up)",
    actualDoseKgHa: "Actual dose (after rounding to bags)",
    delivered: "What the entered fertiliser supplies per hectare",
    deliveredN: "N",
    deliveredP2o5: "P₂O₅",
    deliveredK2o: "K₂O",
    deliveredPElement: "P (element)",
    deliveredKElement: "K (element)",
    totalDeliveredN: "Total N for the area",
    totalDeliveredP2o5: "Total P₂O₅ for the area",
    totalDeliveredK2o: "Total K₂O for the area",
    balance: "Target versus supplied",
    targetMinusDeliveredN: "Target − supplied (N)",
    targetMinusDeliveredP2o5: "Target − supplied (P₂O₅)",
    targetMinusDeliveredK2o: "Target − supplied (K₂O)",
    userInputNote:
      "The target quantities and the fertiliser composition are your input from the label and the recommendation. Nexus does not know, remember or suggest them.",

    inputs: "Entered",
    formula:
      "X = 100·target / lead_percentage     supplied_j = X·percentage_j/100     target − supplied",

    errorAreaHa: "The area must be greater than zero.",
    errorBagMassKg: "The bag mass must be greater than zero.",
    errorComposition: "The fertiliser composition must be in the range 0–100% per nutrient, with a sum up to 100%.",
    errorDoseKgHa: "The fertiliser dose must be greater than zero.",
    errorTargetN: "The target nitrogen is between 0 and 500 kg/ha.",
    errorTargetP: "The target phosphorus is between 0 and 500 kg/ha.",
    errorTargetK: "The target potassium is between 0 and 500 kg/ha.",
    errorPrimary:
      "The base fertiliser composition must be in the range 0–100% per nutrient, with a sum up to 100%.",
    errorSecondary:
      "The supplementary fertiliser composition must be in the range 0–100% per nutrient, with a sum up to 100%.",
    errorPrimaryLead: "The chosen lead nutrient of the base fertiliser must have a percentage greater than zero.",
    errorGeneric: "Check the entered values.",

    unitKg: "kg",
    unitKgHa: "kg/ha",
    unitHa: "ha",
  },

  "grain-moisture-shrink": {
    grossMassKg: "Gross mass",
    measuredMoisturePercent: "Measured moisture",
    targetMoisturePercent: "Target (contract) moisture",
    targetMoisturePercentHint: "From the purchase contract. Nexus does not know or suggest it.",
    impuritiesPercent: "Impurities",
    impuritiesFreeLimitPercent: "Impurities without deduction",
    impuritiesFreeLimitPercentHint:
      "From the purchase contract or the buyer's rulebook. Nexus does not know or suggest it.",
    order: "Order of deductions",
    orderImpuritiesFirst: "Impurities first, then moisture",
    orderMoistureFirst: "Moisture first, then impurities",
    deductionMode: "Impurity deduction",
    deductionModeExcessOnly: "Only above the allowed level (one-way)",
    deductionModeTwoSided: "Below the allowed level too, as a gain (two-way)",
    pricePerKg: "Price per kilogram",
    dryerEfficiencyPercent: "Useful heat of the dryer",

    results: "Result",
    driedMassKg: "Mass after drying (moisture only)",
    waterOutKg: "Water removed",
    shrinkPercent: "Loss (of the gross mass)",
    shrinkPercentMassIndependent: "Loss (check, independent of mass)",
    physicalModelNote:
      "A physical model of water-only loss: no dry-matter loss and no handling or dust loss in the dryer. The difference against the weighbridge may come from there. The upper mass and water are baseline values for moisture-only loss, without impurities — the water actually removed in drying is in the branches below, by the chosen order.",
    impuritiesFirst: "Impurities first, then moisture",
    moistureFirst: "Moisture first, then impurities",
    impurityDeductionKg: "Impurity deduction",
    finalMassKg: "Final mass",
    selected: "Chosen order",
    value: "Value",
    grossValue: "Value of the gross mass",
    netValue: "Value of the final mass",
    valueDifference: "Difference",
    energy: "Drying energy",
    minimumEnergyMJ: "Theoretical minimum",
    minimumEnergyKWh: "Theoretical minimum",
    actualEnergyMJ: "At the entered useful heat",
    actualEnergyKWh: "At the entered useful heat",

    inputs: "Entered",
    formula:
      "m₂ = m₁·(100−w₁)/(100−w₂)     loss % = (w₁−w₂)/(100−w₂)×100     deduction = m·(p−p₀)/100",

    errorGrossMassKg: "The gross mass must be greater than zero.",
    errorMeasuredMoisturePercent: "The measured moisture is between 0 and 60%.",
    errorTargetMoisturePercent: "The target moisture is between 0 and 60% and must be less than 100.",
    errorImpuritiesPercent: "Impurities are between 0 and 50%.",
    errorImpuritiesFreeLimitPercent: "The allowed impurity percentage is between 0 and 50%.",
    errorPricePerKg: "The price per kilogram may not be negative.",
    errorDryerEfficiencyPercent: "The dryer's useful heat is between 1 and 100%.",
    errorGeneric: "Check the entered values.",

    unitKg: "kg",
    unitPercent: "%",
    unitRsd: "RSD",
    unitMj: "MJ",
    unitKwh: "kWh",
  },

  "growing-degree-days": {
    rowsText: "Daily temperatures",
    rowsTextHint:
      "Paste one row per day: date;maximum °C;minimum °C. The separator is a tab, semicolon or comma, the date in the form DD.MM.YYYY.",
    baseTempC: "Base temperature",
    baseTempCHint:
      "Your choice by crop. Nexus does not choose a crop and does not claim 10 °C is right for any.",
    upperLimitC: "Upper limit (modified method)",
    targetSum: "Target sum",
    averageWindowDays: "Averaging period for the projection",

    results: "Result",
    colDate: "Date",
    colSimpleDaily: "Simple (day)",
    colSimpleCumulative: "Simple (cumulative)",
    colModifiedDaily: "Modified (day)",
    colModifiedCumulative: "Modified (cumulative)",
    totalSimple: "Total, simple method",
    totalModified: "Total, modified method",
    averageSimple: "Mean for the whole period",
    averageSimpleRecent: "Mean for the last",
    days: "days",
    zeroContributionDays: "Days with zero contribution",
    projection: "Projection to the target",
    remainingToTarget: "Remaining to the target",
    daysToTarget: "Days at the mean temperature",
    projectedDate: "Projected date",
    projectionNote: "A linear extrapolation of the entered temperatures, not a forecast.",

    inputs: "Entered",
    rowCount: "Number of days in the series",
    formula:
      "simple: max(0, (Tmax+Tmin)/2 − base)     modified: clamp Tmin from below and Tmax from above before averaging",

    errorParse: "A pasted row must be date;maximum;minimum, the date in the form DD.MM.YYYY.",
    errorReadings: "The series must have from 1 to 400 days.",
    errorBaseTempC: "The base temperature is between −10 and 30 °C.",
    errorUpperLimitC: "The upper limit is between 10 and 45 °C and may not be below the base temperature.",
    errorTargetSum: "The target sum must be greater than zero.",
    errorAverageWindowDays: "The averaging period is a whole number from 1 to 60 days.",
    errorTMaxC: "The maximum temperature is between −40 and 55 °C in every row.",
    errorTMinC: "The minimum temperature is between −40 and 55 °C in every row.",
    errorRowOrder: "The minimum temperature may not be greater than the maximum in the same row.",
    errorDateOrder: "The dates must be increasing, without repetition.",
    errorGeneric: "Check the entered values.",

    unitDeg: "°C",
  },

  "honey-mass-moisture": {
    quantityMode: "Method of setting the quantity",
    quantityModeGrossTare: "Measured gross mass with the tare",
    quantityModeVolume: "Container volume",
    grossMassKg: "Gross mass",
    tareKg: "Tare (mass of the empty container)",
    containerVolumeL: "Container volume",
    densityKgL: "Honey density",
    densityKgLHint:
      "Measured, 1.35 to 1.50 kg/l — by weighing a known volume or from a table you have. It is not derived from the moisture.",
    sampleMassKg: "Density measurement: sample mass (optional)",
    sampleHint: "For an independent check of the density — sample mass and volume together.",
    sampleVolumeL: "Density measurement: sample volume",
    moisturePercent: "Moisture (refractometer)",
    targetMoisturePercent: "Target moisture after drying",
    jarVolumeMl: "Jar volume",
    jarDeclaredNetMassG: "Declared net mass of the jar",
    jarToleranceG: "Allowed deviation per jar",
    jarToleranceGHint: "From a regulation or an agreement with the buyer. Nexus does not know or suggest it.",
    pricePerKg: "Price per kilogram",

    results: "Result",
    netMassKg: "Net mass of honey",
    volumeFromMassL: "Volume from mass",
    measuredDensityKgL: "Density from the sample",
    independenceNote: "Density and moisture are entered independently — neither is derived from the other.",
    waterMassKg: "Mass of water",
    dryMatterMassKg: "Dry-matter mass",
    drying: "Drying to the target moisture",
    driedMassKg: "Mass after drying",
    waterRemovedKg: "Water removed",
    shrinkPercent: "Loss",
    jars: "Jars",
    massPerJarKg: "Honey mass per jar",
    massPerJarG: "Honey mass per jar",
    fullJars: "Full jars",
    jarRemainderKg: "Remainder",
    jarsFromDeclaredMass: "Number of jars from the declared net mass",
    fillMassVsDeclaredG: "Fill mass − declared mass",
    value: "Value",
    grossValue: "Value of the net mass",
    driedValue: "Value after drying",

    inputs: "Entered",
    formula: "m = gross − tare (or V·ρ)     water = m·w/100     m₂ = m·(100−w₁)/(100−w₂)",

    errorGrossMassKg: "The gross mass must be greater than zero.",
    errorTareKg: "The tare may not be negative.",
    errorNetMassKg: "The net mass (gross − tare) must be greater than zero.",
    errorContainerVolumeL: "The container volume must be greater than zero.",
    errorDensityKgL: "The honey density must be between 1.35 and 1.50 kg/l.",
    errorSampleMassKg: "The sample mass for the density measurement must be greater than zero.",
    errorSampleVolumeL: "The sample volume for the density measurement must be greater than zero.",
    errorSampleDensity: "The density from the sample is outside the range 1.35 to 1.50 kg/l.",
    errorMoisturePercent: "The moisture must be between 12 and 25%.",
    errorTargetMoisturePercent: "The target moisture must be between 12 and 25%.",
    errorJarVolumeMl: "The jar volume must be greater than zero.",
    errorJarDeclaredNetMassG: "The declared net mass of the jar must be greater than zero.",
    errorJarToleranceG: "The allowed deviation per jar may not be negative.",
    errorPricePerKg: "The price per kilogram may not be negative.",
    errorGeneric: "Check the entered values.",

    unitKg: "kg",
    unitG: "g",
    unitL: "l",
    unitKgL: "kg/l",
    unitPercent: "%",
    unitRsd: "RSD",
  },

  "irrigation-depth-volume": {
    normMm: "Irrigation rate",
    normMmHint: "Your input, 0.5 to 200 mm. Nexus does not suggest it.",
    areaHa: "Area",
    efficiencyPercent: "System efficiency",
    efficiencyPercentHint: "A property of the specific system, 30 to 100%. Nexus does not assume it.",
    flowUnit: "Unit of the available flow",
    flowUnitM3h: "m³/h",
    flowUnitLs: "l/s",
    flowValue: "Available flow",
    method: "Irrigation method",
    methodSprinkler: "Sprinklers",
    methodDrip: "Drip",
    spacingInRowM: "Sprinkler spacing along the row",
    spacingBetweenRowsM: "Spacing between sprinkler rows",
    nozzleFlowUnit: "Unit of the sprinkler flow",
    nozzleFlowValue: "Flow of one sprinkler",
    dripsPerPlant: "Number of drippers per plant",
    dripFlowLh: "Dripper flow",
    areaPerPlantM2: "Area belonging to one plant",
    hoursPerDay: "Number of working hours per day",

    results: "Result",
    netVolumeM3: "Net volume",
    netVolumeL: "Net volume",
    grossVolumeM3: "Gross volume",
    flowM3h: "Data rate",
    timeHours: "System runtime",
    daysNeeded: "Number of days",
    sprinklerResults: "Sprinklers",
    intensityMmH: "Rainfall intensity",
    netTimePerPositionH: "Time per position (net rate)",
    grossTimePerPositionH: "Time per position (gross rate)",
    positions: "Number of positions",
    positionsPerDay: "Positions per day",
    dripResults: "Drip",
    netLitersPerPlant: "Litres per plant (net rate)",
    netDripDurationH: "Cycle duration (net rate)",
    grossLitersPerPlant: "Litres per plant (gross rate)",
    grossDripDurationH: "Cycle duration (gross rate)",

    inputs: "Entered",
    formula: "V_n = N·10·A     V_b = V_n/(η/100)     t = V_b/Q     I = q/(S_r·S_l)",

    errorNormMm: "The irrigation rate is between 0.5 and 200 mm.",
    errorAreaHa: "The area must be greater than zero.",
    errorEfficiencyPercent: "The system efficiency is between 30 and 100%.",
    errorFlowValue: "The available flow must be greater than zero.",
    errorHoursPerDay: "The number of working hours per day is between 0.5 and 24.",
    errorSpacingInRowM: "The sprinkler spacing along the row must be greater than zero.",
    errorSpacingBetweenRowsM: "The spacing between sprinkler rows must be greater than zero.",
    errorNozzleFlowLh: "The flow of one sprinkler must be greater than zero.",
    errorDripsPerPlant: "The number of drippers per plant must be greater than zero.",
    errorDripFlowLh: "The dripper flow must be greater than zero.",
    errorAreaPerPlantM2: "The area per plant must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitM3: "m³",
    unitL: "l",
    unitM3h: "m³/h",
    unitLh: "l/h",
    unitMm: "mm",
    unitMmH: "mm/h",
    unitHa: "ha",
    unitH: "h",
    unitMin: "min",
    unitPercent: "%",
  },

  "livestock-ration-dm": {
    headCount: "Number of head",
    avgBodyMassKg: "Average body mass",
    intakeMode: "Dry-matter intake",
    intakeModePercent: "% of body mass",
    intakeModeKg: "kg DM per head per day",
    intakeValue: "Intake value",
    intakeValueHint: "Your choice — Nexus does not suggest it.",
    feedsText: "Feeds",
    feedsTextHint:
      "Paste one row per feed: name;DM content %;share of the ration by DM %;price per kg fresh mass (optional);package mass in kg (optional).",
    feedsTextPlaceholder: "maize silage;33;50;;250\nhay;86;20;;250\nmix;88;30;40;25",
    days: "Number of days",
    wastePercent: "Loss (spillage) at the trough",

    results: "Result",
    dmPerHeadKgDay: "Dry matter per head",
    dmHerdKgDay: "Dry matter for the herd",
    shareSumPercent: "Sum of the entered shares",
    colFeed: "Feed",
    colDmKgDay: "DM (kg/day)",
    colFreshEaten: "Fresh, eaten (kg/day)",
    colFreshIssued: "Fresh, given out (kg/day)",
    colPeriodIssued: "Given out for the period",
    colPackages: "Packages",
    colCost: "Cost/day",
    freshIssuedKgPerDay: "given out/day",
    periodIssuedKg: "for the period",
    packagesCeil: "packages",
    totalFreshEatenKgDay: "Total fresh, eaten",
    totalFreshIssuedKgDay: "Total fresh, given out",
    totalFreshEatenPerHeadKgDay: "Fresh per head",
    rationDmPercentAsIssued: "DM content of the ration as given out",
    cost: "Cost",
    totalDailyCost: "Daily cost",
    totalPeriodCost: "Cost for the period",

    inputs: "Entered",
    formula:
      "DM_head = mass·intake/100     DM_i = DM_herd·share/100     fresh = 100·DM_i/DM_content     given = fresh/(1−spillage/100)",

    errorHeadCount: "The number of head is a whole number from 1 to 100000.",
    errorAvgBodyMassKg: "The average body mass must be greater than zero.",
    errorIntakeValue:
      "The dry-matter intake is 0.5 to 6% of body mass, or greater than zero in kg/head/day.",
    errorFeeds: "Enter from 1 to 20 feeds.",
    errorDays: "The number of days is a whole number from 1 to 730.",
    errorWastePercent: "The loss at the trough is between 0 and 30%.",
    errorDmPercent: "The dry-matter content of a feed is between 1 and 100%.",
    errorShareOfDmPercent: "A feed's share of the ration is between 0 and 100%.",
    errorPricePerKgFresh: "The price per kg fresh mass may not be negative.",
    errorPackageMassKg: "The package mass must be greater than zero.",
    errorFeedParse:
      "Every feed row is name;DM content %;share %;price (optional);package mass (optional).",
    errorGeneric: "Check the entered values.",

    unitKg: "kg",
    unitPercent: "%",
    unitRsd: "RSD",
  },

  "machine-field-capacity": {
    nominalWidthM: "Working width",
    overlapPercent: "Overlap",
    speedKmh: "Working speed",
    utilizationPercent: "Time utilisation",
    utilizationPercentHint:
      "The ratio of pure work to total time, a property of the specific job. Your input.",
    areaHa: "Area",
    fuelLPerHour: "Fuel consumption",
    fuelPricePerL: "Fuel price",
    hoursPerDay: "Working hours per day",
    turnSeconds: "Time of one turn at the headland",
    fieldLengthM: "Field length in the direction of work",

    results: "Result",
    actualWidthM: "Actual working width",
    theoreticalCapacityHaH: "Theoretical output",
    effectiveCapacityHaH: "Actual output",
    timeHours: "Time for the whole area",
    daysNeeded: "Number of working days",
    capacityPerDayHa: "Output per day",
    lastDayHours: "Hours on the last day",
    fuel: "Fuel",
    fuelLPerHa: "Fuel per hectare",
    fuelTotalL: "Fuel total",
    fuelCostPerHa: "Fuel cost per hectare",
    fuelCostTotal: "Fuel cost total",
    turns: "Turns",
    turnCount: "Number of turns",
    turnTimeHours: "Turning time",
    turnTimeSharePercent: "Share of the working time",

    inputs: "Entered",
    formula:
      "W = W_n·(1−overlap/100)     C_t = W·v/10     C_e = C_t·η     t = A/C_e     passes−1 turns",

    errorNominalWidthM: "The working width is between 0.5 and 60 m.",
    errorOverlapPercent: "The overlap is between 0 and 30%.",
    errorSpeedKmh: "The working speed is between 0.5 and 30 km/h.",
    errorUtilizationPercent: "The time utilisation is between 30 and 100%.",
    errorAreaHa: "The area must be greater than zero.",
    errorHoursPerDay: "The working hours per day is between 0.5 and 24.",
    errorFuelLPerHour: "The fuel consumption must be greater than zero.",
    errorFuelPricePerL: "The fuel price may not be negative.",
    errorTurnSeconds: "The turning time is between 0 and 600 s.",
    errorFieldLengthM: "The field length must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitM: "m",
    unitHa: "ha",
    unitHaH: "ha/h",
    unitH: "h",
    unitMin: "min",
    unitL: "l",
    unitLHa: "l/ha",
    unitKmh: "km/h",
    unitRsd: "RSD",
    unitPercent: "%",
  },

  "orchard-trellis-layout": {
    lengthM: "Field length (row direction)",
    widthM: "Field width",
    rowSpacingM: "Row spacing",
    headlandM: "Headland at each end of the row",
    boundaryOffsetM: "Distance of the first row from the boundary",
    postSpacingM: "Post spacing along the row",
    postSpacingMHint: "Your choice — Nexus does not suggest it.",
    wireRows: "Number of wire rows",
    wireDiameterMm: "Wire diameter",
    wireSlackPercent: "Wire allowance for tying and tensioning",
    plantSpacingM: "Plant spacing along the row",
    anchorsPerEnd: "Anchors per end of the row",
    coilLengthM: "Length of a wire coil",
    coilLengthMHint: "For the number of coils and kilograms per coil — the wire is ordered in coils.",
    plantAtBothEnds: "Plants at the end of the row",
    plantAtBothEndsYes: "At both ends (floor + 1)",
    plantAtBothEndsNo: "Offset by half the spacing (floor)",
    wireMassPerKmOverride: "Declared wire mass per km (optional)",
    wireMassPerKmOverrideHint:
      "From the galvanised wire's label — when entered, it is used instead of the density of steel.",

    results: "Result",
    rowsCount: "Number of lines",
    zeroRowsNote:
      "The headland or the distance from the boundary is greater than the available length or width — there is no room for even one row.",
    rowLengthM: "Length of one row",
    totalRowLengthM: "Total row length",
    postsPerRow: "Posts per row",
    endPostsPerRow: "end",
    midPostsPerRow: "intermediate",
    actualPostSpacingM: "Actual post spacing",
    totalPosts: "Total posts",
    anchors: "Anchors",
    wireLengthM: "Wire length (with the allowance)",
    wireMassKg: "Wire mass",
    coilsCeil: "Number of coils",
    kgPerCoil: "Kilograms per coil",
    plantsPerRow: "Plants per row",
    totalPlants: "Total plants",
    plotAreaHa: "Plot area",
    usedAreaHa: "Used area (rows)",
    densityPerHa: "Actual density",
    theoreticalDensityPerHa: "Theoretical density",
    geometryNote:
      "Only rectangular layout by the entered dimensions. Hexagonal (pyramidal) layout is not calculated; the cross-section, depth and load capacity of the posts, wire and anchors are not part of this calculation.",

    inputs: "Entered",
    formula:
      "n_r = floor((W−2·e_b)/a)+1     posts/row = ceil(L_r/p)+1     wire = n_r·L_r·k·(1+allowance/100)",

    errorLengthM: "The field length must be greater than zero.",
    errorWidthM: "The field width must be greater than zero.",
    errorRowSpacingM: "The row spacing is between 0.5 and 20 m.",
    errorHeadlandM: "The headland is between 0 and 30 m.",
    errorBoundaryOffsetM: "The distance from the boundary is between 0 and 30 m.",
    errorPostSpacingM: "The post spacing along the row is between 2 and 15 m.",
    errorWireRows: "The number of wire rows is a whole number from 1 to 8.",
    errorWireDiameterMm: "The wire diameter is between 1.0 and 5.0 mm.",
    errorWireSlackPercent: "The wire allowance is between 0 and 30%.",
    errorPlantSpacingM: "The plant spacing along the row is between 0.3 and 10 m.",
    errorAnchorsPerEnd: "The anchors per end of the row is a whole number from 0 to 2.",
    errorCoilLengthM: "The length of a wire coil must be greater than zero.",
    errorWireMassPerKmOverride: "The declared wire mass per km must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitM: "m",
    unitKg: "kg",
    unitHa: "ha",
  },

  "plant-spacing-density": {
    pattern: "Layout",
    patternRectangular: "Rectangular (row × plant)",
    patternTriangular: "Triangular (staggered)",
    rowSpacingM: "Row spacing",
    spacingM: "Spacing within the row",
    spacingMHint: "For the triangular layout — the single distance between neighbouring plants.",
    lengthM: "Field length",
    widthM: "Field width",
    headlandM: "Headland at the end of the row",
    boundaryOffsetM: "Distance from the side boundary",
    desiredDensityPerHa: "Target stand",

    results: "Result",
    areaPerPlantM2: "Area per plant",
    theoreticalDensityPerHa: "Theoretical density",
    onParcel: "In the field",
    rowsCount: "Number of lines",
    rowLengthM: "Length of one row",
    plantsPerRow: "Plants per row",
    totalPlants: "Total plants",
    plotAreaHa: "Plot area",
    usedAreaHa: "Used area",
    actualDensityPerHa: "Actual density",
    triangularNote:
      "The number of seedlings in the field is shown only for the rectangular layout — in the triangular one every second row is offset by half the spacing, which this calculation does not model.",
    reverse: "Reverse calculation (from the target stand)",
    requiredInRowSpacingM: "Required spacing within the row (exact)",
    requiredSpacingRoundedM: "Rounded to the centimetre",
    densityAtRoundedSpacing: "Density at the rounded spacing",

    inputs: "Entered",
    formula: "S = a·b (rectangular) or (√3/2)·d² (triangular)     density = 10000/S",

    errorRowSpacingM: "The row spacing is between 0.05 and 50 m.",
    errorSpacingM: "The spacing within the row is between 0.05 and 50 m.",
    errorHeadlandM: "The headland is between 0 and 50 m.",
    errorBoundaryOffsetM: "The distance from the boundary is between 0 and 50 m.",
    errorDesiredDensityPerHa:
      "The target stand must be greater than zero and reachable at the entered row spacing.",
    errorLengthM: "The field length must be greater than zero.",
    errorWidthM: "The field width must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitM: "m",
    unitM2: "m²",
    unitHa: "ha",
  },

  "polygon-area": {
    verticesText: "Vertices",
    verticesTextHint:
      "Paste one vertex per line, two values separated by a space, tab or semicolon (a decimal comma is allowed inside a number). From 3 to 512 vertices.",
    columnOrder: "Column order",
    columnOrderYX: "Y, X (surveying)",
    columnOrderXY: "X, Y (mathematical)",
    unitDisplay: "Unit for displaying the area",
    unitDisplayAll: "All three",

    results: "Result",
    areaM2: "Area",
    areaAr: "Area",
    areaHa: "Area",
    perimeterM: "Scope",
    centroid: "Centroid",
    centroidUndefined: "The centroid does not exist — the vertices are collinear (the area is zero).",
    winding: "Direction of traversal",
    windingCcw: "Counter-clockwise",
    windingCw: "Clockwise",
    colX: "X",
    colY: "Y",

    inputs: "Entered",
    vertexCount: "Number of vertices",
    formula: "A = |Σ(xᵢ·yᵢ₊₁ − xᵢ₊₁·yᵢ)|/2     perimeter = Σ√((Δx)²+(Δy)²)",

    errorParse: "Every row is two values separated by a space, tab or semicolon.",
    errorVertices: "Enter from 3 to 512 vertices, all finite values.",
    errorIntersect: "Two non-adjacent sides of the polygon intersect — the area is not shown.",
    errorGeneric: "Check the entered values.",

    unitM: "m",
    unitM2: "m²",
    unitAr: "ar",
    unitHa: "ha",
  },

  "seeding-rate": {
    standMode: "Unit of the target stand",
    standModePerM2: "plants/m²",
    standModePerHa: "plants/ha",
    standValue: "Target stand",
    standValueHint: "Your choice by crop and variety. Nexus does not suggest it.",
    tkwGrams: "Thousand-grain mass (TKW)",
    germinationPercent: "Germination",
    purityPercent: "Purity",
    fieldLossPercent: "Field loss",
    areaHa: "Sowing area",
    bagMassKg: "Bag mass",
    rowSpacingCm: "Row spacing",
    seedsPerUnit: "Number of grains in a sowing unit",
    priceMode: "Price",
    priceModeNone: "No price",
    priceModePerKg: "Per kilogram",
    priceModePerUnit: "Per sowing unit",
    pricePerKg: "Price per kilogram",
    pricePerUnit: "Price per sowing unit",

    results: "Result",
    normKgHa: "Sowing rate",
    seedsPerM2: "Grains per m²",
    seedsPerHa: "Grains per hectare",
    totalSeedKg: "Total seed",
    bagsExact: "Number of bags (exact)",
    bagsCeil: "Number of bags (rounded up)",
    totalSeeds: "Total grains",
    unitsExact: "Sowing units (exact)",
    unitsCeil: "Sowing units (rounded up)",
    rowSetting: "Drill setting",
    seedsPerLinearMeter: "Grains per running metre of row",
    spacingInRowCm: "Grain spacing within the row",
    reverseStandCheckPerM2: "Check: stand from the calculated rate",
    totalCost: "Total seed cost",

    inputs: "Entered",
    formula: "F = germination·purity·(1−loss/100)     N = stand/F     rate = stand·TKW/(100·F)",

    errorStandValue: "The target stand must be in the allowed range for the chosen unit.",
    errorTkwGrams: "The thousand-grain mass is between 0.05 and 2000 g.",
    errorGerminationPercent:
      "Germination is a percentage from 1 to 100 — a value below 1 is refused as a likely error.",
    errorPurityPercent: "Purity is a percentage from 1 to 100.",
    errorFieldLossPercent: "The field loss is between 0 and 60%.",
    errorAreaHa: "The sowing area must be greater than zero.",
    errorBagMassKg: "The bag mass must be greater than zero.",
    errorRowSpacingCm: "The row spacing must be greater than zero.",
    errorSeedsPerUnit: "The number of grains in a sowing unit must be greater than zero.",
    errorPricePerKg: "The price per kilogram may not be negative.",
    errorPricePerUnit: "The price per sowing unit may not be negative.",
    errorGeneric:
      "Check the entered values — one of the factors (germination, purity, loss) gives zero.",

    unitKg: "kg",
    unitKgHa: "kg/ha",
    unitG: "g",
    unitCm: "cm",
    unitHa: "ha",
    unitPercent: "%",
    unitRsd: "RSD",
  },

  "sprayer-calibration": {
    nozzleFlowMode: "How the nozzle flow was measured",
    nozzleFlowModeDirect: "Directly read flow",
    nozzleFlowModeCatch: "Captured volume and time",
    flowLMin: "Flow of one nozzle",
    flowLMinHint: "Measured by capture, not from a catalogue.",
    catchVolumeMl: "Captured volume",
    catchTimeS: "Capture time",
    nozzleSpacingM: "Nozzle spacing on the boom",
    nozzleCount: "Number of nozzles",
    workingWidthM: "Working width (measured)",
    workingWidthMHint:
      "An independently measured width — it is compared with the number of nozzles × spacing, not silently replacing it.",
    speedKmh: "Travel speed",
    targetRateLHa: "Target spray rate (from the label)",
    limitHint: "From the regulation you apply. Nexus does not know which regulation that is and offers no value.",
    tankVolumeL: "Tank volume",

    results: "Result",
    nozzleFlowLMin: "Flow of one nozzle",
    rateFromSpacingLHa: "Spray rate (from nozzle spacing)",
    boomCheck: "Check over the whole boom",
    totalFlowLMin: "Total boom flow",
    widthFromCountM: "Working width (from number of nozzles × spacing)",
    widthDifferenceM: "Measured width − from number of nozzles × spacing",
    rateFromCountWidthLHa: "Spray rate (from the boom)",
    fromLabel: "Against the target rate from the label",
    requiredNozzleFlowLMin: "Nozzle flow needed for the target rate",
    expectedCatchVolumeMl: "Expected captured volume",
    ratio: "Measured ÷ target",
    tank: "Tank",
    coverageHaPerTank: "Area per full tank",
    distancePerTankM: "Distance per full tank",

    inputs: "Entered",
    formula: "Q = 600·q/(v·w)     q = (V/1000)·(60/t)     q_target = Q_target·v·w/600",

    errorNozzleSpacingM: "The nozzle spacing on the boom is between 0.1 and 2 m.",
    errorSpeedKmh: "The travel speed is between 0.5 and 30 km/h.",
    errorCatchTimeS: "The capture time must be greater than zero.",
    errorNozzleCount: "The number of nozzles is a whole number from 1 to 200.",
    errorWorkingWidthM: "The working width must be greater than zero.",
    errorTargetRateLHa: "The target spray rate is between 20 and 2000 l/ha.",
    errorTankVolumeL: "The tank volume must be greater than zero.",
    errorNozzleFlowLMin: "The flow of one nozzle is between 0.05 and 20 l/min.",
    errorCatchVolumeMl: "The captured volume must be greater than zero.",
    errorGeneric: "Check the entered values.",

    unitLMin: "l/min",
    unitLHa: "l/ha",
    unitM: "m",
    unitMl: "ml",
    unitHa: "ha",
    unitKmh: "km/h",
    unitPercent: "%",
  },

  "tank-mix-dose": {
    productsText: "Products in the tank",
    productsTextHint:
      "Paste one product per line: name;l or kg;dose method (ha, % or ml);value. The “ha” method is a dose per hectare, “%” is a concentration in percent, “ml” is a dose per litre of spray (ml or g per litre). Up to 10 products.",
    productsTextPlaceholder: "Product A;l;ha;1.5\nProduct B;kg;%;0.625",
    sprayRateLHa: "Spray rate (water use)",
    limitHint: "From the regulation you apply. Nexus does not know which regulation that is and offers no value.",
    tankVolumeL: "Tank volume",
    areaHa: "Area to treat",

    results: "Result",
    colProduct: "Product",
    colDosePerHa: "Dose per hectare",
    colPerTank: "Per full tank",
    colTotal: "Total for the area",
    colRemainder: "In the last (partial) fill",
    colConcentration: "Concentration in the tank",
    perFullTankAmount: "per full tank",
    totalAmount: "total",
    remainderAmount: "in the remainder",
    concentrationPercent: "concentration",
    basisVolumeVolume: "volume/volume",
    basisMassVolume: "mass/volume",
    fullTankAreaHa: "Area per full tank",
    totalSprayVolumeL: "Total spray volume",
    fullFills: "Full fills",
    remainderVolumeL: "Volume of the last (partial) fill",
    remainderAreaHa: "Area of the last (partial) fill",
    fullTankCarrierL: "Water per full tank (after adding the products)",
    totalCarrierL: "Total water for the whole area",
    labelNote:
      "The spray is water plus all the added products — the water volume is the tank volume less the liquid products it contains, not the whole tank volume. You enter the dose and the spray rate from the product label; Nexus does not know, remember or suggest them.",

    inputs: "Entered",
    productCount: "Number of products",
    formula:
      "A_r = V/Q     P_r = D·A_r     V_tot = Q·A     P_tot = D·A     n = V_tot/V     n_p = floor(n)     V_o = V_tot − n_p·V     P_o = D·(V_o/Q)     water = V_tot − P_tot (liquid products)",

    errorParse: "Every product row is name;l or kg;ha, % or ml;value.",
    errorProducts: "Enter from 1 to 10 products.",
    errorSprayRateLHa: "The spray rate (water use) is between 20 and 2000 l/ha.",
    errorTankVolumeL: "The tank volume must be greater than zero.",
    errorAreaHa: "The area to treat must be greater than zero.",
    errorDose: "The product dose must be greater than zero, for every product in the list.",
    errorGeneric: "Check the entered values.",

    unitL: "l",
    unitLHa: "l/ha",
    unitHa: "ha",
    unitPercent: "%",
    unitPerHaSuffix: "/ha",
  },

  "yield-estimate-samples": {
    method: "Sampling method",
    methodSmallGrain: "Cereals (ears × grains × TKW)",
    methodRowCrop: "Row crops (plants × fruits × grains)",
    methodMeasuredArea: "Measured area (sample mass)",
    samplesText: "Samples",
    samplesTextHintSmallGrain:
      "Paste one sample per line: ears per m²;grains per ear. From 1 to 50 samples.",
    samplesTextHintRowCrop:
      "Paste one sample per line: plants per hectare;cobs (fruits) per plant;grains per cob. If the grains are counted as rows × grains per row, enter their product as the third value. From 1 to 50 samples.",
    samplesTextHintMeasuredArea:
      "Paste one sample per line: sample area in m²;harvested sample mass in kg. From 1 to 50 samples.",
    tkwGrams: "Thousand-grain mass (TKW)",
    tkwMoisturePercent: "Moisture at which the TKW was measured",
    tkwMoisturePercentHint:
      "The moisture of the grain sample whose thousand-grain mass was measured — the basis from which the conversion to the reference moisture starts for this method. It is not the moisture of the harvested sample.",
    sampleMoisturePercent: "Moisture in the sample",
    sampleMoisturePercentHint:
      "The moisture of the harvested and measured sample — the basis from which the conversion to the reference moisture starts for this method.",
    referenceMoisturePercent: "Reference moisture for the conversion",
    limitHint: "From the purchase contract or the buyer's rulebook. Nexus does not know or suggest it.",
    harvestLossPercent: "Harvest loss (optional)",
    plotAreaHa: "Plot area",

    results: "Result",
    colSample: "Sample",
    colYieldTHa: "Yield",
    meanTHa: "Mean of the samples",
    minTHa: "Minimum",
    maxTHa: "Maximum",
    stdDevTHa: "Standard deviation",
    standardErrorTHa: "Standard error of the mean",
    coefficientOfVariationPercent: "Coefficient of variation",
    singleSampleNote: "The estimate rests on one sample — the spread is not shown.",
    meanAtReferenceMoistureTHa: "Mean at the reference moisture",
    meanAfterLossTHa: "Mean after the harvest loss",
    totalYieldT: "Total estimated yield for the field",

    inputs: "Entered",
    sampleCount: "Number of samples",
    formula:
      "cereals: t/ha = K·Z·TKW/100000     row crops: t/ha = plants/ha·(fruits·grains·TKW/1000)/1000000     measured area: t/ha = mass/area×10     x̄ = Σxᵢ/n     s = √(Σ(xᵢ−x̄)²/(n−1))     m_ref = m·(100−w₁)/(100−w₂)",

    errorParse: "Every sample row must have as many values as the chosen method requires.",
    errorSamples: "Enter from 1 to 50 samples.",
    errorTkwGrams: "The thousand-grain mass is between 0.05 and 2000 g.",
    errorTkwMoisturePercent: "The moisture at which the TKW was measured is between 0 and 60%.",
    errorSampleMoisturePercent: "The moisture in the sample is between 0 and 60%.",
    errorReferenceMoisturePercent:
      "The reference moisture for the conversion is between 0 and 60% and may not equal 100.",
    errorHarvestLossPercent: "The harvest loss is between 0 and 100%.",
    errorPlotAreaHa: "The plot area must be greater than zero.",
    errorEarsPerM2: "Ears per m² is between 1 and 2000, in every sample.",
    errorGrainsPerEar: "Grains per ear (or cob) is between 1 and 200, in every sample.",
    errorPlantsPerHa: "Plants per hectare must be greater than zero, in every sample.",
    errorEarsPerPlant: "Cobs (fruits) per plant must be greater than zero, in every sample.",
    errorSampleAreaM2: "The sample area must be greater than zero, in every sample.",
    errorSampleMassKg: "The sample mass must be greater than zero, in every sample.",
    errorGeneric: "Check the entered values.",

    unitTHa: "t/ha",
    unitT: "t",
    unitG: "g",
    unitHa: "ha",
    unitPercent: "%",
  },
} as const;
