/**
 * „Elektro" — the English copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as the assignment spells the
 * registration. The tool's NAME and its one-line blurb are not here: those live
 * in a different table another process owns.
 *
 * **Three tools carry an absolute discipline.** `transformer-current`,
 * `conduit-fill` and `motor-starting-current` may name a quantity and the user's
 * own limit, and may never say what they mean together — no verdict of any kind,
 * anywhere in this file.
 *
 * **A unit is copy, not a constant.** „A", „mm²", „lm" and „kWh" are written
 * here rather than concatenated in the surface.
 */
export const PRO_ELEKTRO_EN = {
  "energy-cost": {
    power: "Appliance power",
    hoursPerDay: "Hours a day",
    days: "Number of days",
    price: "Price per kilowatt-hour",
    priceHint: "From your electricity bill. Nexus does not know your tariff and offers no figure.",
    duty: "Share of the time at full load",
    dutyHint: "In percent. An empty field means 100 % — the load running at full power throughout.",
    results: "Result",
    effectivePower: "Power after the duty cycle",
    hoursTotal: "Total hours",
    energyPerDay: "Energy a day",
    energy: "Total energy",
    cost: "Total cost",
    costPerDay: "Cost a day",
    formulaLine: "E = P·t/1000     cost = E × price per kilowatt-hour",
    inputs: "Entered",
    unitW: "W",
    unitH: "h",
    unitKwh: "kWh",
    unitCurrency: "din",
    errorPower: "The power must be greater than zero.",
    errorHours: "The hours a day is between 0 and 24.",
    errorDays: "The number of days is a whole number from 1 to 3660.",
    errorDuty: "The share of the time is between 0 and 100 percent.",
    errorPrice: "The price per kilowatt-hour cannot be negative.",
  },

  "lighting-count": {
    area: "Floor area",
    targetLux: "Illuminance wanted",
    targetLuxHint:
      "In lux, from the standard or recommendation you are working to. Nexus does not choose a " +
      "level and offers none.",
    luminaireLumens: "Luminous flux of one fitting",
    luminaireLumensHint: "In lumens, from the manufacturer's data.",
    utilisationFactor: "Utilisation factor",
    utilisationHint: "The share of the flux that reaches the work plane, from the fitting's data.",
    maintenanceFactor: "Maintenance factor",
    maintenanceHint: "What dirt and ageing leave of the flux.",
    results: "Result",
    requiredLumens: "Luminous flux needed",
    luminaireCount: "Number of fittings",
    installedLumens: "Installed flux",
    achievedLux: "Illuminance achieved",
    luxRatio: "Ratio to the illuminance wanted",
    formulaLine: "N = E·A/(Φ·UF·MF)     illuminance = N·Φ·UF·MF/A",
    inputs: "Entered",
    unitLm: "lm",
    unitLx: "lx",
    unitM2: "m²",
    errorArea: "The area must be greater than zero.",
    errorLux: "The illuminance wanted must be a number greater than zero.",
    errorLumens: "The fitting's luminous flux must be greater than zero.",
    errorUtilisation: "The utilisation factor is between 0.1 and 1.",
    errorMaintenance: "The maintenance factor is between 0.1 and 1.",
  },

  "luminaire-spacing": {
    spacingToHeightRatio: "Spacing-to-height ratio",
    ratioHint: "From the fitting's photometric data. No number is entered for you.",
    mountingHeight: "Mounting height",
    workPlaneHeight: "Height of the work plane",
    workPlaneHint: "The ratio is measured from the work plane, not the floor. An empty field means 0.",
    roomLength: "Room length",
    roomWidth: "Room width",
    results: "Result",
    heightAboveWorkPlane: "Height above the work plane",
    maxSpacing: "Greatest fitting spacing",
    countAlong: "Count along the length",
    countAcross: "Count across the width",
    totalCount: "Total fittings",
    formulaLine: "S = SHR·(h − h_wp)     count = ceil(length/S) on each axis",
    inputs: "Entered",
    unitM: "m",
    errorRatio: "The spacing-to-height ratio is between 0.1 and 3.",
    errorHeight: "The mounting height must be above the work plane.",
    errorLength: "The room length must be greater than zero.",
    errorWidth: "The room width must be greater than zero.",
  },

  "transformer-current": {
    apparentPower: "Rated apparent power",
    phases: "Phases",
    phaseSingle: "Single-phase",
    phaseThree: "Three-phase",
    primaryVoltage: "Primary voltage",
    secondaryVoltage: "Secondary voltage",
    results: "Result",
    primaryCurrent: "Primary current",
    secondaryCurrent: "Secondary current",
    phaseFactor: "Phase factor",
    formulaLine: "I = S/(√3·U) three-phase     I = S/U single-phase",
    inputs: "Entered",
    unitA: "A",
    unitKva: "kVA",
    errorPower: "The rated power must be greater than zero.",
    errorPrimary: "The primary voltage must be greater than zero.",
    errorSecondary: "The secondary voltage must be greater than zero.",
  },

  "conduit-fill": {
    conduitDiameter: "Conduit internal diameter",
    conduitDiameterHint: "The internal diameter, not the trade size.",
    conductorDiameter: "Diameter of one conductor",
    conductorCount: "Number of conductors",
    fillLimit: "Fill limit",
    fillLimitHint: "From the code you are working to. Nexus does not know it and offers no figure.",
    results: "Result",
    conduitArea: "Conduit cross-sectional area",
    conductorsArea: "Conductors area",
    fillPercent: "Fill",
    fillRatio: "Ratio to the limit",
    remainingArea: "Free area",
    formulaLine: "fill = Σ(π·d²/4)/(π·D²/4) = Σd²/D²",
    inputs: "Entered",
    unitMm: "mm",
    unitMm2: "mm²",
    errorConduit: "The conduit internal diameter must be greater than zero.",
    errorConductor: "The conductor diameter must be above zero and below the conduit diameter.",
    errorCount: "The number of conductors is a whole number from 1 to 500.",
    errorLimit: "The fill limit is between 1 and 100 percent.",
  },

  "motor-starting-current": {
    ratedCurrent: "Motor rated current",
    ratedCurrentHint: "From the nameplate — the full-load current.",
    startingRatio: "Locked-rotor to rated current",
    startingRatioHint:
      "The k on the nameplate or in the motor data — 4 and 8 describe different machines.",
    method: "Starting method",
    methodDol: "Direct on line",
    methodStarDelta: "Star-delta",
    methodSoft: "Soft starter",
    softStartPercent: "Soft starter initial voltage",
    softStartHint: "In percent of the rated voltage.",
    estimateNote:
      "An estimate from the nameplate figures — the network's impedance, the motor's own " +
      "characteristics and the load's torque are outside it.",
    results: "Result",
    lockedRotorCurrent: "Locked-rotor current",
    startingCurrent: "Starting current",
    startingRatioOut: "Starting current / rated current",
    torqueShare: "Share of the starting torque",
    formulaLine: "I_s = k·I_N     star-delta: I/3 and M/3     soft: I·p/100 and M·(p/100)²",
    inputs: "Entered",
    unitA: "A",
    errorRated: "The rated current must be greater than zero.",
    errorRatio: "The locked-rotor to rated ratio is between 1 and 20.",
    errorSoft: "The soft starter's initial voltage is between 10 and 100 percent.",
  },
} as const;
