/**
 * "Heating & plumbing" - the English copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. The names and blurbs live in `./pro.en.ts`.
 */
export const PRO_GREJANJE_EN = {
  "room-heat-loss": {
    temperature: "Temperature difference",
    temperatureHint: "Indoor design temperature minus outdoor, in kelvin.",
    surfaces: "Envelope surfaces",
    surfacesHint:
      "One line each: area in m² and U-value, separated by a semicolon (for example \"20; 0,3\").",
    bridge: "Thermal-bridge allowance",
    bridgeHint: "Extra coefficient in W/K. Leave 0 when bridges are not counted separately.",
    ventilation: "Ventilation basis",
    ventilationAirChanges: "air changes",
    ventilationPerArea: "flow per area",
    airChanges: "Air changes per hour",
    airChangesHint: "Per hour, for the whole room.",
    volume: "Room volume",
    volumeHint: "In m³.",
    airFlow: "Air flow per floor area",
    airFlowHint: "In m³/(h·m²) - used instead of air changes.",
    floorArea: "Floor area",
    floorAreaHint: "In m².",
    results: "Result",
    transmissionCoefficient: "Transmission coefficient H_T",
    ventilationCoefficient: "Ventilation coefficient H_V",
    transmissionLoss: "Transmission loss",
    ventilationLoss: "Ventilation loss",
    totalLoss: "Total loss",
    lossPerArea: "Loss per m² of floor",
    formula:
      "Φ_T = (Σ(U·A) + H_bridge)·Δθ     H_V = 0,34·n·V (or 0,34·q·A_floor)     Φ = Φ_T + Φ_V",
    inputs: "Entered",
    errorTemperature: "The temperature difference is a number from 1 to 80 K.",
    errorSurfaces: "Check the rows: area above zero, U-value zero or more.",
    errorBridge: "The bridge allowance is a number of zero or more.",
    errorVentilation:
      "Choose exactly one ventilation basis - air changes or flow per area.",
    errorAirChanges: "Air changes per hour is a number above zero.",
    errorVolume: "Room volume is a number above zero.",
    errorAirFlow: "Flow per area is a number of zero or more.",
    errorFloorArea: "Floor area is a number above zero.",
    unitWK: "W/K",
    unitW: "W",
    unitWPerM2: "W/m²",
    unitK: "K",
    unitM2: "m²",
    unitM3: "m³",
    unitM3PerH: "m³/(h·m²)",
  },

  "radiator-output": {
    nominalOutput: "Nominal output",
    nominalOutputHint: "The output the maker gives at the nominal temperature spread, in W.",
    exponent: "Exponent n",
    exponentHint:
      "From the radiator's own data sheet; EN 442-1 measures it per appliance. Typically " +
      "around 1,3, but Nexus does not assume it.",
    temperatureMode: "Temperature-spread input",
    modeTemperatures: "flow, return and room",
    modeSpread: "the spread directly",
    flow: "Flow temperature",
    back: "Return temperature",
    room: "Room temperature",
    spread: "Spread Δθ",
    spreadHint: "Mean water temperature minus room temperature, in K.",
    nominalSpread: "Nominal spread",
    nominalSpreadHint: "50 K is the EN 442 nominal spread; leave empty for 50.",
    requiredOutput: "Output wanted",
    requiredOutputHint:
      "Given a wanted output you also get the spread it needs, in W.",
    results: "Result",
    output: "Output at this spread",
    spreadUsed: "Spread used Δθ",
    neededSpread: "Spread needed for the wanted output",
    formula: "Φ = Φ_n · (Δθ / Δθ_n)^n     Δθ = (flow + return)/2 − room",
    inputs: "Entered",
    errorNominal: "The nominal output is a number above zero.",
    errorExponent: "The exponent is a number from 1 to 2.",
    errorTemperatures:
      "This input mode needs the flow, the return and the room temperature.",
    errorSpread: "Give either the spread directly or the three temperatures - not both.",
    errorSpreadValue: "The spread is a number from 1 to 120 K.",
    errorNominalSpread: "The nominal spread is a number from 10 to 90 K.",
    errorRequired: "The wanted output is a number above zero.",
    unitW: "W",
    unitK: "K",
  },

  "water-heater-time": {
    volume: "Volume of water",
    volumeHint: "In litres.",
    initial: "Starting temperature",
    target: "Target temperature",
    power: "Heater power",
    powerHint: "In watts.",
    loss: "Standing losses",
    lossHint:
      "Percentage of extra energy the cylinder loses while heating. Leave 0 when unmeasured.",
    results: "Result",
    rise: "Temperature rise",
    mass: "Mass of water",
    energy: "Energy needed",
    timeSeconds: "Heating time, seconds",
    timeMinutes: "Heating time, minutes",
    formula: "Q = m·c·Δθ · (1 + losses/100)     t = Q / P     c = 4186 J/(kg·K)",
    inputs: "Entered",
    errorVolume: "Volume is a number above zero.",
    errorInitial: "The starting temperature is a number from −20 to 150 °C.",
    errorTarget: "The target temperature has to be above the starting one.",
    errorPower: "Heater power is a number above zero.",
    errorLoss: "Standing losses are a number from 0 to 100 %.",
    unitL: "l",
    unitKg: "kg",
    unitC: "°C",
    unitK: "K",
    unitW: "W",
    unitKwh: "kWh",
    unitSeconds: "s",
    unitMinutes: "min",
    unitPercent: "%",
  },

  "pipe-pressure-drop": {
    diameter: "Inside diameter",
    diameterHint: "The pipe's inside diameter, in millimetres.",
    length: "Pipe length",
    lengthHint: "Straight run, in metres, before any elbows are counted.",
    known: "Given quantity",
    knownFlow: "flow rate",
    knownVelocity: "velocity",
    flow: "Flow rate",
    flowHint: "A value and a unit.",
    velocity: "Velocity",
    velocityHint: "Mean velocity over the full bore, in m/s.",
    roughness: "Absolute roughness",
    roughnessHint:
      "In millimetres - for example new steel 0,05, drawn copper 0,0015, PEX 0,007.",
    viscosity: "Kinematic viscosity",
    viscosityHint: "In mm²/s. Water at 20 °C is 1,004.",
    density: "Fluid density",
    densityHint: "In kg/m³. Water at 20 °C is 998.",
    fittings: "Fittings' equivalent length",
    fittingsHint: "Total equivalent length of elbows, valves and tees, in metres.",
    results: "Result",
    regime: "Flow regime",
    regimeLaminar: "laminar",
    regimeTransitional: "transitional",
    regimeTurbulent: "turbulent",
    reynolds: "Reynolds number",
    friction: "Friction factor f",
    totalLength: "Total length in the sum",
    headLoss: "Head loss",
    pressureDrop: "Pressure drop",
    formula:
      "Δp = f·(L/D)·ρ·v²/2     h = f·(L/D)·v²/(2g)     f: Swamee–Jain above Re 5000, 64/Re below 2300",
    inputs: "Entered",
    errorDiameter: "The diameter is a number from 0 to 2000 mm and above zero.",
    errorLength: "The length is a number above zero.",
    errorKnown: "Give exactly one - a flow rate or a velocity.",
    errorFlow: "The flow rate is a number of zero or more.",
    errorVelocity: "The velocity is a number of zero or more.",
    errorRoughness: "The roughness is a number of zero or more.",
    errorViscosity: "The viscosity is a number above zero.",
    errorDensity: "The density is a number above zero.",
    errorFittings: "The equivalent length is a number of zero or more.",
    unitM: "m",
    unitMm: "mm",
    unitMs: "m/s",
    unitMm2S: "mm²/s",
    unitKgM3: "kg/m³",
    unitKpa: "kPa",
    unitBar: "bar",
    unitPa: "Pa",
  },

  "power-units": {
    value: "Value",
    unit: "Unit",
    unitW: "watt (W)",
    unitKw: "kilowatt (kW)",
    unitBtu: "BTU/h",
    unitKcal: "kcal/h",
    results: "Result",
    watts: "Watts",
    kilowatts: "Kilowatts",
    btuPerHour: "BTU/h",
    kcalPerHour: "kcal/h",
    formula:
      "1 BTU_IT = 1055,05585262 J    1 cal_IT = 4,1868 J    1 BTU/h = 0,293071 W    1 kcal/h = 1,163 W",
    errorValue: "The value has to be a number.",
  },

  "heating-cost": {
    fuels: "Fuels",
    fuelsHint:
      "One line each: name; price per unit; energy in one unit in kWh; seasonal efficiency " +
      "from 0 to 1. For example: \"Gas; 50; 9,97; 0,9\".",
    results: "Result",
    cheapest: "Lowest cost per kWh of useful heat",
    colFuel: "Fuel",
    colDelivered: "Cost per kWh delivered",
    colUseful: "Cost per kWh useful",
    formula: "cost_delivered = price / energy_per_unit     cost_useful = cost_delivered / efficiency",
    inputs: "Entered",
    errorFuels: "Check the rows: price and energy above zero, efficiency from 0 to 1,5.",
    unitCurrency: "per kWh",
  },
} as const;
