/**
 * „Zanat" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. The tool's NAME and its one-line blurb are not here: those
 * live in the `name` and `blurb` tables of `./pro.ts`.
 *
 * **A unit is copy, not a constant.** „mm", „cm", „kg" are written here rather
 * than concatenated in the surface.
 *
 * **`glass-pane-weight` and `shelf-deflection` are `life-safety`.** Their copy
 * names a quantity and, where the assignment makes a limit an input, the
 * user's own limit — and never what the two mean together
 * (`toolForbidsVerdict`). No „zadovoljava", no „bezbedno", no colour word.
 */
export const PRO_ZANAT_SR = {
  "fabric-yardage-repeat": {
    rows: "Spisak komada",
    rowsHint: "Red po red: širina;visina;broj komada, u centimetrima, pre dodatka na šav.",
    rollWidth: "Širina rolne",
    rollWidthHint: "Korisna širina rolne tkanine, u centimetrima.",
    seamAllowance: "Dodatak na šav po ivici",
    verticalRepeat: "Vertikalni raport",
    verticalRepeatHint: "Korak šare duž rolne, u centimetrima. Unesi 0 za tkaninu bez šare.",
    horizontalRepeat: "Horizontalni raport",
    horizontalRepeatHint:
      "Korak šare preko širine rolne, u centimetrima. Unesi 0 kad šara nema poprečni raport.",
    waste: "Rastur",
    grainMandatory: "Obavezan smer tkanja",
    grainHint: "Kad je uključeno, komad se ne sme okrenuti za 90° radi uklapanja u rolnu.",
    grainYes: "Da",
    grainNo: "Ne",

    results: "Rezultat",
    colPiece: "Komad",
    colCut: "Mera kroja",
    colOrientation: "Položaj",
    colCentered: "Centrirano na raport",
    colAcross: "Po širini rolne",
    colRows: "Redova kroja",
    colRowLength: "Dužina reda",
    colAlignment: "Poravnanje na početku rolne",
    colUsage: "Utrošak",
    colPerPiece: "Po komadu",
    orientationNormal: "normalno",
    orientationRotated: "okrenuto",
    centeredWidth: "širina",
    centeredHeight: "visina",

    totalLength: "Ukupna dužina",
    orderLength: "Dužina za poručivanje",
    usedArea: "Utrošena površina",
    usefulArea: "Korisna površina",
    wasteArea: "Površina otpada",

    inputs: "Uneseno",
    formula:
      "š_k = š+2d   v_k = v+2d   š_k′ = ceil(š_k/R_h)·R_h   n_a = floor(Š_r/š_k′)   red = ceil(kol/n_a)   l = ceil(v_k/R_v)·R_v   L = Σ(red·l + R_v)·(1+rastur/100)",

    errorRows: "Spisak komada je red po red, 1 do 500 redova; svaki red nosi širinu, visinu i broj komada.",
    errorRollWidth: "Širina rolne je broj od 50 do 320 cm.",
    errorSeamAllowance: "Dodatak na šav je broj od 0 do 20 cm.",
    errorVerticalRepeat: "Vertikalni raport je broj od 0 do 120 cm.",
    errorHorizontalRepeat: "Horizontalni raport je broj od 0 do 160 cm.",
    errorWaste: "Rastur je broj od 0 do 30 %.",
    errorWidth: "Širina komada mora biti veća od nule.",
    errorHeight: "Visina komada mora biti veća od nule.",
    errorCount: "Broj komada po redu je ceo broj od 1 do 500.",
    errorAcrossRoll:
      "Komad je širi od rolne u oba moguća položaja — uporedi meru kroja sa širinom rolne.",

    unitCm: "cm",
    unitM: "m",
    unitM2: "m²",
    unitPercent: "%",
  },

  "glass-pane-weight": {
    width: "Širina stakla",
    height: "Visina stakla",
    composition: "Sastav",
    compositionMonolithic: "Monolitno",
    compositionLaminated: "Laminirano",
    compositionInsulated: "Izo-staklo",
    plyThicknesses: "Debljine stakala u paketu",
    plyThicknessesHint:
      "Red po red, debljina svakog stakla u paketu, u milimetrima. Kod izo-stakla se međuprostor ne unosi.",
    pvbLayers: "Broj slojeva PVB folije",
    pvbLayerThickness: "Debljina jednog sloja PVB folije",
    pvbLayerThicknessHint: "U milimetrima. Podrazumevano 0,38 mm.",
    pieces: "Broj komada",
    density: "Gustina stakla",
    densityHint:
      "U kg/m³. Podrazumevano 2500 (float staklo); za posebna stakla unesi svoju vrednost.",

    results: "Rezultat",
    area: "Površina jednog komada",
    totalArea: "Ukupna površina",
    massPerArea: "Masa po m²",
    massPerPiece: "Masa jednog komada",
    totalMass: "Ukupna masa",
    perimeter: "Obim jednog komada",
    densityUsed: "Upotrebljena gustina",
    glassThicknessSum: "Zbir debljina stakala (Σ t_staklo)",
    pvbThicknessSum: "Zbir debljina PVB folije (Σ t_PVB)",
    temperingNote:
      "Debljine iznad su nominalne. Kaljenje ne menja gustinu stakla, pa je masa ista za kaljeno i nekaljeno staklo istih mera. Alatka ne procenjuje nijednu granicu mase, klasu rukovanja ni broj ljudi.",

    inputs: "Uneseno",
    formula:
      "A = (š/1000)·(v/1000)   m_A = ρ_staklo·10⁻³·Σt_staklo + ρ_PVB·10⁻³·Σt_PVB   m = A·m_A   O = 2·(š+v)/1000",

    errorWidth: "Širina je broj od 50 do 6000 mm.",
    errorHeight: "Visina je broj od 50 do 6000 mm.",
    errorDensity: "Gustina je broj od 2200 do 3000 kg/m³.",
    errorPieces: "Broj komada je ceo broj od 1 do 1000.",
    errorPlyThicknesses:
      "Debljine stakala: svaka vrednost 2–25 mm, spisak ne sme biti prazan ni nulti, a za monolitno staklo unosi se tačno jedna vrednost.",
    errorPvbLayers: "Broj slojeva PVB folije je ceo broj od 0 do 8, i moguć je samo kod laminata.",
    errorPvbLayerThickness: "Debljina jednog sloja PVB folije je broj od 0,1 do 2 mm.",

    unitMm: "mm",
    unitM: "m",
    unitM2: "m²",
    unitKg: "kg",
    unitKgM2: "kg/m²",
    unitKgM3: "kg/m³",
  },

  "iso-286-fits": {
    nominalSize: "Nominalna mera",
    nominalSizeHint: "U milimetrima, od 1 do 500.",
    holeMode: "Rupa — način zadavanja",
    holeModeGrade: "Standardna oznaka (H)",
    holeModeManual: "Sopstvena odstupanja",
    holeGrade: "Stepen tolerancije rupe",
    holeGradeHint: "IT5 do IT12. Prazno polje znači IT7 (H7).",
    holeUpper: "Gornje odstupanje rupe",
    holeLower: "Donje odstupanje rupe",
    shaftMode: "Osovina — način zadavanja",
    shaftModeLetter: "Slovo i stepen",
    shaftModeManual: "Sopstvena odstupanja",
    shaftLetter: "Slovo osovine",
    shaftGrade: "Stepen tolerancije osovine",
    shaftUpper: "Gornje odstupanje osovine",
    shaftLower: "Donje odstupanje osovine",

    results: "Rezultat",
    fitDesignation: "Oznaka naleganja",
    range: "Opseg nominalne mere",
    colPart: "Deo",
    colUpper: "Gornje odstupanje",
    colLower: "Donje odstupanje",
    colMax: "Najveća mera",
    colMin: "Najmanja mera",
    colWidth: "Širina polja tolerancije",
    colMean: "Srednja mera",
    hole: "Rupa",
    shaft: "Osovina",
    holeMax: "Rupa — najveća mera",
    holeMin: "Rupa — najmanja mera",
    shaftMax: "Osovina — najveća mera",
    shaftMin: "Osovina — najmanja mera",
    maxClearance: "Najveći zazor",
    minClearance: "Najmanji zazor",
    meanClearance: "Srednji zazor",
    signedNote:
      "Zazor je prikazan sa znakom. Kod sopstvenih odstupanja negativna vrednost znači preklop, ne zazor — alatka to ne ocenjuje.",

    inputs: "Uneseno",
    formula:
      "ES = +IT(rupa)   ei(osovina) = es − IT(osovina)   D_max/min = D + ES/EI÷1000   Z_max = ES − ei   Z_min = EI − es",

    errorNominalSize: "Nominalna mera je broj od 1 do 500 mm.",
    errorHoleGrade: "Stepen tolerancije rupe je ceo broj od IT5 do IT12.",
    errorHoleDeviations: "Sopstvena odstupanja rupe: gornje mora biti veće ili jednako donjem, oba realni brojevi.",
    errorShaftLetter: "Slovo osovine mora biti izabrano (d, e, f, g ili h).",
    errorShaftGrade: "Stepen tolerancije osovine je ceo broj od IT5 do IT12.",
    errorShaftDeviations:
      "Sopstvena odstupanja osovine: gornje mora biti veće ili jednako donjem, oba realni brojevi.",

    unitMm: "mm",
    unitUm: "µm",
  },

  "linear-cutting-stock": {
    items: "Spisak potrebnih komada",
    itemsHint: "Red po red: dužina;broj komada, u milimetrima.",
    barLength: "Dužina šipke iz magacina",
    kerf: "Širina reza",
    kerfHint: "Zavisi od lista testere koji je na mašini, u milimetrima.",
    startWaste: "Otpad na početku šipke",
    endWaste: "Otpad na kraju šipke",
    minUsableRemnant: "Najmanji ostatak koji se čuva",
    minUsableRemnantHint:
      "Ostatak kraći od ovoga se u prikazu vodi kao otpad, ne kao upotrebljiv komad.",

    results: "Rezultat",
    colBar: "Šipka",
    colPieces: "Raspored (dužina, položaj)",
    colUsed: "Iskorišćena dužina",
    colRemainder: "Ostatak",
    colUsable: "Upotrebljiv ostatak",
    usableYes: "da",
    usableNo: "ne",

    barCount: "Broj šipki",
    usableLength: "Korisna dužina šipke",
    totalCutLength: "Ukupna dužina komada",
    totalPurchasedLength: "Ukupno nabavljeno",
    cutCount: "Broj rezova",
    kerfLength: "Dužina koju pojede rez",
    wasteIncludingUsable: "Ukupan otpad (sa upotrebljivim ostacima)",
    wasteIncludingUsablePercent: "Ukupan otpad, % nabavke",
    wasteExcludingUsable: "Otpad bez upotrebljivih ostataka",
    wasteExcludingUsablePercent: "Otpad bez upotrebljivih ostataka, % nabavke",
    usableRemnantLength: "Ukupno upotrebljivih ostataka",
    lowerBoundBars: "Donja granica broja šipki",
    lowerBoundNote:
      "Donja granica važi u okviru ovog modela — svaki komad troši dužinu plus jedan rez, a svaka šipka nudi korisnu dužinu. Kad je broj šipki jednak donjoj granici, raspored je u okviru modela optimalan.",

    inputs: "Uneseno",
    formula: "trošak(d) = d + w   red first-fit-decreasing   LB = ceil(Σ(d+w) / U)",

    errorItems: "Spisak komada ima 1 do 500 redova; svaki red nosi dužinu i broj komada.",
    errorBarLength: "Dužina šipke je broj od 100 do 24000 mm.",
    errorKerf: "Širina reza je broj od 0 do 15 mm.",
    errorStartWaste: "Otpad na početku šipke je broj od 0 do 500 mm.",
    errorEndWaste: "Otpad na kraju šipke je broj od 0 do 500 mm.",
    errorMinUsableRemnant: "Najmanji upotrebljiv ostatak je broj od 0 do 5000 mm.",
    errorUsableLength: "Korisna dužina šipke (dužina minus obrezivanja) mora biti veća od nule.",
    errorLength: "Dužina komada mora biti veća od nule i manja od korisne dužine šipke.",
    errorCount: "Broj komada po redu je ceo broj od 1 do 999.",

    unitMm: "mm",
  },

  "mitre-angles": {
    angleMode: "Ugao — način zadavanja",
    angleModeSides: "Broj stranica",
    angleModeBaseAngle: "Ugao u osnovi (θ)",
    sides: "Broj stranica N",
    baseAngleField: "Ugao u osnovi θ",
    slopeMode: "Nagib — način zadavanja",
    slopeModeSlope: "Nagib od vertikale (B)",
    slopeModeSpring: "Ugao naslona (spring angle, S)",
    slope: "Nagib stranice od vertikale (B)",
    slopeHint: "0 je uspravna stranica, odnosno ravan ram.",
    springAngle: "Ugao naslona lajsne (S)",
    springAngleHint: "Meri se od zida. B = 90 − S.",
    pieceWidth: "Širina komada w",
    pieceWidthHint: "Opciono, samo za dužine stranica — unosi se zajedno sa unutrašnjom dužinom.",
    insideLength: "Unutrašnja svetla dužina stranice",

    results: "Rezultat",
    baseAngle: "Ugao u osnovi (θ)",
    /** B as the arithmetic used it — S is converted before anything is cut. */
    slopeUsed: "Primenjen nagib od vertikale (B)",
    m0: "Pomoćni ugao m₀",
    simpleMitre: "Prost gerung po komadu (θ/2)",
    sawMitreAngle: "Podešavanje testere — gerung (od pravog ugla)",
    sawMitreComplement: "Dopunsko očitavanje (90° − gerung)",
    sawBevelAngle: "Podešavanje testere — nagib lista",
    scaleConventionNote: "Konvencija skale: 0° je pravi ugao (uspravna, neuvrnuta stranica).",
    outsideLength: "Spoljašnja mera komada",
    lengthToLongPoint: "Mera do duge tačke",
    lengthToShortPoint: "Mera do kratke tačke",
    centeredMeasureNote: "Formula centrira meru:",
    centeredOutsideWidth: "spoljašnja širina komada",
    lengthsCautionNote:
      "m₀ je 85° ili više — tan m₀ brzo raste, pa je dobijena dužina osetljiva na malu grešku merenja. Broj je tačan, ali ga treba čitati s tim na umu.",
    tanM0: "tan m₀",

    inputs: "Uneseno",
    formula:
      "θ = (N−2)·180/N   m₀ = 90 − θ/2   M = atan(cos B · tan m₀)   T = asin(sin B · cos m₀)   s_s = s_u + 2·w·cos B·tan m₀",

    errorSides: "Broj stranica je ceo broj od 3 do 48.",
    errorBaseAngle: "Ugao u osnovi je broj od 1 do 179°.",
    errorSlope: "Nagib od vertikale je broj od 0 do 89°.",
    errorSpringAngle: "Ugao naslona je broj od 1 do 89°.",
    errorPieceWidth: "Širina komada je broj od 5 do 500 mm — unosi se zajedno sa unutrašnjom dužinom.",
    errorInsideLength:
      "Unutrašnja svetla dužina je broj od 10 do 10000 mm — unosi se zajedno sa širinom komada.",

    unitDeg: "°",
    unitMm: "mm",
  },

  "mortar-mix-quantity": {
    mode: "Način",
    modePremixed: "Gotova smeša",
    modeOnsite: "Mešanje na licu mesta",

    area: "Površina",
    thickness: "Debljina sloja",
    volume: "Zapremina sveže smeše",
    waste: "Rastur",
    consumptionUnit: "Jedinica potrošnje",
    consumptionUnitPerM2mm: "kg/(m²·mm)",
    consumptionUnitPerM3: "kg/m³",
    consumption: "Potrošnja gotove smeše",
    consumptionHint: "Podatak sa deklaracije proizvoda, u jedinici izabranoj iznad.",
    bagMass: "Masa vreće",
    waterPerKg: "Voda po kilogramu smeše",
    waterPerKgHint: "U l/kg. Podatak sa deklaracije.",

    onsiteVolumeMode: "Zapremina — način zadavanja",
    onsiteVolumeModeArea: "Iz površine i debljine",
    onsiteVolumeModeVolume: "Zapremina direktno",
    packingFactor: "Faktor zbijanja",
    packingFactorHint:
      "Zbir zapremina sastojaka prema zapremini svežeg maltera. Cementno testo popunjava šupljine peska, pa je faktor uvek veći od 1 — vrednost unosi korisnik.",
    ratio: "Odnos vezivo : agregat (1 : n)",
    ratioHint: "Odnos po zapremini. Alatka ga ne predlaže.",
    binderDensity: "Nasipna gustina veziva",
    aggregateDensity: "Nasipna gustina agregata",
    waterCementRatio: "Vodovezivni faktor",
    aggregateMoisture: "Vlaga agregata",
    aggregateMoistureHint: "U procentima. Oduzima se od potrebne vode — nikad ispod nule.",
    mixerVolume: "Zapremina mešalice",
    mixerVolumeHint: "U litrima, za preračun na broj šarži.",

    results: "Rezultat",
    freshVolume: "Zapremina svežeg maltera",
    compactedVolume: "Zbir zapremina sastojaka",
    binderVolume: "Zapremina veziva",
    aggregateVolume: "Zapremina agregata",
    binderMass: "Masa veziva",
    aggregateMass: "Masa agregata",
    mass: "Masa gotove smeše",
    bags: "Broj vreća",
    bagSurplus: "Višak iz poslednje vreće",
    binderBags: "Broj vreća veziva",
    binderBagSurplus: "Višak iz poslednje vreće veziva",
    waterTheoretical: "Voda po vodovezivnom faktoru",
    aggregateMoistureWater: "Voda već sadržana u agregatu",
    water: "Voda za dodavanje",
    batches: "Broj šarži",
    batchBinderMass: "Vezivo po šarži",
    batchAggregateMass: "Agregat po šarži",
    batchWater: "Voda po šarži",
    consumptionUnitUsed: "Upotrebljena potrošnja",

    inputs: "Uneseno",
    formulaPremixed: "m = A·(1+rastur/100)·q·d   vreće = ceil(m / m_vreće)   voda = m·v",
    formulaOnsite:
      "V_s = V·k   V_vezivo = V_s/(1+n)   V_agregat = V_s·n/(1+n)   voda = w·m_vezivo − m_agregat·vlaga/100 (≥ 0)",

    errorWaste: "Rastur je broj od 0 do 30 %.",
    errorVolume: "Zapremina mora biti veća od nule.",
    errorArea: "Površina je broj od 0,1 do 10000 m².",
    errorThickness: "Debljina sloja je broj od 1 do 200 mm.",
    errorConsumption: "Potrošnja gotove smeše je broj od 0,5 do 3 kg/(m²·mm).",
    errorBagMass: "Masa vreće je broj od 0 do 50 kg.",
    errorWaterPerKg: "Voda po kilogramu smeše je broj od 0,05 do 0,5 l/kg.",
    errorPackingFactor: "Faktor zbijanja je broj od 1,0 do 1,6.",
    errorRatio: "Odnos n je broj od 1 do 10.",
    errorBinderDensity: "Nasipna gustina veziva je broj od 800 do 2000 kg/m³.",
    errorAggregateDensity: "Nasipna gustina agregata je broj od 1200 do 2000 kg/m³.",
    errorWaterCementRatio: "Vodovezivni faktor je broj od 0,3 do 1,0.",
    errorAggregateMoisture: "Vlaga agregata je broj od 0 do 100 %.",
    errorMixerVolume: "Zapremina mešalice mora biti veća od nule.",

    unitM2: "m²",
    unitM3: "m³",
    unitMm: "mm",
    unitKg: "kg",
    unitL: "l",
    unitKgM2mm: "kg/(m²·mm)",
  },

  "panel-cutting-yield": {
    panelWidth: "Format ploče — širina (A)",
    panelHeight: "Format ploče — visina (B)",
    pieceWidth: "Format komada — širina (a)",
    pieceHeight: "Format komada — visina (b)",
    piecesNeeded: "Potreban broj komada",
    kerf: "Širina reza",
    kerfHint: "Podatak o listu testere, u milimetrima.",
    edgeTrim: "Obrezivanje ivice ploče",
    grainMandatory: "Smer teksture obavezan",
    grainHint: "Kad je uključeno, komad se ne sme okrenuti za 90°.",
    grainYes: "Da",
    grainNo: "Ne",

    results: "Rezultat",
    piecesPerPanel: "Komada po ploči",
    panelsNeeded: "Broj ploča",
    leftoverOnLastPanel: "Neiskorišćeno na poslednjoj ploči",
    yieldPercent: "Iskorišćenje",
    wasteArea: "Otpad po ploči",
    totalWasteArea: "Ukupan otpad",
    rightStrip: "Desna traka",
    bottomStrip: "Donja traka",
    cutCount: "Broj rezova po ploči",
    cutLength: "Dužina reza po ploči",
    totalCutLength: "Ukupna dužina reza",
    guillotineNote:
      "Ovo je giljotinski raskroj jednog formata komada. Iskorišćenje se računa prema punom formatu ploče, jer se obrezivanje ivice plaća.",

    inputs: "Uneseno",
    formula:
      "A′ = A−2t   B′ = B−2t   n = floor((A′+w)/(a+w))   m = floor((B′+w)/(b+w))   N = max preko oba položaja i obe trake",

    errorPanelWidth: "Format ploče — širina je broj od 100 do 6000 mm.",
    errorPanelHeight: "Format ploče — visina je broj od 100 do 6000 mm.",
    errorPieceWidth:
      "Format komada — širina je broj od 10 do 6000 mm, ili komad ne staje u korisnu ploču ni u jednom položaju.",
    errorPieceHeight: "Format komada — visina je broj od 10 do 6000 mm.",
    errorPiecesNeeded: "Potreban broj komada je ceo broj od 1 do 100000.",
    errorKerf: "Širina reza je broj od 0 do 15 mm.",
    errorEdgeTrim: "Obrezivanje ivice je broj od 0 do 100 mm po strani, i mora ostaviti korisnu ploču.",

    unitMm: "mm",
    unitM: "m",
    unitM2: "m²",
  },

  "sheet-metal-bend": {
    thickness: "Debljina lima T",
    radius: "Unutrašnji radijus savijanja R",
    radiusHint: "Radijus koji daje alat, ne debljina lima.",
    angle: "Ugao savijanja A (skretanje pravca)",
    kFactor: "K-faktor",
    kFactorHint: "Zavisi od materijala i alata. Najpouzdanije se dobija merenjem uzorka ispod.",
    legsAs: "Način zadavanja krakova",
    legsAsOuter: "Spoljne mere",
    legsAsTangent: "Mere do tangente",
    legs: "Krakovi",
    legsHint: "Red po red, jedna mera po kraku, u milimetrima — u obliku izabranom iznad.",

    results: "Rezultat",
    bendAllowance: "Dodatak na savijanje (BA)",
    bendDeduction: "Odbitak (BD)",
    setback: "Spoljni odmak od temena (OSSB)",
    developedLength: "Razvijena dužina table",
    colBend: "Savijanje",
    colStart: "Početak linije",
    colEnd: "Kraj linije",
    colStartOpposite: "Početak od suprotne ivice",
    colEndOpposite: "Kraj od suprotne ivice",

    measuredLength: "Izmerena razvijena dužina uzorka",
    measuredLengthHint:
      "Opciono, za obrnuti račun K-faktora — uzorak isečen sa istim spoljnim krakovima kao iznad.",
    measuredLengthDisabledHint:
      "Obrnuti račun K-faktora radi samo kad su krakovi zadati kao spoljne mere.",
    reverseResults: "K-faktor iz uzorka",
    kFactorFromSample: "Izračunat K-faktor",
    radiusToThickness: "Odnos R/T",
    kFactorScopeNote:
      "Izmereni K-faktor važi samo za ovu kombinaciju alata i materijala (T, R i A iznad) — ne prenosi se na drugi posao.",

    inputs: "Uneseno",
    formula: "BA = (π/180)·A·(R+K·T)   OSSB = (R+T)·tan(A/2)   BD = 2·OSSB − BA",
    reverseFormula: "K = ((L_izmereno − Σtangentni)/n_savijanja/((π/180)·A) − R)/T",

    errorThickness: "Debljina lima je broj od 0,1 do 20 mm.",
    errorRadius: "Unutrašnji radijus je broj od 0,1 do 200 mm.",
    errorAngle: "Ugao savijanja je broj od 1 do 179°.",
    errorKFactor: "K-faktor je broj od 0 do 0,5.",
    errorLegs:
      "Krakova mora biti 2 do 50, svaki veći od nule, i svaki mora dati tangentnu dužinu veću od nule (spoljna mera mora biti veća od odmaka koji joj pripada).",
    errorMeasuredLength: "Izmerena razvijena dužina uzorka je broj od 1 do 6000 mm.",

    unitMm: "mm",
    unitDeg: "°",
  },

  "shelf-deflection": {
    span: "Raspon L (svetlo između oslonaca)",
    width: "Širina police b",
    thickness: "Debljina police h",
    udlMass: "Ravnomerno opterećenje",
    pointLoadMass: "Koncentrisana sila u sredini raspona",
    modulus: "Modul elastičnosti E",
    modulusHint: "Podatak iz deklaracije ploče. Za istu debljinu se između proizvoda razlikuje višestruko.",
    weightMode: "Sopstvena težina police",
    weightModeHint: "Polica nosi i sebe. Ako se ne unese ni gustina ni masa, sopstvena težina se ne računa.",
    weightModeNone: "Ne računa se",
    weightModeDensity: "Iz gustine ploče",
    weightModeMass: "Masa police direktno",
    shelfDensity: "Gustina ploče",
    shelfMass: "Masa police",
    limitMode: "Granica ugiba — način zadavanja",
    limitModeValue: "U milimetrima",
    limitModeRatio: "Kao L/x",
    deflectionLimit: "Sopstvena granica ugiba koju si uneo",
    deflectionLimitDivisor: "Sopstvena granica ugiba kao L/x koju si uneo",
    stressLimit: "Sopstvena granica napona koju si uneo",
    limitHint: "Iz propisa koji primenjuješ. Nexus ne zna koji je to propis i ne nudi vrednost.",

    results: "Rezultat",
    inertia: "Moment inercije I (mm⁴)",
    sectionModulus: "Otporni moment W (mm³)",
    selfWeightMass: "Masa police (iz gustine ili unesena)",
    selfWeightDeflection: "Ugib od sopstvene težine",
    distributedDeflection: "Ugib od ravnomernog opterećenja",
    pointDeflection: "Ugib od koncentrisane sile",
    totalDeflection: "Ukupan ugib",
    spanOverDeflection: "Ugib kao L/x",
    maxMoment: "Najveći moment savijanja",
    stress: "Napon",
    reaction: "Reakcija po osloncu",
    deflectionRatio: "Ugib ÷ tvoja granica",
    stressRatio: "Napon ÷ tvoja granica",
    modelNote:
      "Model je prosta greda na dva oslonca. Polica uklještena u bokove ili oslonjena po celoj dužini nije ovaj model. Prikazan ugib je trenutni — puzanje pri dugotrajnom opterećenju nije obuhvaćeno.",

    inputs: "Uneseno",
    formula:
      "q = m·g/L   δ_q = 5·q·L⁴/(384·E·I)   δ_F = F·L³/(48·E·I)   M = q·L²/8 + F·L/4   σ = M/W   R = (q·L+F)/2",

    errorSpan: "Raspon je broj od 50 do 5000 mm.",
    errorWidth: "Širina police je broj od 10 do 2000 mm.",
    errorThickness: "Debljina police je broj od 3 do 200 mm.",
    errorUdlMass: "Ravnomerno opterećenje je broj od 0 do 2000 kg.",
    errorPointLoadMass: "Koncentrisana sila je broj od 0 do 2000 kg.",
    errorModulus: "Modul elastičnosti je broj od 100 do 20000 N/mm².",
    errorShelfDensity: "Gustina ploče mora biti veća od nule.",
    errorShelfMass: "Masa police mora biti nula ili veća.",
    errorDeflectionLimitDivisor: "Delilac x (u L/x) mora biti veći od nule.",
    errorDeflectionLimit: "Granica ugiba mora biti veća od nule.",
    errorStressLimit: "Granica napona mora biti veća od nule.",

    unitMm: "mm",
    unitKg: "kg",
    unitN: "N",
    unitNmm: "N·mm",
    unitMpa: "N/mm²",
  },

  "shelf-spacing": {
    innerHeight: "Unutrašnja visina korpusa H",
    innerHeightHint: "Svetlo između donjeg i gornjeg dna, u milimetrima.",
    countMode: "Broj polica — način zadavanja",
    countModeCount: "Zadat broj",
    countModeMaxOpening: "Iz najvećeg dozvoljenog otvora",
    shelfCount: "Broj polica n",
    maxClearOpening: "Najveći dozvoljeni svetli otvor",
    maxClearOpeningHint: "Meru bira korisnik — alatka je ne predlaže.",
    thickness: "Debljina police t",
    mode: "Način rasporeda",
    modeEqualClear: "Jednaki svetli otvori",
    modeEqualAxis: "Jednaki osni razmaci",
    modeGivenFirst: "Zadata visina donjeg otvora",
    firstOpeningHeight: "Visina donjeg otvora",
    raster: "Raster otvora za police",
    rasterHint: "Podrazumevano 32 mm (sistem 32). Vrednost je polje koje se može promeniti.",
    snap: "Snap na raster bušenja",
    snapYes: "Uključeno",
    snapNo: "Isključeno",
    firstHoleFromBottom: "Prvi otvor od donje ivice",
    firstHoleFromBottomHint:
      "Razlikuje se po šabloni i okovu — nema podrazumevanu vrednost, proveri na svojoj šabloni.",

    results: "Rezultat",
    usableHeight: "Korisna visina (bez debljina polica)",
    colShelf: "Polica",
    colBottomEdge: "Donja ivica",
    colTopDistance: "Od gornje ivice",
    colHoleIndex: "Redni broj otvora",
    colSnapped: "Stvarni položaj",
    colDeviation: "Odstupanje",
    shelf: "Polica",
    bottomEdge: "donja ivica",
    snappedBottomEdge: "stvarno",
    deviation: "odstupanje",
    clearOpenings: "Svetli otvori",
    snappedClearOpenings: "Stvarni svetli otvori (posle snapa)",

    inputs: "Uneseno",
    formula:
      "U = H − n·t   s = U/(n+1)   y_i = i·s + (i−1)·t   [osni: p = H/(n+1), y_i = i·p − t/2]   snap: j = round((y−o)/R)",

    errorInnerHeight: "Unutrašnja visina je broj od 50 do 5000 mm.",
    errorThickness: "Debljina police je broj od 3 do 100 mm.",
    errorShelfCount: "Broj polica je ceo broj od 0 do 30.",
    errorMaxClearOpening: "Najveći svetli otvor mora biti veći od nule i dati broj polica u opsegu 0–30.",
    errorUsableHeight: "Police ne staju — zbir njihovih debljina je veći ili jednak unutrašnjoj visini.",
    errorFirstOpeningHeight: "Visina donjeg otvora mora biti veća od nule i manja od ukupne svetle visine.",
    errorFirstHoleFromBottom: "Prvi otvor od donje ivice je broj od 0 do 200 mm.",
    errorRaster: "Raster otvora je broj od 1 do 100 mm.",
    errorSnap:
      "Posle snapa dve police padaju na isti otvor ili van korpusa — pomeri prvi otvor ili raster.",

    unitMm: "mm",
  },

  "tap-drill-size": {
    nominalDiameter: "Nominalni prečnik D",
    nominalDiameterHint: "U milimetrima — bira se oznaka navoja, npr. M8.",
    pitch: "Korak P",
    pitchHint: "Prazno polje uzima krupni korak iz ISO 261 za uneti prečnik. Sitni korak se unosi ručno.",
    desiredEngagement: "Traženi procenat zahvata",
    desiredEngagementHint: "Radionička konvencija, nije zahtev standarda. Prazno polje znači 75 %.",
    ownDrillDiameter: "Prečnik burgije koju imate",
    ownDrillDiameterHint: "Opciono, za obrnuti račun procenta zahvata.",
    passHoleSeries: "Serija prolazne rupe",
    passHoleSeriesFine: "Fina",
    passHoleSeriesMedium: "Srednja",
    passHoleSeriesCoarse: "Gruba",
    chamferedThreads: "Broj zahodnih navoja ureznika",
    chamferedThreadsHint: "Opciono, uz dubinu navoja, za najmanju dubinu slepe rupe. Zavisi od ureznika.",
    threadDepth: "Dubina navoja (aksijalna)",

    results: "Rezultat",
    drillDiameter: "Prečnik burgije za traženi zahvat",
    coreDiameter: "Prečnik jezgra navoja D₁",
    threadDepthPerSide: "Dubina navoja po strani",
    ownDrillEngagement: "Procenat zahvata tvoje burgije",
    ownDrillThreadDepth: "Dubina navoja po strani (tvoja burgija)",
    passHoleDiameter: "Prečnik prolazne rupe",
    minBlindHoleDepth: "Najmanja dubina slepe rupe",
    pitchUsed: "Upotrebljen korak",
    engagementUsed: "Upotrebljen procenat zahvata",
    pitchSourceCoarseAuto: "krupni, ISO 261",
    pitchSourceCoarseEntered: "krupni, unet ručno",
    pitchSourceFine: "sitni, ISO 261",
    pitchSourceCustom: "unet ručno, van tabele",

    inputs: "Uneseno",
    formula:
      "D₁ = D − 1.082532·P   d = D − (h/100)·1.299038·P   h(d) = 100·(D−d)/(1.299038·P)   dubina/strana = (D−d)/2",

    errorNominalDiameter: "Nominalni prečnik je broj od 1,6 do 30 mm.",
    errorPitch:
      "Korak je broj od 0,2 do 3,5 mm; ako je polje prazno a prečnik nema krupni korak u tabeli, korak se mora uneti.",
    errorDesiredEngagement: "Traženi procenat zahvata je broj od 50 do 100.",
    errorOwnDrillDiameter:
      "Prečnik burgije je broj od 0,5 do 30 mm i mora biti manji od nominalnog prečnika.",
    errorChamferedThreads: "Broj zahodnih navoja mora biti veći od nule — unosi se zajedno sa dubinom navoja.",
    errorThreadDepth: "Dubina navoja mora biti veća od nule — unosi se zajedno sa brojem zahodnih navoja.",

    unitMm: "mm",
  },

  "timber-volume": {
    mode: "Način obračuna",
    modeHuber: "Huberova formula (srednji prečnik)",
    modeSmalian: "Smalianova formula (dva čeona prečnika)",
    modeHuberSmalian: "Huber i Smalian uporedo",
    modeSawn: "Rezana građa — iz broja komada",
    modeSawnFromVolume: "Rezana građa — iz tražene zapremine",
    modeStackedToSolid: "Prostorni metar → puna zapremina",
    modeSolidToStacked: "Puna zapremina → prostorni metar",

    meanDiameter: "Srednji prečnik trupca",
    meanDiameterHint: "Meri se na sredini dužine trupca, bez kore ako je uneta debljina kore.",
    d1: "Prečnik na debljem čelu (d1)",
    d2: "Prečnik na tanjem čelu (d2)",
    length: "Dužina trupca",
    logCount: "Broj trupaca",
    barkThickness: "Debljina kore",

    sawnThickness: "Debljina daske",
    sawnWidth: "Širina daske",
    pieceLength: "Dužina komada",
    pieces: "Broj komada",
    targetVolume: "Tražena zapremina",
    section: "Presek",
    sectionRough: "grubo rezan",
    sectionPlaned: "blanjan",

    stackedVolume: "Prostorna (naslagana) zapremina",
    solidVolume: "Puna (čvrsta) zapremina",
    packingCoefficient: "Koeficijent punoće slaganja",
    packingCoefficientHint: "Odnos pune zapremine drveta prema prostornoj — broj između 0 i 1.",

    density: "Gustina drveta",
    densityHint: "Za masu; ako je prazno, masa se ne prikazuje.",

    results: "Rezultat",
    huberVolume: "Zapremina po Huberu",
    smalianVolume: "Zapremina po Smalianu",
    volumeDifference: "Razlika Huber − Smalian",
    taper: "Konicitet",
    totalLogVolume: "Ukupna zapremina trupaca",
    totalLogVolumeHuber: "Ukupna zapremina trupaca (Huber)",
    totalLogVolumeSmalian: "Ukupna zapremina trupaca (Smalian)",
    pieceVolume: "Zapremina jednog komada",
    pieceCount: "Broj komada",
    totalVolume: "Ukupna zapremina",
    surfaceArea: "Površina",
    mass: "Masa",
    massHuber: "Masa (Huber)",
    massSmalian: "Masa (Smalian)",

    inputs: "Uneseno",
    formula:
      "Huber: V = L·π·(Dsr/2)²   Smalian: V = L·π·((d1²+d2²)/2)/4   rezana: V = t·š·L·broj komada   prm → puna: V = prm·koeficijent",

    errorBarkThickness: "Debljina kore je broj, manji od srednjeg prečnika.",
    errorDensity: "Gustina je broj veći od nule.",
    errorLength: "Dužina trupca je broj veći od nule.",
    errorLogCount: "Broj trupaca je ceo broj veći od nule.",
    errorMeanDiameter: "Srednji prečnik je broj veći od nule.",
    errorD1: "Prečnik d1 je broj veći od nule.",
    errorD2: "Prečnik d2 je broj veći od nule.",
    errorSawnThickness: "Debljina daske je broj veći od nule.",
    errorSawnWidth: "Širina daske je broj veći od nule.",
    errorPieceLength: "Dužina komada je broj veći od nule.",
    errorPieces: "Broj komada je ceo broj veći od nule.",
    errorTargetVolume: "Tražena zapremina je broj veći od nule.",
    errorStackedVolume: "Prostorna zapremina je broj veći od nule.",
    errorPackingCoefficient: "Koeficijent punoće slaganja je broj između 0 i 1.",
    errorSolidVolume: "Puna zapremina je broj veći od nule.",

    unitM3: "m³",
    unitM2: "m²",
    unitKg: "kg",
    unitCmM: "cm/m",
  },

  "wallpaper-rolls": {
    walls: "Zidovi (širina;otvor pune visine — po jedan zid u redu)",
    wallsHint:
      "Jedan zid po redu, širina i tačkom-zarezom odvojena širina otvora pune visine (vrata) koja se odbija; bez otvora unesi 0.",
    height: "Visina lepljenja",
    rollWidth: "Širina rolne",
    rollLength: "Dužina rolne",
    repeat: "Vertikalni raport šare",
    repeatHint: "0 za tapetu bez šare.",
    matching: "Vrsta slaganja",
    matchingStraight: "pravi raport",
    matchingHalfDrop: "polupomereni raport",
    allowance: "Rezerva po traci",
    allowanceHint: "Gore i dole zajedno.",
    reserveStrips: "Rezervne trake",
    reserveStripsHint: "Dodatne trake preko izračunatih, za kalo i greške u sečenju.",
    spareStripHeight: "Visina komada iznad otvora",
    spareStripHeightHint: "Za procenu koliko takvih komada izlazi iz ostataka rolni.",

    results: "Rezultat",
    stripCount: "Broj traka",
    stripLength: "Dužina jedne trake",
    stripsPerRollCheck: "Traka po rolni (kontrola, zatvoreni oblik)",
    rollCount: "Broj rolni",
    totalPatternWaste: "Ukupno na uklapanje šare",
    sparePiecesFromRemnants: "Komada iznad otvora iz ostataka rolni",
    colRoll: "Rolna",
    colStripsOnRoll: "Traka na rolni",
    colRemainder: "Ostatak",
    colPatternWaste: "Na uklapanje šare",

    inputs: "Uneseno",
    formula:
      "n po zidu = ⌈(širina − otvori pune visine)/širina rolne⌉ + rezervne trake; svaka traka seče se sekvencijalno sa tekuće rolne, u fazi šare koju traži raspored",

    errorWalls: "Unesi bar jedan zid, širinu i po potrebi otvor pune visine.",
    errorHeight: "Visina lepljenja je broj od 0,5 do 10 m.",
    errorRollWidth: "Širina rolne je broj od 0,3 do 1,6 m.",
    errorRollLength: "Dužina rolne je broj od 1 do 100 m.",
    errorRepeat: "Raport je broj od 0 do 1,5 m.",
    errorAllowance: "Rezerva po traci je broj od 0 do 0,5 m.",
    errorReserveStrips: "Rezervne trake su ceo broj od 0 do 20.",
    errorSpareStripHeight: "Visina komada iznad otvora je broj veći od nule.",

    unitM: "m",
  },

  "weld-consumable": {
    seamType: "Vrsta šava",
    seamTypeFillet: "ugaoni",
    seamTypeButtV: "sučeoni, V žleb",
    seamTypeButtX: "sučeoni, X žleb",

    filletMode: "Mera ugaonog šava",
    filletModeLeg: "katet",
    filletModeThroat: "debljina šava (grlo)",
    leg: "Katet ugaonog šava z",
    throat: "Debljina šava a",

    plateThickness: "Debljina lima t",
    grooveAngle: "Ugao žleba α",
    rootGap: "Otvor korena b",
    rootFaceHeight: "Visina korenskog nosa c",
    rootFaceHeightHint: "Mora biti manja od debljine lima.",

    reinforcement: "Nadvišenje šava",
    reinforcementHint: "Kao procenat preseka.",
    weldLength: "Dužina šava",
    seamCount: "Broj istih šavova",
    density: "Gustina metala",
    densityHint: "Podrazumevano 7850 kg/m³ za nelegirani čelik; za aluminijum unosi korisnik.",
    efficiency: "Iskorišćenje dodatnog materijala",
    efficiencyHint: "Podatak proizvođača za postupak i prečnik — deo istopljenog materijala koji ostane u šavu.",
    waste: "Rastur",

    wireDiameter: "Prečnik žice",
    wireDiameterHint: "Za dužinu žice; ostavi prazno ako se potrošnja ne izražava u metrima žice.",
    electrodeMass: "Masa jedne elektrode",
    electrodeMassHint: "Sa iskoristivim delom, za broj elektroda.",
    electrodeUsableFraction: "Iskoristivi deo elektrode",
    spoolMass: "Masa koluta žice",
    spoolMassHint: "Za broj kolutova — žica se poručuje po kolutu, ne po metru.",

    results: "Rezultat",
    legUsed: "Upotrebljen katet",
    crossSectionArea: "Površina preseka šava (sa nadvišenjem)",
    weldMassPerMetre: "Masa navara po dužnom metru",
    weldVolume: "Zapremina navara",
    weldMass: "Masa navara",
    consumableMass: "Masa dodatnog materijala",
    wireLength: "Dužina žice",
    electrodeCount: "Broj elektroda",
    spoolCount: "Broj kolutova žice",

    inputs: "Uneseno",
    formula:
      "ugaoni: A = z²/2   V žleb: A = b·t + (t−c)²·tan(α/2)   X žleb: A = b·t + 2·((t−c)/2)²·tan(α/2)   m_navar = V·ρ   m_dodatni = m_navar/η·(1+rastur)",

    errorReinforcement: "Nadvišenje šava je broj od 0 do 30 %.",
    errorWeldLength: "Dužina šava je broj od 0,01 do 10000 m.",
    errorSeamCount: "Broj istih šavova je ceo broj od 1 do 10000.",
    errorDensity: "Gustina metala je broj od 2000 do 9000 kg/m³.",
    errorEfficiency: "Iskorišćenje dodatnog materijala je broj od 0,3 do 1.",
    errorWaste: "Rastur je broj od 0 do 20 %.",
    errorThroat: "Debljina šava a je broj veći od nule.",
    errorLeg: "Katet ugaonog šava je broj od 2 do 30 mm.",
    errorPlateThickness: "Debljina lima je broj od 1 do 100 mm.",
    errorGrooveAngle: "Ugao žleba je broj od 30 do 90 stepeni.",
    errorRootGap: "Otvor korena je broj od 0 do 10 mm.",
    errorRootFaceHeight:
      "Visina korenskog nosa je broj od 0 do 10 mm i mora biti manja od debljine lima.",
    errorWireDiameter: "Prečnik žice je broj od 0,6 do 2,4 mm.",
    errorElectrodeMass: "Masa elektrode je broj od 10 do 500 g — unosi se zajedno sa iskoristivim delom.",
    errorElectrodeUsableFraction:
      "Iskoristivi deo elektrode je broj od 50 do 95 % — unosi se zajedno sa masom elektrode.",
    errorSpoolMass: "Masa koluta žice je broj veći od nule.",

    unitMm: "mm",
    unitMm2: "mm²",
    unitCm3: "cm³",
    unitKg: "kg",
    unitKgM: "kg/m",
    unitM: "m",
  },

  "wood-moisture-movement": {
    initialDimension: "Polazna dimenzija D₀",
    initialMoisture: "Polazna vlažnost drveta",
    initialMoistureHint: "Izmerena vlagomerom, procenat vlage drveta — ne vlažnost vazduha.",
    finalMoisture: "Krajnja vlažnost drveta",
    grainDirection: "Pravac vlakana",
    grainRadial: "radijalno",
    grainTangential: "tangencijalno",
    grainLongitudinal: "uzdužno",

    shrinkageMode: "Način unosa koeficijenta",
    shrinkageModeCoefficient: "koeficijent skupljanja direktno",
    shrinkageModeTotalShrinkage: "ukupno skupljanje sirovo → apsolutno suvo",
    shrinkageCoefficient: "Koeficijent skupljanja c",
    shrinkageCoefficientHint:
      "Procenat promene dimenzije po 1 % vlažnosti, za tu vrstu i taj pravac — radijalno i tangencijalno se razlikuju i do dva puta.",
    totalShrinkage: "Ukupno skupljanje S (sirovo → apsolutno suvo)",
    totalShrinkageHint: "Koeficijent se izvodi kao S / tačka zasićenja vlakana, uz linearnu pretpostavku.",

    fiberSaturationPoint: "Tačka zasićenja vlakana",
    fiberSaturationPointHint: "Iznad ove vlažnosti dimenzija se dalje ne menja. Podrazumevano 30 %.",

    elementWidth: "Širina elementa za zazor W",
    installMoisture: "Vlažnost drveta pri ugradnji",
    installMoistureHint: "Procenat vlage drveta, ne vlažnost vazduha.",
    roomMoistureMin: "Očekivana vlažnost prostorije, minimum",
    roomMoistureHint: "Procenat vlage drveta u ravnoteži sa prostorijom, ne relativna vlažnost vazduha.",
    roomMoistureMax: "Očekivana vlažnost prostorije, maksimum",

    results: "Rezultat",
    clampedInitialMoisture: "Polazna vlažnost (ograničena na TZV)",
    clampedFinalMoisture: "Krajnja vlažnost (ograničena na TZV)",
    dimensionChange: "Promena dimenzije",
    finalDimension: "Krajnja dimenzija",
    derivedCoefficient: "Izveden koeficijent skupljanja",
    swellToMax: "Hod bubrenja do maksimuma",
    shrinkToMin: "Hod skupljanja do minimuma",
    totalSwing: "Ukupan hod",

    inputs: "Uneseno",
    formula:
      "MC* = min(MC, TZV)   ΔD = D₀·(c/100)·(MC*₁−MC*₀)   ΔW⁺ = W·(c/100)·(MC*max−MC*ugradnja)   ΔW⁻ = W·(c/100)·(MC*ugradnja−MC*min)",

    errorInitialDimension: "Polazna dimenzija je broj od 1 do 5000 mm.",
    errorInitialMoisture: "Polazna vlažnost je broj od 0 do 40 %.",
    errorFinalMoisture: "Krajnja vlažnost je broj od 0 do 40 %.",
    errorFiberSaturationPoint: "Tačka zasićenja vlakana je broj od 25 do 35 %.",
    errorShrinkageCoefficient:
      "Koeficijent skupljanja je broj od 0,01 do 0,6 — unosi se ili on ili ukupno skupljanje, ne oba.",
    errorTotalShrinkage: "Ukupno skupljanje je broj od 1 do 20 %.",
    errorElementWidth: "Širina elementa je broj veći od nule.",
    errorInstallMoisture: "Vlažnost pri ugradnji je broj od 3 do 25 %.",
    errorRoomMoistureMin: "Minimalna vlažnost prostorije je broj od 3 do 25 %.",
    errorRoomMoistureMax: "Maksimalna vlažnost prostorije je broj od 3 do 25 %.",

    unitMm: "mm",
    unitPercentPerPercent: "%/%",
  },
} as const;
