/**
 * „Inženjering i elektrotehnika" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. The tool's NAME and its one-line blurb are not here: those
 * live in the `name` and `blurb` tables of `./pro.ts`.
 *
 * **Almost everything in this pack is `life-safety`.** A conductor, a
 * fastener, a pressure vessel, a belt guard — a wrong number here is not a
 * cosmetic bug. So this file never writes a verdict word: no „zadovoljava",
 * „bezbedno", „ispravno", „u skladu", „dozvoljeno". Where a limit appears it
 * is always „tvoja granica" — whose it is, said in the label — and the number
 * beside it is left to speak for itself. The possessive, never „koju si uneo":
 * that participle agrees with the addressee's gender.
 */
export const PRO_INZENJERING_EN = {
  "awg-to-mm2": {
    direction: "Direction",
    directionToMetric: "AWG → metric",
    directionToAwg: "Metric → AWG",
    material: "Material",
    materialHint: "Affects only the Ω/km row — the geometry does not depend on the material.",
    materialCopper: "copper",
    materialAluminium: "aluminium",
    gauge: "AWG number n",
    gaugeHint: "A whole number 40 to 0000, where 00 = −1, 000 = −2, 0000 = −3.",
    known: "Known",
    knownDiameter: "diameter",
    knownArea: "cross-section",
    value: "Value",
    diameterMm: "Diameter",
    diameterIn: "Diameter in inches",
    areaMm2: "Cross-section",
    resistance: "Resistance of a solid conductor at 20 °C",
    resistanceNote:
      "This is the resistance of a SOLID conductor of exactly that geometry. Stranded cable of the same AWG is about 2% higher, and the real value for stranded cable comes from the manufacturer's label.",
    tableNote:
      "This is the defining formula of the AWG series, computed directly. Published tables are the same formula rounded to four decimals of an inch, so the last digit sometimes differs — the formula is more precise than the rounded table, not an error.",
    fractionalGauge: "Fractional AWG number",
    nearestGauge: "Nearest whole AWG number",
    nearestDiameter: "Diameter of the nearest whole number",
    nearestArea: "Cross-section of the nearest whole number",
    // „4/0" and not „#0000" — the same gauge in the other standard notation.
    // Four zeroes behind a hash is also a four-digit hex colour, so `check:colours`
    // reads it as a raw literal; this is the second time the collision has come up.
    outsideSeriesNote: "The nearest whole AWG number falls outside the range 40 … 4/0, so it is not shown.",
    results: "Result",
    formula:
      "d(n) = 0.127 · 92^((36−n)/39) mm     S = πd²/4     R/km = 1000·ρ₂₀/S     (reverse: n = 36 − 39·ln(d/0.127)/ln 92)",
    inputs: "Entered",
    errorGauge: "The AWG number is a whole number from 40 to 0000 (enter 00, 000 and 0000 as −1, −2, −3).",
    errorDiameter: "The diameter must be between 0 and 20 mm.",
    errorArea: "The cross-section must be between 0 and 300 mm².",
    errorKnown: "Enter exactly one of the two — diameter or cross-section.",
    unitMm: "mm",
    unitIn: "in",
    unitMm2: "mm²",
    unitOhmKm: "Ω/km",
  },

  "battery-bank-runtime": {
    cellCapacity: "Cell or battery capacity",
    cellCapacityHint: "The capacity of ONE cell, before multiplying by the parallel count.",
    cellVoltage: "Nominal cell or battery voltage",
    series: "Number in series",
    seriesHint: "An empty field means 1.",
    parallel: "Number in parallel",
    parallelHint: "An empty field means 1.",
    depthOfDischarge: "Allowed depth of discharge",
    depthOfDischargeHint:
      "A datum about the cell chemistry and the manufacturer's guarantee — Neagle does not guess it. Without it there is no result.",
    loadKind: "Load kind",
    loadPower: "power [W]",
    loadCurrent: "current [A]",
    load: "Load",
    efficiency: "Inverter efficiency",
    efficiencyHint:
      "An empty field means 100% — until you say an inverter exists, no loss is assumed.",
    efficiencyNote:
      "The efficiency enters the calculation only when the load is entered in watts — a current measured at the battery terminals already includes it, so it is not applied a second time there.",
    peukert: "Peukert exponent k",
    peukertHint:
      "From 1 to 2. An empty field means 1, which is without correction — a neutral value, not an assumption about the cell.",
    peukertNote:
      "Peukert's correction is applied to a full discharge, and the depth of discharge is then applied to that time linearly — that is the usual convention, not a consequence of Peukert's law itself.",
    ratedHours: "Nominal discharge regime H",
    ratedHoursHint: "The number of hours the entered capacity refers to. Required only when k > 1.",
    results: "Result",
    packVoltage: "Pack voltage",
    packCapacity: "Pack capacity",
    energy: "Energy",
    usableEnergy: "Usable energy",
    packCurrent: "Current from the pack",
    hours: "Runtime",
    hoursWithoutPeukert: "Runtime without Peukert's correction",
    modelNote:
      "The model is a constant load at nominal temperature, without cell ageing and without voltage sag.",
    formula:
      "U = s·U_cell     C = p·C_cell     E = U·C     E_usable = E·DoD·η     t = E_usable/P  or  t = C·DoD/I",
    inputs: "Entered",
    errorCapacity: "The capacity must be greater than zero.",
    errorVoltage: "The cell voltage must be greater than zero.",
    errorSeries: "The number in series is a whole number from 1 to 1000.",
    errorParallel: "The number in parallel is a whole number from 1 to 1000.",
    errorDepthOfDischarge: "The depth of discharge must be between 0 and 100%.",
    errorEfficiency: "The efficiency must be between 0 and 100%.",
    errorPeukert: "The Peukert exponent is between 1 and 2.",
    errorLoad: "The load must be greater than zero.",
    errorRatedHours:
      "The nominal discharge regime is required when k > 1, and must be between 0 and 100 h.",
    unitV: "V",
    unitAh: "Ah",
    unitWh: "Wh",
    unitA: "A",
    unitH: "h",
  },

  "belt-and-gear-drive": {
    regime: "Mode",
    regimeBelt: "belt drive",
    regimeGear: "gear pair",
    drivingDiameter: "Driving pulley diameter",
    drivenDiameter: "Driven pulley diameter",
    pitchDiameterHint: "The pitch (reference) diameter, not the outside diameter measured with callipers.",
    drivingSpeed: "Driving speed",
    centreDistance: "Centre distance",
    drivingTorque: "Torque on the driving pulley",
    efficiency: "Drive efficiency",
    efficiencyHint: "An empty field means 100% — a neutral value until the loss is known.",
    errorDrivingDiameter: "The driving pulley diameter must be between 0 and 10000 mm.",
    errorDrivenDiameter: "The driven pulley diameter must be between 0 and 10000 mm.",
    errorSpeed: "The speed must be in the range 0 to 1 000 000 min⁻¹.",
    errorCentreDistance:
      "The centre distance must be greater than zero and large enough that the small pulleys do not collide.",
    errorEfficiency: "The efficiency must be between 0 and 100%.",
    errorTorque: "The torque must be in the range 0 to 1e9 N·m.",
    errorDrivingTeeth: "The number of teeth on the driving gear is a whole number from 1 to 10000.",
    errorDrivenTeeth: "The number of teeth on the driven gear is a whole number from 1 to 10000.",
    errorModule: "The module must be between 0 and 100 mm.",
    results: "Result",
    ratio: "Gear ratio i",
    drivenSpeed: "Driven speed",
    beltSpeed: "Belt speed",
    beltLength: "Length of an open belt",
    wrapSmall: "Wrap angle of the small pulley",
    wrapLarge: "Wrap angle of the large pulley",
    drivenTorque: "Torque on the driven pulley",
    beltPitchNote:
      "The diameters in this calculation are pitch (reference) diameters. For a V-belt these are not the outside diameters you measure with callipers.",
    beltFormula: "i = d₂/d₁     v = πd₁n₁/60000     L = √(4C²−(D−d)²) + (D/2)(π+2γ) + (d/2)(π−2γ)",
    inputs: "Entered",
    drivingTeeth: "Number of teeth on the driving gear",
    drivenTeeth: "Number of teeth on the driven gear",
    module: "Module m",
    moduleHint: "Without the module there are no pitch diameters or centre distance.",
    drivingPitchDiameter: "Pitch diameter of the driving gear",
    drivenPitchDiameter: "Pitch diameter of the driven gear",
    gearCentreDistance: "Centre distance",
    gearCentreDistanceNote:
      "The centre distance a = m·(z₁+z₂)/2 holds only for a standard EXTERNAL pair of cylindrical gears without profile shift. For an internal pair or a shifted profile this formula does not hold.",
    gearFormula: "i = z₂/z₁     d = m·z     a = m·(z₁+z₂)/2",
    unitRpm: "min⁻¹",
    unitMs: "m/s",
    unitMm: "mm",
    unitDeg: "°",
    unitNm: "N·m",
  },

  "cable-cross-section": {
    system: "System",
    material: "Material",
    materialCopper: "copper",
    materialAluminium: "aluminium",
    length: "Route length L",
    lengthHint:
      "The length in ONE direction. The factor k already includes the return conductor — do not double it here.",
    current: "Current I",
    voltage: "Nominal voltage U",
    voltageHint:
      "In a three-phase system this is the LINE voltage of a balanced load. A single-phase load from a three-phase board is calculated in the single-phase system, at the phase voltage.",
    permittedDrop: "Allowed voltage drop ΔU_allowed",
    permittedDropHint:
      "From the regulation you apply. Neagle does not know which regulation that is and offers no value.",
    temperature: "Conductor temperature θ",
    temperatureHint:
      "The temperature of the CONDUCTOR under load, not the ambient. An empty field means 20 °C, the reference temperature at which the resistance is defined — it gives the smallest possible result.",
    temperatureNote:
      "At 70 °C the resistance of copper is 1.1965 times that at 20 °C, and the required cross-section grows by the same factor.",
    chosenArea: "Your chosen cross-section",
    chosenAreaHint: "Optional — for the row about the voltage drop at that cross-section.",
    errorLength: "The route length must be between 0 and 100000 m.",
    errorCurrent: "The current must be between 0 and 100000 A.",
    errorVoltage: "The voltage must be greater than zero.",
    errorPermittedDrop: "The allowed voltage drop must be between 0 and 100%.",
    errorTemperature: "The conductor temperature is outside the range −60 … 250 °C.",
    errorChosenArea: "The chosen cross-section must be between 0 and 5000 mm².",
    resistivity: "Resistivity used ρ(θ)",
    loopFactor: "Factor used k",
    maxDrop: "Allowed drop ΔU_max",
    minimumArea: "Required cross-section S_min",
    roundUpNote:
      "S_min is the smallest cross-section that keeps the drop within the limit. When choosing a real cable this number is rounded UP to the nearest standard cross-section, never down.",
    dropAtChosenPct: "Drop at the chosen cross-section",
    dropAtChosenV: "Drop at the chosen cross-section, in volts",
    dropRatio: "Drop ÷ your limit",
    reactanceNote:
      "The model is purely resistive (X = 0, cos φ = 1). At large cross-sections the inductive reactance becomes comparable to the resistance, so the real drop is LARGER than calculated and S_min may be smaller than needed.",
    lengthNote:
      "S_min is the cross-section PER CONDUCTOR. The calculation knows no parallel conductors per phase.",
    systemNote:
      "The same route entered as three-phase instead of single-phase gives a different cross-section — a single-phase load from a three-phase board needs a single-phase branch.",
    formula:
      "S_min = k·ρ(θ)·L·I/ΔU_max     ρ(θ) = ρ₂₀·(1+α₂₀·(θ−20))     k = 2 (DC/single-phase) or √3 (three-phase)",
    results: "Result",
    inputs: "Entered",
    unitOhmMmM: "Ω·mm²/m",
    unitV: "V",
    unitMm2: "mm²",
    unitM: "m",
    unitA: "A",
    unitDeg: "°C",
  },

  "induction-motor-rating": {
    system: "System",
    shaftPower: "Shaft power P",
    shaftPowerHint: "From the nameplate.",
    voltageSingle: "Supply voltage U",
    voltageThree: "Line voltage U",
    powerFactor: "Power factor cos φ",
    plateHint: "From the nameplate — Neagle does not guess it from the IE class or anything else.",
    efficiency: "Efficiency η",
    poles: "Number of poles",
    polesHint: "An even whole number, at least 2.",
    frequency: "Frequency f",
    measuredSpeed: "Measured speed n",
    measuredSpeedHint:
      "Optional — without it there is no slip, and the torque is calculated at synchronous speed.",
    errorPower: "Power must be greater than zero.",
    errorVoltage: "The voltage must be greater than zero.",
    errorPowerFactor: "The power factor must be between 0 and 1.",
    errorEfficiency: "The efficiency must be between 0 and 100%.",
    errorPoles: "The number of poles is an even whole number, at least 2.",
    errorFrequency: "The frequency must be greater than zero.",
    errorSpeed: "The measured speed must be greater than zero.",
    results: "Result",
    current: "Rated current I",
    inputPower: "Input power P₁",
    synchronousSpeed: "Synchronous speed n_s",
    slip: "Slip s",
    generating: "generating",
    torque: "Torque M",
    atSynchronous: "at synchronous speed",
    atMeasured: "at the measured speed",
    currentNote:
      "The current is the motor's INPUT current — the efficiency is inside it, because the nameplate power is shaft power and a motor draws more than that from the grid.",
    formula: "I = 1000P/(√3·U·cos φ·η)     n_s = 120f/p     s = (n_s−n)/n_s     M = 30000P/(πn)",
    inputs: "Entered",
    unitA: "A",
    unitKw: "kW",
    unitRpm: "min⁻¹",
    unitNm: "N·m",
    unitV: "V",
    unitHz: "Hz",
  },

  "junction-temperature": {
    regime: "Direction",
    regimeJunction: "junction temperature",
    regimeSink: "required heatsink Rth",
    regimePower: "allowable power",
    ambient: "Ambient temperature T_a",
    junctionToCase: "Rth junction-to-case",
    junctionToCaseHint: "From the datasheet.",
    caseToSink: "Rth case-to-heatsink",
    caseToSinkHint: "A datum about the mounting, paste and washer.",
    sinkToAmbient: "Rth heatsink-to-ambient",
    sinkToAmbientHint:
      "Required in the forward direction; in the reverse directions it is what is being found or checked.",
    dissipation: "Dissipated power P",
    maxJunction: "Maximum junction temperature T_j_max",
    maxJunctionHint: "From the datasheet.",
    errorDissipation: "Power must be greater than zero.",
    errorAmbient: "The ambient temperature is outside the range −60 … 200 °C.",
    errorJunctionToCase: "Rth junction-to-case must be between 0 and 1000 K/W.",
    errorCaseToSink: "Rth case-to-heatsink must be between 0 and 1000 K/W.",
    errorSinkToAmbient: "Rth heatsink-to-ambient must be between 0 and 1000 K/W.",
    errorMaxJunction: "The maximum junction temperature is outside the range 0 … 400 °C.",
    errorAmbientAtOrAboveLimit:
      "The ambient temperature is already at or above the maximum junction temperature.",
    errorChainOverBudget:
      "The sum of the existing resistances (junction-to-case, case-to-heatsink) by itself exceeds the available temperature budget — no heatsink of that mounting can make up for it.",
    results: "Result",
    totalRth: "Total Rth",
    junctionTemp: "Junction temperature T_j",
    caseTemp: "Case temperature",
    sinkTemp: "Heatsink temperature",
    modelNote:
      "A static one-dimensional model: steady state, one heat path, without coupling to neighbouring parts and without transients.",
    formula:
      "T_j = T_a + P·ΣRth     T_case = T_j − P·Rth(j-c)     T_heatsink = T_j − P·(Rth(j-c)+Rth(c-h))",
    sinkFormula: "Rth(h-a) = (T_j_max−T_a)/P − Rth(j-c) − Rth(c-h)",
    powerFormula: "P_max = (T_j_max−T_a)/ΣRth",
    inputs: "Entered",
    availableRise: "Available temperature budget",
    requiredSink: "Required Rth(h-a)",
    maxDissipation: "Allowable power P_max",
    unitKW: "K/W",
    unitDeg: "°C",
    unitW: "W",
  },

  "metric-thread-strength": {
    nominalDiameter: "Nominal diameter d",
    pitch: "Thread pitch P",
    pitchHint: "Coarse or fine pitch — the user chooses, no pitch table is needed.",
    strength: "Yield strength or tensile strength R",
    strengthHint:
      "The strength-class value of the fastener as bought (e.g. 8.8 → R_p0.2 = 640 MPa). Neagle does not choose the class.",
    drill: "Drill diameter",
    drillHint:
      "For the row about the percentage of thread engagement. It must be between the minor diameter D₁ and the nominal d.",
    errorDiameter: "The nominal diameter must be between 0 and 200 mm.",
    errorPitch: "The pitch must be greater than zero and less than the diameter divided by 1.226869.",
    errorStrength: "The strength must be between 0 and 3000 MPa.",
    errorDrill:
      "The drill diameter must be between the nut's minor diameter D₁ and the nominal diameter d.",
    results: "Result",
    fundamentalHeight: "Height of the fundamental triangle H",
    pitchDiameter: "Pitch diameter d₂",
    minorDiameterBolt: "Bolt core diameter d₃",
    minorDiameterNut: "Nut minor diameter D₁",
    stressArea: "Stress area A_s",
    force: "Force F = A_s·R",
    forceNote:
      "This is the force at which the stress in area A_s reaches the entered strength — not the allowable load of the joint. Without preload, friction, eccentricity, engagement length, fatigue and the number of bolts.",
    engagement: "Percentage of engagement (relative to H₁ = 5/8·H)",
    engagementNote:
      "ISO 898-1 convention: 100% means the full internal-thread form relative to H₁ = (5/8)H.",
    engagementWorkshop: "Percentage of engagement (workshop convention)",
    engagementWorkshopNote:
      "Older convention from a workshop table, measured against a different reference depth. For the same drill diameter it gives a different number from the row above — both are correct in their own system.",
    formula:
      "H = P·√3/2     d₂ = d−(3/4)H     d₃ = d−(17/12)H     D₁ = d−(5/4)H     A_s = (π/4)((d₂+d₃)/2)²",
    inputs: "Entered",
    unitMm: "mm",
    unitMm2: "mm²",
    unitKn: "kN",
    unitMpa: "MPa",
  },

  "ohms-law-power": {
    voltage: "Voltage U",
    current: "Current I",
    resistance: "Resistance R",
    power: "Power P",
    pairHint: "Enter exactly two of the four quantities — the other two are calculated.",
    errorPair: "Enter exactly two of the four quantities.",
    errorVoltage: "The voltage must be in the range 0 to 1e9 V.",
    errorCurrent: "The current must be in the range 0 to 1e6 A, and may not be zero with a voltage entered.",
    errorResistance:
      "The resistance must be in the range 0 to 1e12 Ω, and may not be zero with a voltage or power entered.",
    errorPower: "The power must be in the range 0 to 1e9 W, and may not be zero with a voltage entered.",
    results: "Result",
    entered: "entered",
    computed: "calculated",
    formula: "U = IR     P = UI     (from any two quantities)",
    inputs: "Entered",
    unitV: "V",
    unitA: "A",
    unitOhm: "Ω",
    unitW: "W",
  },

  "pipe-flow-velocity": {
    innerDiameter: "Internal diameter D",
    innerDiameterHint: "Nothing in this calculation holds for a non-circular duct.",
    known: "Known",
    knownFlow: "flow Q",
    knownVelocity: "velocity v",
    flow: "Flow Q",
    flowUnit: "Flow unit",
    velocity: "Velocity v",
    velocityNote: "The mean velocity over the whole cross-section — not a local or axial value.",
    viscosity: "Kinematic viscosity ν",
    viscosityHint:
      "A property of the fluid at the temperature you actually have — without it there is no Reynolds number.",
    density: "Density ρ",
    densityHint: "Without it there is no mass flow.",
    errorDiameter: "The diameter must be between 0 and 10000 mm.",
    errorFlow: "The flow may not be negative.",
    errorVelocity: "The velocity may not be negative.",
    errorViscosity: "The viscosity must be between 0 and 1e6 mm²/s.",
    errorDensity: "The density must be between 0 and 25000 kg/m³.",
    errorKnown: "Enter exactly one of the two — flow or velocity.",
    results: "Result",
    areaMm2: "Cross-sectional area",
    flowLs: "Data rate",
    flowLmin: "Flow in l/min",
    flowM3h: "Flow in m³/h",
    flowM3s: "Flow in m³/s",
    reynolds: "Reynolds number Re",
    reynoldsHint: "Without the viscosity entered the Reynolds number is not shown.",
    massFlowKgS: "Mass flow",
    massFlowKgH: "Mass flow in kg/h",
    roundDuctNote:
      "The diameter is the INTERNAL diameter of a circular pipe — nothing here holds for a non-circular duct.",
    formula: "A = πD²/4     v = Q/A     Re = vD/ν     ṁ = ρQ",
    inputs: "Entered",
    unitMm: "mm",
    unitMm2: "mm²",
    unitM2: "m²",
    unitMs: "m/s",
    unitLs: "l/s",
    unitLmin: "l/min",
    unitM3h: "m³/h",
    unitM3s: "m³/s",
    unitKgS: "kg/s",
    unitKgH: "kg/h",
  },

  "power-factor-correction": {
    activePower: "Active power P",
    presentPowerFactor: "Existing power factor cos φ₁",
    targetPowerFactor: "Target power factor cos φ₂",
    lineVoltage: "Line voltage U",
    frequency: "Mains frequency f",
    system: "System",
    connection: "Battery connection",
    connectionHint:
      "A star-connected battery needs THREE TIMES the capacitance of a delta-connected one for the same Qc.",
    connectionDelta: "delta",
    connectionStar: "star",
    errorPower: "The active power must be greater than zero.",
    errorPresentPowerFactor: "The existing power factor must be between 0 and 1.",
    errorTargetPowerFactor:
      "The target power factor must be between 0 and 1 and may not be less than the existing one — that would not be compensation.",
    errorVoltage: "The voltage must be greater than zero.",
    errorFrequency: "The frequency must be greater than zero.",
    results: "Result",
    reactiveBefore: "Reactive power before compensation Q₁",
    reactiveAfter: "Reactive power after compensation Q₂",
    correction: "Required reactive power Qc",
    capacitance: "Capacitance per phase C",
    currentBefore: "Current before compensation I₁",
    currentAfter: "Current after compensation I₂",
    starDeltaNote:
      "A star-connected battery needs three times the capacitance of a delta-connected one for the same Qc.",
    harmonicsNote:
      "This is a fundamental-harmonic calculation with a balanced load. Higher harmonics and resonance with the grid transformer are not covered.",
    formula:
      "tan φ = √(1−cos²φ)/cos φ     Qc = P(tan φ₁−tan φ₂)     C = Qc/(3ωU²) delta, Qc/(ωU²) star",
    inputs: "Entered",
    unitKvar: "kvar",
    unitUf: "µF",
    unitA: "A",
    unitKw: "kW",
    unitV: "V",
  },

  "pressure-and-piston-force": {
    value: "Value",
    unit: "Unit",
    kind: "Kind",
    kindGauge: "gauge",
    kindAbsolute: "absolute",
    atmospheric: "Atmospheric pressure",
    atmosphericHint:
      "An empty field means standard atmosphere (101325 Pa). At altitude or in other weather enter the barometer reading.",
    bore: "Cylinder diameter",
    rod: "Rod diameter",
    rodHint:
      "Optional. An empty field or zero means a plunger (the whole piston area works in both directions except retraction).",
    errorAtmospheric: "The atmospheric pressure must be between 0 and 200000 Pa.",
    errorValue:
      "The entered pressure is outside the allowed range, or the absolute pressure would come out negative.",
    errorBore: "The cylinder diameter must be between 0 and 5000 mm.",
    errorRod: "The rod diameter must be non-negative and smaller than the cylinder diameter.",
    results: "Pressure in all units",
    forceResults: "Force on the piston",
    gauge: "Gauge pressure",
    absolute: "Absolute",
    boreArea: "Piston area",
    annulusArea: "Annular area (rod side)",
    extendForce: "Force extending",
    retractForce: "Force retracting",
    theoreticalForceNote:
      "This is the THEORETICAL force — pressure times area, without seal friction and without back-pressure on the opposite side. The actual delivered force is a few percent lower.",
    formula: "p_absolute = p_gauge + p_atm",
    forceFormula: "A = πD²/4     A' = π(D²−d²)/4     F = p_gauge·A",
    inputs: "Entered",
    unitMm2: "mm²",
    unitN: "N",
    unitKn: "kN",
    unitMm: "mm",
  },

  "resistor-colour-code": {
    direction: "Direction",
    directionToValue: "colours → value",
    directionToBands: "value → colours",
    bandCount: "Number of bands",
    series: "E series",
    seriesHint: "For the row about the nearest preferred value.",
    band1: "1st band (digit)",
    band2: "2nd band (digit)",
    band3digit: "3rd band (digit)",
    multiplierBand: "Multiplier band",
    toleranceBand: "Tolerance band",
    tempCoefficientBand: "6th band (temperature coefficient)",
    tempCoefficientHint: "ppm/K — only for a six-band resistor.",
    colourBlack: "black",
    colourBrown: "brown",
    colourRed: "red",
    colourOrange: "orange",
    colourYellow: "yellow",
    colourGreen: "green",
    colourBlue: "blue",
    colourViolet: "violet",
    colourGrey: "grey",
    colourWhite: "white",
    colourGold: "gold",
    colourSilver: "silver",
    errorBandCount: "The number of bands is 3, 4, 5 or 6.",
    errorDigitBand: "The chosen colour has no meaning as a digit in this position.",
    errorMultiplierBand: "The chosen colour has no meaning as a multiplier.",
    errorToleranceBand: "The chosen colour has no meaning as a tolerance.",
    errorTempCoefficientBand: "The chosen colour has no meaning as a temperature coefficient.",
    errorValue: "The value must be greater than zero.",
    errorMultiplierRange:
      "The value cannot be written with this number of bands — the multiplier falls outside the range 10⁻² … 10⁹.",
    errorPrecision:
      "The value cannot be written exactly with this number of bands without silently rounding to another value.",
    errorToleranceValue: "The entered tolerance matches no colour in the IEC 60062 table.",
    errorTempCoefficientValue:
      "The entered temperature coefficient matches no colour in the IEC 60062 table.",
    results: "Result",
    value: "Value",
    valueHint: "In ohms, without a prefix (e.g. 4700, not 4.7k).",
    tolerance: "Tolerance",
    toleranceInput: "Tolerance",
    toleranceInputHint: "In percent (e.g. 5 for ±5%). Required from 4 bands up.",
    unmarkedToleranceNote: "A three-band resistor has no tolerance band and is ±20% by convention.",
    range: "Range",
    tempCoefficient: "Temperature coefficient",
    tempCoefficientInput: "Temperature coefficient",
    preferred: "Nearest value from the chosen series",
    bands: "Bands",
    formula: "value = digits · multiplier",
    reverseFormula:
      "digits and multiplier from the value normalised to the number of bands; colour from the IEC 60062 table",
    inputs: "Entered",
    unitOhm: "Ω",
    unitPpmK: "ppm/K",
  },

  "rlc-impedance": {
    frequency: "Frequency f",
    resistance: "Resistance R",
    inductance: "Inductance L",
    inductanceHint:
      "In henries. For millihenries divide by 1000, for microhenries by 1 000 000. An empty field means there is no inductor.",
    capacitance: "Capacitance C",
    capacitanceHint:
      "In farads. For microfarads divide by 1e6, for nanofarads by 1e9, for picofarads by 1e12. An empty field means there is no capacitor.",
    connection: "Connection",
    connectionSeries: "series",
    connectionParallel: "parallel",
    errorFrequency: "The frequency must be greater than zero.",
    errorResistance: "The resistance must be between 0 and 1e12 Ω.",
    errorInductance: "The inductance must be between 0 and 1e6 H.",
    errorCapacitance: "The capacitance must be between 0 and 1 F.",
    results: "Result",
    reactanceInductive: "Inductive reactance X_L",
    reactanceCapacitive: "Capacitive reactance X_C",
    netReactance: "Total reactance X",
    conductance: "Conductance G",
    susceptance: "Susceptance B",
    impedance: "Impedance |Z|",
    phase: "Phase angle φ",
    phaseSignNote:
      "A positive angle means an inductive load — that is the only indication of character in this result.",
    resonance: "Resonant frequency f₀",
    qualityFactor: "Quality factor Q",
    bandwidth: "Bandwidth",
    cornerRc: "Cutoff frequency of the RC branch",
    cornerRl: "Cutoff frequency of the RL branch",
    absentNote:
      "Only the quantities the entered elements define are shown — nothing is filled in by assumption.",
    formulaSeries:
      "X = X_L−X_C     |Z| = √(R²+X²)     φ = atan2(X,R)     f₀ = 1/(2π√(LC))     Q = (1/R)√(L/C)",
    formulaParallel:
      "B = ωC−1/(ωL)     |Z| = 1/√(G²+B²)     φ = −atan2(B,G)     Q = R√(C/L)     BW = f₀/Q = 1/(2πRC)",
    inputs: "Entered",
    unitOhm: "Ω",
    unitS: "S",
    unitDeg: "°",
    unitHz: "Hz",
    unitH: "H",
    unitF: "F",
    unitS2: "s",
  },

  "section-modulus": {
    shape: "Form",
    shapeRectangle: "rectangle",
    shapeCircle: "circle",
    shapeTube: "pipe",
    shapeRectangularTube: "rectangular tube",
    shapeISection: "I-section",
    width: "Width b",
    height: "Height h",
    diameter: "Diameter d",
    outerDiameter: "Outer diameter D",
    innerDiameter: "Inner diameter d",
    outerWidth: "Outer width B",
    outerHeight: "Outer height H",
    innerWidth: "Inner width b",
    innerHeight: "Inner height h",
    flangeWidth: "Flange width b",
    depth: "Overall height h",
    flangeThickness: "Flange thickness t_f",
    webThickness: "Web thickness t_r",
    iSectionNote:
      "Right angles between flange and web are assumed, without root fillets — a rolled section has slightly more area and I than this calculation gives.",
    allowableStress: "Allowable stress σ_allow",
    allowableStressHint:
      "Chosen by the material standard and the regulation you calculate by. Neagle does not suggest it.",
    bendingMoment: "Bending moment M",
    torsionMoment: "Torsional moment T",
    torsionHint:
      "For a circle and a pipe only — in other shapes the torsion constant is not 2I and this calculation does not give it.",
    errorDimensions: "The entered dimensions are not geometrically possible for the chosen shape.",
    errorAllowableStress: "The allowable stress must be between 0 and 3000 MPa.",
    errorBendingMoment: "The bending moment must be in the range 0 to 1e9 N·m.",
    errorTorsionMoment: "The torsional moment must be in the range 0 to 1e9 N·m.",
    results: "Result",
    area: "Area A",
    momentOfInertiaX: "Second moment of area I_x",
    momentOfInertiaY: "Second moment of area I_y",
    sectionModulusX: "Section modulus W_x",
    sectionModulusY: "Section modulus W_y",
    radiusOfGyrationX: "Radius of gyration i_x",
    radiusOfGyrationY: "Radius of gyration i_y",
    polarMoment: "Polar second moment of area I_p",
    polarModulus: "Polar section modulus W_p",
    noPolarNote:
      "Polar quantities are shown only for a circle and a pipe. For a rectangle, rectangular tube and I-section the torsion constant depends on the shape and I_p = 2I does not hold here, so that row is not shown.",
    allowableMoment: "Moment at the allowable stress M_allow",
    bendingStress: "Bending stress σ",
    stressRatio: "Stress ÷ your limit",
    torsionalStress: "Torsional stress τ",
    modelNote:
      "The model does not cover buckling, lateral-torsional buckling, local stability or fatigue.",
    formulaRectangle: "A = bh     I_x = bh³/12     I_y = hb³/12     W_x = bh²/6     W_y = hb²/6",
    formulaCircle:
      "A = πd²/4     I_x = I_y = πd⁴/64     W_x = W_y = πd³/32     I_p = 2I     W_p = 2W",
    formulaTube: "A = π(D²−d²)/4     I = π(D⁴−d⁴)/64     W = 2I/D     I_p = 2I     W_p = 2W",
    formulaRectangularTube:
      "A = BH−bh     I_x = (BH³−bh³)/12     W_x = 2I_x/H     I_y = (HB³−hb³)/12     W_y = 2I_y/B",
    formulaISection:
      "A = 2bt_f+(h−2t_f)t_r     I_x = [bh³−(b−t_r)(h−2t_f)³]/12     W_x = 2I_x/h     I_y = [2t_fb³+(h−2t_f)t_r³]/12     W_y = 2I_y/b",
    inputs: "Entered",
    unitMm: "mm",
    unitMm2: "mm²",
    unitMm3: "mm³",
    unitMm4: "mm⁴",
    unitNm: "N·m",
    unitMpa: "MPa",
  },

  "series-parallel-network": {
    regime: "Mode",
    regimeNetwork: "component network",
    regimeDivider: "voltage divider",
    element: "Element type",
    elementResistor: "resistor",
    elementInductor: "inductor",
    elementCapacitor: "capacitor",
    connection: "Connection",
    connectionSeries: "series",
    connectionParallel: "parallel",
    values: "Values",
    valuesHint:
      "One value per line, in Ω, H or F without a prefix (e.g. 470, not 470k). From 1 to 32 entries.",
    errorValues: "Every value must be non-negative, and there must be at least one.",
    errorTooMany: "At most 32 values.",
    errorInputVoltage: "The input voltage must be in the range 0 to 1e6 V.",
    errorUpper: "The upper resistor may not be negative.",
    errorLower: "The lower resistor may not be negative.",
    errorTotal: "The sum of R1 and R2 may not be zero.",
    results: "Result",
    equivalent: "Equivalent value",
    zeroNote:
      "A zero in a parallel group of resistors or inductors short-circuits the network (the result is exactly 0). A zero in a series string of capacitors blocks it (the result is exactly 0). Outside those cases a zero simply contributes nothing.",
    formula:
      "series: sum     parallel: reciprocal of the sum of reciprocals     (capacitors the other way round)",
    inputs: "Entered",
    inputVoltage: "Input voltage U_in",
    upper: "Upper resistor R1",
    lower: "Lower resistor R2",
    outputVoltage: "Output voltage U_out",
    unloadedNote:
      "This is the UNLOADED voltage — as soon as something draws current from the output, this value no longer holds.",
    current: "Current through the divider",
    upperPower: "Power in R1",
    lowerPower: "Power in R2",
    totalPower: "Total power",
    theveninResistance: "Thévenin resistance of the divider R1‖R2",
    dividerFormula:
      "U_out = U_in·R2/(R1+R2)     I = U_in/(R1+R2)     P_i = I²·R_i     R_th = R1·R2/(R1+R2)",
    unitV: "V",
    unitA: "A",
    unitW: "W",
    unitOhm: "Ω",
  },

  "three-phase-power": {
    system: "System",
    voltageSingle: "Supply voltage U",
    voltageThree: "Line voltage U",
    known: "Known quantity",
    knownCurrent: "current I",
    knownActivePower: "active power P",
    knownApparentPower: "apparent power S",
    powerFactor: "Power factor cos φ",
    connection: "Load connection",
    connectionHint:
      "Affects only the phase voltage and phase current — the line values are the same in both cases.",
    connectionStar: "star",
    connectionDelta: "delta",
    errorVoltage: "The voltage must be greater than zero.",
    errorPowerFactor: "The power factor must be between 0 and 1.",
    errorCurrent: "The current must be in the range 0 to 1e6 A.",
    errorActivePower: "The active power must be in the range 0 to 1e6 kW.",
    errorApparentPower: "The apparent power must be in the range 0 to 1e6 kVA.",
    errorKnown: "Enter exactly one of the three quantities — current, active or apparent power.",
    results: "Result",
    apparent: "Apparent power S",
    active: "Active power P",
    reactive: "Reactive power Q",
    current: "Line current I",
    phase: "Phase angle φ",
    tanPhi: "tan φ",
    phaseVoltage: "Phase voltage U_ph",
    phaseCurrent: "Phase current I_ph",
    inductiveNote:
      "sin φ is taken non-negative — the load is assumed inductive (lagging).",
    balancedNote: "A balanced symmetrical network and sinusoidal voltage and current are assumed.",
    formula: "S = √3·U·I     P = S·cos φ     Q = S·sin φ     U_ph star = U/√3, delta = U",
    inputs: "Entered",
    unitKva: "kVA",
    unitKw: "kW",
    unitKvar: "kvar",
    unitA: "A",
    unitDeg: "°",
    unitV: "V",
  },

  "torque-speed-power": {
    torque: "Torque M",
    speed: "Speed n",
    speedOmegaHint: "n and ω are the SAME quantity in two units — fill in only one of them, not both.",
    angularVelocity: "Angular speed ω",
    power: "Power P",
    pairHint: "Enter exactly two of the three quantities (torque, speed, power) — the third is calculated.",
    errorSpeed:
      "Fill in either the speed or the angular speed, not both, and the value must be greater than zero.",
    errorTorque: "The torque must be in the range 0 to 1e9 N·m.",
    errorPower: "The power must be in the range 0 to 1e9 W.",
    errorPair: "Enter exactly two of the three quantities — torque, speed (n or ω) and power.",
    results: "Result",
    hpNote:
      "metric hp is metric horsepower (735.49875 W), hp is mechanical/imperial horsepower (745.69987 W).",
    formula: "P = M·ω     ω = 2πn/60     M = 30000·P[kW]/(πn)",
    inputs: "Entered",
    computed: "calculated",
    unitNm: "N·m",
    unitKgfM: "kgf·m",
    unitLbfFt: "lbf·ft",
    unitRpm: "min⁻¹",
    unitRadS: "rad/s",
    unitW: "W",
    unitKw: "kW",
    unitKs: "metric hp",
    unitHp: "hp",
  },
} as const;
