/**
 * „Event i produkcija" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as the assignment spells the
 * registration. The tool's NAME and its one-line blurb are not here: those live
 * in a different table that another process owns.
 *
 * **A unit is copy, not a constant.** „m" and „kg" are written here rather than
 * concatenated in the surface, so a translation moves this table only.
 *
 * **Nothing in here judges.** `generator-sizing`, `led-wall-pitch-viewing`,
 * `rigging-sling-angle-force`, `stage-deck-layout`, `three-phase-load-balance`,
 * `truss-hoist-reactions`, `voltage-drop` and `venue-occupancy-area` are
 * `life-safety`; `ice-and-chilling` is `food-safety`. Their copy may name a
 * quantity and may name the user's own limit, and may never say what the two
 * mean together. Where a limit appears it is always „tvoja granica" — whose it
 * is, said in the label, and in the possessive rather than a participle that
 * would have to pick the reader's gender.
 */
export const PRO_EVENT_EN = {
  "beam-spot-diameter": {
    beamAngle: "Beam angle (50% intensity)",
    beamAngleHint: "From the floodlight's catalogue.",
    fieldAngle: "Field angle (10% intensity)",
    fieldAngleHint:
      "Optional, from the catalogue. Not shown for oblique incidence — see the note beside the ellipse.",
    mode: "Distance method",
    modeNormal: "Perpendicular distance D",
    modeOblique: "Mounting height h and horizontal distance to the target",
    distance: "Perpendicular distance D",
    height: "Mounting height h",
    offset: "Horizontal distance to the target x",
    offsetHint: "An empty field means the target directly below the floodlight.",
    intensity: "Luminous intensity I",
    intensityHint: "Optional, from the catalogue (cd). Without it the illuminance is not shown.",
    overlap: "Overlap of adjacent beams",
    coverage: "Length to cover",

    results: "Result",
    beamDiameter: "Beam diameter (perpendicular)",
    fieldDiameter: "Field diameter (perpendicular)",
    slantDistance: "Distance to the target",
    minorAxis: "Minor axis of the ellipse (exact shape)",
    majorAxis: "Major axis of the ellipse",
    tilt: "Tilt γ from the normal",
    nearEdge: "Near edge of the patch (from the point below the floodlight)",
    farEdge: "Far edge of the patch (from the point below the floodlight)",
    illuminance: "Illuminance at the aiming point",
    spacing: "Spacing of adjacent floodlights",
    fixtureCount: "Number of floodlights needed",
    coveredLength: "Actual covered length",
    axisNote:
      "The spacing and count hold only along the axis of the row — two adjacent circular beams overlap in a lenticular section, so coverage off that axis is smaller.",

    inputs: "Entered",
    formula:
      "perpendicular: d=2D·tan(θ/2)     oblique incidence: β=atan(x/h), Ds=√(h²+x²), b=2h·sin(θ/2)/√(cos(β−θ/2)cos(β+θ/2)), a=h(tan(β+θ/2)−tan(β−θ/2))     E=I·cosβ/Ds²     s=d_eff(1−overlap/100), n=max(1, ceil((L−d_eff)/s)+1)",

    errorBeamAngle: "The beam angle is a number from 1° to 120°.",
    errorFieldAngle: "The field angle is a number from 1° to 160°, and is not shown for oblique incidence.",
    errorAmbiguousDistance:
      "Both a perpendicular distance and a mounting height were entered — choose one method, otherwise it is not clear which distance the illuminance uses.",
    errorDistance: "The perpendicular distance is a number from 0.5 to 200 m.",
    errorHeight: "The mounting height is a number from 0.5 to 60 m.",
    errorOffset: "The horizontal distance is a number from 0 to 100 m.",
    errorIntensity: "The luminous intensity is a number from 100 to 10,000,000 cd.",
    errorOverlap: "The overlap is a number from 0 to 90%, and goes together with the length to cover.",
    errorCoverage: "The length to cover is a number from 0.5 to 200 m, and goes together with the overlap.",
    errorGrazing: "At this tilt the beam runs parallel to the surface and never touches it.",

    unitM: "m",
    unitDeg: "°",
    unitLx: "lx",
  },

  "budget-per-guest": {
    guests: "Number of guests",
    tables: "Number of tables",
    tablesHint: "An empty field reads as 0 — no per-table items.",
    lines: "Costs",
    linesHint:
      "One row per item: name;type;amount;basis;taxable. The type is fixed, guest, table or percentage. The basis applies only to a percentage — the item numbers (from 1) the percentage applies to, separated by commas; empty means all non-percentage rows. Taxable is yes or no, used only with the “marked items only” tax basis.",
    reserve: "Reserve",
    taxRate: "Tax rate",
    taxRateHint:
      "The user's input — Neagle holds no tax rate and does not know which one applies.",
    taxBaseMode: "Tax basis",
    taxBaseModeHint:
      "The reserve never enters the “marked items only” basis — the markup is on the whole budget.",
    taxBaseModeTotal: "Whole amount",
    taxBaseModeMarked: "Marked items only",
    revenueLines: "Income",
    revenueLinesHint: "One row per item: name;amount. Optional — sponsor, donation and the like.",
    payingGuests: "Number of paying guests",
    ticketPrice: "Ticket price",

    results: "Result",
    colName: "Item",
    colType: "Type",
    colAmount: "Amount",
    colShare: "Weight",
    colPercentBase: "Percentage basis",
    typeFixed: "Fixed",
    typePerGuest: "Per guest",
    typePerTable: "Per table",
    typePercent: "Percentage of the basis",
    base: "Basis (fixed + per guest + per table)",
    percentSum: "Sum of percentage items",
    subtotal: "Subtotal",
    reserveAmount: "Reserve",
    preTaxTotal: "Total without tax",
    taxBaseAmount: "Basis the rate was applied to",
    tax: "Tax",
    grandTotal: "Total with tax",
    costPerGuestWithTax: "Cost per guest, with tax",
    costPerGuestWithoutTax: "Cost per guest, without tax",
    costPerTableWithTax: "Cost per table, with tax",
    costPerTableWithoutTax: "Cost per table, without tax",
    revenueTotal: "Total income",
    revenueDifference: "Difference income − cost",
    breakEvenTicketPrice: "Ticket price at which the difference is zero",
    ticketRevenue: "Ticket income",

    inputs: "Entered",
    formula:
      "basis=Σ(fixed+guest·G+table·T)     percentage_i=(%ᵢ/100)·basis_i     subtotal=basis+Σpercentage     reserve=subtotal·r/100     tax=tax_basis·t/100     total=subtotal+reserve+tax     break_even_ticket=ceil_to_cent((total−other_income)/paying)",

    errorGuests: "The number of guests is a whole number from 1 to 100,000.",
    errorTables: "The number of tables is a whole number from 0 to 10,000.",
    errorLines: "At least one cost row is needed.",
    errorLineType: "Every row must have the type fixed, guest, table or percentage.",
    errorLineAmount: "The amount or percentage in a row must be a number, zero or greater.",
    errorPercentOfLines:
      "The basis of a percentage row must point to existing non-percentage rows.",
    errorReserve: "The reserve is a number from 0 to 50%.",
    errorTaxRate: "The tax rate is a number from 0 to 100%.",

    rowLabel: "line",
  },

  "catering-per-guest": {
    guests: "Number of guests",
    lines: "Items",
    linesHint:
      "One row per item: name;unit;quantity per guest;share who take it (%);reserve (%);package size;package unit;package price;pouring portion (ml). The unit is g, ml or piece. The package unit is g, kg, ml, l or piece — kg/l reads as ×1000. The price and portion are optional.",
    packRounding: "Package rounding",
    packRoundingUp: "Up",
    packRoundingExact: "Exact",

    results: "Result",
    colName: "Item",
    colGross: "Gross quantity",
    colGrossBig: "Gross (kg/l)",
    colPacks: "Packages",
    colSurplus: "Surplus",
    colPoursNeed: "Portions from the requirement",
    colPoursPurchased: "Portions from what is bought",
    colCost: "Item price",
    colCostPerGuest: "Price per guest",
    colCostPerTaking: "Price per guest who takes it",
    colActualReserve: "Actual reserve (after rounding)",
    packs: "packages:",
    surplus: "surplus:",
    totalCost: "Sum of the prices of all items",
    totalCostPerGuest: "Sum per guest",

    inputs: "Entered",
    formula:
      "net=G·q·(share/100)     gross=net·(1+reserve/100)     packages=ceil(gross/package_size) (up) or gross/package_size (exact)     surplus=packages·size−gross     portions_needed=floor(gross/portion)     portions_bought=floor(packages·size/portion)",

    errorGuests: "The number of guests is a whole number from 1 to 5000.",
    errorLines: "At least one item row is needed.",
    errorUnitToken:
      "The item unit must be g, ml or piece, and the package unit g, kg, ml, l or piece, of the same dimension as the item.",
    errorQuantity: "The quantity per guest must be greater than zero.",
    errorUptake: "The share who take it is a number from 0 to 100%.",
    errorReserve: "The reserve is a number from 0 to 100%.",
    errorPackSize: "The package size must be greater than zero.",
    errorPackUnit:
      "The package unit must be the same dimension (mass/volume/piece) as the item unit.",
    errorPourSize: "The pouring portion must be greater than zero, and holds only for liquid items.",
    errorPrice: "The package price may not be negative.",

    rowLabel: "line",
  },

  "generator-sizing": {
    consumers: "Loads",
    consumersHint:
      "One row per load: name;power in kW;cos φ;simultaneity (%, empty = 100);motor (yes/no);starting kVA per kW (motor only, from the nameplate);cos φ at start (motor only). A negative cos φ means a leading (capacitive) load — LED drivers, filters.",
    reserve: "Reserve",
    derate: "Power derating",
    derateHint: "Altitude and temperature, from the generator manufacturer's table.",
    ratedPowerFactor: "Nominal generator power factor",
    ratedPowerFactorHint: "From the specific generator's nameplate. There is no default value.",
    ratedPowerKw: "Nominal generator power",
    ratedPowerKwHint: "Optional — for the load percentage and consumption in l/h.",
    fuelRate: "Specific fuel consumption",
    fuelRateHint: "From the generator's catalogue, per load order. Optional.",
    hours: "Work duration",

    results: "Result",
    runningActive: "Working active power",
    runningReactive: "Working reactive power",
    runningApparent: "Working apparent power",
    runningPowerFactor: "Resulting power factor",
    peakActive: "Active power at the starting peak",
    peakReactive: "Reactive power at the starting peak",
    peakApparent: "Apparent power at the starting peak",
    designApparent: "Required apparent power (after reserve and derating)",
    designActive: "Corresponding active power",
    fuelPerHour: "Fuel consumption",
    fuelTotal: "Total consumption for the entered duration",
    loadPct: "Generator load percentage",
    fuelNote:
      "The consumption model is linear in the delivered active power and does not include idle consumption.",

    inputs: "Entered",
    formula:
      "P=ΣkW·sim/100     Q=ΣP·tanφ (signed)     S=√(P²+Q²)     start: S_start=kW_motor·kVA/kW     S_peak=√((P−P_motor+S_start·cosφ_p)²+(Q−Q_motor+S_start·sinφ_p)²)     S_required=max(S,S_peak)·(1+reserve/100)/(1−derating/100)     P_required=S_required·cosφ_generator",

    errorConsumers: "At least one load row is needed.",
    errorReserve: "The reserve is a number from 0 to 100%.",
    errorDerate: "The power derating is a number from 0 to 50%.",
    errorRatedPowerFactor: "The nominal generator power factor is a number from 0.5 to 1.0.",
    errorRatedPowerKw: "The nominal generator power must be greater than zero.",
    errorFuelRate: "The specific fuel consumption must be greater than zero.",
    errorHours: "The work duration must be greater than zero.",
    errorKw: "A load's power must be greater than zero.",
    errorCosPhi: "Cos φ is a number whose absolute value is from 0.1 to 1.0.",
    errorSimultaneity: "The simultaneity is a number from 0 to 100%.",
    errorStartingKva: "The starting kVA per kW is a number from 1.0 to 10.0, required for a motor.",
    errorStartingCosPhi:
      "Cos φ at start is a number whose absolute value is from 0.1 to 1.0, required for a motor.",

    unitKw: "kW",
    unitKvar: "kvar",
    unitKva: "kVA",
    unitLh: "l/h",
    unitL: "l",

    rowLabel: "line",
  },

  "ice-and-chilling": {
    quantityMode: "How the drink quantity was entered",
    quantityModeMass: "Mass",
    quantityModeVolume: "Volume",
    drinkMass: "Drink mass",
    drinkVolume: "Drink volume",
    drinkDensity: "Drink density",
    drinkSpecificHeat: "Specific heat of the drink",
    drinkSpecificHeatHint: "An empty field uses the value for watery drinks, 4.184 kJ/(kg·K).",
    packagingMass: "Packaging mass",
    packagingMassHint: "Glass and cans that cool together with the contents. An empty field is 0.",
    packagingSpecificHeat: "Specific heat of the packaging",
    packagingSpecificHeatHint:
      "An empty field uses the value for glass, 0.84 kJ/(kg·K); for aluminium 0.897.",
    startTemp: "Initial drink temperature T1",
    targetTemp: "Target temperature T2",
    targetTempHint:
      "The user chooses the target temperature — the tool does not say whether something is chilled enough.",
    iceTemp: "Ice temperature Ti",
    iceTempHint: "An empty field is 0 °C. For ice from a freezer enter a negative value.",
    holdMode: "Heat ingress while holding",
    holdModeNone: "No holding calculation",
    holdModeWatt: "Ingress in watts",
    holdModeUa: "UA and ambient temperature",
    ambientWatt: "Heat ingress from the surroundings",
    holdUa: "Tub UA coefficient",
    holdUaHint: "W/K, from a measurement or the tub's label.",
    ambientTemp: "Ambient temperature",
    holdHours: "Holding time",
    bagMass: "Mass of one ice package",
    bagMassHint: "An empty field is 5 kg.",
    bulkFraction: "Ice bulk coefficient",
    bulkFractionHint:
      "The share of solid ice in the volume of the filled tub, 0 to 1 — cubes and flakes carry 35 to 45% voids. Optional; without it only the solid-ice volume is shown.",
    meltsIntoDrink: "Ice melts directly in the drink",
    meltsIntoDrinkHint: "Turn on for punch bowls; off for cooling closed packaging in a tub.",
    yes: "Yes",
    no: "No",

    results: "Result",
    heatToRemove: "Heat removed",
    noCoolingNeededNote:
      "The target temperature is already reached or higher than the initial one — there is nothing to remove, so the zeros above are the correct answer, not a calculation that fell to zero.",
    icePulldown: "Ice mass for cooling (ideal lower bound)",
    iceHoldingMelt: "Additional ice melted while holding (upper bound)",
    totalIce: "Total ice mass",
    solidVolume: "Solid ice volume",
    bulkVolume: "Bulk volume (tub/container)",
    bags: "Number of packs",
    meltwaterMass: "Mass of meltwater from cooling",
    dilution: "Dilution of the drink by melted ice",
    iceToDrinkRatio: "kg of ice per kg of drink",
    boundsNote:
      "The cooling mass is the ideal lower bound with all the ice fully melted; the extra melting while holding counts only latent heat and is therefore the upper bound. This is one step to equilibrium, not a cooling curve — there is no time axis and it does not say how quickly the drink reaches the temperature.",

    inputs: "Entered",
    formula:
      "Q=(m·c+m_pack·c_pack)·(T1−T2)     h=c_ice·(0−Ti)+333.55+4.184·max(T2,0)     m_ice=Q/h     m_melt=Q̇·t·3600/1000/333.55     V_solid=m_total/917·1000",

    errorDrinkMass: "The drink mass must be greater than zero.",
    errorDrinkVolume: "The drink volume must be greater than zero.",
    errorDrinkDensity: "The drink density must be greater than zero.",
    errorDrinkSpecificHeat: "The specific heat of the drink is a number from 1.0 to 5.0 kJ/(kg·K).",
    errorPackagingMass: "The packaging mass may not be negative.",
    errorPackagingSpecificHeat: "The specific heat of the packaging is a number from 0.4 to 1.2 kJ/(kg·K).",
    errorStartTemp: "The initial temperature is a number from −10 to 60 °C.",
    errorTargetTemp: "The target temperature is a number from 0 to 40 °C.",
    errorIceTemp: "The ice temperature is a number from −30 to 0 °C.",
    errorBagMass: "The mass of one package is a number from 0.5 to 25 kg.",
    errorBulkFraction: "The bulk coefficient is a number from 0.1 to 1.",
    errorAmbiguousHold: "Choose only one way of setting the heat ingress while holding.",
    errorHoldHours: "The holding time must be greater than zero.",
    errorAmbientWatt: "The heat ingress must be greater than zero.",
    errorHoldUa: "The UA coefficient must be greater than zero, with a realistic ambient temperature.",

    unitKj: "kJ",
    unitKg: "kg",
    unitL: "l",
    unitC: "°C",
  },

  "led-wall-pitch-viewing": {
    pitch: "Pixel pitch",
    pitchHint: "The panel designation, e.g. P2.5 means 2.5 mm.",
    panelWidth: "Panel width",
    panelDimHint: "An empty field is 500 mm.",
    panelHeight: "Panel height",
    sizeMode: "How the wall size was set",
    sizeModePanels: "Number of panels across and down",
    sizeModeTarget: "Target wall width and height",
    panelsWide: "Number of panels across",
    panelsHigh: "Number of panels down",
    targetWidth: "Target wall width",
    targetHeight: "Target wall height",
    acuity: "Visual acuity angle",
    acuityHint: "A catalogue or acuity reference — a required input, the tool does not offer it.",
    portCapacity: "Processor port capacity",
    portCapacityHint: "Pixels per port, from the processor's catalogue. Optional.",
    panelMaxW: "Maximum panel power",
    panelPowerHint: "From the panel's catalogue. Optional — without it the power and current are not shown.",
    panelAvgW: "Average panel power",
    voltage: "Supply voltage",
    voltageHint: "An empty field is 230 V.",
    powerFactor: "Supply power factor",
    powerFactorHint: "From the panel's catalogue. Without it the current is not shown.",

    results: "Result",
    panelResolution: "Resolution of one panel",
    wallResolution: "Total wall resolution",
    wallSize: "Physical size of the wall",
    aspect: "Aspect ratio",
    pixelDensity: "Pixel density",
    viewingAtAcuity: "Distance at the entered acuity angle",
    viewingAt1: "Distance for 1′",
    viewingAt2: "Distance for 2′",
    ports: "Number of processor ports needed",
    powerMax: "Maximum wall power",
    powerAvg: "Average wall power",
    apparentMax: "Maximum apparent wall power",
    apparentAvg: "Average apparent wall power",
    currentMax: "Current at maximum power",
    currentAvg: "Current at average power",
    inrushNote:
      "The current and apparent power are steady-state loads — the inrush current when the wall is switched on is not modelled.",

    inputs: "Entered",
    formula:
      "px=panel/pitch     wall=panel_count·panel/1000     d(θ)=pitch/(θ·0.0002908882)/1000     panels_per_port=floor(capacity/panel_px), ports=ceil(panel_count/panels_per_port)     S=P/PF     I=P·1000/(U·PF)",

    errorPitch:
      "The pixel pitch must be greater than zero, and must divide the panel dimensions into a whole number of pixels.",
    errorPanelWidth: "The panel width is a number from 100 to 2000 mm.",
    errorPanelHeight: "The panel height is a number from 100 to 2000 mm.",
    errorAcuity: "The visual acuity angle is a number from 0.5 to 10 arc minutes.",
    errorPanelsWide:
      "The number of panels across is a whole number from 1 to 200 — enter either this or the target size, never both.",
    errorPanelsHigh: "The number of panels down is a whole number from 1 to 100.",
    errorTargetWidth:
      "The target wall width must be greater than zero and give a number of panels in the allowed range.",
    errorTargetHeight:
      "The target wall height must be greater than zero and give a number of panels in the allowed range.",
    errorPortCapacity:
      "The port capacity is a number from 10,000 to 2,000,000 pixels, enough for at least one panel.",
    errorPanelMaxW: "The maximum panel power is a number from 10 to 2000 W.",
    errorPanelAvgW: "The average panel power is a number from 5 to 2000 W.",
    errorVoltage: "The voltage is a number from 100 to 400 V.",
    errorPowerFactor: "The power factor is a number from 0.5 to 1.0.",

    unitM: "m",
    unitMm: "mm",
    unitPxM: "px/m",
    unitKw: "kW",
    unitKva: "kVA",
    unitA: "A",
  },

  "parking-cloakroom": {
    guests: "Number of guests",
    carShare: "Share arriving by car",
    occupancyPerCar: "Average people per car",
    busShare: "Share arriving by bus",
    seatsPerBus: "Seats on the bus",
    areaPerStall: "Area per parking space",
    areaPerStallHint: "With manoeuvring space, from a regulation or the venue's conditions. The user's input.",
    availableStalls: "Available parking spaces",
    coatShare: "Share of guests with a cloakroom",
    itemsPerGuest: "Items per guest",
    hangerPitch: "Hanger spacing",
    railSegments: "Available rails",
    railSegmentsHint:
      "One row per physical rail, length in m. The capacity is calculated per rail and summed, not by total length.",
    checkInWindow: "Reception window",
    checkInRate: "Service rate per worker",
    rateHint: "Items per minute, per worker — the unit of work is the item, not the guest.",
    checkInAttendants: "Enter the number of reception workers",
    hasCheckOut: "A separate hand-back window at the end",
    checkOutWindow: "Hand-back window",
    checkOutRate: "Hand-back rate per worker",
    checkOutAttendants: "Enter the number of hand-back workers",
    yes: "Yes",
    no: "No",

    results: "Result",
    carGuests: "Guests arriving by car",
    cars: "Number of cars",
    parkingArea: "Parking area needed",
    stallRatio: "Cars ÷ available spaces",
    buses: "Number of buses",
    busGuests: "guests:",
    coatGuests: "Guests with a cloakroom",
    items: "Number of pieces",
    railLengthNeeded: "Required rail length",
    railCapacity: "Capacity of the available rails",
    railRatio: "Needed ÷ capacity",
    pieces: "items",
    checkInSection: "Reception",
    checkInAttendantsNeeded: "Number of workers needed for the window",
    checkInClearTime: "Processing time with the entered number of workers",
    checkInClearDiff: "Difference against the window",
    checkOutSection: "Hand-back",
    checkOutAttendantsNeeded: "Number of workers needed for the window",
    checkOutClearTime: "Processing time with the entered number of workers",
    checkOutClearDiff: "Difference against the window",
    throughputNote:
      "The throughput assumes arrivals spread evenly over the whole window — a sudden rush at one moment is not covered by it.",

    inputs: "Entered",
    formula:
      "G_car=round(G·share/100)     cars=ceil(G_car/occupancy)     items=ceil(G_cloak·items/guest)     length=items·spacing     workers=ceil(items/(window·rate))     t=items/(workers·rate)",

    errorGuests: "The number of guests is a whole number from 1 to 100,000.",
    errorCarShare: "The share arriving by car is a number from 0 to 100%.",
    errorOccupancy: "The average people per car is a number from 1.0 to 8.0.",
    errorBusShare: "The share arriving by bus is a number from 0 to 100%.",
    errorShareSum: "The sum of the car and bus shares may not exceed 100%.",
    errorAreaPerStall: "The area per parking space is a number from 5 to 100 m².",
    errorCoatShare: "The share of guests with a cloakroom is a number from 0 to 100%.",
    errorItemsPerGuest: "The items per guest is a number from 0.5 to 4.0.",
    errorHangerPitch: "The hanger spacing is a number from 0.03 to 0.15 m.",
    errorSeatsPerBus: "The seats on the bus is a number from 10 to 100, required with the bus share.",
    errorAvailableStalls: "The available parking spaces may not be negative.",
    errorRailSegments: "Every rail must be of length zero or greater.",
    errorWindow: "The window must be greater than zero.",
    errorRate: "The service rate must be greater than zero.",
    errorAttendants: "The number of workers is a whole number from 1 to 100.",

    unitM: "m",
    unitM2: "m²",
    unitMin: "min",
  },

  "projector-throw-screen": {
    lensMode: "Lens",
    lensModeSingle: "Fixed, one throw ratio",
    lensModeZoom: "Zoom, ratio range",
    throwRatio: "Throw ratio TR",
    throwRatioHint: "From the lens's catalogue.",
    throwRatioMin: "Throw ratio — lower value",
    throwRatioMax: "Throw ratio — upper value",
    known: "Known quantity",
    knownDistance: "Distance D",
    knownWidth: "Image width W",
    knownDiagonal: "Diagonal",
    knownZoomHint:
      "With a zoom lens the known quantity may not be the distance — the range gives a span of distances, not one.",
    knownValue: "Value",
    aspect: "Aspect ratio",
    aspectCustom: "Arbitrary",
    aspectCustomValue: "Aspect ratio (width ÷ height)",
    aspectCustomHint: "A decimal number, e.g. for 1.85:1 enter 1.85.",
    lumens: "Projector luminous flux",
    lumensHint: "ANSI lumens, from the catalogue. Optional — without it the illuminance is not shown.",
    gain: "Screen gain",
    gainHint: "An empty field is 1.0 — a Lambertian matte-white screen.",
    contrastRatio: "Projector contrast",
    ambientLux: "Ambient illuminance on the screen",
    diffuseReflectance: "Diffuse screen reflectance for ambient light",
    diffuseReflectanceHint:
      "A separate datum from the gain — the gain holds for the projector's directed beam, not for light falling from all sides. Without it the contrast is calculated via the gain and is overestimated at gain > 1.",
    seatingDistance: "Viewer-row distance",
    targetLuminanceFl: "Target luminance (reverse direction)",
    targetLuminanceHint: "In fL — gives the projector flux needed for that luminance, instead of the reverse.",

    results: "Result",
    width: "Image width",
    height: "Image height",
    diagonal: "Diagonal",
    area: "Image area",
    distance: "Distance D",
    zoomRange: "Distance range (zoom)",
    avgIlluminance: "Screen illuminance (ANSI nine-point average)",
    avgLuminance: "Luminance (ANSI average)",
    onScreenContrast: "Contrast on the screen",
    requiredLumens: "Flux needed for the target luminance",
    viewingAngle: "Horizontal viewing angle",
    gainApproxNote:
      "The screen's diffuse reflectance was not entered — the contrast is calculated via the gain, which is a directed quantity for the projector beam, so this number is overestimated for a screen with gain > 1.",
    axisNote:
      "The geometry assumes an axis perpendicular to the centre of the screen, with no lens shift — under keystone distortion none of these numbers holds any more.",

    inputs: "Entered",
    formula:
      "TR=D/W     W=D/TR or D=W·TR     H=W/a     diagonal=W√(1+1/a²)     E=lm/(W·H)     L=E·gain/π     L_fL=lm·gain/(W·H in ft²)     contrast=(L_white+L_amb)/(L_black+L_amb)     θ=2·atan((W/2)/D_row)",

    errorGain: "The screen gain is a number from 0.4 to 4.0.",
    errorAspectRatio: "The aspect ratio must be greater than zero.",
    errorKnownValue: "The known quantity must be greater than zero.",
    errorThrowRatio: "The throw ratio must be greater than zero.",
    errorThrowRatioZoom: "Both ends of the zoom lens's range must be greater than zero.",
    errorAmbiguousZoom: "With a zoom lens the known quantity may not be the distance.",
    errorLumens: "The luminous flux is a number from 100 to 100,000 lm.",
    errorContrastRatio: "The projector contrast is a number from 100 to 2,000,000.",
    errorAmbientLux: "The ambient illuminance is a number from 0 to 2000 lx.",
    errorDiffuseReflectance: "The diffuse screen reflectance is a number from 0 to 1.",
    errorSeatingDistance: "The viewer-row distance is a number from 0.5 to 100 m.",
    errorTargetLuminance: "The target luminance must be greater than zero.",

    unitM: "m",
    unitM2: "m²",
    unitIn: "in",
    unitLx: "lx",
    unitCdm2: "cd/m²",
    unitFl: "fL",
    unitLm: "lm",
    unitDeg: "°",
  },

  "rigging-sling-angle-force": {
    mass: "Load mass",
    mode: "Pick method",
    modeSingle: "One common angle (up to 4 legs)",
    modeTwoPoint: "Two-point pick, one hook above",
    legs: "Number of legs",
    angleMode: "Angle method",
    angleModeFromVertical: "From vertical",
    angleModeFromHorizontal: "From horizontal",
    angleModeIncluded: "Included angle between the legs",
    angleModeHeightRadius: "Height and horizontal distance",
    angleValue: "Angle",
    height: "Height of the suspension point h",
    radius: "Horizontal distance r",
    span: "Spacing of the pick points L",
    cogFromA: "Distance of the centre of gravity from point A",
    hookHeight: "Height of the hook above the pick points h",
    hookHeightHint:
      "Both angles follow from this height — they are not a free choice, because one hook stands above both legs.",
    dynamicFactor: "Dynamic factor",
    dynamicFactorHint:
      "From the job's rules. Without it only the static (unfactored) force is shown.",
    dynamicFactorNone: "not entered",
    wllPerLeg: "Nameplate limit (WLL) per leg",
    wllHint: "From the sling's nameplate. Neagle holds no load table.",
    wllUnit: "Limit unit",

    results: "Result",
    weight: "Load weight",
    weightFactored: "Load weight, with the dynamic factor",
    beta: "Angle β from vertical",
    forceLeg: "Force per leg",
    forceLegFactored: "Force per leg, with the dynamic factor",
    vertical: "Vertical component per leg",
    angleFactor: "Angle factor 1/cos β",
    fourLegShare: "Ideal four-leg distribution",
    twoLegShare: "Two-leg distribution (conservative)",
    fourLegNote:
      "A rigid load on four legs is statically indeterminate — the ideal four-leg distribution is one possible assumption.",
    twoPointBetaA: "Angle β at point A",
    twoPointBetaB: "Angle β at point B",
    twoPointForceA: "Force at point A",
    twoPointForceB: "Force at point B",
    twoPointLegLengthA: "Leg length to point A",
    twoPointLegLengthB: "Leg length to point B",
    horizontal: "Horizontal component",
    horizontalNote:
      "The horizontal component presses the load inwards — numerically equal to the compression force a spreader bar would take.",
    legLength: "Leg length",
    wllRatio: "Force per leg (factored) ÷ nameplate limit",

    inputs: "Entered",
    formula:
      "W=m·g     β from the angle, or β=atan(r/h)     F=W/(n·cosβ)     H=F·sinβ     V=W/n     two-point pick: V_A=W(L−a)/L, V_B=Wa/L, β_A=atan(a/h), β_B=atan((L−a)/h), F=V/cosβ",

    errorMass: "The load mass is a number from 0.1 to 100,000 kg.",
    errorLegs: "The number of legs is a whole number from 1 to 4.",
    errorDynamicFactor: "The dynamic factor is a number from 1.0 to 5.0.",
    errorSpan: "The spacing of the pick points must be greater than zero.",
    errorCogFromA:
      "The distance of the centre of gravity from point A may not be negative or greater than the point spacing.",
    errorHookHeight: "The hook height must be greater than zero and enough to keep both angles below 90°.",
    errorWllPerLeg: "The nameplate limit must be greater than zero.",
    errorAngleValue: "The angle must be entered for the chosen method.",
    errorHeight: "The height of the suspension point must be greater than zero.",
    errorRadius: "The horizontal distance may not be negative.",
    errorAngle: "The angle β from vertical must be in the range 0° to 89.999°.",

    unitKn: "kN",
    unitKgf: "kgf",
    unitM: "m",
    unitDeg: "°",
  },

  "run-of-show": {
    start: "Start time",
    startHint: "HH:MM, 00:00 to 23:59.",
    items: "Running-order cues",
    itemsHint:
      "One row each: name; duration in minutes or H:MM (e.g. 1:30 = 90 min); optionally a fixed time HH:MM. In the “backwards” direction only the last row may carry a fixed time.",
    changeover: "Transition between cues",
    changeoverHint: "Minutes, the same for all cues, 0 to 240.",
    curfew: "Final deadline",
    curfewHint: "HH:MM, as agreed with the venue. Optional.",
    direction: "Direction",
    directionForward: "Forwards, from the start time",
    directionBackward: "Backwards, from the last (pinned) cue",
    buffer: "Reserve before the last cue",
    bufferHint: "Minutes held before the last, pinned cue — only the “backwards” direction uses it.",
    display: "Time display in the table",
    displayAbsolute: "Absolute times",
    displayRelative: "Time from the start",

    results: "Hourly rate",
    colName: "Point",
    colStart: "Start",
    colEnd: "End",
    colDuration: "Duration",
    colShare: "Weight",
    colGapCollision: "Gap / overlap",
    gap: "gap",
    collision: "overlap",
    totalDuration: "Total duration of the cues",
    totalChangeover: "Total transitions",
    totalGap: "Total gaps",
    totalCollision: "Total overlaps",
    span: "Total span",
    curfewRemaining: "Remaining to the final deadline",
    requiredStart: "Required start",
    slack: "Reserve relative to the entered start",

    inputs: "Entered",
    formula:
      "forwards: start_i = end_{i−1} + transition (or the fixed time); end_i = start_i + duration_i     backwards: required_start = pinned_time − Σ(duration + transition) − reserve     gap = fixed − cursor (> 0)     overlap = cursor − fixed (> 0)",

    rowLabel: "line",
    errorItems: "Enter at least one cue, at most 200.",
    errorStart: "The start time must be in the form HH:MM, between 00:00 and 23:59.",
    errorChangeover: "The transition between cues is a number of minutes from 0 to 240.",
    errorCurfew: "The final deadline must be in the form HH:MM, between 00:00 and 23:59.",
    errorBuffer: "The reserve before the last cue may not be negative.",
    errorDuration: "The cue duration must be greater than zero — a number of minutes or H:MM.",
    errorAnchorMissing: "In the “backwards” direction the last cue must have a fixed time.",
    errorAnchorNotLast: "In the “backwards” direction only the last cue may carry a fixed time.",
    errorAnchorFormat: "The fixed time must be in the form HH:MM, between 00:00 and 23:59.",

    unitMin: "min",
  },

  "seating-tables": {
    guests: "Number of guests",
    kind: "Table type",
    kindRound: "Round",
    kindLong: "Long (banquet)",
    diameter: "Table-top diameter",
    length: "Table length",
    width: "Table width",
    ends: "Seating at the ends",
    yes: "Yes",
    no: "No",
    seatWidth: "Seat width per guest",
    clearance: "Clear space around the table",
    clearanceHint:
      "The user's planning dimension for chairs and circulation, per side of the table. Neagle does not offer it as a recommendation — it is not an escape-route width and the tool does not call it one.",
    availableArea: "Available area for tables",
    availableAreaHint: "Optional, only to compare with the area needed.",
    availableWidth: "Available space — width",
    availableSpaceHint:
      "Optional, an alternative to the area — gives the number of tables that fit in a grid, not fluidly.",
    availableDepth: "Available space — depth",

    results: "Result",
    seatsPerTable: "Seats per table",
    tables: "Number of tables needed",
    lastTableGuests: "Guests at the last table",
    cellArea: "Cell area of one table",
    totalCellArea: "Total area of all tables",
    totalCircularFootprint: "Total circular footprint",
    continuousSegments: "Segments of a continuous table",
    continuousLength: "Length of the continuous table",
    continuousCapacity: "Seats at the continuous table",
    continuous: "Continuous table",
    guestsUnit: "guests",
    areaRatio: "Ratio of area needed to available",
    gridFitTables: "Tables fitting the available space (grid)",

    inputs: "Entered",
    formula:
      "round: P=π·D, n=floor(P/s), A_cell=(D+2c)²     long: n=2·floor(L/s)+2·floor(W/s)·[ends], A_cell=(L+2c)(W+2c)     T=ceil(G/n)     A_total=T·A_cell     grid: floor(width/(D+2c))·floor(depth/(D+2c))",

    errorGuests: "The number of guests is a whole number from 1 to 5000.",
    errorSeatWidth: "The seat width per guest is a number from 0.45 to 1.00 m.",
    errorClearance: "The clear space around the table is a number from 0.40 to 2.00 m.",
    errorDiameter: "The table-top diameter is a number from 0.80 to 3.00 m.",
    errorLength: "The table length is a number from 0.80 to 6.00 m.",
    errorWidth: "The table width is a number from 0.60 to 2.00 m.",
    errorTooFewSeats:
      "With this seat width the table does not take even two guests — reduce the seat width or enlarge the table.",
    errorAvailableArea: "The available area may not be negative.",
    errorAvailableSpace: "The available space's width and depth must be greater than zero.",

    unitM: "m",
    unitM2: "m²",
  },

  "stage-deck-layout": {
    width: "Stage width",
    depth: "Stage depth",
    moduleLength: "Deck module length",
    moduleLengthHint: "From the deck's catalogue.",
    moduleWidth: "Deck module width",
    moduleWidthHint: "From the deck's catalogue.",
    stageHeight: "Stage height",
    skirtSides: "Skirt around the perimeter",
    skirtAll: "All sides",
    skirtThree: "Three sides",
    skirtTwo: "Two sides",
    skirtNone: "No skirt",
    totalMass: "Total mass on the stage",
    totalMassHint: "People, backline and equipment together.",
    udlLimit: "Uniform-load limit from the deck manufacturer's table",
    occupancyDensity: "Occupant density on the platform",
    regulatedHint:
      "From the regulation you apply. Neagle does not know which regulation that is and offers no value.",

    results: "Result",
    requiredArea: "Required stage area",
    perimeter: "Stage perimeter",
    skirtArea: "Skirt area",
    mixedNote:
      "Both module orientations are written out in full — a mixed orientation was not considered.",
    positionA: "Position A",
    positionB: "Position B",
    decksWide: "decks across",
    decksDeep: "decks down",
    decks: "number of decks",
    decksUnit: "decks",
    coveredArea: "covered area",
    waste: "surplus over the required area",
    legs: "number of legs",
    massPerLeg: "mass per leg under uniform distribution",
    fewerDecks: "Uses fewer decks",
    fewerDecksEqual: "equal",
    udlAreaNote:
      "The load is calculated over the nominal stage area (width × depth), not over the larger overlapped area the decks actually cover.",
    udl: "Calculated uniform load",
    udlRatio: "Calculated load ÷ manufacturer's limit",
    occupancyPersons: "Number of occupants at the entered density",

    inputs: "Entered",
    formula:
      "A=W·D     perimeter=2(W+D)     position: n_w=ceil(W/l), n_d=ceil(D/w), decks=n_w·n_d, covered=n_w·l·n_d·w     legs=(n_w+1)(n_d+1)     load=mass/A     occupants=floor(A/density)",

    errorWidth: "The stage width is a number from 0.5 to 100 m.",
    errorDepth: "The stage depth is a number from 0.5 to 100 m.",
    errorModuleLength: "The deck module length is a number from 0.5 to 4.0 m.",
    errorModuleWidth: "The deck module width is a number from 0.5 to 4.0 m.",
    errorStageHeight: "The stage height is a number from 0.1 to 3.0 m.",
    errorTotalMass: "The total mass on the stage may not be negative.",
    errorUdlLimit: "The load limit must be greater than zero.",
    errorOccupancyDensity: "The occupant density on the platform must be greater than zero.",

    unitM: "m",
    unitM2: "m²",
    unitKg: "kg",
    unitKgM2: "kg/m²",
  },

  "tent-bay-layout": {
    sizeMode: "Size method",
    sizeModeArea: "Required area",
    sizeModeLength: "Given length",
    requiredArea: "Required covered area",
    requiredLength: "Given length instead of area",
    width: "Tent width",
    bayLength: "Bay length (module)",
    bayLengthHint:
      "A common manufacturer module — check with the manufacturer before relying on it.",
    eaveHeight: "Eaves height",
    roofPitch: "Roof pitch",
    margin: "Clear band around the tent",
    marginHint: "For guy lines and anchoring. The tool suggests neither the number nor the layout of guys or anchors.",
    sides: "Sides",
    sidesAll: "All",
    sidesNoEnds: "Without the ends",
    sidesNone: "None",
    requiredHeadHeight: "Required head height",
    requiredHeadHeightHint: "Optional — the usable width under the pitched roof at this height.",

    results: "Result",
    bays: "Number of bays",
    length: "Total length",
    area: "Covered area",
    waste: "Surplus over the required area",
    lengthDiff: "Difference between the achieved and given length",
    footprint: "Overall size with the clear band",
    tentPerimeter: "Tent perimeter",
    footprintPerimeter: "Perimeter of the overall size (for a request to the venue)",
    ridgeHeight: "Ridge height",
    roofArea: "Roof area",
    sideWallArea: "Side-wall area",
    gableEndsArea: "End-wall area",
    totalSheeting: "Total canvas area",
    sheetingNote:
      "Geometric net area — without seam overlaps, without door openings, without the excluded ends. It is not a material order quantity.",
    legs: "Number of legs",
    usableWidth: "Usable width at the required head height",

    inputs: "Entered",
    formula:
      "n=ceil(A/(w·b)) or ceil(L/b)     L=n·b     A=w·L     ridge: r=(w/2)tan α, h_ridge=h_eaves+r     roof=w·L/cos α     sides=2·L·h     ends=2(w·h+w·r/2)     legs=2(n+1)",

    errorRequiredArea:
      "Enter exactly one of the two — the required area or the given length, neither both nor neither.",
    errorRequiredLength: "The given length must be greater than zero.",
    errorWidth: "The tent width is a number from 3 to 60 m.",
    errorBayLength: "The bay length is a number from 1 to 10 m.",
    errorEaveHeight: "The eaves height is a number from 1.5 to 8 m.",
    errorRoofPitch: "The roof pitch is a number from 5° to 45°.",
    errorMargin: "The clear band may not be negative.",
    errorRequiredHeadHeight:
      "The required head height must be greater than zero and less than the ridge height.",

    unitM: "m",
    unitM2: "m²",
    unitDeg: "°",
  },

  "three-phase-load-balance": {
    lineVoltage: "Line voltage",
    lineVoltageHint: "The installation's nominal voltage. An empty field counts as 400 V.",
    phaseVoltage: "Phase voltage (direct)",
    phaseVoltageHint:
      "Only for a single-phase system where the phase voltage is not derived from the line voltage (e.g. 230 V). It overrides it and returns the line voltage.",
    consumers: "Loads",
    consumersHint:
      "One row each: name; power in W or kW; connection (L1 / L2 / L3 / three-phase / L1L2 / L2L3 / L3L1); power factor cos φ (0.1 to 1.0, negative for a leading load); simultaneity in % (default 100).",
    ratedBreaker: "Rated fuse current per phase",
    regulatedHint: "Copied from the distribution board. Neagle has no fuse list and offers no value.",

    results: "Result per phase",
    colPhase: "Phase",
    colActive: "Active power",
    colReactive: "Reactive power",
    colApparent: "Apparent power",
    colCurrent: "Current",
    phaseL1: "L1",
    phaseL2: "L2",
    phaseL3: "L3",
    breakerRatio: "Current ÷ rated fuse current",
    totalActive: "Total active power",
    totalReactive: "Total reactive power",
    totalApparent: "Total apparent power (vector sum)",
    sumPhaseApparent: "Sum of apparent powers per phase",
    threeTimesMaxPhase: "3 × the most loaded phase",
    powerFactor: "Resulting power factor",
    neutralCurrent: "Neutral current",
    avgCurrent: "Mean current per phase",
    imbalance: "Imbalance",
    modelNote:
      "Harmonics and motor inrush are not modelled — the neutral current of a non-linear load is not the phasor sum of the fundamental components.",

    inputs: "Entered",
    formula:
      "U_LN=U/√3     P=P_rated·(simultaneity/100)     Q=P·tanφ     S_phase=√(P²+Q²)     I_phase=S_phase/U_LN     I_N=|ΣI_phase (phasor)|     imbalance=max|I_k−I_mean|/I_mean",

    rowLabel: "line",
    errorConsumers: "Enter at least one load.",
    errorLineVoltage: "The line voltage is a number from 100 to 1000 V.",
    errorPhaseVoltage: "The phase voltage is a number from 60 to 600 V.",
    errorRatedBreaker: "The rated fuse current is a number from 1 to 630 A.",
    errorKw: "A load's power must be greater than zero.",
    errorCosPhi: "The power factor (by absolute value) is a number from 0.1 to 1.0.",
    errorSimultaneity: "The simultaneity is a number from 0 to 100%.",
    errorConnectionFormat: "The connection was not recognised — L1, L2, L3, three-phase, L1L2, L2L3 or L3L1.",
    errorConnectionRange:
      "With a directly entered phase voltage (single-phase system) the connection must be L1.",

    unitV: "V",
    unitA: "A",
    unitKw: "kW",
    unitKvar: "kvar",
    unitKva: "kVA",
  },

  "truss-hoist-reactions": {
    length: "Truss length",
    selfWeight: "Truss self-weight",
    selfWeightHint: "From the truss's catalogue, kg/m.",
    pointA: "Position of point A",
    pointB: "Position of point B",
    loads: "Loads",
    loadsHint: "One row each: name; mass in kg; position in m from the left end of the truss.",
    extraDistributed: "Additional uniform load",
    extraDistributedHint: "Cables, drapery and the like, kg/m.",
    hoistCapacityA: "Motor capacity at point A",
    hoistCapacityB: "Motor capacity at point B",
    regulatedHint: "From the motor's nameplate. Neagle has no motor list and offers no value.",
    slingAngle: "Sling angle from vertical",
    slingAngleHint: "Optional — gives the force in the sling instead of the vertical reaction alone.",

    results: "Result",
    totalMass: "Total mass on the truss",
    pointMass: "Load mass",
    distributedMass: "Self-weight and additional uniform mass",
    swappedNote:
      "Points A and B were swapped because A was entered to the right of B — the calculation proceeds with the smaller coordinate as A.",
    reactionA: "Force at point A",
    reactionB: "Force at point B",
    uplift: "lifting",
    cogPosition: "Centre-of-gravity position",
    checkResidual: "Check residual (must be ~0)",
    maxMoment: "Maximum bending moment",
    shearA: "Shear force at point A",
    shearB: "Shear force at point B",
    equivalentUdl: "Equivalent uniform load",
    ratioA: "Force at A ÷ motor capacity A",
    ratioB: "Force at B ÷ motor capacity B",
    legTensionNote:
      "The force in the sling at the pick angle — the reaction is the vertical component, and the motor pulls a larger force through the sling.",
    legTensionA: "Sling force, point A",
    legTensionB: "Sling force, point B",

    inputs: "Entered",
    formula:
      "M=ΣM_i+M_w     R_B=[Σm_i(x_i−x_A)+M_w(L/2−x_A)]/(x_B−x_A)     R_A=M−R_B     x_cg=[Σm_i·x_i+M_w·L/2]/M     q_equiv=8·M_max/span²     sling=R/cosβ",

    rowLabel: "line",
    errorLength: "The truss length must be greater than zero.",
    errorSelfWeight: "The truss self-weight may not be negative.",
    errorPointA: "The position of point A must be between 0 and the truss length, and different from point B.",
    errorPointB: "The position of point B must be between 0 and the truss length.",
    errorExtraDistributed: "The additional uniform load may not be negative.",
    errorNoLoad: "The truss has no mass at all — enter a self-weight, an additional load or a load.",
    errorHoistCapacityA: "The motor capacity at point A must be greater than zero.",
    errorHoistCapacityB: "The motor capacity at point B must be greater than zero.",
    errorSlingAngle: "The sling angle is a number from 0° to 89°.",
    errorMass: "The load mass must be greater than zero.",
    errorPosition: "The load position must be between 0 and the truss length.",

    unitM: "m",
    unitKg: "kg",
    unitKn: "kN",
    unitKgm: "kg·m",
    unitKgPerM: "kg/m",
  },

  "venue-occupancy-area": {
    grossArea: "Gross area",
    zones: "Deducted zones",
    zonesHint:
      "One row each: name; area in m² (stage, bar, dance floor, technical area, circulation). Exclusively with the “deducted as a percentage” field.",
    deductPct: "Deducted as a percentage",
    deductPctHint: "Instead of the individual zones, not alongside them.",
    layouts: "Layouts",
    layoutsHint:
      "One row each: layout name; density in m²/person; gross or net (which area the density applies to); optionally the occupant count from the venue's documentation.",
    guests: "Number of guests",
    guestsHint: "Optional — for the reverse calculation, the area per person and the area needed.",

    results: "Result",
    netArea: "Net area",
    deductedArea: "Sum of the deducted zones",
    areaPerGuest: "Area per person for the entered number of guests",
    layoutFallback: "Layout",
    basisUsed: "Density applied to",
    basisGross: "Gross area",
    basisNet: "Net area",
    personsAtDensity: "Number of people at the entered density",
    requiredAreaDiff: "Difference between the net area and the area needed for guests",
    documented: "Occupant count from the venue's documentation",
    ratio: "Ratio",
    personsUnit: "people",

    inputs: "Entered",
    formula:
      "A_net=A_gross−deducted (zones or %)     N=floor(area/density)     A_needed=G·density",

    rowLabel: "line",
    errorGrossArea: "The gross area is a number from 1 to 100,000 m².",
    errorDeduction: "Enter either the zones or the deduction percentage — not both.",
    errorNetArea:
      "The deducted zones and percentage exceed the gross area — the net area must be greater than zero.",
    errorLayouts: "Enter at least one layout.",
    errorGuests: "The number of guests must be greater than zero.",
    errorDeductPct: "The deduction percentage is a number from 0 to 90%.",
    errorZoneArea: "A zone's area may not be negative.",
    errorDensity: "The density must be greater than zero.",
    errorDocumentedCount: "The occupant count from the venue's documentation must be greater than zero.",
    errorBasisFormat: "The density basis was not recognised — write “gross” or “net”.",

    unitM2: "m²",
    unitM2PerPerson: "m²/person",
  },

  "voltage-drop": {
    system: "System",
    systemDc: "DC",
    systemSinglePhase: "Single-phase",
    systemThreePhase: "Three-phase",
    material: "Conductor material",
    materialCopper: "Copper",
    materialAluminium: "Aluminium",
    mode: "Direction of calculation",
    modeForward: "Given cross-section → voltage drop",
    modeReverse: "Given voltage drop → required cross-section",
    crossSection: "Conductor cross-section",
    crossSectionHint:
      "Copied from the cable, mm². Required unless the resistance from the label is entered.",
    customResistance: "Resistance from the cable's label",
    customResistanceHint:
      "Ω/km — when entered, it bypasses the calculation from cross-section and material entirely.",
    length: "Route length in one direction",
    current: "Current",
    nominalVoltage: "Nominal voltage",
    nominalVoltageHint: "Required for the drop percentage, the end-of-line voltage and the reverse calculation.",
    conductorTemp: "Conductor temperature",
    conductorTempHint: "An empty field counts as 20 °C, the reference temperature for the resistance.",
    dropLimit: "Voltage-drop limit you apply",
    regulatedHint:
      "From a regulation, a design or the job's conditions. Neagle does not offer it even as a default.",

    results: "Result",
    resistance: "Line resistance",
    dropVolts: "Voltage drop",
    perPhaseNote: "The three-phase drop above is PHASE-TO-PHASE. The drop per phase (÷√3) is a separate row below.",
    dropVoltsPerPhase: "Voltage drop per phase",
    dropPct: "Voltage drop as % of the nominal voltage",
    farEndVoltage: "Voltage at the end of the line",
    powerLoss: "Power loss",
    dropRatio: "Calculated drop ÷ limit",
    requiredSection: "Required cross-section (without rounding to the standard series)",
    selectedSection: "Selected standard cross-section (IEC 60228)",
    noStandardSection: "no standard cross-section in the series",

    inputs: "Entered",
    formula:
      "ρ(θ)=ρ₂₀(1+α(θ−20))     R₁=ρ(θ)·L/S     DC/single-phase: ΔU=2·I·R₁     three-phase: ΔU=√3·I·R₁ (phase-to-phase), ΔU_phase=ΔU/√3     ΔU%=ΔU/U·100     reverse: S=ρ(θ)·L/R₁_target, R₁_target=ΔU_target/(k·I)",

    errorLength: "The route length is a number from 0.1 to 5000 m.",
    errorCurrent: "The current is a number from 0.01 to 2000 A.",
    errorConductorTemp: "The conductor temperature is a number from −20 to 120 °C.",
    errorNominalVoltage: "The nominal voltage is a number from 12 to 1000 V — required in the reverse direction.",
    errorDropLimit: "The voltage-drop limit is a number from 0.1 to 20% — required in the reverse direction.",
    errorCrossSection:
      "The conductor cross-section is a number from 0.5 to 630 mm², or enter the resistance from the cable's label.",
    errorCustomResistance: "The resistance from the cable's label must be greater than zero.",

    unitOhm: "Ω",
    unitV: "V",
    unitW: "W",
    unitMm2: "mm²",
    unitM: "m",
    unitA: "A",
  },
} as const;
