/**
 * „Kuhinja i pekara" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as the assignment spells the
 * registration. The tool's NAME and its one-line blurb are not here: those
 * live in a different table another process owns.
 *
 * **Two tools in this pack carry an absolute discipline.** `brine-salt`
 * (food-safety) and `solution-concentration` (life-safety) may name a
 * quantity and the user's own limit, and may never say what the two mean
 * together — no „bezbedno", no „dovoljno", no „ispravno", no verdict of any
 * kind, anywhere in this file.
 *
 * **A unit is copy, not a constant.** „g" and „ml" are written here rather
 * than concatenated in the surface, so a translator can find every one of
 * them and a raw string never hides inside a component.
 */
export const PRO_KUHINJA_SR = {
  "backwards-timeline": {
    serviceTime: "Vreme serviranja",
    serviceTimeHint: "Sat u koji jelo mora biti na stolu, HH:MM, 24-časovni zapis.",
    serviceDate: "Datum serviranja",
    serviceDateHint:
      "Opciono — samo da bi oznaka dana bila konkretan datum, a ne „−1 dan\". Bez ovog polja današnji dan se ne pretpostavlja.",
    steps: "Koraci pripreme",
    stepsHint:
      "Jedan red po koraku, redom kojim se izvode: naziv;trajanje. Trajanje kao „12\" je 12 minuta, a „12:00\" je 12 sati — dvotačka bira sate i minute, go broj bira minute.",
    buffer: "Rezerva pre serviranja",
    bufferHint: "Minuti slobodnog vremena između poslednjeg koraka i serviranja. Prazno polje znači da rezerve nema.",

    results: "Rezultat",
    colStep: "Korak",
    colStart: "Početak",
    colEnd: "Kraj",
    colMinutes: "Trajanje (min)",
    bufferRowName: "Rezerva",
    totalLabel: "Ukupno trajanje pripreme",
    jobStart: "Ceo posao počinje",
    wallClockNote:
      "Alat računa u zidnom vremenu. Ne pomera ništa zbog prelaska na letnje ili zimsko računanje vremena.",
    dayWordOne: "dan",
    dayWordMany: "dana",

    inputs: "Uneseno",
    formula: "pomak_i = −(rezerva + Σd_j, j=i..n)     trenutak = ((serviranje + pomak) mod 1440), podno deljenje",

    errorServiceTime: "Vreme serviranja mora biti u obliku HH:MM, 24-časovni zapis.",
    errorServiceDate: "Datum serviranja mora biti u obliku GGGG-MM-DD i mora postojati u kalendaru.",
    errorSteps: "Unesi bar jedan korak.",
    errorBuffer: "Rezerva je ceo broj minuta, nula ili više.",
    errorStepDuration:
      "Trajanje koraka nije prepoznato. Dvotačka bira sate i minute (12:00 = 12 sati), go broj bira minute (12 = 12 minuta).",
  },

  "bakers-percentage": {
    mode: "Režim",
    modeWeightsToPercent: "Težine → procenti",
    modePercentToWeights: "Procenti → težine",
    lines: "Stavke recepta",
    linesHint:
      "Jedan red po sastojku: naziv;uloga;vrednost. Uloga je jedna od reči „brašno\", „voda\", „ostalo\" ili „predferment\" — vrednost je masa u gramima (režim 1) ili procenat od brašna (režim 2). Predferment se ne deli ovde: alat ga odbija i uputi na „Hidratacija i starter\".",
    targetMode: "Cilj",
    targetModeMass: "Ciljna masa testa",
    targetModePieces: "Broj komada",
    pieces: "Broj komada",
    bakedPieceMass: "Masa pečenog komada",
    bakeLoss: "Gubitak pečenjem",
    bakeLossHint: "Procenat mase koji komad izgubi u peći, meren na sopstvenoj peći.",

    results: "Rezultat",
    colName: "Sastojak",
    colRole: "Uloga",
    colPercent: "%",
    colWeight: "Masa",
    roleFlour: "brašno",
    roleWater: "voda",
    roleOther: "ostalo",
    rolePreferment: "predferment",
    totalPercent: "Zbir procenata",
    flourWeight: "Masa brašna",
    doughMass: "Masa testa",
    hydration: "Hidratacija",
    hydrationNote:
      "Uračunati su isključivo redovi koje si označio kao vodu — mleko, jaja i ulje ulaze samo ako si ih tako obeležio.",
    rawPieceMass: "Masa sirovog komada",

    inputs: "Uneseno",
    formula: "režim 1: p_i = w_i/F·100, D=Σw_i     režim 2: F=D/(Σp/100), w_i=F·p_i/100     komadi: sirov=pečen/(1−L/100)",

    errorLines: "Unesi bar jedan sastojak.",
    errorLineValue: "Vrednost svakog sastojka mora biti nula ili više.",
    errorPreferment:
      "Predferment nije ni brašno ni voda — podeli ga alatom „Hidratacija i starter\" pa unesi dobijeno brašno i vodu kao zasebne redove.",
    errorFlour: "Bar jedan red mora biti označen kao brašno, sa masom ili procentom većim od nule.",
    errorDoughMass: "Ciljna masa testa mora biti veća od nule.",
    errorPieces: "Broj komada je ceo broj, 1 ili više.",
    errorBakedPieceMass: "Masa pečenog komada mora biti veća od nule.",
    errorBakeLoss: "Gubitak pečenjem je procenat od 0 do ispod 100.",
    errorFlourPercentSum:
      "U režimu „procenti → težine\" redovi označeni kao brašno moraju zbirno dati tačno 100 %.",

    unitG: "g",
  },

  "brine-salt": {
    mode: "Režim",
    modeBrine: "Ravnotežna salamura",
    modeDryCure: "Suvo soljenje",
    modeConcentration: "Koncentracija postojeće salamure",
    basis: "Osnova procenta",
    basisFoodAndWater: "% od mesa i vode",
    basisTotalWithSalt: "% od ukupne mase sa solju",
    foodMass: "Masa mesa ili povrća",
    waterMass: "Masa vode",
    waterMassHint: "Unosi se kao masa, ne zapremina, da se ne bi pretpostavljala gustina vode.",
    saltPercent: "Ciljni procenat soli",
    dissolvedSalt: "So već rastvorena u salamuri",
    sugarPercent: "Ciljni procenat šećera",
    sugarPercentHint: "Opciono, na istoj osnovi kao so. Računa se nezavisno od soli.",
    percentLimit: "Granica koju si uneo",
    percentLimitHint: "Iz propisa koji primenjuješ. Nexus ne zna koji je to propis i ne nudi vrednost.",

    results: "Rezultat",
    saltMass: "Masa soli",
    sugarMass: "Masa šećera",
    totalMass: "Ukupna masa rastvora sa namirnicom",
    percentOfBase: "So kao % od mesa i vode",
    percentOfTotal: "So kao % od ukupne mase sa solju",
    selectedPercent: "So na izabranoj osnovi",
    percentRatio: "Odnos prema tvojoj granici",

    inputs: "Uneseno",
    formula:
      "% od mesa i vode: S=(M+W)·p/100     % od ukupnog sa solju: S=(M+W)·p/(100−p)     koncentracija: p=S/(S+W)·100",

    errorWaterMass: "Masa vode mora biti veća od nule.",
    errorDissolvedSalt: "So već rastvorena u salamuri ne sme biti negativna.",
    errorFoodMass: "Masa mesa ili povrća mora biti veća od nule.",
    errorSaltPercent: "Ciljni procenat soli je broj strogo između 0 i 100.",
    errorSugarPercent: "Ciljni procenat šećera je broj od 0 do ispod 100, a zbir sa procentom soli ne sme dostići 100 na osnovi „% od ukupnog\".",

    unitG: "g",
  },

  "coffee-extraction": {
    dose: "Doza mlevene kafe",
    brewWater: "Voda za kuvanje",
    brewWaterHint: "Opciono kod espresa, gde se ne meri posebno.",
    beverageMass: "Masa napitka u šolji",
    tds: "TDS (rastvorena materija)",
    tdsHint: "Procenat po masi, izmeren refraktometrom, već korigovan činiocem tvog instrumenta.",
    targetRatio: "Ciljni odnos vode prema dozi (1:x)",

    results: "Rezultat",
    waterRatio: "Odnos voda ÷ doza",
    beverageRatio: "Odnos napitak ÷ doza",
    extractionYield: "Procenat ekstrakcije",
    dissolved: "Rastvorena materija u šolji",
    retained: "Voda zadržana u talogu",
    weighingShortfall: "Razlika koju merenja ne objašnjavaju",
    weighingShortfallNote:
      "Napitak je teži od upotrebljene vode za kuvanje — dva merenja se ne slažu, pa zadržana voda nije prikazana.",
    waterForTarget: "Voda za zadati odnos",

    inputs: "Uneseno",
    formula:
      "voda÷doza = voda/doza     napitak÷doza = napitak/doza     ekstrakcija% = napitak·TDS/doza     zadržano = voda−napitak",

    errorDose: "Doza mlevene kafe mora biti veća od nule.",
    errorBeverageMass: "Masa napitka u šolji mora biti veća od nule.",
    errorTds: "TDS je procenat strogo između 0 i 100.",
    errorBrewWater: "Voda za kuvanje mora biti veća od nule.",
    errorTargetRatio: "Ciljni odnos mora biti veći od nule.",

    unitG: "g",
  },

  "dough-water-temp": {
    mode: "Režim",
    modeWaterTemperature: "Temperatura vode",
    modeFrictionFactor: "Faktor trenja iz izmerene šarže",
    flourTemp: "Temperatura brašna",
    roomTemp: "Temperatura prostorije",
    hasPreferment: "Predferment u šarži",
    hasPrefermentNo: "Nema predfermenta",
    hasPrefermentYes: "Ima predfermenta",
    prefermentTemp: "Temperatura predfermenta",
    desiredDoughTemp: "Željena temperatura testa",
    frictionFactor: "Faktor trenja",
    frictionFactorHint: "Meri ga pekar za svoju mešalicu, svoju šaržu i svoje vreme mešenja.",
    frictionN: "N pri kome je faktor trenja izmeren",
    frictionNHint:
      "Faktor trenja važi samo za onaj N pri kome je izmeren — sa istom mešalicom, veličinom šarže i vremenom mešenja. N=3 je brašno+prostorija, N=4 dodaje predferment.",
    frictionN3: "N=3 (bez predfermenta)",
    frictionN4: "N=4 (sa predfermentom)",
    availableWaterTemp: "Najviša temperatura vode koju imaš",
    measuredDoughTemp: "Izmerena temperatura testa",
    measuredWaterTemp: "Izmerena temperatura vode",

    results: "Rezultat",
    multiplier: "Množilac N",
    components: "Sabrane temperature",
    waterTemp: "Potrebna temperatura vode",
    belowFreezingNote:
      "Voda na ovoj temperaturi pri atmosferskom pritisku nije tečna — ova šarža se ne može voditi samo vodom.",
    availableDelta: "Razlika (potrebna − raspoloživa)",

    inputs: "Uneseno",
    formula: "voda = N·željena_temp − Σ(komponente + trenje)     trenje = N·izmereno_testo − Σ(komponente + izmerena_voda)",

    errorFlourTemp: "Temperatura brašna je broj od −10 do 60 °C.",
    errorRoomTemp: "Temperatura prostorije je broj od −10 do 60 °C.",
    errorPrefermentTemp: "Temperatura predfermenta je broj od −10 do 60 °C.",
    errorDesiredDoughTemp: "Željena temperatura testa je broj od −10 do 60 °C.",
    errorFrictionFactor: "Faktor trenja je broj od 0 do 40 °C.",
    errorFrictionFactorMeasuredAtN:
      "N pri kome je faktor trenja izmeren mora odgovarati ovoj šarži — sa predfermentom N=4, bez njega N=3.",
    errorAvailableWaterTemp: "Najviša temperatura vode koju imaš je broj od −10 do 60 °C.",
    errorMeasuredDoughTemp: "Izmerena temperatura testa je broj od −10 do 60 °C.",
    errorMeasuredWaterTemp: "Izmerena temperatura vode je broj od −10 do 60 °C.",

    unitC: "°C",
  },

  "ice-cream-overrun": {
    mode: "Režim",
    modeFromWeighings: "Iz dva merenja iste posude",
    modeFromTarget: "Iz zadatog overruna",
    grossMixMass: "Masa posude sa smesom",
    grossFrozenMass: "Masa posude sa gotovim sladoledom",
    tare: "Tara posude",
    tareHint:
      "Obavezno polje — sa tarom u obe mase izračunati overrun bude tiho manji od stvarnog. Oba punjenja moraju dosezati isti nivo u istoj posudi.",
    targetOverrun: "Ciljni overrun",
    mixVolume: "Zapremina smese",
    mixDensity: "Gustina smese",
    tubVolume: "Zapremina pakovanja",

    results: "Rezultat",
    overrun: "Overrun",
    netMixMass: "Neto masa smese",
    netFrozenMass: "Neto masa gotovog proizvoda",
    frozenVolume: "Zapremina gotovog sladoleda",
    finishedMassPerLitre: "Masa gotovog proizvoda po litru",
    tubNetWeight: "Neto težina pakovanja",

    inputs: "Uneseno",
    formula: "overrun% = (m_smesa−m_smrznuto)/m_smrznuto·100     V_izlaz = V_ulaz·(1+OR/100)     gustina_gotovog = gustina_smese/(1+OR/100)",

    errorGrossMixMass: "Masa posude sa smesom mora biti veća od nule.",
    errorGrossFrozenMass: "Masa posude sa gotovim sladoledom mora biti veća od nule.",
    errorTare: "Tara ne sme biti negativna niti veća ili jednaka bilo kojoj od dve mase.",
    errorTargetOverrun: "Ciljni overrun mora biti veći od −100 %.",
    errorMixVolume: "Zapremina smese mora biti veća od nule.",
    errorMixDensity: "Gustina smese mora biti veća od nule.",
    errorTubVolume: "Zapremina pakovanja mora biti veća od nule, a gustina smese mora biti uneta.",

    unitG: "g",
    unitL: "l",
    unitGPerL: "g/l",
  },

  "lamination-layers": {
    folds: "Niz presavijanja",
    foldsHint:
      "Jedan red po presavijanju, redom kojim se izvode: vrsta ili vrsta;debljina posle valjanja u mm. Vrsta je jedna od reči „jednostruko\" (×3), „knjiga\" (×4) ili „napola\" (×2). Debljina posle valjanja je opciona — bez nje red ostaje samo presavijen, bez razvijanja.",
    startingFatLayers: "Početni broj slojeva masti",
    startingFatLayersHint: "Prazno polje znači 1 — jedan blok masti zatvoren u testo.",
    fatMass: "Masa masti",
    doughMass: "Masa testa oko masti",
    finalThickness: "Završna debljina razvijenog testa",
    startThickness: "Početna debljina",
    startLength: "Početna dužina",

    results: "Rezultat",
    fatLayers: "Broj slojeva masti",
    doughLayers: "Broj slojeva testa",
    fatLayerMicrons: "Debljina jednog sloja masti",
    doughLayerMicrons: "Debljina jednog sloja testa",
    colFold: "Presavijanje",
    colFoldedThickness: "Debljina posle presavijanja",
    colFoldedLength: "Dužina posle presavijanja",
    colRolledThickness: "Debljina posle valjanja",
    colRolledLength: "Dužina posle valjanja",
    foldLetter: "jednostruko",
    foldBook: "knjiga",
    foldHalf: "napola",
    constantWidthNote: "Odnos dužine i debljine pri valjanju važi samo pri stalnoj širini trake.",

    inputs: "Uneseno",
    formula:
      "B=B₀·Πf_i     D=B+1     φ=masa_masti/(masa_masti+masa_testa)     t_mast=t·φ/B     t_testo=t·(1−φ)/D",

    errorFolds: "Unesi bar jedno presavijanje, svako prepoznato kao „jednostruko\", „knjiga\" ili „napola\".",
    errorStartingFatLayers: "Početni broj slojeva masti je ceo broj, 1 ili više.",
    errorFinalThickness: "Završna debljina mora biti veća od nule i ne veća od debljine dostignute na kraju niza presavijanja i valjanja.",
    errorFatMass: "Masa masti mora biti veća od nule.",
    errorDoughMass: "Masa testa oko masti mora biti veća od nule.",
    errorStartThickness: "Početna debljina mora biti veća od nule.",
    errorStartLength: "Početna dužina mora biti veća od nule.",
    errorRollThickness: "Debljina posle valjanja mora biti veća od nule i manja od debljine odmah posle tog presavijanja.",

    unitMm: "mm",
    unitCm: "cm",
    unitUm: "µm",
    unitG: "g",
  },

  "levain-hydration": {
    mode: "Režim",
    modeCorrectDough: "Ispravi testo",
    modeBuildLevain: "Napravi starter",
    totalFlour: "Ukupno brašno u gotovom testu",
    totalFlourHint: "Uključuje i brašno koje nosi starter, ne samo brašno koje se dodaje naknadno.",
    targetHydration: "Ciljna ukupna hidratacija",
    levainMass: "Masa startera ili predfermenta",
    levainHydration: "Hidratacija startera",
    seedMass: "Masa zametka",
    seedHydration: "Hidratacija zametka",
    targetLevainMass: "Ciljna masa startera",
    targetLevainHydration: "Ciljna hidratacija startera",

    results: "Rezultat",
    levainFlour: "Brašno koje starter unosi",
    levainWater: "Voda koju starter unosi",
    addedFlour: "Brašno koje još treba dodati",
    addedWater: "Voda koju još treba dodati",
    doughMass: "Ukupna masa testa bez soli i dodataka",
    achievedHydration: "Postignuta ukupna hidratacija",

    inputs: "Uneseno",
    formula: "f=masa/(1+h/100), w=masa−f     dodato_brašno=F_ukupno−f_starter     dodata_voda=W_ukupno−w_starter",

    errorTotalFlour: "Ukupno brašno u gotovom testu mora biti veće od nule.",
    errorTargetHydration: "Ciljna ukupna hidratacija mora biti veća od nule.",
    errorLevainMass: "Masa startera ne sme biti negativna niti veća od ukupne mase testa.",
    errorLevainHydration: "Hidratacija startera mora biti veća od nule.",
    errorSeedMass: "Masa zametka ne sme biti negativna.",
    errorSeedHydration: "Hidratacija zametka mora biti veća od nule.",
    errorTargetLevainMass: "Ciljna masa startera mora biti veća od mase zametka.",
    errorTargetLevainHydration: "Ciljna hidratacija startera mora biti veća od nule.",
    errorFlourOver: "Starter već nosi više brašna nego što formula dozvoljava — smanji njegovu masu ili hidrataciju.",
    errorWaterOver: "Starter već nosi više vode nego što ciljna hidratacija dozvoljava — smanji njegovu masu ili hidrataciju.",

    unitG: "g",
  },

  "nutrition-per-portion": {
    direction: "Smer",
    directionPer100ToPortion: "Na 100 g → po porciji",
    directionPortionToPer100: "Po porciji → na 100 g",
    energy: "Energija",
    energyUnit: "Jedinica energije",
    fat: "Masti",
    satFat: "od toga zasićene masne kiseline",
    carbs: "Ugljeni hidrati",
    sugars: "od toga šećeri",
    fiber: "Vlakna",
    protein: "Belančevine",
    salt: "So",
    portionMass: "Masa porcije",
    packageMass: "Masa pakovanja",
    packageMassHint: "Opciono. Ako je i broj porcija u pakovanju unet, dva podatka moraju da se slažu.",
    portionsPerPackage: "Broj porcija u pakovanju",
    referencePrefix: "Referentni dnevni unos —",
    referenceHint: "Iz propisa koji primenjuješ. Nexus nema nikakvu tabelu i ne nudi vrednost.",
    digits: "Broj decimala za prikaz",
    digitsHint: "Izbor prikaza, ne zaokruživanje zakonske deklaracije — šta i kako mora da stoji na pakovanju određuje propis koji ovaj alat ne poznaje.",

    results: "Rezultat",
    energyKJ: "Energija (kJ) — na 100 g / po porciji",
    energyKcal: "Energija (kcal) — na 100 g / po porciji",
    colNutrient: "Materija",
    colPer100: "Na 100 g",
    colPerPortion: "Po porciji",
    colPerPackage: "Po pakovanju",
    colReferencePercent: "% reference",
    notADeclarationNote:
      "Ovo je pomoćni preračun, ne gotova deklaracija. Nijedna vrednost ne dolazi iz alata — sve je uneo korisnik, a alat ih samo preračunava. Šta mora da stoji na pakovanju određuje propis koji ovaj alat ne poznaje i ne proverava.",

    inputs: "Uneseno",
    formula: "po_porciji = na_100g·masa_porcije/100     kcal = kJ/4,184     % reference = po_porciji/referenca·100",

    errorPortionMass: "Masa porcije mora biti veća od nule.",
    errorEnergy: "Energija ne sme biti negativna.",
    errorNutrientValue: "Vrednost svake materije ne sme biti negativna.",
    errorReference: "Referentni dnevni unos ne sme biti negativan.",
    errorPackageMass: "Masa pakovanja mora biti veća od nule.",
    errorPortionsPerPackage: "Broj porcija u pakovanju je ceo broj, 1 ili više.",
    errorPackage: "Masa pakovanja i broj porcija u pakovanju se ne slažu sa masom porcije.",

    unitG: "g",
    unitKj: "kJ",
    unitKcal: "kcal",
  },

  "pan-area-volume": {
    sectionA: "Kalup ili posuda A",
    sectionB: "Kalup ili posuda B",
    shapeKind: "Oblik",
    shapeCircle: "Krug (prečnik)",
    shapeSquare: "Kvadrat (stranica)",
    shapeRect: "Pravougaonik (a × b)",
    shapeRing: "Venac (spoljni/unutrašnji prečnik)",
    diameter: "Prečnik",
    side: "Stranica",
    a: "Dimenzija a",
    b: "Dimenzija b",
    outer: "Spoljni prečnik",
    inner: "Unutrašnji prečnik",
    hasShapeB: "Preračun za drugi kalup",
    hasShapeBNo: "Ne treba",
    hasShapeBYes: "Treba",
    batterMassA: "Masa smese u kalupu A",
    fillHeight: "Visina punjenja (kalup A)",
    targetVolume: "Ciljna zapremina (kalup A)",

    results: "Rezultat",
    areaA: "Površina A",
    areaB: "Površina B",
    swapFactor: "Faktor zamene A_B/A_A",
    massB: "Masa smese za kalup B",
    massBNote: "Preračun važi samo ako smesa u oba kalupa stoji na istoj visini.",
    volumeAtHeight: "Zapremina pri visini punjenja",
    heightForVolume: "Visina punjenja za ciljnu zapreminu",
    straightWalledNote:
      "Zapremina = površina × visina tretira posudu kao pravostranu. Za venac važi samo ako cev ide punom visinom, a za konusan ili sužen kalup (kuglof) koristi preračun zarubljene kupe ispod.",

    frustumTitle: "Zarubljena kupa — kalup sa sužavanjem",
    topDiameter: "Prečnik pri vrhu",
    bottomDiameter: "Prečnik pri dnu",
    frustumHeight: "Visina",
    frustumVolume: "Zapremina",
    frustumFormula: "V = π·h·(R²+R·r+r²)/3",

    inputs: "Uneseno",
    formula: "krug: A=π(d/2)²     kvadrat: A=a²     pravougaonik: A=a·b     venac: A=π((D/2)²−(d/2)²)     V=A·h     h=1000·V/A",

    errorDiameter: "Prečnik mora biti veći od nule.",
    errorSide: "Stranica mora biti veća od nule.",
    errorA: "Dimenzija a mora biti veća od nule.",
    errorB: "Dimenzija b mora biti veća od nule.",
    errorRing: "Prečnici venca moraju biti veći od nule, a unutrašnji manji od spoljnog.",
    errorFillHeight: "Visina punjenja mora biti veća od nule.",
    errorTargetVolume: "Ciljna zapremina mora biti veća od nule.",
    errorBatterMassA: "Masa smese u kalupu A mora biti veća od nule.",
    errorTopDiameter: "Prečnik pri vrhu mora biti veći od nule.",
    errorBottomDiameter: "Prečnik pri dnu mora biti veći od nule.",
    errorFrustumHeight: "Visina mora biti veća od nule.",

    unitCm: "cm",
    unitCm2: "cm²",
    unitG: "g",
    unitL: "l",
  },

  "plate-cost": {
    lines: "Stavke jela",
    linesHint:
      "Jedan red po sastojku: naziv;količina;jedinica;nabavna cena po kg/l/kom;randman %. Jedinica je g, ml ili kom. Randman je isti složeni randman (čišćenje × termička obrada) koji daje „Randman i kalo\".",
    portions: "Broj porcija koje recept daje",
    targetFoodCost: "Ciljni food-cost",
    extraPerPortion: "Dodatni trošak po porciji",
    extraPerPortionHint: "Opciono — ambalaža, dodaci i slično.",

    results: "Rezultat",
    colName: "Sastojak",
    colUsed: "Neto količina",
    colCost: "Trošak",
    colShare: "Udeo",
    total: "Ukupan trošak recepta",
    costPerPortion: "Trošak po porciji",
    sellingPrice: "Prodajna cena",
    netPriceNote:
      "Neto iznos, bez ijednog poreza. Alat ne primenjuje PDV niti bilo koju drugu stopu — stope propisuje država i menjaju se; ako ih želiš u računu, unesi ih sam u zaseban alat za procente.",
    margin: "Marža po porciji",

    inputs: "Uneseno",
    formula: "trošak_reda = (količina/randman%)·cena     trošak_porcije = Σtrošak_reda/porcije+dodatak     prodajna=trošak_porcije/(fc/100)",

    errorLines: "Unesi bar jednu stavku.",
    errorPortions: "Broj porcija je ceo broj, 1 ili više.",
    errorTargetFoodCost: "Ciljni food-cost je broj strogo veći od 0 i do 100 %.",
    errorExtraPerPortion: "Dodatni trošak po porciji ne sme biti negativan.",
    errorQuantity: "Količina svake stavke ne sme biti negativna.",
    errorUnitPrice: "Nabavna cena svake stavke ne sme biti negativna.",
    errorYieldPercent: "Randman svake stavke je broj strogo veći od 0 i do 100 %.",
    errorUnit: "Jedinica svake stavke je g, ml ili kom.",

    unitCurrency: "RSD",
    unitG: "g",
    unitMl: "ml",
    unitPiece: "kom",
  },

  "portions-from-pack": {
    packQuantity: "Količina u pakovanju",
    packUnit: "Jedinica pakovanja",
    portionQuantity: "Veličina porcije",
    portionUnit: "Jedinica porcije",
    lossPercent: "Gubitak u pakovanju",
    portionsNeeded: "Potreban broj porcija",
    packPrice: "Cena pakovanja",

    results: "Rezultat",
    portionsPerPack: "Broj porcija po pakovanju",
    leftover: "Ostatak u pakovanju",
    yieldPercent: "Randman (100 − gubitak)",
    packsNeeded: "Broj pakovanja za traženi broj porcija",
    surplusPortions: "Višak porcija",
    totalCost: "Ukupan trošak pakovanja",
    pricePerPortion: "Cena po porciji",
    unitPrice: "Cena po kg, l ili komadu",

    inputs: "Uneseno",
    formula: "upotrebljivo=pakovanje·(1−gubitak/100)     porcije=floor(upotrebljivo/porcija)     pakovanja=ceil(potrebno/porcije)",

    errorPackUnit: "Jedinica pakovanja je g, kg, ml, l ili kom.",
    errorPortionUnit: "Jedinica porcije je g, kg, ml, l ili kom.",
    errorUnitMismatch: "Pakovanje i porcija moraju biti iste dimenzije — masa se ne pretvara u zapreminu ni obrnuto.",
    errorPackQuantity: "Količina u pakovanju mora biti veća od nule.",
    errorPortionQuantity: "Veličina porcije mora biti veća od nule.",
    errorLossPercent: "Gubitak u pakovanju je procenat od 0 do ispod 100.",
    errorPortionsNeeded: "Potreban broj porcija je ceo broj, 1 ili više.",
    errorPackPrice: "Cena pakovanja ne sme biti negativna.",
    errorPortionLargerThanPack: "Porcija je veća od upotrebljivog sadržaja pakovanja — nijedna cela porcija ne staje.",

    unitCurrency: "RSD",
    unitG: "g",
    unitKg: "kg",
    unitMl: "ml",
    unitL: "l",
    unitPiece: "kom",
  },

  "ratio-split": {
    total: "Ukupna količina",
    unit: "Jedinica",
    unitHint: "Slobodan tekst, npr. g, kg, ml, l — ispisuje se uz svaku vrednost.",
    ratio: "Odnos",
    ratioHint: "Dva ili više članova odvojena dvotačkom, npr. 3:2:1. Svaki član ≥ 0, bar jedan > 0.",
    names: "Nazivi delova",
    namesHint: "Opciono, po jedan naziv u redu, istim redosledom kao članovi odnosa.",
    step: "Korak zaokruživanja",
    stepHint: "U jedinici iznad. Prazno polje znači 0,01.",

    results: "Rezultat",
    colName: "Deo",
    colRatioPart: "Član odnosa",
    colExact: "Tačno",
    colAmount: "Zaokruženo",
    colShare: "Udeo",
    partPrefix: "Deo",
    unallocated: "Neraspoređeni ostatak",

    inputs: "Uneseno",
    formula: "deo_i = ukupno·r_i/Σr, zaokruženo po najvećem ostatku (Hare) na broj koraka = floor(ukupno/korak)",

    errorRatio: "Odnos mora imati bar dva broja odvojena dvotačkom, svaki nula ili veći, bar jedan veći od nule.",
    errorTotal: "Ukupna količina mora biti veća od nule.",
    errorStep: "Korak zaokruživanja mora biti veći od nule i ne veći od ukupne količine.",

    unitG: "g",
  },

  "recipe-scale": {
    mode: "Režim",
    modePortions: "Broj porcija",
    modeFactor: "Faktor",
    modeTargetMass: "Ciljna ukupna masa",
    lines: "Stavke recepta",
    linesHint:
      "Jedan red po sastojku: količina;jedinica;naziv;korak (poslednji opcionalan). Količina može biti decimalna („1,5\"), razlomak („1/2\") ili mešovita („1 1/2\"). Jedinica je g, kg, ml, l, kom ili ostalo.",
    originalPortions: "Polazni broj porcija",
    targetPortions: "Ciljni broj porcija",
    factor: "Faktor",
    targetMass: "Ciljna ukupna masa",
    step: "Podrazumevani korak zaokruživanja",
    stepHint: "Za redove bez sopstvenog koraka. Prazno polje znači 0,01, u jedinici tog reda.",

    results: "Rezultat",
    colName: "Sastojak",
    colScaled: "Skalirano",
    colShare: "Udeo mase",
    totalMass: "Zbir masa",

    inputs: "Uneseno",
    formula: "faktor=cilj/polazno ili ciljna_masa/Σmasa     količina'=količina·faktor, zaokruženo po najvećem ostatku",

    errorLines: "Unesi bar jednu stavku.",
    errorLineQuantity: "Količina svakog reda ne sme biti negativna.",
    errorLineStep: "Sopstveni korak reda mora biti veći od nule.",
    errorQuantityFormat: "Količina nije prepoznata kao decimalan broj, razlomak ili mešovit broj.",
    errorStep: "Podrazumevani korak zaokruživanja mora biti veći od nule.",
    errorOriginalPortions: "Polazni broj porcija je ceo broj, 1 ili više.",
    errorTargetPortions: "Ciljni broj porcija je ceo broj, 1 ili više.",
    errorFactor: "Faktor mora biti veći od nule.",
    errorTargetMass: "Ciljna ukupna masa mora biti veća od nule, a svi redovi moraju biti u jedinicama mase.",
    errorUnitMismatch: "Ciljna ukupna masa važi samo kad su svi redovi u jedinicama mase (g ili kg).",

    unitG: "g",
    unitKg: "kg",
    unitMl: "ml",
    unitL: "l",
    unitPiece: "kom",
    // The word `linesHint` above tells the user to type. It read „drugo" while
    // the hint asked for „ostalo" — one vocabulary, two spellings.
    unitOther: "ostalo",
  },

  "solution-concentration": {
    mode: "Režim",
    modeBlend: "Mešaj dve do ciljane mase",
    modeBlendAddSecond: "Dodaj drugu komponentu do ciljane koncentracije",
    modeDilute: "Razblaži rastvaračem",
    modeConcentrate: "Ukuvaj (ispari rastvarač)",
    modeAddSolute: "Dodaj čist sastojak",
    c1: "Koncentracija komponente 1",
    c2: "Koncentracija komponente 2",
    massBasisHint: "Procenat po masi. Alat odbija procenat po zapremini (npr. ABV) — za to je potrebna gustina koju alat nema.",
    targetConcentration: "Ciljna koncentracija",
    mass: "Masa komponente 1",
    targetMass: "Ciljna ukupna masa",
    concentrationLimit: "Regulatorni maksimum",
    limitHint: "Iz propisa koji primenjuješ. Nexus ne zna koji je to propis i ne nudi vrednost.",
    concentrateNote: "Pretpostavka: isparava samo rastvarač, rastvorena materija se ne gubi.",
    results: "Rezultat",
    componentMass1: "Masa komponente 1",
    componentMass2: "Masa komponente 2",
    solventAdded: "Dodat rastvarač",
    massRemoved: "Uklonjena masa (isparavanje)",
    soluteAdded: "Dodat čist sastojak",
    totalMass: "Ukupna masa",
    achievedConcentration: "Postignuta koncentracija",
    concentrationRatio: "Odnos prema maksimumu",
    concentrationSpread: "Razlika koncentracija komponenti (c1 − c2)",
    formula: "očuvanje mase rastvorene materije, rešeno po nepoznatoj za odabrani režim; kontrola = ukupna rastvorena materija / ukupna masa",
    inputs: "Uneseno",
    errorC1: "Koncentracija komponente 1 mora biti između 0 i 100.",
    errorC2: "Koncentracija komponente 2 mora biti između 0 i 100.",
    errorTargetConcentration: "Ciljna koncentracija mora biti između 0 i 100.",
    errorMass: "Masa mora biti veća od nule.",
    errorTargetMass: "Ciljna ukupna masa mora biti veća od nule.",
    errorEqualConcentrations: "Koncentracije komponenti su jednake — nijedna mešavina ne daje drugu vrednost.",
    errorTargetOutOfRange: "Ciljna koncentracija je van dometa koji ove komponente mogu da dostignu.",
    unitG: "g",
  },

  "us-customary-kitchen-units": {
    value: "Vrednost",
    from: "Iz jedinice",
    to: "U jedinicu",
    usCupLegal: "US šoljica (zakonska, 240 ml)",
    usCupDeclared: "US šoljica (deklarativna, 236,588 ml)",
    auNzCup: "AU/NZ šoljica (250 ml)",
    usFlOz: "US tečna unca",
    usTbsp: "US kašika",
    usTsp: "US kašičica",
    usPint: "US pinta",
    usQuart: "US kvart",
    usGallon: "US galon",
    impFlOz: "Imperijalna tečna unca",
    impPint: "Imperijalna pinta",
    impQuart: "Imperijalni kvart",
    impGallon: "Imperijalni galon",
    metricTbsp: "Metrička kašika (ručni unos u ml)",
    metricTsp: "Metrička kašičica (ručni unos u ml)",
    ozAvoirdupois: "Unca (masa)",
    pound: "Funta",
    degF: "Stepen Farenhajta",
    degC: "Stepen Celzijusa",
    tablespoonMl: "Zapremina kašike",
    teaspoonMl: "Zapremina kašičice",
    spoonHint: "U mililitrima. Zavisi od recepta koji koristiš.",
    targetMl: "mililitri",
    targetL: "litri",
    targetG: "grami",
    targetKg: "kilogrami",
    results: "Rezultat",
    result: "Rezultat",
    relationPrefix: "Odnos:",
    relationTemperature: "Temperaturna razmera nema jedinstven množilac — pretvaranje ide po formuli, ne po odnosu.",
    formula: "zapremina→zapremina i masa→masa: množilac po jedinici     °F→°C: (°F − 32)·5/9",
    inputs: "Uneseno",
    errorFrom: "Izaberi izvornu jedinicu.",
    errorTargetUnit: "Ova izvorna jedinica ne može da se pretvori u izabranu ciljnu jedinicu — zapremina se ne pretvara u masu bez gustine.",
    errorValue: "Vrednost mora biti prepoznata kao broj.",
    errorTablespoonMl: "Zapremina kašike mora biti veća od nule.",
    errorTeaspoonMl: "Zapremina kašičice mora biti veća od nule.",
    unitMl: "ml",
    unitL: "l",
    unitG: "g",
    unitKg: "kg",
  },

  "yield-trim-cook": {
    mode: "Režim",
    modeForward: "Od bruto nabavke",
    modeInverse: "Od potrebnog broja porcija",
    apMass: "Bruto (nabavna) masa",
    cleaningYield: "Randman čišćenja",
    yieldHint: "Meri se na sopstvenoj sirovini. Nijedan randman nije unapred upisan.",
    cookingYield: "Randman termičke obrade",
    cookingYieldHint: "Sme biti i preko 100% — pirinač i testenina upijaju vodu.",
    portionMass: "Masa porcije, kuvano",
    portionsNeeded: "Potreban broj porcija",
    pricePerKgAp: "Cena po kilogramu bruto sirovine",
    results: "Rezultat",
    cleanedMass: "Očišćena masa",
    cookedMass: "Kuvana masa",
    combinedYield: "Ukupan randman",
    combinedLossPercent: "Ukupan kalo",
    yieldLossPairNote: "Randman i kalo su isto merenje, prikazana kao vezan par — jedno se ne unosi u drugo.",
    portions: "Broj porcija",
    leftover: "Ostatak",
    apNeeded: "Bruto masu treba kupiti",
    pricePerKgCooked: "Cena po kilogramu kuvanog proizvoda",
    pricePerPortion: "Cena porcije",
    formula: "randman=randman_čišćenja·randman_obrade     porcije=floor(kuvano/porcija)     obrnuto: bruto=porcije·porcija/randman",
    inputs: "Uneseno",
    errorApMass: "Bruto masa mora biti veća od nule.",
    errorCleaningYield: "Randman čišćenja mora biti veći od nule i ne veći od 100%.",
    errorCookingYield: "Randman termičke obrade mora biti veći od nule.",
    errorPortionMass: "Masa porcije mora biti veća od nule.",
    errorPortionsNeeded: "Potreban broj porcija je ceo broj, 1 ili više.",
    errorPricePerKgAp: "Cena po kilogramu ne sme biti negativna.",
    unitG: "g",
    unitKg: "kg",
    unitCurrency: "RSD",
  },
} as const;
