/**
 * „Grejanje i vodovod" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. Names and blurbs live in `./pro.ts`, because the rail needs them
 * before any surface is opened.
 *
 * **Nothing here judges, and that is the pack's whole discipline.** EN 12831-1
 * and EN 442-1 fix how a heat load and a radiator's off-rating are computed;
 * neither says what a wall's U-value has to be. Every such figure is typed by
 * the user and echoed back, and the copy says which method ran rather than
 * whether the answer is good.
 */
export const PRO_GREJANJE_SR = {
  "room-heat-loss": {
    temperature: "Razlika temperatura",
    temperatureHint: "Unutrašnja projektna temperatura minus spoljna, u kelvinima.",
    surfaces: "Površine omotača",
    surfacesHint:
      "Red po red: površina u m² i U-vrednost, razdvojeno tačkom i zarezom (npr. „20; 0,3“).",
    bridge: "Dodatak za toplotne mostove",
    bridgeHint:
      "Dodatni koeficijent u W/K. Ostavi 0 ako se mostovi ne računaju posebno.",
    ventilation: "Osnova ventilacije",
    ventilationAirChanges: "izmena vazduha",
    ventilationPerArea: "protok po površini",
    airChanges: "Broj izmena vazduha",
    airChangesHint: "Na sat, za celu prostoriju.",
    volume: "Zapremina prostorije",
    volumeHint: "U m³.",
    airFlow: "Protok vazduha po podu",
    airFlowHint: "U m³/(h·m²) — koristi se umesto izmena vazduha.",
    floorArea: "Površina poda",
    floorAreaHint: "U m².",
    results: "Rezultat",
    transmissionCoefficient: "Koeficijent transmisije H_T",
    ventilationCoefficient: "Koeficijent ventilacije H_V",
    transmissionLoss: "Gubitak transmisijom",
    ventilationLoss: "Gubitak ventilacijom",
    totalLoss: "Ukupan gubitak",
    lossPerArea: "Gubitak po m² poda",
    formula:
      "Φ_T = (Σ(U·A) + H_most)·Δθ     H_V = 0,34·n·V (ili 0,34·q·A_poda)     Φ = Φ_T + Φ_V",
    inputs: "Uneseno",
    errorTemperature: "Razlika temperatura je broj od 1 do 80 K.",
    errorSurfaces: "Proveri redove: površina veća od nule, U-vrednost nula ili više.",
    errorBridge: "Dodatak za mostove je broj nula ili više.",
    errorVentilation:
      "Izaberi tačno jednu osnovu ventilacije — izmene vazduha ili protok po površini.",
    errorAirChanges: "Broj izmena vazduha je broj veći od nule.",
    errorVolume: "Zapremina prostorije je broj veći od nule.",
    errorAirFlow: "Protok po površini je broj nula ili više.",
    errorFloorArea: "Površina poda je broj veći od nule.",
    unitWK: "W/K",
    unitW: "W",
    unitWPerM2: "W/m²",
    unitK: "K",
    unitM2: "m²",
    unitM3: "m³",
    unitM3PerH: "m³/(h·m²)",
  },

  "radiator-output": {
    nominalOutput: "Nazivni učinak",
    nominalOutputHint: "Učinak koji proizvođač daje za nominalni temperaturni režim, u W.",
    exponent: "Eksponent n",
    exponentHint:
      "Podatak iz deklaracije radijatora; EN 442-1 ga meri po uređaju. Tipično oko 1,3, " +
      "ali Nexus ga ne pretpostavlja.",
    temperatureMode: "Ulaz za temperaturni režim",
    modeTemperatures: "polaz, povrat i prostorija",
    modeSpread: "razlika direktno",
    flow: "Polazna temperatura",
    back: "Povratna temperatura",
    room: "Temperatura prostorije",
    spread: "Razlika Δθ",
    spreadHint: "Srednja temperatura vode minus temperatura prostorije, u K.",
    nominalSpread: "Nominalna razlika",
    nominalSpreadHint: "50 K je nominalna razlika EN 442; ostavi prazno za 50.",
    requiredOutput: "Traženi učinak",
    requiredOutputHint:
      "Ako uneseš željeni učinak, dobijaš i razliku koja je za njega potrebna, u W.",
    results: "Rezultat",
    output: "Učinak pri ovoj razlici",
    spreadUsed: "Upotrebljena razlika Δθ",
    neededSpread: "Potrebna razlika za traženi učinak",
    formula: "Φ = Φ_n · (Δθ / Δθ_n)^n     Δθ = (polaz + povrat)/2 − prostorija",
    inputs: "Uneseno",
    errorNominal: "Nazivni učinak je broj veći od nule.",
    errorExponent: "Eksponent je broj od 1 do 2.",
    errorTemperatures:
      "Za ovaj način unosa trebaju polazna, povratna i temperatura prostorije.",
    errorSpread: "Unesi ili razliku direktno ili tri temperature — ne oba.",
    errorSpreadValue: "Razlika je broj od 1 do 120 K.",
    errorNominalSpread: "Nominalna razlika je broj od 10 do 90 K.",
    errorRequired: "Traženi učinak je broj veći od nule.",
    unitW: "W",
    unitK: "K",
  },

  "water-heater-time": {
    volume: "Zapremina vode",
    volumeHint: "U litrima.",
    initial: "Polazna temperatura",
    target: "Ciljna temperatura",
    power: "Snaga grejača",
    powerHint: "U vatima.",
    loss: "Stalni gubici",
    lossHint:
      "Procenat dodatne energije koju bojler izgubi dok greje. Ostavi 0 ako nije mereno.",
    results: "Rezultat",
    rise: "Porast temperature",
    mass: "Masa vode",
    energy: "Potrebna energija",
    timeSeconds: "Vreme zagrevanja, sekunde",
    timeMinutes: "Vreme zagrevanja, minute",
    formula: "Q = m·c·Δθ · (1 + gubici/100)     t = Q / P     c = 4186 J/(kg·K)",
    inputs: "Uneseno",
    errorVolume: "Zapremina je broj veći od nule.",
    errorInitial: "Polazna temperatura je broj od −20 do 150 °C.",
    errorTarget: "Ciljna temperatura mora biti viša od polazne.",
    errorPower: "Snaga grejača je broj veći od nule.",
    errorLoss: "Stalni gubici su broj od 0 do 100 %.",
    unitL: "l",
    unitKg: "kg",
    unitC: "°C",
    unitK: "K",
    unitW: "W",
    unitKwh: "kWh",
    unitSeconds: "s",
    unitMinutes: "min",
    unitPercent: "%",
  },

  "pipe-pressure-drop": {
    diameter: "Unutrašnji prečnik",
    diameterHint: "Unutrašnji prečnik cevi, u milimetrima.",
    length: "Dužina cevi",
    lengthHint: "Prava dužina trase, u metrima, pre uračunatih kolena.",
    known: "Zadata veličina",
    knownFlow: "protok",
    knownVelocity: "brzina",
    flow: "Protok",
    flowHint: "Vrednost i jedinica.",
    velocity: "Brzina",
    velocityHint: "Srednja brzina po punom preseku, u m/s.",
    roughness: "Apsolutna hrapavost",
    roughnessHint:
      "U milimetrima — npr. nova čelična cev 0,05, vučena bakarna 0,0015, PEX 0,007.",
    viscosity: "Kinematicka viskoznost",
    viscosityHint: "U mm²/s. Voda na 20 °C je 1,004.",
    density: "Gustina fluida",
    densityHint: "U kg/m³. Voda na 20 °C je 998.",
    fittings: "Ekvivalentna dužina armatura",
    fittingsHint: "Ukupna ekvivalentna dužina kolena, slavina i razdelnika, u metrima.",
    results: "Rezultat",
    regime: "Režim strujanja",
    regimeLaminar: "laminarno",
    regimeTransitional: "prelazno",
    regimeTurbulent: "turbulentno",
    reynolds: "Reynoldsov broj",
    friction: "Faktor trenja f",
    totalLength: "Ukupna dužina u računu",
    headLoss: "Gubitak napora",
    pressureDrop: "Pad pritiska",
    formula:
      "Δp = f·(L/D)·ρ·v²/2     h = f·(L/D)·v²/(2g)     f: Swamee–Jain za Re > 5000, 64/Re za Re < 2300",
    inputs: "Uneseno",
    errorDiameter: "Prečnik je broj od 0 do 2000 mm i veći od nule.",
    errorLength: "Dužina je broj veći od nule.",
    errorKnown: "Zadaj tačno jedno — protok ili brzinu.",
    errorFlow: "Protok je broj nula ili više.",
    errorVelocity: "Brzina je broj nula ili više.",
    errorRoughness: "Hrapavost je broj nula ili više.",
    errorViscosity: "Viskoznost je broj veći od nule.",
    errorDensity: "Gustina je broj veći od nule.",
    errorFittings: "Ekvivalentna dužina je broj nula ili više.",
    unitM: "m",
    unitMm: "mm",
    unitMs: "m/s",
    unitMm2S: "mm²/s",
    unitKgM3: "kg/m³",
    unitKpa: "kPa",
    unitBar: "bar",
    unitPa: "Pa",
  },

  "power-units": {
    value: "Vrednost",
    unit: "Jedinica",
    unitW: "vat (W)",
    unitKw: "kilovat (kW)",
    unitBtu: "BTU/h",
    unitKcal: "kcal/h",
    results: "Rezultat",
    watts: "Vati",
    kilowatts: "Kilovati",
    btuPerHour: "BTU/h",
    kcalPerHour: "kcal/h",
    formula:
      "1 BTU_IT = 1055,05585262 J    1 cal_IT = 4,1868 J    1 BTU/h = 0,293071 W    1 kcal/h = 1,163 W",
    errorValue: "Vrednost mora biti broj.",
  },

  "heating-cost": {
    fuels: "Goriva",
    fuelsHint:
      "Red po red: naziv; cena za jednu jedinicu; energija u jednoj jedinici u kWh; " +
      "stepen korisnosti od 0 do 1. Primer: „Gas; 50; 9,97; 0,9“.",
    results: "Rezultat",
    cheapest: "Najniža cena po kWh korisne toplote",
    colFuel: "Gorivo",
    colDelivered: "Cena po kWh isporučene",
    colUseful: "Cena po kWh korisne",
    formula: "cena_isporučeno = cena / energija_po_jedinici     cena_korisno = cena_isporučeno / korisnost",
    inputs: "Uneseno",
    errorFuels: "Proveri redove: cena i energija veće od nule, korisnost od 0 do 1,5.",
    unitCurrency: "po kWh",
  },
} as const;
