/**
 * „Računovodstvo i finansije" — the Serbian copy of this toolkit's surfaces.
 *
 * One entry per tool id, keyed exactly as `shared/modules.ts` spells the
 * registration. The tool's NAME and its one-line blurb are not here: those live
 * in the `name` and `blurb` tables of `./pro.ts`, because the drawer's rail
 * needs them before any surface is opened.
 *
 * **A unit is copy, not a constant.** „%" and „dana" are written here rather
 * than concatenated in the surface, so the day this table has a second locale
 * the units move with it — and because a unit hard-coded in a component is a
 * string `check:strings` cannot see and a translator cannot find.
 *
 * **Nothing in here judges.** Every tool in this pack is `riskClass:
 * "financial"` except `benford-first-digit` (`"none"`) — none of the seventeen
 * may say a number is good, bad, over a threshold or a finding. A refusal
 * names the input that made the answer impossible, never a verdict on the
 * user's business. Where the assignment's own corrections insist on a
 * distinction (necessary vs. sufficient, booked vs. exact, computed vs.
 * verified), that distinction is carried into the copy, not silently dropped.
 */
export const PRO_RACUNOVODSTVO_SR = {
  "allocation-remainder": {
    total: "Ukupan iznos",
    mode: "Režim",
    modeHint: "Po ključu deli srazmerno unetim ključevima; na jednake delove ignoriše ključeve i deli na uneti broj delova.",
    modeByKey: "Po ključu",
    modeEqual: "Na jednake delove",
    items: "Stavke",
    itemsHint: "Jedan red po stavci: naziv i ključ, odvojeni tačkom-zarezom. Naziv može ostati prazan.",
    itemsHintEqual: "U ovom režimu je dovoljan naziv po redu — ključ se ne koristi, broj delova zadaje se posebno.",
    itemsPlaceholder: "Kupac A; 3\nKupac B; 5\nKupac V; 2",
    parts: "Broj delova",
    partsHint: "Koliko jednakih delova. Ceo broj od 1 do 200.",
    decimals: "Broj decimala valute",
    decimalsHint: "0 do 4. Podrazumevano 2.",

    results: "Rezultat",
    colName: "Stavka",
    colKey: "Ključ",
    colKeyShare: "Udeo ključa",
    colExact: "Tačan iznos",
    colAllocated: "Dodeljen iznos",
    colAllocatedShare: "Udeo dodeljenog",
    colRounding: "Korekcija zaokruživanja",
    colRank: "Redni broj po ostatku",
    allocatedTotal: "Zbir dodeljenih iznosa",
    adjustedCount: "Broj stavki sa korekcijom od 1 minor jedinice",
    key: "ključ",
    allocated: "dodeljeno",
    bumped: "dobila korekciju",

    inputs: "Uneseno",
    formula:
      "Metoda najvećeg ostatka: Tu = round(T·10^d); ei = Tu·wi/W; bi = floor(ei); ostatak R = Tu − Σbi ide prvih R stavki po opadajućem ostatku.",

    errorTotal: "Ukupan iznos mora biti realan broj.",
    errorDecimals: "Broj decimala je ceo broj od 0 do 4.",
    errorParts: "Broj delova je ceo broj od 1 do 200.",
    errorItems: "Potrebna je bar jedna stavka sa ključem većim od nule; ključ ne sme biti negativan.",
  },

  "amount-in-words": {
    amount: "Iznos",
    amountHint: "Najviše dve decimale. Treća decimala se odbija, ne zaokružuje.",
    mode: "Režim",
    modeWithCurrency: "Sa valutom",
    modePlain: "Bez valute (samo broj slovima)",
    currencySingular: "Valuta — jednina",
    currencySingularHint: "Na primer „dinar\", „evro\". Oblik za broj koji se slaže sa jedninom (1, 21, 31…).",
    currencyPaucal: "Valuta — paukal",
    currencyPlural: "Valuta — množina",
    currencyGender: "Rod imenice valute",
    paraStyle: "Zapis podjedinice",
    paraStyleWords: "Slovima",
    paraStyleFraction: "Razlomak xx/100",
    subunitSingular: "Podjedinica — jednina",
    subunitSingularHint: "Na primer „para\", „cent\". Koristi se samo kad je podjedinica zapisana slovima.",
    subunitPaucal: "Podjedinica — paukal",
    subunitPlural: "Podjedinica — množina",
    subunitGender: "Rod imenice podjedinice",
    plainGender: "Rod uz broj",
    plainGenderHint: "Bez valute broj sam nosi rod (jedan/jedna/jedno, dva/dve).",
    genderMasculine: "muški",
    genderFeminine: "ženski",
    genderNeuter: "srednji",
    letterCase: "Veličina slova",
    letterCaseLower: "mala slova",
    letterCaseUpper: "VELIKA SLOVA",
    letterCaseSentence: "Prvo veliko",

    results: "Rezultat",
    resultText: "Iznos slovima",
    resultWhole: "Cela jedinica",
    resultSubunits: "Podjedinica",

    inputs: "Uneseno",
    formula:
      "cents = celi minor iznos; D = floor(cents/100), P = cents mod 100; slaganje po jednina/paukal/množina iz u = n mod 10, l = n mod 100.",
    source: "Brojevne reči i slaganje po rodu i broju: Pravopis srpskoga jezika, Matica srpska, izmenjeno i dopunjeno izdanje (2010).",

    errorAmountDecimals: "Iznos sme imati najviše dve decimale.",
    errorCurrency: "Sva tri oblika imena valute (jednina, paukal, množina) moraju biti popunjena.",
    errorCurrencyGender: "Rod imenice valute nije prepoznat.",
    errorSubunit: "Sva tri oblika imena podjedinice moraju biti popunjena kad je zapis slovima.",
    errorSubunitGender: "Rod imenice podjedinice nije prepoznat.",
    errorCents: "Iznos mora biti nula ili veći, i unutar dozvoljenog opsega.",
  },

  "financial-ratios": {
    groupBalance: "Bilans stanja",
    currentAssets: "Obrtna imovina",
    inventory: "Zalihe",
    inventoryHint: "Stanje na dan ili prosek — unesi ono što imaš, i to piše u napomeni uz rezultat.",
    cash: "Gotovina i gotovinski ekvivalenti",
    receivables: "Potraživanja od kupaca",
    currentLiabilities: "Kratkoročne obaveze",
    payables: "Obaveze prema dobavljačima",
    totalLiabilities: "Ukupne obaveze",
    totalAssets: "Ukupna aktiva",
    equity: "Sopstveni kapital",
    groupIncome: "Bilans uspeha",
    revenue: "Poslovni prihod",
    cogs: "Nabavna vrednost prodate robe (NVPR)",
    ebit: "Poslovni dobitak (EBIT)",
    interestExpense: "Rashodi kamata",
    netProfit: "Neto dobitak",
    days: "Dani u godini",
    daysHint: "Osnova za DIO, DSO, DPO i ciklus konverzije gotovine.",
    days365: "365",
    days360: "360 (bankarska konvencija)",

    results: "Rezultat",
    currentRatio: "Tekuća likvidnost",
    quickRatio: "Brza (redukovana) likvidnost",
    cashRatio: "Novčana likvidnost",
    workingCapital: "Neto obrtni kapital",
    debtRatio: "Koeficijent zaduženosti",
    debtToEquity: "Odnos duga i kapitala",
    interestCoverage: "Pokriće kamata",
    inventoryTurnover: "Obrt zaliha",
    dio: "Dani zaliha (DIO)",
    unitDays: "dana",
    dso: "Dani naplate potraživanja (DSO)",
    dpo: "Dani plaćanja dobavljačima (DPO)",
    cashConversionCycle: "Ciklus konverzije gotovine",
    assetTurnover: "Obrt ukupne aktive",
    roaPercent: "ROA",
    roePercent: "ROE",
    netMarginPercent: "Neto marža",
    ebitMarginPercent: "Poslovna (EBIT) marža",

    averageNote:
      "Pozicija koja nije uneta ostavlja svoj pokazatelj praznim; deljenje nulom takođe ostavlja prazno polje umesto broja. Alat ne pravi proseke sam — koristi tačno one iznose koje si uneo.",
    inputs: "Uneseno",
    formula:
      "Likvidnost = obrtna imovina/kratkoročne obaveze (brza: bez zaliha, novčana: samo gotovina). DIO = dani/obrt zaliha. DSO = potraživanja/prihod·dani. DPO = obaveze/NVPR·dani. CCC = DIO + DSO − DPO. ROA = neto dobitak/aktiva. ROE = neto dobitak/kapital.",

    errorDays: "Dani u godini su 365 ili 360.",
  },

  "fx-difference": {
    amount: "Iznos u stranoj valuti",
    rateOrigin: "Kurs na dan nastanka",
    rateSettlement: "Kurs na dan obračuna ili plaćanja",
    rateUnit: "Jedinica kursa",
    rateUnitHint: "Neki kursevi se objavljuju za 100 ili 1.000 jedinica strane valute — izaberi tačno onu koju si uneo.",
    rateUnit1: "za 1 jedinicu",
    rateUnit100: "za 100 jedinica",
    rateUnit1000: "za 1.000 jedinica",
    side: "Vrsta stavke",
    sideReceivable: "Potraživanje (aktiva)",
    sidePayable: "Obaveza (pasiva)",
    amountDecimals: "Broj decimala iznosa",
    originDay: "Dan nastanka — dan",
    originMonth: "Dan nastanka — mesec",
    originYear: "Dan nastanka — godina",
    settlementDay: "Dan obračuna/plaćanja — dan",
    settlementMonth: "Dan obračuna/plaćanja — mesec",
    settlementYear: "Dan obračuna/plaćanja — godina",

    results: "Rezultat",
    valueOrigin: "Protivvrednost na dan nastanka",
    valueSettlement: "Protivvrednost na dan obračuna",
    bookedDifference: "Kursna razlika za knjiženje",
    exactDifference: "Nezaokružena kursna razlika",
    exactDifferenceRaw: "Nezaokružena razlika (puna preciznost)",
    roundingNote:
      "Za knjiženje se koristi razlika ZAOKRUŽENIH protivvrednosti — ona može odstupati od nezaokružene razlike prikazane pored nje.",
    magnitude: "Iznos (apsolutna vrednost)",
    effect: "Efekat",
    effectIncome: "Pozitivna kursna razlika (prihod)",
    effectExpense: "Negativna kursna razlika (rashod)",
    effectNone: "Nema kursne razlike",
    rateChangePercent: "Promena kursa",

    inputs: "Uneseno",
    formula:
      "V1 = iznos·kurs1, V2 = iznos·kurs2; knjižena razlika = round(V2) − round(V1). Potraživanje: rast kursa je prihod. Obaveza: rast kursa je rashod (isti iznos, suprotan naziv).",

    errorAmount: "Iznos mora biti realan broj.",
    errorRateOrigin: "Kurs na dan nastanka mora biti veći od nule.",
    errorRateSettlement: "Kurs na dan obračuna mora biti veći od nule.",
    errorAmountDecimals: "Broj decimala iznosa je ceo broj od 0 do 4.",
    errorDateOrigin: "Dan nastanka nije ispravan datum.",
    errorDateSettlement: "Dan obračuna/plaćanja nije ispravan datum.",

    crossResults: "Unakrsni kurs",
    rateAB: "Kurs valute X (jedinice Y za 1 X)",
    rateABHint: "Na primer EUR/RSD — koliko RSD za 1 EUR.",
    rateSecond: "Kurs valute Z",
    rateSecondHint: "Prema istoj bazi Y (na primer USD/RSD), ili obrnuto (RSD/USD) — izaberi smer pored.",
    crossDirection: "Smer drugog kursa",
    crossDirectionSameBase: "Prema istoj bazi (Z/Y)",
    crossDirectionInverse: "Obrnuto (Y/Z)",
    crossDecimals: "Broj decimala unakrsnog kursa",
    crossRate: "Unakrsni kurs (X/Z)",
    crossFormula: "Ista baza: (Y po X)/(Y po Z) = Z po X. Obrnut drugi kurs: (Y po X)·(Y po Z) = Z po X.",

    errorRateAB: "Kurs valute X mora biti veći od nule.",
    errorRateSecond: "Kurs valute Z mora biti veći od nule.",
    errorRateDecimals: "Broj decimala unakrsnog kursa je ceo broj od 0 do 6.",
  },

  "check-digits-id": {
    kind: "Vrsta",
    kindPib: "PIB (9 cifara)",
    kindMaticni: "Matični broj (8 cifara)",
    kindJmbg: "JMBG (13 cifara)",
    mode: "Režim",
    modeHint: "Provera traži ceo broj sa kontrolnom cifrom; izračunavanje traži samo osnovu, bez nje.",
    modeVerify: "Provera celog broja",
    modeCompute: "Izračunavanje kontrolne cifre",
    value: "Broj",
    valueHint: "Samo cifre — razmaci i crtice se ignorišu.",

    results: "Rezultat",
    computed: "Izračunata kontrolna cifra",
    given: "Unesena kontrolna cifra",
    matches: "Poklapaju se",
    matchesYes: "da",
    matchesNo: "ne",
    corrected: "Broj sa izračunatom kontrolnom cifrom",
    jmbgRawRemainder: "Sirovi ostatak m (pre pravila m > 9 → 0)",
    jmbgTenBranch: "Grana m = 10",
    jmbgNote:
      "Alat kaže samo da li se kontrolna cifra slaže sa ostatkom broja — ne tvrdi da broj postoji u ijednom registru, kome pripada, niti da je aktivan. JMBG ima slepu tačku: zamena cifara na pozicijama i i i+6 ne menja kontrolnu cifru.",

    inputs: "Uneseno",
    formulaMod1110: "ISO 7064 MOD 11,10: p = 10; za svaku cifru d: s = (p+d) mod 10 (0 → 10); p = 2s mod 11; k = (11 − p) mod 10.",
    formulaJmbg: "S = 7(a1+a7) + 6(a2+a8) + 5(a3+a9) + 4(a4+a10) + 3(a5+a11) + 2(a6+a12); m = 11 − (S mod 11); m > 9 → 0.",

    errorLength: "Broj cifara ne odgovara izabranoj vrsti i režimu.",
    errorValue: "Broj sme sadržati samo cifre, razmake i crtice.",
  },

  "depreciation-schedule": {
    cost: "Nabavna vrednost",
    residual: "Ostatak (rezidualna) vrednost",
    usefulLife: "Vek trajanja (godine)",
    method: "Metod",
    methodLinear: "Linearni",
    methodDeclining: "Degresivni sa koeficijentom",
    methodSyd: "Zbir godina (SYD)",
    methodUnits: "Funkcionalni (po učinku)",
    decliningFactor: "Koeficijent degresije",
    decliningFactorHint: "Veći od 1 do 5 — na primer 2 za dvostruko degresivni metod.",
    displayYears: "Broj godina prikaza",
    displayYearsHint: "Degresivni metod nikad ne stiže tačno do ostatka — odredi koliko redova plan prikazuje.",
    usage: "Učinak po godinama",
    usageHint: "Jedan red po godini, u jedinicama učinka.",
    usagePlaceholder: "1200\n1500\n1100",
    capacity: "Ukupan kapacitet",
    activationDay: "Datum aktiviranja — dan",
    activationMonth: "Datum aktiviranja — mesec",
    activationYear: "Datum aktiviranja — godina",
    proration: "Srazmera prve godine",
    prorationHint: "Bez srazmere računa pune godine od dana aktiviranja pa nadalje.",
    prorationNone: "Bez",
    prorationMonths: "Po mesecima",
    prorationDays: "Po danima",

    results: "Rezultat",
    colYear: "Godina",
    colCalendarYear: "Kalendarska godina",
    colBasis: "Osnovica",
    colOpening: "Početna vrednost",
    colCharge: "Godišnja amortizacija",
    colAccumulated: "Ispravka vrednosti (kumulativno)",
    colClosing: "Sadašnja vrednost",
    depreciableBase: "Osnovica za amortizaciju",
    firstYearFactor: "Faktor srazmere prve godine",
    writtenOff: "Ukupno otpisano",
    noRateNote:
      "Vek trajanja i koeficijent degresije su tvoj izbor — alat ne poznaje nijednu poresku amortizacionu grupu i nijednu propisanu stopu.",

    inputs: "Uneseno",
    formula:
      "Linearni: A = (C−S)/n. SYD: A_k = (C−S)·(n−k+1)/(n(n+1)/2). Degresivni: A_k = min(B_(k−1)·f/n, B_(k−1)−S). Funkcionalni: A_k = (C−S)·u_k/U.",

    errorCost: "Nabavna vrednost mora biti veća od nule.",
    errorResidual: "Ostatak mora biti od nule do nabavne vrednosti.",
    errorActivation: "Datum aktiviranja nije ispravan datum.",
    errorUsefulLife: "Vek trajanja je ceo broj od 1 do 100 godina.",
    errorDecliningFactor: "Koeficijent degresije je broj veći od 1 do 5.",
    errorDisplayYears: "Broj godina prikaza je ceo pozitivan broj.",
    errorUsage: "Učinak po godinama mora biti pozitivan broj u svakom redu.",
    errorCapacity: "Ukupan kapacitet mora biti veći od nule i ne manji od zbira učinka.",
    errorProration: "Srazmera prve godine nije prepoznata.",
  },

  "benford-first-digit": {
    text: "Iznosi",
    textHint: "Nalepi kolonu brojeva, jedan po redu (ili razdvojene tačkom-zarezom ili tabom).",
    test: "Test",
    testFirst: "Prva cifra (1–9)",
    testFirstTwo: "Prve dve cifre (10–99)",
    negatives: "Postupak sa negativnim vrednostima",
    negativesAbsolute: "Apsolutna vrednost",
    negativesSkip: "Izostavi",
    separator: "Decimalni separator ulaza",
    separatorComma: "Zarez",
    separatorDot: "Tačka",

    results: "Rezultat",
    colDigit: "Cifra",
    colObserved: "Posmatrana učestalost",
    colObservedShare: "Posmatran udeo",
    colExpectedShare: "Očekivan udeo",
    colExpected: "Očekivana učestalost",
    colDifference: "Odstupanje",
    colZ: "Z-vrednost",
    usable: "Upotrebljivi zapisi",
    skipped: "Izostavljeni zapisi",
    chiSquare: "Hi-kvadrat",
    mad: "MAD",
    minExpected: "Najmanja očekivana učestalost",

    inputs: "Uneseno",
    formula:
      "p_d = log10(1 + 1/d). Hi-kvadrat = Σ(n_d − e_d)²/e_d. MAD = (1/k)Σ|n_d/N − p_d|. z_d = (|n_d/N − p_d| − 1/(2N))/√(p_d(1−p_d)/N).",

    errorTooManyRows: "Najviše 100.000 redova.",
    errorValues: "Nije pronađen nijedan upotrebljiv broj.",
  },

  "breakeven-cvp": {
    fixedCost: "Fiksni troškovi za period",
    price: "Prodajna cena po jedinici",
    variableCost: "Varijabilni trošak po jedinici",
    targetProfit: "Ciljna dobit",
    plannedVolume: "Planirani obim",
    plannedVolumeHint: "Opciono — bez njega nema margine sigurnosti ni operativnog leveridža.",

    results: "Rezultat",
    contributionMargin: "Marža pokrića po jedinici",
    contributionMarginPercent: "Stopa marže pokrića",
    breakevenUnits: "Prelomna tačka (tačna)",
    breakevenUnitsWhole: "Prelomna tačka (zaokruženo naviše na komad)",
    breakevenRevenue: "Prelomni promet (tačan)",
    breakevenRevenueAtWholeUnits: "Prelomni promet pri zaokruženom broju komada",
    revenueNote:
      "Prelomni promet i broj komada se računaju iz različitih brojeva — tačne vrednosti i zaokruženog broja komada — zato se oba prikazuju, svako označeno.",
    targetUnits: "Obim za ciljnu dobit",
    targetRevenue: "Promet za ciljnu dobit",
    marginOfSafetyPercent: "Margina sigurnosti",
    operatingLeverage: "Stepen operativnog leveridža",
    singleProductNote:
      "Račun je za JEDAN proizvod. Sa više artikala prelomna tačka zavisi od strukture prodaje.",

    inputs: "Uneseno",
    formula:
      "MP = P − V. Q0 = FT/MP. R0 = FT/(MP/P). Qd = (FT+D)/MP. MS = 100·(Qp−Q0)/Qp. DOL = (Qp·MP)/(Qp·MP−FT).",

    errorFixedCost: "Fiksni troškovi ne smeju biti negativni.",
    errorPrice: "Prodajna cena mora biti veća od nule.",
    errorVariableCost: "Varijabilni trošak ne sme biti negativan.",
    errorTargetProfit: "Ciljna dobit ne sme biti negativna.",
    errorPlannedVolume: "Planirani obim mora biti veći od nule.",
    errorContribution: "Marža pokrića mora biti veća od nule — prodajna cena mora premašiti varijabilni trošak.",
  },

  "bank-account-iban": {
    kind: "Vrsta",
    kindDomestic: "Domaći tekući račun",
    kindIban: "IBAN",
    subMode: "Režim",
    subModeHint: "Provera traži i kontrolne cifre; izračunavanje ih vraća iz osnove.",
    subModeVerify: "Provera",
    subModeCompute: "Izračunavanje",
    bank: "Šifra banke",
    bankHint: "3 cifre.",
    party: "Broj partije",
    partyHint: "1 do 13 cifara — dopunjava se nulama sleva do 13.",
    domesticCheck: "Kontrolne cifre",
    iban: "IBAN",
    ibanHintVerify: "Slova i cifre, 5 do 34 znaka. Razmaci se ignorišu.",
    ibanHintCompute: "Oznaka zemlje (2 slova) + BBAN. Kontrolne cifre 3–4 se zanemaruju ako su unete.",

    results: "Rezultat",
    formatted: "Formatiran zapis",
    checkDigits: "Kontrolne cifre",
    matches: "Kontrolna cifra se slaže",
    matchesYes: "da",
    matchesNo: "ne",
    remainder: "Ostatak po modulu 97",

    inputs: "Uneseno",
    formulaDomestic: "N = 3 cifre banke + 13 cifara partije; K = 98 − ((N·100) mod 97); ispravno akko (N·100+K) mod 97 = 1.",
    formulaIban: "Prva 4 znaka na kraj, slova A=10…Z=35; n mod 97 = 1 je ispravno; K = 98 − (n mod 97) za izračunavanje.",

    errorBank: "Šifra banke mora imati tačno 3 cifre.",
    errorPartyNumber: "Broj partije mora imati 1 do 13 cifara.",
    errorCheckDigits: "Kontrolne cifre moraju imati tačno 2 cifre.",
    errorConfusable: "Ćirilični znakovi (na primer РС, ВА) ne mapiraju se isto kao latinični — unesi IBAN latinicom.",
    errorLength: "Dužina IBAN-a mora biti 5 do 34 znaka.",
    errorAlreadyIban: "Unet je ceo IBAN, a ne oznaka zemlje i BBAN za izračunavanje.",
    errorIban: "IBAN sme sadržati samo slova A–Z i cifre.",
  },

  "gross-up": {
    net: "Neto iznos",
    model: "Model",
    modelHint: "A: porez na osnovicu umanjenu za neoporezivi iznos, doprinosi na bruto. B: porez i doprinosi na bruto umanjen za normirane troškove.",
    modelA: "A (neoporezivi iznos)",
    modelB: "B (normirani troškovi)",
    taxPercent: "Stopa poreza",
    contributionPercent: "Stopa doprinosa na teret primaoca",
    rateHint: "%, tvoj unos — alat ne poznaje nijednu propisanu stopu.",
    nonTaxableHint: "Iznos, ne procenat — tvoj unos. Alat ne poznaje nijedan propisani iznos.",
    nonTaxable: "Neoporezivi iznos (model A)",
    standardCostPercent: "Normirani troškovi (model B)",
    employerPercent: "Stopa doprinosa na teret isplatioca",
    employerPercentHint: "Opciono — ostavljeno prazno, ukupan trošak se ne prikazuje.",

    results: "Rezultat",
    gross: "Bruto iznos",
    taxBase: "Poreska osnovica",
    tax: "Porez",
    contributions: "Doprinosi na teret primaoca",
    netCheck: "Kontrolni neto",
    totalCost: "Ukupan trošak isplatioca",
    rateNote: "Sve stope i neoporezivi iznos su tvoj unos — alat ne poznaje nijednu stopu, ne bira model i ne tvrdi da je obračun po bilo kom propisu.",

    inputs: "Uneseno",
    formulaA: "Grana bez poreza: bruto = neto/(1−d/100), prihvata se ako je bruto ≤ A. Grana sa porezom: bruto = (neto − (p/100)A)/(1 − d/100 − p/100).",
    formulaB: "bruto = neto/(1 − ((p+d)/100)·(1 − k/100)).",

    errorNet: "Neto iznos mora biti veći od nule.",
    errorTaxPercent: "Stopa poreza je od 0 do 100 %.",
    errorContributionPercent: "Stopa doprinosa je od 0 do 100 %.",
    errorEmployerPercent: "Stopa doprinosa isplatioca je od 0 do 100 %.",
    errorNonTaxable: "Neoporezivi iznos ne sme biti negativan.",
    errorStandardCostPercent: "Normirani troškovi su od 0 do 100 %.",
    errorRates: "Zbir stopa poreza i doprinosa dostiže ili prelazi 100 % — jednačina nema rešenje.",
  },

  "rate-conversion": {
    ratePercent: "Stopa",
    kind: "Vrsta unete stope",
    kindHint: "Određuje kako se stopa čita — kao nominalna sa m obračuna, efektivna godišnja ili periodična.",
    kindNominal: "Nominalna godišnja (m obračuna)",
    kindEffective: "Efektivna godišnja",
    kindPeriodic: "Periodična",
    compoundingsPerYear: "Broj obračunskih perioda godišnje (m)",
    compoundingsPerYearHint: "12 mesečno, 4 kvartalno, 365 dnevno — obračunska konvencija stope, ne ciljni period.",
    target: "Ciljni period",
    targetHint: "Period za koji se traži periodična stopa.",
    targetYear: "Godina",
    targetHalf: "Polugodište",
    targetQuarter: "Kvartal",
    targetMonth: "Mesec",
    targetDay: "Dan",

    results: "Rezultat",
    effectivePercent: "Efektivna godišnja stopa",
    nominalPercent: "Nominalna godišnja stopa",
    proportionalPeriodicPercent: "Proporcionalna periodična stopa",
    conformalPeriodicPercent: "Konformna periodična stopa",
    periodicNote: "Proporcionalna i konformna periodična stopa su dva različita broja za isti period — razlika je cela svrha ovog alata.",
    continuousEffectivePercent: "Granica neprekidnog ukamaćivanja (m → ∞)",
    periodsPerYear: "Broj ciljnih perioda godišnje (k)",

    inputs: "Uneseno",
    formula:
      "EGS = (1 + r/(100m))^m − 1. i_prop = r/(100k). i_konf = (1+EGS)^(1/k) − 1. Granica: EGS = e^(r/100) − 1.",

    errorRatePercent: "Stopa mora biti veća od −100 %.",
    errorCompoundingsPerYear: "Broj obračunskih perioda godišnje je ceo broj od 1 do 365.",
    errorTarget: "Ciljni period nije prepoznat.",
  },

  "interest-periods": {
    principal: "Glavnica",
    periods: "Periodi",
    periodsHint: "Jedan red po periodu: datum od; datum do; godišnja stopa u %. Datum u obliku DD.MM.GGGG.",
    periodsPlaceholder: "01.01.2025.; 01.04.2025.; 10\n01.04.2025.; 01.07.2025.; 12",
    dayCount: "Osnova za dane",
    dayCountAct365: "ACT/365",
    dayCountAct360: "ACT/360",
    dayCountActActIsda: "ACT/ACT (ISDA)",
    dayCountBond30360: "30/360 (bond)",
    dayCountEuro30E360: "30E/360",
    method: "Metod",
    methodSimple: "Prost (linearni)",
    methodCompound: "Konformni",
    capitalize: "Pripis kamate glavnici na kraju perioda",
    capitalizeHint: "Bez pripisa svaki period se računa na istu glavnicu; sa pripisom se obračunata kamata dodaje glavnici narednog perioda.",
    capitalizeYes: "Da",
    capitalizeNo: "Ne",
    decimals: "Broj decimala prikaza",

    results: "Rezultat",
    colIndex: "Period",
    colDays: "Dani",
    colDcf: "Godišnji udeo (DCF)",
    colRate: "Stopa",
    colInterest: "Kamata",
    totalDays: "Zbir dana svih perioda",
    totalInterestRows: "Ukupna kamata (zbir prikazanih redova)",
    totalInterestExact: "Ukupna kamata (nezaokružena)",
    totalsNote: "Prikazana su oba zbira, svaki označen — tabela čija se kolona ne sabira u sopstveni zaokruženi zbir bila bi greška u ispisu.",
    totalDue: "Ukupno dugovanje (glavnica + kamata)",
    earliestFrom: "Najraniji datum „od\"",
    latestTo: "Najkasniji datum „do\"",
    overlapDays: "Dani u preklapanju perioda",
    uncoveredDays: "Nepokriveni dani",
    coverageNote: "Preklapanje i rupe između perioda alat ne popravlja — prikazuje ih kao unete.",

    inputs: "Uneseno",
    formula:
      "DCF: ACT/365 → d/365; ACT/360 → d/360; ACT/ACT (ISDA) deli interval na 1. januaru; 30/360 i 30E/360 po ISDA 4.16(f)/(g). Prost: I = P·(r/100)·DCF. Konformni: I = P·((1+r/100)^DCF − 1).",

    errorPrincipal: "Glavnica mora biti veća od nule.",
    errorDecimals: "Broj decimala prikaza je ceo broj od 0 do 6.",
    errorPeriod: "Datum do mora biti posle datuma od u svakom periodu.",
    errorRatePercent: "Stopa u svakom periodu mora biti veća od −100 % (i različita od −100 % kod konformnog metoda).",
    errorPeriods: "Potreban je bar jedan period.",
  },

  "inventory-costing": {
    openingQuantity: "Početna količina",
    openingUnitCost: "Početna jedinična cena",
    movements: "Promene",
    movementsHint: "Jedan red po promeni: tip (ulaz/izlaz); količina; jedinična cena (samo za ulaz).",
    movementsPlaceholder: "ulaz; 100; 100\nulaz; 100; 120\nizlaz; 150",
    averageMode: "Metod proseka",
    averageModeHint: "Kontinuirani preračunava prosek posle svakog ulaza; periodični računa jedan prosek za ceo period (prosečna ponderisana cena na kraju perioda).",
    averageModeMoving: "Kontinuirani",
    averageModePeriodic: "Periodični",
    decimals: "Broj decimala prikaza",

    results: "Rezultat",
    groupFifo: "FIFO",
    groupAverage: "Prosečna cena",
    colType: "Tip",
    typeIn: "ulaz",
    typeOut: "izlaz",
    colQuantity: "Količina",
    colUnitCost: "Jedinična cena",
    colValue: "Vrednost",
    colBalanceQuantity: "Stanje — količina",
    colBalanceValue: "Stanje — vrednost",
    cogs: "Nabavna vrednost prodate robe (NVPR)",
    closingQuantity: "Završna količina",
    closingValue: "Završna vrednost",
    fifoCogs: "NVPR (FIFO)",
    fifoClosingValue: "Završna vrednost (FIFO)",
    averageCogs: "NVPR (prosek)",
    averageClosingValue: "Završna vrednost (prosek)",
    costDifference: "Razlika NVPR-a (prosek − FIFO)",
    closingDifference: "Razlika završnog stanja (prosek − FIFO)",
    purchaseValue: "Ukupna nabavka perioda",
    policyNote: "Metode nisu rangirane — prikazane su obe i njihova razlika; izbor metode je tvoja računovodstvena politika.",

    inputs: "Uneseno",
    formula:
      "FIFO troši najstarije slojeve prvi. Kontinuirani prosek: cena = V/Q posle svakog ulaza. Periodični prosek: cena = (početna vrednost + Σulaza)/(početna količina + Σulaza), primenjena na sve izlaze.",

    errorMovementType: "Tip promene mora biti „ulaz\" ili „izlaz\".",
    errorOpeningQuantity: "Početna količina ne sme biti negativna.",
    errorOpeningUnitCost: "Početna jedinična cena ne sme biti negativna.",
    errorUnitCost: "Jedinična cena ulaza mora biti nula ili veća.",
    errorDecimals: "Broj decimala prikaza je ceo broj od 0 do 6.",
    errorMovements: "Izlaz veći od raspoložive količine — provera unosa reda po red.",
  },

  "loan-schedule": {
    principal: "Iznos kredita",
    annualRatePercent: "Nominalna godišnja stopa",
    instalments: "Broj rata",
    frequency: "Broj rata godišnje",
    frequency12: "12 (mesečno)",
    frequency4: "4 (kvartalno)",
    frequency2: "2 (polugodišnje)",
    frequency1: "1 (godišnje)",
    plan: "Tip plana",
    planAnnuity: "Anuitetski",
    planEqualPrincipal: "Jednaka glavnica",
    rateMethod: "Obračun periodične stope",
    rateMethodHint: "Proporcionalno: r/100/m. Konformno: (1+r/100)^(1/m) − 1.",
    rateMethodProportional: "Proporcionalno",
    rateMethodConformal: "Konformno",
    decimals: "Broj decimala",

    results: "Rezultat",
    colIndex: "Rata",
    colOpening: "Stanje duga — početak",
    colInterest: "Kamata",
    colPrincipal: "Otplata glavnice",
    colPayment: "Rata",
    colClosing: "Stanje duga — kraj",
    annuity: "Anuitet",
    periodicRate: "Periodična stopa",
    totalPaid: "Ukupno plaćeno",
    totalInterest: "Ukupna kamata",
    notAprNote: "Plan je čist obračun po unetim uslovima — nema naknada, grejsa, valutne klauzule ni osiguranja, pa ovo nije EKS.",

    inputs: "Uneseno",
    formula:
      "i = r/(100m) ili (1+r/100)^(1/m) − 1. Anuitet: A = P·i/(1 − (1+i)^(−n)); za i = 0, A = P/n. Poslednja rata nosi razliku zaokruživanja, tako da završno stanje bude tačno nula.",

    errorPrincipal: "Iznos kredita mora biti veći od nule.",
    errorAnnualRatePercent: "Nominalna godišnja stopa je od 0 do 1000 %.",
    errorInstalments: "Broj rata je ceo broj od 1 do 600.",
    errorFrequency: "Broj rata godišnje je 12, 4, 2 ili 1.",
    errorDecimals: "Broj decimala je ceo broj od 0 do 4.",
  },

  "rebate-chain": {
    groupMargin: "Marža i razlika u ceni",
    purchasePrice: "Nabavna cena",
    landedCosts: "Zavisni troškovi nabavke",
    pair: "Poznati par",
    pairCostAndPrice: "Nabavna + prodajna cena",
    pairCostAndMarginOnPrice: "Nabavna cena + marža na prodajnu",
    pairCostAndMarginOnCost: "Nabavna cena + marža na nabavnu",
    pairPriceAndMarginOnPrice: "Prodajna cena + marža na prodajnu",
    pairPriceAndMarginOnCost: "Prodajna cena + marža na nabavnu",
    sellingPrice: "Prodajna cena",
    marginOnPricePercent: "Marža na prodajnu cenu",
    marginOnPricePercentHint: "% — manje od 100.",
    marginOnCostPercent: "Marža na nabavnu cenu (razlika u ceni)",
    marginOnCostPercentHint: "% — veće od −100.",
    cost: "Nabavna vrednost (sa zavisnim troškovima)",
    difference: "Razlika u ceni",
    formulaMargin: "m = 100(P−C)/P na prodajnu cenu; u = 100(P−C)/C na nabavnu cenu (razlika u ceni). Prevodi: u = 100m/(100−m); m = 100u/(100+u).",

    groupChain: "Lančani rabati",
    listPrice: "Cenovnik (bruto cena pre rabata)",
    rebates: "Lančani rabati",
    rebatesHint: "Lista procenata, redom kako se odobravaju (na primer 10; 5).",
    rebatesPlaceholder: "10\n5",
    colStep: "Korak",
    colBasis: "Osnovica",
    colRebatePercent: "Rabat",
    colRebateAmount: "Iznos rabata",
    colRemaining: "Ostatak posle koraka",
    netPrice: "Neto cena posle svih rabata",
    effectiveRebatePercent: "Efektivni rabat",
    effectiveNote: "Efektivni rabat je proizvod, nikad zbir pojedinačnih rabata — 10 % pa 5 % je 14,5 %, ne 15 %.",
    formulaChain: "neto = cenovnik·Π(1 − d_i/100). efektivni rabat = 100·(1 − Π(1 − d_i/100)).",

    inputs: "Uneseno",

    errorPurchasePrice: "Nabavna cena ne sme biti negativna.",
    errorLandedCosts: "Zavisni troškovi nabavke ne smeju biti negativni.",
    errorSellingPrice: "Prodajna cena ne sme biti negativna.",
    errorMarginOnPricePercent: "Marža na prodajnu cenu mora biti manja od 100 %.",
    errorMarginOnCostPercent: "Marža na nabavnu cenu mora biti veća od −100 %.",
    errorListPrice: "Cenovnik ne sme biti negativan.",
    errorRebatePercents: "Svaki rabat u lancu je od 0 do 100 %, najviše 20 rabata.",
  },

  "trial-balance-check": {
    mode: "Način unosa",
    modeHint: "Kolone sabiraju obe strane; jedan iznos je za dijagnostiku kad je razlika već poznata.",
    modeColumns: "Dugovna i potražna kolona",
    modeDifferenceOnly: "Samo razlika",
    debits: "Dugovna strana",
    credits: "Potražna strana",
    listHint: "Nalepljena kolona iznosa, jedan po redu (ili razdvojeni tačkom-zarezom ili tabom). Do 5.000 redova.",
    differenceAmount: "Razlika",
    decimals: "Broj decimala valute",

    results: "Rezultat",
    debitTotal: "Zbir duguje",
    creditTotal: "Zbir potražuje",
    debitCount: "Broj stavki — duguje",
    creditCount: "Broj stavki — potražuje",
    difference: "Razlika",
    magnitude: "Iznos razlike (apsolutna vrednost)",
    balancedNote: "Strane su izjednačene — dijagnostika se ne prikazuje.",
    necessaryNote: "Ovo su aritmetički mogući uzroci, ne nalaz — alat ne bira među njima i ne tvrdi da je uzrok pronašao.",
    reversedItem: "Stavka na pogrešnoj strani (proknjižena obrnuto)",
    shiftedByTen: "Iznos upisan deset puta veći",
    shiftedByHundred: "Iznos upisan sto puta veći",
    colLowerPosition: "Niža pozicija",
    colUpperPosition: "Viša pozicija",
    colDigitGap: "Razlika cifara",
    colStep: "Korak",
    colPairs: "Mogući parovi cifara",

    inputs: "Uneseno",
    formula:
      "R = Σduguje − Σpotražuje, u celim minor jedinicama. Zamena cifara a,b na pozicijama i<j menja iznos za (a−b)(10^j−10^i); deljivost sa 9 je nužan uslov. Pomerena decimala: m/9 ili m/99.",

    errorDecimals: "Broj decimala valute je ceo broj od 0 do 4.",
    errorDifference: "Razlika mora biti broj, sa najviše onoliko decimala koliko je izabrano.",
    errorDebits: "Dugovna strana sadrži vrednost koja nije broj.",
    errorCredits: "Potražna strana sadrži vrednost koja nije broj.",
    errorTooManyRows: "Najviše 5.000 redova po strani.",
  },

  "tvm-solver": {
    solveFor: "Tražena veličina",
    unknownPv: "Sadašnja vrednost (PV)",
    unknownFv: "Buduća vrednost (FV)",
    unknownPmt: "Rata (PMT)",
    unknownPeriods: "Broj perioda (n)",
    unknownRate: "Periodična stopa (i)",
    pv: "Sadašnja vrednost (PV)",
    pvHint: "Priliv je pozitivan, odliv negativan. Zanemareno kad je ovo tražena veličina.",
    fv: "Buduća vrednost (FV)",
    fvHint: "Isti znakovni dogovor kao PV. Zanemareno kad je ovo tražena veličina.",
    pmt: "Rata (PMT)",
    pmtHint: "Novčana jedinica po periodu, isti znakovni dogovor. Zanemareno kad je ovo tražena veličina.",
    periods: "Broj perioda (n)",
    ratePercent: "Periodična stopa (i)",
    ratePercentHint: "% po periodu, veće od −100 %. Zanemareno kad je ovo tražena veličina.",
    timing: "Tip plaćanja",
    timingEnd: "Na kraju perioda (postnumerando)",
    timingBegin: "Na početku perioda (prenumerando)",

    results: "Rezultat",
    solved: "Tražena veličina",
    residual: "Rezidual osnovne jednačine",

    inputs: "Uneseno",
    formula: "PV + PMT·k·(1 − (1+i)^(−n))/i + FV·(1+i)^(−n) = 0, k = 1 na kraju perioda, k = 1+i na početku. Za i = 0: PV + PMT·n + FV = 0.",

    errorPv: "Sadašnja vrednost mora biti realan broj.",
    errorFv: "Buduća vrednost mora biti realan broj.",
    errorPmt: "Rata mora biti realan broj.",
    errorPeriods: "Broj perioda je od 0 do 1200.",
    errorRate: "Periodična stopa mora biti veća od −100 %.",
    errorRateOutOfRange: "Rešenje po stopi nije u pretraživanom opsegu (−99,9999 % do 1000 % po periodu).",
    errorCashflows: "Rešenje ne postoji ili nije jedinstveno — tokovi moraju promeniti znak tačno jednom.",
  },
} as const;
