/**
 * COOKBOOK's own copy, in Serbian — the SHAPE every other locale of this module
 * is checked against (ADR-090).
 *
 * The table lives here rather than in the shell's `strings.ts` because the
 * module's page is a lazy chunk: copy the shell does not need before this chunk
 * loads would be paid for on every launch without it. `copy.ts` registers this
 * table with the locale machinery the moment the chunk arrives, and `copy.en.ts`
 * is typed `typeof sr`, so a sentence left untranslated is one compile error.
 *
 * Two tables inside it are DATA rather than prose — `courses` and `units` — and
 * they are read by index (`copy.units[unit]`), because their keys are the
 * module's closed vocabularies from `@nexus/core` and a second spelling of one
 * would be a label that stops resolving the day the vocabulary grows.
 */
export const sr = {
  page: {
    subtitle: "Tvoji recepti i kuhinje sveta iz paketa.",
    loading: "Učitavanje…",
  },
  list: {
    title: "Recepti",
    search: "Pretraga",
    searchHint: "Naziv, oznaka ili sastojak — pitaj „šta mogu da napravim sa…“.",
    emptyTitle: "Još nema recepata",
    emptyBody: "Dodaj prvi recept, ili pogledaj kuhinje sveta u paketima.",
    noResults: "Nijedan recept ne odgovara pretrazi.",
    add: "Novi recept",
    open: "Otvori",
    cook: "Kuvaj",
    edit: "Izmeni",
    remove: "Obriši",
    tick: "Označi kao omiljeno",
    untick: "Skini oznaku omiljenog",
    servings: "Porcija",
  },
  confirm: {
    title: "Brisanje recepta",
    question: "Recept se uklanja iz kuvarice, zajedno sa sastojcima i koracima.",
    confirm: "Obriši",
    cancel: "Otkaži",
  },
  courses: {
    breakfast: "Doručak",
    starter: "Predjelo",
    soup: "Supa",
    main: "Glavno jelo",
    side: "Prilog",
    salad: "Salata",
    dessert: "Dezert",
    baking: "Pekara",
    drink: "Piće",
    preserve: "Zimnica",
    other: "Ostalo",
  },
  units: {
    g: "g",
    kg: "kg",
    ml: "ml",
    l: "l",
    tsp: "kašičica",
    tbsp: "kašika",
    cup: "šolja",
    fl_oz: "fl oz",
    pinch: "prstohvat",
    dash: "prstohvat",
    clove: "čen",
    piece: "komad",
    slice: "kriška",
    sprig: "grančica",
    stalk: "stabljika",
    head: "glavica",
    bunch: "veza",
    handful: "šaka",
    stick: "štapić",
    sheet: "list",
    can: "konzerva",
    packet: "paket",
    cube: "kocka",
  },
  detail: {
    title: "Recept",
    servings: "Porcije",
    less: "Manje porcija",
    more: "Više porcija",
    prep: "Priprema",
    cook: "Kuvanje",
    minutes: "min",
    hours: "h",
    ingredients: "Sastojci",
    noIngredients: "Recept nema sastojke.",
    steps: "Postupak",
    noSteps: "Recept nema korake.",
    notes: "Beleške",
    photo: "Fotografija",
    photoAdd: "Dodaj fotografiju",
    photoRemove: "Ukloni fotografiju",
    photoNone: "Bez fotografije.",
    source: "Izvor",
    licence: "Licenca",
    attribution: "Autorstvo",
    own: "Moj recept",
    scaled: "Količine su preračunate za izabrani broj porcija.",
  },
  editor: {
    title: "Izmena recepta",
    newTitle: "Novi recept",
    name: "Naziv",
    course: "Vrsta jela",
    servings: "Porcije",
    prep: "Priprema (min)",
    cook: "Kuvanje (min)",
    ingredients: "Sastojci — jedan po redu",
    ingredientsHint: "Svaki red se čita: količina, jedinica, naziv, pa napomena posle zareza.",
    steps: "Koraci — jedan po redu",
    stepTimer: "Minuta",
    tags: "Oznake, odvojene zarezom",
    notes: "Beleške",
    save: "Sačuvaj",
    cancel: "Otkaži",
    errorName: "Naziv je obavezan.",
    errorIngredients: "Svaki sastojak mora imati naziv.",
    errorSteps: "Svaki korak mora imati tekst.",
  },
  cooking: {
    title: "Kuvanje",
    step: "Korak",
    of: "od",
    previous: "Nazad",
    next: "Dalje",
    done: "Završi",
    ingredients: "Sastojci",
    keys: "Strelica levo i desno menjaju korak; Escape zatvara kuvanje.",
    awake: "Ekran ostaje uključen dok je kuvanje otvoreno.",
    timer: "Tajmer koraka",
  },
  nutrition: {
    title: "Hranljive vrednosti",
    perServing: "po porciji",
    kcal: "Energija",
    kcalUnit: "kcal",
    protein: "Proteini",
    carbs: "Ugljeni hidrati",
    fat: "Masti",
    fibre: "Vlakna",
    sugar: "Šećeri",
    salt: "So",
    gram: "g",
    milligram: "mg",
    uncounted: "Nije uračunato",
    unlinked: "nije povezano sa namirnicom",
    unknownFood: "namirnice nema u instaliranim paketima",
    unknownGrams: "nije poznato koliko jedna jedinica teži",
    noPack: "Nema paketa sa namirnicama",
    noPackBody: "Instaliraj dataset paket koji sadrži foods.json, pa se vrednosti računaju iz njega.",
    link: "Poveži",
    unlink: "Otkači",
    linkLabel: "Namirnica za",
    linkSearch: "Traži namirnicu",
    suggestionNone: "Nema predloga.",
    gramsPerUnit: "Gram po jedinici",
    gramsHint: "Samo za jedinice koje se ne mogu izmeriti — kašika, šolja.",
  },
  packs: {
    title: "Kuhinje sveta",
    empty: "Nijedan paket sa receptima nije instaliran.",
    emptyBody: "Paketi sadržaja se dodaju u Podešavanjima, u kartici „Paketi sadržaja“.",
    pack: "Paket",
    query: "Pretraga u paketu",
    save: "Sačuvaj u moju kuvaricu",
    count: "recepta",
    servings: "Porcija",
    notStated: "nije navedeno",
    source: "Izvor",
    saved: "Sačuvano u tvoju kuvaricu.",
    noResults: "Nijedan recept u paketu ne odgovara.",
    open: "Prikaži",
    close: "Zatvori",
  },
  widget: {
    empty: "Još nema recepata.",
    loading: "Učitavanje…",
    loadError: "Recepti nisu učitani.",
  },
  settings: {
    caption: "Jedinice se koriste za prikaz i zaokruživanje količina u receptima.",
    hint: "Metričke su grami i mililitri; kuhinjske su kašike i šolje.",
    saved: "Sačuvano.",
    loadError: "Podešavanje nije učitano.",
    saveError: "Podešavanje nije sačuvano.",
  },
  errors: {
    load: "Kuvarica nije učitana.",
    mutate: "Izmena nije sačuvana.",
    recipe: "Recept nije učitan.",
  },
};
