import { sr } from "./copy.sr.js";

/**
 * COOKBOOK in English — the same shape as `copy.sr.ts`, checked by the compiler.
 *
 * `typeof sr` is the whole mechanism: a sentence left untranslated, a key
 * invented here, or a nested table that does not match is one compile error
 * each, so this file cannot drift from the Serbian table. The register is the
 * app's own English: sentence case, informative, no exclamation marks.
 */
export const en: typeof sr = {
  page: {
    subtitle: "Your recipes and the world's cuisines from packs.",
    loading: "Loading…",
  },
  list: {
    title: "Recipes",
    search: "Search",
    searchHint: "A title, a tag or an ingredient — ask „what can I make with…“.",
    emptyTitle: "No recipes yet",
    emptyBody: "Add the first recipe, or look at the world's cuisines in packs.",
    noResults: "No recipe matches the search.",
    add: "New recipe",
    open: "Open",
    cook: "Cook",
    edit: "Edit",
    remove: "Delete",
    tick: "Mark as a favourite",
    untick: "Remove the favourite mark",
    servings: "Servings",
  },
  confirm: {
    title: "Delete recipe",
    question: "The recipe leaves the cookbook, its ingredients and steps with it.",
    confirm: "Delete",
    cancel: "Cancel",
  },
  courses: {
    breakfast: "Breakfast",
    starter: "Starter",
    soup: "Soup",
    main: "Main course",
    side: "Side",
    salad: "Salad",
    dessert: "Dessert",
    baking: "Baking",
    drink: "Drink",
    preserve: "Preserve",
    other: "Other",
  },
  units: {
    g: "g",
    kg: "kg",
    ml: "ml",
    l: "l",
    tsp: "tsp",
    tbsp: "tbsp",
    cup: "cup",
    fl_oz: "fl oz",
    pinch: "pinch",
    dash: "dash",
    clove: "clove",
    piece: "piece",
    slice: "slice",
    sprig: "sprig",
    stalk: "stalk",
    head: "head",
    bunch: "bunch",
    handful: "handful",
    stick: "stick",
    sheet: "sheet",
    can: "can",
    packet: "packet",
    cube: "cube",
  },
  detail: {
    title: "Recipe",
    servings: "Servings",
    less: "Fewer servings",
    more: "More servings",
    prep: "Prep",
    cook: "Cook",
    minutes: "min",
    hours: "h",
    ingredients: "Ingredients",
    noIngredients: "The recipe lists no ingredients.",
    steps: "Steps",
    noSteps: "The recipe lists no steps.",
    notes: "Notes",
    photo: "Photo",
    photoAdd: "Add a photo",
    photoRemove: "Remove the photo",
    photoNone: "No photo.",
    source: "Source",
    licence: "Licence",
    attribution: "Attribution",
    own: "My recipe",
    scaled: "The amounts are recalculated for the chosen number of servings.",
  },
  editor: {
    title: "Edit the recipe",
    newTitle: "New recipe",
    name: "Title",
    course: "Course",
    servings: "Servings",
    prep: "Prep (min)",
    cook: "Cook (min)",
    ingredients: "Ingredients — one per line",
    ingredientsHint: "Each line is read: amount, unit, name, then a note after the comma.",
    steps: "Steps — one per line",
    stepTimer: "Minutes",
    tags: "Tags, separated by commas",
    notes: "Notes",
    save: "Save",
    cancel: "Cancel",
    errorName: "A title is required.",
    errorIngredients: "Every ingredient needs a name.",
    errorSteps: "Every step needs its text.",
  },
  cooking: {
    title: "Cooking",
    step: "Step",
    of: "of",
    previous: "Back",
    next: "Next",
    done: "Finish",
    ingredients: "Ingredients",
    keys: "Left and right arrows change the step; Escape closes the cooking view.",
    awake: "The screen stays awake while the cooking view is open.",
    timer: "Step timer",
  },
  nutrition: {
    title: "Nutrition",
    perServing: "per serving",
    kcal: "Energy",
    kcalUnit: "kcal",
    protein: "Protein",
    carbs: "Carbohydrate",
    fat: "Fat",
    fibre: "Fibre",
    sugar: "Sugars",
    salt: "Salt",
    gram: "g",
    milligram: "mg",
    uncounted: "Not counted",
    unlinked: "is not linked to a food",
    unknownFood: "the food is in no installed pack",
    unknownGrams: "what one unit weighs is unknown",
    noPack: "No foods pack is installed",
    noPackBody: "Install a dataset pack carrying foods.json and the figures are computed from it.",
    link: "Link",
    unlink: "Unlink",
    linkLabel: "Food for",
    linkSearch: "Search foods",
    suggestionNone: "No suggestions.",
    gramsPerUnit: "Grams per unit",
    gramsHint: "Only for units that cannot be weighed — a spoon, a cup.",
  },
  packs: {
    title: "The world's cuisines",
    empty: "No pack carrying recipes is installed.",
    emptyBody: "Content packs are added in Settings, in the „Content packs“ card.",
    pack: "Pack",
    query: "Search the pack",
    save: "Save to my cookbook",
    count: "recipes",
    servings: "Servings",
    notStated: "not stated",
    source: "Source",
    saved: "Saved to your cookbook.",
    noResults: "No recipe in the pack matches.",
    open: "Show",
    close: "Close",
  },
  widget: {
    empty: "No recipes yet.",
    loading: "Loading…",
    loadError: "The recipes could not be loaded.",
  },
  settings: {
    caption: "The units are used to show and to round amounts in recipes.",
    hint: "Metric is grams and millilitres; kitchen is spoons and cups.",
    saved: "Saved.",
    loadError: "The setting could not be loaded.",
    saveError: "The setting was not saved.",
  },
  errors: {
    load: "The cookbook could not be loaded.",
    mutate: "The change was not saved.",
    recipe: "The recipe could not be loaded.",
  },
};
