import { spawn, type ChildProcess } from "node:child_process";

/**
 * The update's last step: start the installer the service verified, and let it
 * outlive the app that is about to quit.
 *
 * This is the SECOND file in the shipped application that starts a process —
 * `main/elecRunner.ts` is the first, and `scripts/check-runner.mjs` names both
 * and holds both to the same rules. What is different here is the program: the
 * runner may not spell the name of what it spawns, because its command line
 * comes out of a closed table, while this file is handed exactly one path — the
 * installer under `userData/updates/` that the service hashed while streaming
 * and hashed again immediately before this call — and passes it the arguments
 * below and nothing else. Nothing a renderer sends reaches either one.
 *
 * WHY THESE ARGUMENTS. An NSIS installer decides for itself what an
 * installation IS, and it decides it from its command line; every claim here is
 * read from the templates electron-builder compiles it from
 * (`app-builder-lib/templates/nsis/`, with `${isUpdated}` and `${isForceRun}`
 * generated by `out/targets/nsis/nsisScriptGenerator.js` from the two words
 * "updated" and "force-run"):
 *
 * - `--updated` is what keeps the user's shortcuts, and the taskbar pin is
 *   attached to one. `include/installUtil.nsh`'s `setIsTryToKeepShortcuts` sets
 *   `$isTryToKeepShortcuts` to "true", and then back to "false" when
 *   `!ifdef allowToChangeInstallationDirectory` and `${ifNot} ${isUpdated}` —
 *   and this build sets `allowToChangeInstallationDirectory: true`
 *   (`electron-builder.yml`), so a plain double-click of the installer takes
 *   exactly that branch. With "false" the OLD version's uninstaller is run
 *   without `--keep-shortcuts`, and `uninstaller.nsh` then reaches
 *   `WinShell::UninstAppUserModelId "${APP_ID}"` and
 *   `Delete "$oldDesktopLink"`. With "true" that whole block is skipped
 *   (`${ifNot} ${isKeepShortcuts}`) and the existing `.lnk` files are left where
 *   they are.
 * - `/S` and `--force-run` are what bring the app back. `installSection.nsh`
 *   starts it again after an update in ONE place, and only for an assisted
 *   installer (`oneClick: false`, which this product builds): `${if}
 *   ${isForceRun}` `${andIf} ${Silent}` runs `doStartApp`, which executes the
 *   start-menu shortcut and passes `--updated` on to the app (`common.nsh`,
 *   `StartApp`). Neither is enough alone — `--force-run` without `/S` leaves the
 *   installer's wizard on screen, and `/S` without it installs and leaves the
 *   app closed.
 *
 * The identity those shortcuts carry is `appId` from `electron-builder.yml`
 * (`rs.stojiljkovic.nexus`), which no version changes: a changed
 * AppUserModelID loses the pin whatever the flags say.
 */

/**
 * The installer's whole command line, and the only one this app ever hands it.
 * Written here rather than assembled anywhere, for `elecRunner.ts`'s reason:
 * a command built one piece at a time is a command no reader can check.
 */
const INSTALLER_ARGS: readonly string[] = ["--updated", "/S", "--force-run"];

export interface InstallerLaunchDeps {
  /** `node:child_process`'s own `spawn`, injected so a test can assert the argv without an installer on this machine. */
  readonly spawn: typeof spawn;
}

/**
 * The seam a test drives; `launchInstaller` below is the door main comes in by.
 *
 * The answer is `openPath`'s old answer, because `install()` treats it the same
 * way: an empty string once the installer process exists, and a message when it
 * does not. It resolves on `spawn`'s own event rather than on the call, because
 * the call returns a handle and only the event says whether the OS started
 * anything — and the app quits on the strength of this answer.
 */
export function createInstallerLauncher(
  deps: InstallerLaunchDeps,
): (path: string) => Promise<string> {
  return (path) =>
    new Promise<string>((resolve) => {
      let child: ChildProcess;
      try {
        child = deps.spawn(path, INSTALLER_ARGS, {
          // Detached, because this app quits the moment the answer arrives and
          // the installer has to finish without it; no inherited stdio, because
          // there is nothing for it to say to a process that is going away.
          detached: true,
          stdio: "ignore",
          // Explicit rather than defaulted, `elecRunner.ts`'s word: with no
          // shell an argument is an argument and never a word that can be split.
          shell: false,
          windowsHide: true,
        });
      } catch (error) {
        resolve(messageOf(error));
        return;
      }

      child.once("spawn", () => {
        // Outliving this process is the point, so the handle is dropped: an
        // installer that has started must not hold the app open one moment
        // longer than the user asked.
        child.unref();
        resolve("");
      });
      child.once("error", (error) => {
        // ENOENT, a refused path, a policy block: the process never existed, and
        // the message is the OS's own words rather than a guess about them.
        resolve(messageOf(error));
      });
    });
}

/**
 * The launcher the application uses: this file's own `spawn`, and nothing to
 * decide. It exists so that `index.ts` never has to name `node:child_process` —
 * the capability lives in the files that are allowed it, and `check:runner` is
 * what keeps that true rather than either file's own good manners.
 */
export function launchInstaller(path: string): Promise<string> {
  return createInstallerLauncher({ spawn })(path);
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
