import { sr } from "./copy.sr.js";

/**
 * CULTURE in English - the same shape as `copy.sr.ts`, checked by the compiler.
 *
 * `typeof sr` is the whole mechanism: a sentence left untranslated, a key
 * invented here, or a nested table that does not match is one compile error
 * each, so this file cannot drift from the Serbian table the way a second
 * hand-kept table would. The register is the app's own English: sentence case,
 * informative, no exclamation marks.
 */
export const en: typeof sr = {
  page: {
    subtitle:
      "Museums, theatre, concerts and cinema - one corner for culture, with a programme and music.",
    loading: "Loading…",
    tabsLabel: "Areas of culture",
  },
  tabs: {
    visits: "Visits",
    venues: "Places",
    programme: "Programme",
    art: "Guide",
    music: "Music",
  },
  more: "Show more",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  confirm: "Confirm",
  kinds: {
    museum: "Museum",
    gallery: "Gallery",
    exhibition: "Exhibition",
    theatre: "Theatre",
    opera: "Opera",
    ballet: "Ballet",
    concert: "Concert",
    cinema: "Cinema",
    festival: "Festival",
    other: "Other",
  },
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  filters: {
    kind: "Kind",
    place: "Place",
    query: "Search",
    anyKind: "Any kind",
    anyPlace: "Any place",
    clear: "Clear the filter",
    noResults: "No visit matches the filter.",
  },
  visits: {
    title: "Visits",
    empty: "No visits yet.",
    emptyHint: "Add the first visit: a title, a place and a date.",
    add: "New visit",
    edit: "Edit",
    remove: "Delete",
    asList: "List",
    asCalendar: "Calendar",
    previousYear: "Previous year",
    nextYear: "Next year",
    kind: "Kind",
    titleLabel: "Title",
    venueLabel: "Place",
    city: "City",
    date: "Date",
    startTime: "Start time",
    rating: "Rating (1-10)",
    price: "Price",
    currency: "Currency",
    notes: "Notes",
    withWhom: "With whom",
    attach: "Attach a ticket",
    photos: "Attachments",
    noPhotos: "No attachments",
    noRating: "Not rated",
  },
  venues: {
    title: "Places",
    add: "New place",
    edit: "Edit",
    remove: "Delete",
    empty: "No places remembered yet.",
    emptyHint: "Every visit remembers the place it was at, so the list fills itself.",
    noCity: "No city",
    visitsCount: "Visits",
    name: "Name",
    city: "City",
    kind: "Kind",
    notes: "Notes about the place",
  },
  programme: {
    title: "Programme",
    add: "New plan",
    empty: "The programme is empty.",
    emptyHint: "Write down what is planned; once the date passes a plan becomes a visit.",
    askHint: "Past plans with no answer",
    went: "Went",
    didNotGo: "Drop the plan",
    becameVisit: "Became a visit",
    upcoming: "Ahead",
    past: "Past",
    openLink: "Open the link",
    remove: "Delete",
    kind: "Kind",
    titleLabel: "Title",
    venueLabel: "Place",
    city: "City",
    date: "Date",
    startTime: "Start time",
    link: "Link",
    notes: "Notes",
  },
  art: {
    title: "Arts guide",
    loadError: "The guide could not be read.",
    empty: "No dataset pack is installed.",
    emptyHint: "The arts guide is filled from a dataset pack holding an art.json file.",
    search: "Search",
    artist: "Artist",
    museum: "Museum",
    period: "Period",
    anyArtist: "Any artist",
    anyMuseum: "Any museum",
    anyPeriod: "Any period",
    unknownPeriod: "No year",
    century: "century",
    skipped: "Packs that could not be read",
    noResults: "No work matches the filter.",
    credit: "Credit",
    licence: "Licence",
  },
  music: {
    player: "Player",
    noTrack: "Nothing is playing.",
    seek: "Seek within the track",
    previous: "Previous",
    play: "Play",
    pause: "Pause",
    next: "Next",
    repeatQueue: "Repeat the queue",
    library: "My tracks",
    import: "Import audio",
    importing: "Importing…",
    libraryEmpty: "The library is empty.",
    libraryEmptyHint: "Import MP3, FLAC, Ogg, M4A or WAV - titles and duration are read from the file.",
    playlists: "Playlists",
    log: "Listening log",
    addEntry: "New entry",
    logEmpty: "The log is empty.",
    logEmptyHint: "Write down what was listened to and when.",
    removeTrack: "Delete",
    untagged: "No artist",
    plays: "Plays",
    playlistLabel: "Playlist",
    allTracks: "All tracks",
    newPlaylist: "New playlist",
    createPlaylist: "Create",
    playlistsEmpty: "No playlists yet.",
    playlistsEmptyHint: "Make a playlist and put the tracks in the order you want.",
    pickPlaylist: "Pick a playlist to see its tracks.",
    rename: "Rename",
    deletePlaylist: "Delete the playlist",
    addTrack: "Add a track",
    chooseTrack: "Choose a track",
    add: "Add",
    playlistEmpty: "The playlist is empty.",
    missingTrack: "This track left the library.",
    moveUp: "Up",
    moveDown: "Down",
    removeItem: "Remove",
    removeEntry: "Delete",
    artist: "Artist",
    trackTitle: "Title",
    kind: "Kind",
    date: "Date",
    rating: "Rating (1-10)",
    track: "Link to a track",
    noTrackLink: "No link",
    notes: "Notes",
    kinds: {
      album: "Album",
      track: "Track",
      live: "Live",
      other: "Other",
    },
  },
  errors: {
    load: "The culture corner could not be loaded.",
    save: "The change was not saved.",
    title: "A title is required.",
    venue: "A place is required.",
    venueName: "A place name is required.",
    rating: "A rating must be a whole number from 1 to 10.",
    price: "A price must have both an amount and a currency, such as 1200 RSD.",
    link: "A link must start with http:// or https://.",
    photoType: "A ticket may be a picture or a PDF.",
    playback: "The track could not be played.",
    audioFormat: "MP3, FLAC, Ogg, M4A and WAV are supported.",
    importFailed: "The file could not be imported.",
    entryArtist: "An artist is required.",
    entryTitle: "A title is required.",
  },
  settings: {
    caption: "The programme remembers what has passed.",
    hint: "When this is on, the programme asks about plans whose date has passed.",
    saved: "Saved.",
    loadError: "The setting could not be loaded.",
    saveError: "The setting was not saved.",
  },
  widget: {
    empty: "Nothing on the programme ahead.",
    loading: "Loading…",
    loadError: "The programme could not be loaded.",
  },
};
