/**
 * CULTURE's own copy, in Serbian - the SHAPE every other locale of this module
 * is checked against (ADR-090).
 *
 * **Why this is not in `strings.ts`.** The shell's table is part of the startup
 * chunk and this module's page is not: a module that put its page copy there
 * would pay for it on every launch, whether or not anybody ever opened the
 * culture corner. So the module carries its own table, `copy.ts` registers it
 * with the locale machinery the moment this chunk loads, and from that moment
 * switching language rewrites these leaves in place exactly as it rewrites the
 * shell's.
 *
 * English is `copy.en.ts`, typed `typeof sr` - one compile error per sentence
 * left untranslated and one per key invented.
 *
 * No `as const`: the literal type of a sentence is not something either locale
 * should be pinned to, and `typeof sr` widened to `string` is exactly the shape
 * `en` has to match.
 */
export const sr = {
  page: {
    // The page's own header is the module's name, which the shell draws from the
    // manifest; this is the line under it.
    subtitle:
      "Muzeji, predstave, koncerti i bioskop - jedan kutak za kulturu, sa programom i muzikom.",
    loading: "Učitavanje…",
    tabsLabel: "Oblasti kulture",
  },
  tabs: {
    visits: "Posete",
    venues: "Mesta",
    programme: "Program",
    art: "Vodič",
    music: "Muzika",
  },
  // Words more than one form draws, so they are said once.
  more: "Prikaži još",
  save: "Sačuvaj",
  cancel: "Otkaži",
  close: "Zatvori",
  confirm: "Potvrdi",
  // The ten visit kinds, in `VISIT_KINDS` order (the store's and the schema's
  // own list, which the pickers render as they stand).
  kinds: {
    museum: "Muzej",
    gallery: "Galerija",
    exhibition: "Izložba",
    theatre: "Pozorište",
    opera: "Opera",
    ballet: "Balet",
    concert: "Koncert",
    cinema: "Bioskop",
    festival: "Festival",
    other: "Ostalo",
  },
  // The twelve month names, January first - what each month card is headed with.
  months: [
    "januar",
    "februar",
    "mart",
    "april",
    "maj",
    "jun",
    "jul",
    "avgust",
    "septembar",
    "oktobar",
    "novembar",
    "decembar",
  ],
  filters: {
    kind: "Vrsta",
    place: "Mesto",
    query: "Pretraga",
    anyKind: "Sve vrste",
    anyPlace: "Sva mesta",
    clear: "Očisti filter",
    noResults: "Nema poseta koje odgovaraju filteru.",
  },
  visits: {
    title: "Posete",
    empty: "Još nema poseta.",
    emptyHint: "Dodaj prvu posetu: naslov, mesto i datum.",
    add: "Nova poseta",
    edit: "Uredi",
    remove: "Obriši",
    asList: "Lista",
    asCalendar: "Kalendar",
    previousYear: "Prethodna godina",
    nextYear: "Sledeća godina",
    kind: "Vrsta",
    titleLabel: "Naslov",
    venueLabel: "Mesto",
    city: "Grad",
    date: "Datum",
    startTime: "Vreme početka",
    rating: "Ocena (1-10)",
    price: "Cena",
    currency: "Valuta",
    notes: "Beleške",
    withWhom: "S kim",
    attach: "Priloži kartu",
    photos: "Prilozi",
    noPhotos: "Bez priloga",
    noRating: "Bez ocene",
  },
  venues: {
    title: "Mesta",
    add: "Novo mesto",
    edit: "Uredi",
    remove: "Obriši",
    empty: "Još nema zapamćenih mesta.",
    emptyHint: "Svaka poseta pamti mesto na kojem je bila, pa se mesta skupljaju sama.",
    noCity: "Bez grada",
    visitsCount: "Poseta",
    name: "Naziv",
    city: "Grad",
    kind: "Vrsta",
    notes: "Beleške o mestu",
  },
  programme: {
    title: "Program",
    add: "Novi plan",
    empty: "Program je prazan.",
    emptyHint: "Zapiši šta se planira, pa se posle datuma plan pretvara u posetu.",
    askHint: "Prošli planovi bez odgovora",
    went: "Bilo je",
    didNotGo: "Otkaži plan",
    becameVisit: "Postalo poseta",
    upcoming: "Predstoji",
    past: "Prošlo",
    openLink: "Otvori link",
    remove: "Obriši",
    kind: "Vrsta",
    titleLabel: "Naslov",
    venueLabel: "Mesto",
    city: "Grad",
    date: "Datum",
    startTime: "Vreme početka",
    link: "Link",
    notes: "Beleške",
  },
  art: {
    title: "Likovni vodič",
    loadError: "Vodič nije mogao da se pročita.",
    empty: "Nema instaliranog dataset paketa.",
    emptyHint: "Likovni vodič se puni iz dataset paketa koji sadrži fajl art.json.",
    search: "Pretraga",
    artist: "Autor",
    museum: "Muzej",
    period: "Period",
    anyArtist: "Svi autori",
    anyMuseum: "Svi muzeji",
    anyPeriod: "Svi periodi",
    unknownPeriod: "Bez godine",
    century: "vek",
    skipped: "Paketi koji nisu pročitani",
    noResults: "Nema dela koja odgovaraju filteru.",
    credit: "Zasluga",
    licence: "Licenca",
  },
  music: {
    player: "Plejer",
    noTrack: "Ništa se ne pušta.",
    seek: "Pomeri u numeri",
    previous: "Prethodna",
    play: "Pusti",
    pause: "Pauza",
    next: "Sledeća",
    repeatQueue: "Ponavljaj red",
    library: "Moje numere",
    import: "Uvezi audio",
    importing: "Uvozim…",
    libraryEmpty: "Biblioteka je prazna.",
    libraryEmptyHint: "Uvezi MP3, FLAC, Ogg, M4A ili WAV - naslovi i trajanje se čitaju iz fajla.",
    playlists: "Liste",
    log: "Dnevnik slušanja",
    addEntry: "Novi unos",
    logEmpty: "Dnevnik je prazan.",
    logEmptyHint: "Zapiši šta se slušalo i kada.",
    removeTrack: "Obriši",
    untagged: "Bez izvođača",
    plays: "Puštanja",
    playlistLabel: "Lista",
    allTracks: "Sve numere",
    newPlaylist: "Nova lista",
    createPlaylist: "Napravi",
    playlistsEmpty: "Još nema listi.",
    playlistsEmptyHint: "Napravi listu i poređaj numere kako želiš.",
    pickPlaylist: "Izaberi listu da vidiš njene numere.",
    rename: "Preimenuj",
    deletePlaylist: "Obriši listu",
    addTrack: "Dodaj numeru",
    chooseTrack: "Izaberi numeru",
    add: "Dodaj",
    playlistEmpty: "Lista je prazna.",
    missingTrack: "Numera više nije u biblioteci.",
    moveUp: "Gore",
    moveDown: "Dole",
    removeItem: "Ukloni",
    removeEntry: "Obriši",
    artist: "Izvođač",
    trackTitle: "Naslov",
    kind: "Vrsta",
    date: "Datum",
    rating: "Ocena (1-10)",
    track: "Poveži sa numerom",
    noTrackLink: "Bez veze",
    notes: "Beleške",
    // The four listening-log kinds, in `MUSIC_LOG_KINDS` order.
    kinds: {
      album: "Album",
      track: "Numera",
      live: "Uživo",
      other: "Ostalo",
    },
  },
  errors: {
    load: "Kutak za kulturu nije mogao da se učita.",
    save: "Izmena nije sačuvana.",
    title: "Naslov je obavezan.",
    venue: "Mesto je obavezno.",
    venueName: "Naziv mesta je obavezan.",
    rating: "Ocena mora biti ceo broj od 1 do 10.",
    price: "Cena mora biti iznos i valuta, na primer 1200 RSD.",
    link: "Link mora da počinje sa http:// ili https://.",
    photoType: "Prilog može biti slika ili PDF.",
    playback: "Numeru nije moguće pustiti.",
    audioFormat: "Podržani su MP3, FLAC, Ogg, M4A i WAV.",
    importFailed: "Fajl nije mogao da se uveze.",
    entryArtist: "Izvođač je obavezan.",
    entryTitle: "Naslov je obavezan.",
  },
  settings: {
    caption: "Program pamti šta je prošlo.",
    hint: "Kada je uključeno, program pita za planove čiji je datum prošao.",
    saved: "Sačuvano.",
    loadError: "Podešavanje nije moglo da se učita.",
    saveError: "Podešavanje nije sačuvano.",
  },
  widget: {
    empty: "Nema planova pred tobom.",
    loading: "Učitavanje…",
    loadError: "Program nije mogao da se učita.",
  },
};
