import { sr } from "./copy.sr.js";

/**
 * CAR in English -- the same shape as `copy.sr.ts`, checked by the compiler.
 *
 * `typeof sr` is the whole mechanism: a sentence left untranslated, a key
 * invented here, or a nested table that does not match is one compile error
 * each. The register is the app's own English: sentence case, informative, no
 * exclamation marks.
 */
export const en: typeof sr = {
  page: {
    subtitle: "A service book: vehicles, services, intervals, fuel and faults.",
    loading: "Loading…",
  },
  errors: {
    load: "The vehicles could not be loaded.",
    mutate: "The change was not saved.",
    name: "A vehicle needs a name.",
    year: "The year must be a number.",
    date: "A date is required.",
    odometer: "The odometer must be a whole number, zero or more.",
    integer: "The value must be a whole number above zero.",
    description: "A description is required.",
    symptom: "A symptom is required.",
    money: "An amount and its currency go together, or neither does.",
    quantity: "The quantity must be a number above zero.",
  },
  garage: {
    title: "Garage",
    add: "Add a vehicle",
    edit: "Edit the vehicle",
    save: "Save",
    cancel: "Cancel",
    archive: "Archive",
    unarchive: "Put back in the garage",
    remove: "Delete",
    archived: "Archived",
    emptyTitle: "No vehicles yet",
    emptyBody: "Add the first vehicle — services, intervals and fuel are kept per vehicle.",
    name: "Name",
    make: "Make",
    model: "Model",
    year: "Year",
    plate: "Plate",
    vin: "VIN (optional)",
    fuelType: "Fuel",
    distanceUnit: "Distance unit",
    notes: "Notes",
    vinHint: "A VIN is 17 characters, without the letters I, O and Q.",
    removeTitle: "Deleting a vehicle",
    removeQuestion: "This deletes the vehicle and its whole history — services, fuel and faults.",
    removeNote: "If the car was sold, archive it instead: the history stays.",
    removeConfirm: "Delete the vehicle",
  },
  fuelTypes: {
    petrol: "Petrol",
    diesel: "Diesel",
    lpg: "LPG",
    cng: "CNG",
    hybrid: "Hybrid",
    electric: "Electric",
    other: "Other",
  },
  units: {
    km: "km",
    mi: "mi",
  },
  categories: {
    oil: "Oil",
    filters: "Filters",
    tyres: "Tyres",
    brakes: "Brakes",
    battery: "Battery",
    "timing-belt": "Timing belt",
    inspection: "Technical inspection",
    registration: "Registration",
    repair: "Repair",
    other: "Other",
  },
  due: {
    title: "What is due",
    rule: "An interval is what was entered: kilometres, months, or both — whichever comes first is due.",
    empty: "No interval is set, so nothing can come due.",
    ok: "Fine",
    soon: "Due soon",
    overdue: "Overdue",
    left: "{value} {phrase} left",
    passed: "{value} {phrase} overdue",
    days: "days",
    units: "{unit}",
    byDate: "the date decides this",
    byDistance: "the odometer decides this",
    noHistory: "No service of this kind has been logged, so there is nothing to measure from.",
    daysLabel: "Due soon means within (days)",
    unitsLabel: "Due soon means within ({unit})",
    saveThresholds: "Save the thresholds",
    thresholdsNow: "Now:",
  },
  readings: {
    title: "Odometer",
    hint: "The readings are what today's estimate and every measured distance rest on.",
    estimated: "Today's estimate:",
    empty: "No reading has been logged.",
    date: "Date",
    value: "Odometer ({unit})",
    add: "Add a reading",
    remove: "Delete",
    newSegment: "A new odometer (replacement)",
    segment: "Odometer {n}",
  },
  log: {
    title: "Service log",
    hint: "What was done, where, and for how much. Receipts hang off the service.",
    empty: "No service has been logged.",
    add: "Add a service",
    save: "Save the service",
    cancel: "Cancel",
    date: "Date",
    category: "Kind",
    description: "Description",
    odometer: "Odometer ({unit})",
    cost: "Price",
    currency: "Currency",
    currencyHint: "The price and its currency go together; without them the service has no price.",
    skipped: "Receipts not attached: {value} (they were too large).",
    workshop: "Garage",
    parts: "Parts",
    attach: "Add a receipt",
    removeReceipt: "Delete the receipt",
    noReceipts: "No receipts.",
    remove: "Delete the service",
  },
  intervals: {
    title: "Intervals",
    hint: "One interval per kind of service: whichever comes first is due.",
    everyKm: "Every ({unit})",
    everyMonths: "Every (months)",
    save: "Save",
    clear: "Remove",
    problem: "An interval needs kilometres, months, or both.",
  },
  fuel: {
    title: "Fuel",
    rule: "Consumption is measured from full tank to full tank: the fills in between are summed, and a stretch with no full tank is left out.",
    noMeasure: "There are not two full tanks yet, so consumption has not been measured.",
    empty: "No fill has been logged.",
    per100: "Consumption:",
    mpg: "mpg:",
    segments: "Measured stretches:",
    add: "Add a fill",
    save: "Save the fill",
    date: "Date",
    quantity: "Quantity ({unit})",
    odometer: "Odometer ({unit})",
    price: "Price per ({unit})",
    total: "Total",
    currency: "Currency",
    fullTank: "The tank is full",
    priceHint: "One price is enough: per unit, or the total.",
    full: "Full",
    noOdometer: "No odometer",
    remove: "Delete",
  },
  faults: {
    title: "Faults",
    empty: "No fault has been logged.",
    add: "Add a fault",
    save: "Save the fault",
    markFixed: "Fixed",
    remove: "Delete",
    date: "Date",
    status: "State",
    symptom: "What happens",
    service: "The service that fixed it",
    noService: "No service",
    fixNotes: "What helped",
  },
  faultStatus: {
    open: "Open",
    fixed: "Fixed",
  },
  costs: {
    title: "Costs",
    hint: "Amounts are never converted between currencies, so each currency keeps its own row.",
    byMonth: "By month",
    byCategory: "By kind",
    fuelCategory: "Fuel",
    empty: "No cost has been logged: a service with no price and a fill with no price are not summed.",
    count: "{value} entries",
  },
  settings: {
    caption: "The thresholds cover every vehicle in the profile.",
    days: "Due soon means within (days)",
    distance: "Due soon means within ({unit})",
    save: "Save",
    saved: "Saved.",
    hint: "The car speaks in the morning of the day an interval comes due.",
    loadError: "The thresholds could not be loaded.",
    saveError: "The thresholds were not saved.",
  },
  widget: {
    empty: "Nothing is coming due.",
    loading: "Loading…",
    loadError: "The next service could not be loaded.",
  },
};
