/**
 * CAR's own copy, in Serbian -- the SHAPE every other locale of this module is
 * checked against (ADR-090).
 *
 * **Why this is not in `strings.ts`.** The shell's table is part of the startup
 * chunk and this module's page is not, so a module that put its page copy there
 * would pay for it on every launch, whether or not anybody ever opened a car.
 * `copy.ts` registers this table with the locale machinery the moment the chunk
 * loads, and from that moment switching language rewrites these leaves in place
 * exactly as it rewrites the shell's.
 *
 * **The two LISTS are read by key**: `fuelTypes`, `units`, `categories` and
 * `faultStatus` are indexed by the module's own closed vocabularies (never by
 * anything a user typed), and every leaf of them is drawn wherever the
 * vocabulary is -- a picker, a row, a chip. `{unit}`/`{value}`/`{n}`/`{phrase}`
 * are filled by the component that owns the sentence, because a number is the
 * locale's (`Intl`) while the sentence around it is this table's.
 *
 * English is `copy.en.ts`, typed `typeof sr` -- one compile error per sentence
 * left untranslated and one per key invented.
 */
export const sr = {
  page: {
    subtitle: "Servisna knjiga: vozila, servisi, intervali, gorivo i kvarovi.",
    loading: "Učitavanje…",
  },
  errors: {
    load: "Nije moguće učitati podatke o vozilima.",
    mutate: "Izmena nije sačuvana.",
    name: "Naziv vozila je obavezan.",
    year: "Godina mora biti broj.",
    date: "Datum je obavezan.",
    odometer: "Kilometraža mora biti ceo broj, nula ili više.",
    integer: "Vrednost mora biti ceo broj veći od nule.",
    description: "Opis je obavezan.",
    symptom: "Simptom je obavezan.",
    money: "Iznos i valuta idu zajedno, ili ni jedno.",
    quantity: "Količina mora biti broj veći od nule.",
  },
  garage: {
    title: "Garaža",
    add: "Dodaj vozilo",
    edit: "Izmeni vozilo",
    save: "Sačuvaj",
    cancel: "Otkaži",
    archive: "Arhiviraj",
    unarchive: "Vrati u garažu",
    remove: "Obriši",
    archived: "Arhivirano",
    emptyTitle: "Još nema vozila",
    emptyBody: "Dodaj prvo vozilo — servisi, intervali i gorivo vode se po vozilu.",
    name: "Naziv",
    make: "Marka",
    model: "Model",
    year: "Godina",
    plate: "Tablice",
    vin: "VIN (opciono)",
    fuelType: "Gorivo",
    distanceUnit: "Jedinica rastojanja",
    notes: "Beleške",
    vinHint: "VIN je 17 znakova, bez slova I, O i Q.",
    removeTitle: "Brisanje vozila",
    removeQuestion: "Brišeš vozilo i celu njegovu istoriju — servise, gorivo i kvarove.",
    removeNote: "Ako je auto prodat, arhiviraj ga umesto brisanja: istorija ostaje.",
    removeConfirm: "Obriši vozilo",
  },
  fuelTypes: {
    petrol: "Benzin",
    diesel: "Dizel",
    lpg: "TNG",
    cng: "CNG",
    hybrid: "Hibrid",
    electric: "Električni",
    other: "Drugo",
  },
  units: {
    km: "km",
    mi: "mi",
  },
  categories: {
    oil: "Ulje",
    filters: "Filteri",
    tyres: "Gume",
    brakes: "Kočnice",
    battery: "Akumulator",
    "timing-belt": "Zupčasti kaiš",
    inspection: "Tehnički pregled",
    registration: "Registracija",
    repair: "Popravka",
    other: "Ostalo",
  },
  due: {
    title: "Šta je due",
    rule: "Interval je ono što je upisano: kilometri, meseci ili oboje — dospeva ono što prvo dođe.",
    empty: "Nijedan interval nije upisan, pa nema šta da dospe.",
    ok: "U redu",
    soon: "Uskoro",
    overdue: "Dospelo",
    left: "još {value} {phrase}",
    passed: "{value} {phrase} je prošlo",
    days: "dana",
    units: "{unit}",
    byDate: "odlučuje datum",
    byDistance: "odlučuje kilometraža",
    noHistory: "Nema servisa ove vrste, pa nema od čega da se meri.",
    daysLabel: "Uskoro znači u narednih (dana)",
    unitsLabel: "Uskoro znači na još ({unit})",
    saveThresholds: "Sačuvaj pragove",
    thresholdsNow: "Sada:",
  },
  readings: {
    title: "Kilometraža",
    hint: "Očitavanja su osnova za procenu današnje kilometraže i za merenje pređenog puta.",
    estimated: "Današnja procena:",
    empty: "Nijedno očitavanje nije upisano.",
    date: "Datum",
    value: "Kilometraža ({unit})",
    add: "Dodaj očitavanje",
    remove: "Obriši",
    newSegment: "Novi odometar (zamena)",
    segment: "Odometer {n}",
  },
  log: {
    title: "Servisna knjiga",
    hint: "Šta je urađeno, gde i za koliko. Računi se kače na servis.",
    empty: "Nijedan servis nije upisan.",
    add: "Dodaj servis",
    save: "Sačuvaj servis",
    cancel: "Otkaži",
    date: "Datum",
    category: "Vrsta",
    description: "Opis",
    odometer: "Kilometraža ({unit})",
    cost: "Cena",
    currency: "Valuta",
    currencyHint: "Cena i valuta idu zajedno; bez njih servis ostaje bez cene.",
    skipped: "Računa nije priloženo: {value} (preveliki su).",
    workshop: "Servis / radionica",
    parts: "Delovi",
    attach: "Dodaj račun",
    removeReceipt: "Obriši račun",
    noReceipts: "Bez računa.",
    remove: "Obriši servis",
  },
  intervals: {
    title: "Intervali",
    hint: "Isti interval važi za svaki servis te vrste: dospeva prvo što dođe.",
    everyKm: "Na ({unit})",
    everyMonths: "Na (meseci)",
    save: "Sačuvaj",
    clear: "Ukloni",
    problem: "Interval treba kilometre, mesece ili oboje.",
  },
  fuel: {
    title: "Gorivo",
    rule: "Potrošnja se meri od punog do punog rezervoara: dolivanja između se sabiraju, a deonica bez punog rezervoara se izostavlja.",
    noMeasure: "Nema još dve pune kante, pa potrošnja nije izmerena.",
    empty: "Nijedno točenje nije upisano.",
    per100: "Potrošnja:",
    mpg: "mpg:",
    segments: "Izmerenih deonica:",
    add: "Dodaj točenje",
    save: "Sačuvaj točenje",
    date: "Datum",
    quantity: "Količina ({unit})",
    odometer: "Kilometraža ({unit})",
    price: "Cena po ({unit})",
    total: "Ukupno",
    currency: "Valuta",
    fullTank: "Rezervoar je pun",
    priceHint: "Dovoljna je jedna cena: po jedinici ili ukupno.",
    full: "Pun",
    noOdometer: "Bez kilometraže",
    remove: "Obriši",
  },
  faults: {
    title: "Kvarovi",
    empty: "Nijedan kvar nije upisan.",
    add: "Dodaj kvar",
    save: "Sačuvaj kvar",
    markFixed: "Rešeno",
    remove: "Obriši",
    date: "Datum",
    status: "Stanje",
    symptom: "Šta se dešava",
    service: "Servis koji ga je rešio",
    noService: "Bez servisa",
    fixNotes: "Šta je pomoglo",
  },
  faultStatus: {
    open: "Otvoren",
    fixed: "Rešen",
  },
  costs: {
    title: "Troškovi",
    hint: "Iznosi se nikada ne preračunavaju iz jedne valute u drugu, pa svaka valuta ima svoj red.",
    byMonth: "Po mesecu",
    byCategory: "Po vrsti",
    fuelCategory: "Gorivo",
    empty: "Nijedan trošak nije upisan: servis bez cene i točenje bez cene se ne sabiraju.",
    count: "{value} unosa",
  },
  settings: {
    caption: "Pragovi važe za sva vozila u profilu.",
    days: "„Uskoro“ znači u narednih (dana)",
    distance: "„Uskoro“ znači na još ({unit})",
    save: "Sačuvaj",
    saved: "Sačuvano.",
    hint: "Automobil se oglašava ujutru, na dan kada interval dospeva.",
    loadError: "Nije moguće učitati pragove.",
    saveError: "Pragovi nisu sačuvani.",
  },
  widget: {
    empty: "Ništa ne dospeva.",
    loading: "Učitavanje…",
    loadError: "Nije moguće učitati sledeći servis.",
  },
};
