import { describe, expect, it } from "vitest";
import { MAX_CULTURE_TITLE_LENGTH, MAX_CULTURE_NAME_LENGTH, MAX_CULTURE_TRACK_NUMBER } from "@nexus/db";
import { AudioImportError, readAudioTags, sniffAudioMime } from "./audio.js";

/**
 * Tag reading, against FIXTURE FILES THIS FILE BUILDS, byte by byte.
 *
 * **Why the fixtures are built here rather than committed.** A repository that
 * carries an audio file carries somebody's recording, and the licence question
 * is not one this test needs to raise. Both fixtures below are a few hundred
 * bytes (the WAV is one second of silence, the FLAC carries metadata and no
 * audio frames at all), they are generated by the code in this file, and every
 * expected value in the tests is a value the builder WROTE - so the assertions
 * are the file's own layout read back, not a decoder's opinion.
 *
 * The layouts are the published ones: RIFF/WAVE with the EXIF 2.3 `INFO`
 * tag ids `music-metadata` maps (`INAM` title, `IART` artist, `IPRD` album,
 * `ITRK` track, `ICRD` date), and FLAC's `STREAMINFO` + VORBIS_COMMENT blocks
 * (https://xiph.org/flac/format.html).
 *
 * MP3, Ogg and M4A are covered by `sniffAudioMime` rather than by a fixture:
 * a hand-written MPEG or Ogg stream is a frame-accurate invention, and the
 * mime gate is the half of the import this module owns. Tag reading itself is
 * one code path over whatever `music-metadata` reports, demonstrated on two
 * containers.
 */

const BOUNDS = {
  title: MAX_CULTURE_TITLE_LENGTH,
  name: MAX_CULTURE_NAME_LENGTH,
  trackNumber: MAX_CULTURE_TRACK_NUMBER,
};

function ascii(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.byteLength, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.byteLength;
  }
  return out;
}

function u32le(value: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, value, true);
  return out;
}

function u32be(value: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, value, false);
  return out;
}

/** One RIFF chunk: its four-character id, its length, and its bytes padded to an even count. */
function riffChunk(id: string, payload: Uint8Array): Uint8Array {
  const padded = payload.byteLength % 2 === 0 ? payload : concat(payload, new Uint8Array(1));
  return concat(ascii(id), u32le(payload.byteLength), padded);
}

/**
 * One second of silent 16-bit mono PCM at 8 kHz, wrapped in a WAVE file whose
 * `LIST/INFO` chunk carries `tags` (an empty map leaves the chunk out, which is
 * the untagged file the title fallback is about).
 */
function wav(tags: Readonly<Record<string, string>>): Uint8Array {
  const format = concat(
    new Uint8Array([1, 0]), // PCM
    new Uint8Array([1, 0]), // one channel
    u32le(8_000), // sample rate
    u32le(16_000), // byte rate: 8000 * 1 channel * 2 bytes
    new Uint8Array([2, 0]), // block align
    new Uint8Array([16, 0]), // bits per sample
  );
  const infoEntries = Object.entries(tags);
  const info =
    infoEntries.length === 0
      ? null
      : concat(
          ascii("INFO"),
          ...infoEntries.map(([id, value]) => riffChunk(id, ascii(value))),
        );
  const samples = new Uint8Array(16_000); // 8000 samples * 2 bytes = 1.000 s
  const body = concat(
    ascii("WAVE"),
    riffChunk("fmt ", format),
    ...(info === null ? [] : [riffChunk("LIST", info)]),
    riffChunk("data", samples),
  );
  return concat(ascii("RIFF"), u32le(body.byteLength), body);
}

/**
 * The tagged WAVE the tag tests read.
 *
 * **The tag text is deliberately ASCII, and that is a fact about the format
 * rather than a shortcut.** A RIFF `INFO` field is a SINGLE-BYTE string
 * (Windows-1252 in practice, EXIF 2.3's own definition), so a Serbian title put
 * into a WAV's tag is decoded through whichever code page the reader guesses -
 * and `music-metadata` reads it as Latin-1. A real WAV tagged by a Serbian
 * encoder therefore reads with mojibake in ANY tool that guesses, and the
 * diacritic case is asserted on the FLAC fixture below instead, where Vorbis
 * comments are defined as UTF-8 and come back exactly as written.
 */
function wavWithInfo(): Uint8Array {
  return wav({
    INAM: "Zvucni test",
    IART: "Test Izvodjac",
    IPRD: "Test Album",
    ITRK: "3",
    ICRD: "2026",
  });
}

/** One FLAC file: `STREAMINFO` declaring 44 100 samples at 44.1 kHz, and a VORBIS_COMMENT block. */
function flacWithComments(): Uint8Array {
  const sampleRate = 44_100;
  const channels = 2;
  const bitsPerSample = 16;
  const totalSamples = 44_100;
  // The 64-bit packing STREAMINFO ends with, per the format's own bit layout:
  // sample rate (20 bits), channels-1 (3), bits per sample-1 (5), samples (36).
  const packed =
    (BigInt(sampleRate) << 44n) |
    (BigInt(channels - 1) << 41n) |
    (BigInt(bitsPerSample - 1) << 36n) |
    BigInt(totalSamples);
  const packedBytes = new Uint8Array(8);
  for (let index = 0; index < 8; index += 1) {
    packedBytes[index] = Number((packed >> BigInt(8 * (7 - index))) & 0xffn);
  }
  const streamInfo = concat(
    new Uint8Array([0x10, 0x00]), // minimum block size 4096
    new Uint8Array([0x10, 0x00]), // maximum block size 4096
    new Uint8Array([0, 0, 0]), // minimum frame size 0 (unknown)
    new Uint8Array([0, 0, 0]), // maximum frame size 0 (unknown)
    packedBytes,
    // The MD5 of the unencoded audio, which a file with no audio frames cannot
    // have: sixteen zero bytes is what a stream that was never written carries.
    new Uint8Array(16),
  );
  expect(streamInfo.byteLength).toBe(34);

  const vendor = ascii("nexus-culture-test");
  const comments = [
    "TITLE=Severni vetar",
    "ARTIST=Test Izvođač",
    "ALBUM=Test Album",
    "TRACKNUMBER=2",
    "DATE=1977",
  ];
  const commentBlock = concat(
    u32le(vendor.byteLength),
    vendor,
    u32le(comments.length),
    ...comments.map((comment) => {
      const bytes = ascii(comment);
      return concat(u32le(bytes.byteLength), bytes);
    }),
  );
  return concat(
    ascii("fLaC"),
    new Uint8Array([0x00]), // STREAMINFO, not the last block
    u32be(streamInfo.byteLength).subarray(1), // a 24-bit big-endian length
    streamInfo,
    new Uint8Array([0x84]), // VORBIS_COMMENT, last block
    u32be(commentBlock.byteLength).subarray(1),
    commentBlock,
  );
}

describe("sniffAudioMime", () => {
  it("knows the five containers the library holds", () => {
    expect(sniffAudioMime(ascii("ID3\u0004\u0000"))).toBe("audio/mpeg");
    expect(sniffAudioMime(new Uint8Array([0xff, 0xfb, 0x90, 0x00]))).toBe("audio/mpeg");
    expect(sniffAudioMime(ascii("fLaC"))).toBe("audio/flac");
    expect(sniffAudioMime(ascii("OggS"))).toBe("audio/ogg");
    expect(sniffAudioMime(concat(new Uint8Array([0, 0, 0, 0x20]), ascii("ftypM4A ")))).toBe(
      "audio/mp4",
    );
    expect(sniffAudioMime(ascii("RIFF....WAVE"))).toBe("audio/wav");
  });

  it("refuses anything else by answering null, including a file named like audio", () => {
    expect(sniffAudioMime(ascii("Ovo je običan tekst, ne muzika."))).toBeNull();
    expect(sniffAudioMime(new Uint8Array())).toBeNull();
    // A frame sync byte pair is required, not just a 0xFF: 0xFF 0x00 is not MPEG.
    expect(sniffAudioMime(new Uint8Array([0xff, 0x00]))).toBeNull();
  });
});

describe("readAudioTags", () => {
  it("reads a WAVE file's INFO tags and its duration from the data chunk", async () => {
    const tags = await readAudioTags(wavWithInfo(), "zvu- test.wav", BOUNDS);
    expect(tags).toEqual({
      mime: "audio/wav",
      title: "Zvucni test",
      artist: "Test Izvodjac",
      album: "Test Album",
      trackNumber: 3,
      releaseYear: 2026,
      // 16 000 bytes of 16-bit mono at 8 kHz is one second, exactly.
      durationMs: 1_000,
    });
  });

  it("reads a FLAC file's Vorbis comments and its duration from STREAMINFO", async () => {
    const tags = await readAudioTags(flacWithComments(), "severi.flac", BOUNDS);
    expect(tags.mime).toBe("audio/flac");
    expect(tags.title).toBe("Severni vetar");
    expect(tags.artist).toBe("Test Izvođač");
    expect(tags.album).toBe("Test Album");
    expect(tags.trackNumber).toBe(2);
    expect(tags.releaseYear).toBe(1977);
    // 44 100 samples at 44.1 kHz is one second; FLAC states the count itself, so
    // no frame has to be decoded for this number to be exact.
    expect(tags.durationMs).toBe(1_000);
  });

  it("falls back to the file's own name when the file carries no title", async () => {
    const tags = await readAudioTags(wav({}), "bez naslova.wav", BOUNDS);
    expect(tags.title).toBe("bez naslova");
    expect(tags.artist).toBeNull();
    expect(tags.album).toBeNull();
    expect(tags.trackNumber).toBeNull();
    expect(tags.releaseYear).toBeNull();
    expect(tags.durationMs).toBe(1_000);
  });

  it("refuses bytes that are not audio, naming the format rather than the file's extension", async () => {
    const failure = await readAudioTags(ascii("nije muzika"), "lazni.mp3", BOUNDS).catch(
      (error: unknown) => error,
    );
    expect(failure).toBeInstanceOf(AudioImportError);
    expect((failure as AudioImportError).problem).toBe("unsupported-format");
  });
});
