import { sr } from "./copy.sr.js";

/**
 * MINI-APPS in English - the same shape as `copy.sr.ts`, checked by the compiler.
 *
 * `typeof sr` is the whole mechanism: a sentence left untranslated, a key
 * invented here, or a nested table that does not match is one compile error
 * each. The register is the app's own English: sentence case, informative, no
 * exclamation marks.
 *
 * The tile ids and city ids are keys and stay as they are; only the words beside
 * them change.
 */
export const en: typeof sr = {
  page: {
    subtitle: "Nine small tools in one place - open the one you need.",
    loading: "Loading…",
  },
  grid: {
    hint: "Pick a tool. The last one you open is remembered.",
  },
  actions: {
    back: "Back to the tools",
    save: "Save",
    cancel: "Cancel",
    remove: "Delete",
    rename: "Rename",
    undo: "Undo",
    redo: "Redo",
    clear: "Clear",
    copy: "Copy",
    copied: "Copied.",
    start: "Start",
    stop: "Stop",
    today: "Today",
  },
  apps: {
    metronome: {
      name: "Metronome",
      hint: "Tempo, time signature and accents, with tap tempo.",
    },
    dice: {
      name: "Dice and picks",
      hint: "Dice notation, a coin, a pick from a list, a shuffle and a random number.",
    },
    tally: {
      name: "Counters",
      hint: "Several named counters, kept.",
    },
    scoreboard: {
      name: "Scoreboard",
      hint: "Players, rounds, scores and standings.",
    },
    typing: {
      name: "Typing",
      hint: "Drills for the Serbian and the English layout, with speed and accuracy.",
    },
    dates: {
      name: "Date calculator",
      hint: "Days between dates, adding days, and working days in Serbia.",
    },
    worldclock: {
      name: "World clock",
      hint: "The local times of picked cities and a meeting window across them.",
    },
    screenlight: {
      name: "Screen light",
      hint: "The window as a light: white, warm or red, with a brightness.",
    },
    qr: {
      name: "QR reader",
      hint: "Read a QR code from an image, then copy or open what it says.",
    },
  },
  metronome: {
    bpm: "Tempo (BPM)",
    beats: "Beats per bar",
    note: "Note value",
    subdivisions: "Subdivisions",
    accents: "Accents",
    beat: "Beat",
    beatStrong: "Strong",
    beatWeak: "Weak",
    beatOff: "Off",
    bar: "Bar",
    pulse: "Pulse",
    tapTitle: "Tap tempo",
    tap: "Tap in time",
    tapHint: "Tap at least twice; the tempo is the median gap.",
    tapResult: "Measured tempo",
    tapNone: "Nothing measured yet.",
    applyTap: "Use the measured tempo",
    audioUnavailable: "Sound is not available in this environment.",
    bpmError: "Tempo is a whole number from 20 to 400.",
  },
  dice: {
    notation: "Dice notation",
    notationHint: "For example 2d6+3, 4d6kh3 or d20.",
    roll: "Roll the dice",
    total: "Total",
    dropped: "Dropped",
    coinTitle: "Coin",
    flip: "Flip a coin",
    heads: "Heads",
    tails: "Tails",
    pickTitle: "Pick from a list",
    list: "List",
    listHint: "One item per line.",
    count: "How many",
    pick: "Pick",
    shuffle: "Shuffle",
    numberTitle: "Random number",
    min: "From",
    max: "To",
    draw: "Draw",
    result: "Result",
    history: "History",
    historyEmpty: "No results yet.",
    historyHint: "The last 50 results are kept.",
    listEmpty: "A list needs at least one item.",
    countTooBig: "No more than the list holds.",
    countInvalid: "How many is a whole number of 1 or more.",
    rangeInvalid: "The lower bound must be at or below the upper one.",
    emptyError: "Type dice notation.",
    tooLongError: "The notation is too long.",
    syntaxError: "The notation is not valid.",
    noDiceError: "The notation needs at least one die.",
    diceCountError: "At most 100 dice in one term.",
    facesError: "Faces are from 2 to 1000.",
    keepCountError: "Keep is between 1 and the dice in the term.",
  },
  tally: {
    add: "Add a counter",
    name: "Name",
    step: "Step",
    floor: "Never below zero",
    plus: "Add",
    minus: "Subtract",
    total: "Total",
    empty: "No counters yet.",
    emptyBody: "Add the first counter, then move it with a click.",
    nameError: "A name is required and may be at most 60 characters.",
    stepError: "A step is a whole number from 1 to 1000.",
    limitError: "At most 24 counters.",
  },
  scoreboard: {
    players: "Players",
    playerName: "Player name",
    addPlayer: "Add a player",
    rounds: "Rounds",
    round: "Round",
    addRound: "Add a round",
    removeRound: "Delete the round",
    target: "Target",
    targetHint: "Leave it empty for a game with no target.",
    standings: "Standings",
    rank: "Rank",
    total: "Total",
    won: "Won",
    tied: "Tied",
    over: "The target has been reached.",
    empty: "No players yet.",
    emptyBody: "Add players, then write the scores round by round.",
    nameError: "A name is required and may be at most 40 characters.",
    limitError: "At most 32 players.",
    targetError: "A target is a whole number of 1 or more.",
    roundLimit: "At most 100 rounds.",
  },
  typing: {
    layout: "Layout",
    layoutNames: {
      "sr-Latn": "Serbian (Latin)",
      "en-US": "English (US)",
    },
    lesson: "Lesson",
    lessonHint: "Lessons are named by the keys they drill.",
    start: "Start",
    restart: "Again",
    target: "Text",
    nextKey: "Next key",
    space: "Space",
    wpm: "Words per minute",
    net: "Net",
    accuracy: "Accuracy",
    errors: "Errors",
    duration: "Duration",
    progress: "Progress",
    progressEmpty: "No results for this lesson yet.",
    best: "Best",
    practise: "Practise",
    newBest: "A new best result.",
    idle: "Pick a layout and a lesson, then start typing.",
  },
  dates: {
    difference: "Between two dates",
    from: "From",
    to: "To",
    days: "Days",
    workdays: "Working days",
    workdaysHint: "Weekends and state holidays are skipped.",
    calendar: "Years, months and days",
    years: "Years",
    months: "Months",
    weeks: "Weeks",
    adjust: "Add or subtract",
    base: "Date",
    add: "Add",
    subtract: "Subtract",
    result: "Result",
    holidays: "Non-working days",
    holidaysHint: "State and religious holidays, with the substitute day when a state holiday falls on a Sunday.",
    substitute: "Substitute for a state holiday",
    easter: "Orthodox Easter",
    format: "Format: YYYY-MM-DD",
    invalid: "That date is not valid.",
  },
  worldclock: {
    home: "Your zone",
    city: "City",
    add: "Add a city",
    cities: "Cities",
    empty: "No cities yet.",
    emptyBody: "Pick a city and add it to the clock.",
    local: "Local time",
    offset: "Offset",
    dst: "Daylight saving",
    dayAhead: "A day ahead",
    dayBehind: "A day behind",
    meeting: "Meeting",
    meetingHint: "Working hours are 09:00-17:00 in each city's own local time.",
    date: "Date",
    start: "From",
    end: "To",
    utc: "UTC",
    window: "A window that works",
    noWindow: "Working hours do not overlap on that day.",
    limitError: "At most 12 cities.",
    unknownZone: "Unknown time zone.",
  },
  screenlight: {
    cast: "Light colour",
    castWhite: "White",
    castWarm: "Warm",
    castRed: "Red",
    redHint: "Red light keeps night vision.",
    brightness: "Brightness",
    levelLow: "Low",
    levelMedium: "Medium",
    levelHigh: "High",
    leave: "Leave",
    hint: "Press Esc to go back to the tools.",
  },
  qr: {
    file: "From an image",
    choose: "Choose an image",
    fileHint: "A PNG or JPEG holding a QR code.",
    decoding: "Reading…",
    noCode: "There is no readable QR code in that image.",
    badImage: "That image could not be read.",
    tooLarge: "That image is too large to read.",
    text: "Text",
    urlHint: "Nexus never opens a link itself - copy it and open it in your browser.",
    empty: "No result yet.",
  },
  errors: {
    load: "The mini apps could not be loaded.",
    mutate: "The change was not saved.",
  },
  cities: {
    beograd: "Belgrade",
    zagreb: "Zagreb",
    sarajevo: "Sarajevo",
    podgorica: "Podgorica",
    ljubljana: "Ljubljana",
    bec: "Vienna",
    budimpesta: "Budapest",
    prag: "Prague",
    berlin: "Berlin",
    pariz: "Paris",
    amsterdam: "Amsterdam",
    london: "London",
    rim: "Rome",
    madrid: "Madrid",
    atina: "Athens",
    istanbul: "Istanbul",
    moskva: "Moscow",
    kijev: "Kyiv",
    njujork: "New York",
    cikago: "Chicago",
    losandjeles: "Los Angeles",
    toronto: "Toronto",
    meksiko: "Mexico City",
    saopaulo: "Sao Paulo",
    buenosajres: "Buenos Aires",
    kairo: "Cairo",
    najrobi: "Nairobi",
    dubai: "Dubai",
    mumbaj: "Mumbai",
    singapur: "Singapore",
    hongkong: "Hong Kong",
    sangaj: "Shanghai",
    tokio: "Tokyo",
    seul: "Seoul",
    sidnej: "Sydney",
    okland: "Auckland",
    honolulu: "Honolulu",
  },
  holidays: {
    "nova-godina": "New Year",
    bozic: "Christmas",
    sretenje: "Sretenje",
    vaskrs: "Easter",
    "praznik-rada": "Labour Day",
    "dan-pobede": "Victory Day",
    "dan-primirja": "Armistice Day",
  },
};
