/**
 * MINI-APPS' own copy, in Serbian - the SHAPE every other locale of this module
 * is checked against (ADR-090).
 *
 * **Why this is not in `strings.ts`.** The shell's table is part of the startup
 * chunk and this module's page is not, so a module that put its page copy there
 * would pay for it on every launch whether or not anybody opened a mini app.
 * The table joins the locale machinery when this chunk loads, and from then on
 * switching language rewrites these leaves in place exactly as it rewrites the
 * shell's.
 *
 * English is `copy.en.ts`, typed `typeof sr` - one compile error per sentence
 * left untranslated and one per key invented.
 *
 * The tile ids in `apps` and the city ids in `cities` are the KEYS the code
 * looks up (`copy.apps[appId]`, `copy.cities[cityId]`), so the table is the one
 * place a tile's or a city's name is written.
 */
export const sr = {
  page: {
    // The page's own header is the module's name, which the shell draws from the
    // manifest; this is the line under it.
    subtitle: "Devet sitnih alata na jednom mestu - otvori onaj koji ti treba.",
    loading: "Učitavanje…",
  },
  grid: {
    hint: "Izaberi alat. Poslednji koji otvoriš ostaje zapamćen.",
  },
  actions: {
    back: "Nazad na alatke",
    save: "Sačuvaj",
    cancel: "Otkaži",
    remove: "Obriši",
    rename: "Preimenuj",
    undo: "Vrati",
    redo: "Ponovi",
    clear: "Očisti",
    copy: "Kopiraj",
    copied: "Kopirano.",
    start: "Pokreni",
    stop: "Zaustavi",
    today: "Danas",
  },
  apps: {
    metronome: {
      name: "Metronom",
      hint: "Tempo, takt i akcenti, sa tapkanjem tempa.",
    },
    dice: {
      name: "Kockice i izbor",
      hint: "Oznake kockica, novčić, izbor iz liste, mešanje i slučajan broj.",
    },
    tally: {
      name: "Brojači",
      hint: "Više imenovanih brojača koji se pamte.",
    },
    scoreboard: {
      name: "Semafor",
      hint: "Igrači, kola, poeni i poredak.",
    },
    typing: {
      name: "Kucanje",
      hint: "Vežbe za srpski i engleski raspored, sa brzinom i tačnošću.",
    },
    dates: {
      name: "Kalkulator datuma",
      hint: "Razlika između datuma, dodavanje dana i radni dani u Srbiji.",
    },
    worldclock: {
      name: "Svetski sat",
      hint: "Vremena izabranih gradova i zajednički termin za sastanak.",
    },
    screenlight: {
      name: "Svetlo ekrana",
      hint: "Ekran kao svetlo: belo, toplo ili crveno, sa jačinom.",
    },
    qr: {
      name: "QR čitač",
      hint: "Pročitaj QR kod sa slike i kopiraj ili otvori ono što piše.",
    },
  },
  metronome: {
    bpm: "Tempo (BPM)",
    beats: "Doba u taktu",
    note: "Notna vrednost",
    subdivisions: "Podele dobe",
    accents: "Akcenti",
    beat: "Doba",
    beatStrong: "Jak",
    beatWeak: "Slab",
    beatOff: "Tiho",
    bar: "Takt",
    pulse: "Puls",
    tapTitle: "Tapkanje tempa",
    tap: "Tapkaj u ritmu",
    tapHint: "Kucaj najmanje dva puta; tempo je medijana razmaka.",
    tapResult: "Izmereni tempo",
    tapNone: "Još nema merenja.",
    applyTap: "Primeni izmereni tempo",
    audioUnavailable: "Zvuk nije dostupan u ovom okruženju.",
    bpmError: "Tempo je ceo broj od 20 do 400.",
  },
  dice: {
    notation: "Oznaka kockica",
    notationHint: "Na primer 2d6+3, 4d6kh3 ili d20.",
    roll: "Baci kockice",
    total: "Ukupno",
    dropped: "Odbačeno",
    coinTitle: "Novčić",
    flip: "Baci novčić",
    heads: "Glava",
    tails: "Pismo",
    pickTitle: "Izbor iz liste",
    list: "Lista",
    listHint: "Jedna stavka u redu.",
    count: "Koliko",
    pick: "Izaberi",
    shuffle: "Promešaj",
    numberTitle: "Slučajan broj",
    min: "Od",
    max: "Do",
    draw: "Izvuci",
    result: "Rezultat",
    history: "Istorija",
    historyEmpty: "Još nema rezultata.",
    historyHint: "Pamti se poslednjih 50 rezultata.",
    listEmpty: "Lista treba bar jednu stavku.",
    countTooBig: "Ne može više od broja stavki u listi.",
    countInvalid: "Koliko je ceo broj od 1 naviše.",
    rangeInvalid: "Donja granica mora biti manja ili jednaka gornjoj.",
    emptyError: "Upiši oznaku kockica.",
    tooLongError: "Oznaka je predugačka.",
    syntaxError: "Oznaka nije ispravna.",
    noDiceError: "Oznaka mora imati bar jednu kockicu.",
    diceCountError: "Najviše 100 kockica u jednom članu.",
    facesError: "Broj strana je od 2 do 1000.",
    keepCountError: "Zadržavanje je između 1 i broja kockica u članu.",
  },
  tally: {
    add: "Dodaj brojač",
    name: "Naziv",
    step: "Korak",
    floor: "Ne dozvoli ispod nule",
    plus: "Dodaj",
    minus: "Oduzmi",
    total: "Ukupno",
    empty: "Još nema brojača.",
    emptyBody: "Dodaj prvi brojač, pa ga uvećavaj klikom.",
    nameError: "Naziv je obavezan i može imati najviše 60 znakova.",
    stepError: "Korak je ceo broj od 1 do 1000.",
    limitError: "Najviše 24 brojača.",
  },
  scoreboard: {
    players: "Igrači",
    playerName: "Ime igrača",
    addPlayer: "Dodaj igrača",
    rounds: "Kola",
    round: "Kolo",
    addRound: "Dodaj kolo",
    removeRound: "Obriši kolo",
    target: "Cilj",
    targetHint: "Ostavi prazno za igru bez cilja.",
    standings: "Poredak",
    rank: "Mesto",
    total: "Ukupno",
    won: "Pobede",
    tied: "Nerešeno",
    over: "Cilj je dostignut.",
    empty: "Još nema igrača.",
    emptyBody: "Dodaj igrače, pa upisuj poene po kolima.",
    nameError: "Ime je obavezno i može imati najviše 40 znakova.",
    limitError: "Najviše 32 igrača.",
    targetError: "Cilj je ceo broj od 1 naviše.",
    roundLimit: "Najviše 100 kola.",
  },
  typing: {
    layout: "Raspored",
    layoutNames: {
      "sr-Latn": "Srpski (latinica)",
      "en-US": "Engleski (SAD)",
    },
    lesson: "Lekcija",
    lessonHint: "Lekcije su označene slovima koja vežbaju.",
    start: "Počni",
    restart: "Ponovo",
    target: "Tekst",
    nextKey: "Sledeći taster",
    space: "Razmak",
    wpm: "Reči u minuti",
    net: "Neto",
    accuracy: "Tačnost",
    errors: "Greške",
    duration: "Trajanje",
    progress: "Napredak",
    progressEmpty: "Još nema rezultata za ovu lekciju.",
    best: "Najbolje",
    practise: "Vežbaj",
    newBest: "Novi najbolji rezultat.",
    idle: "Izaberi raspored i lekciju, pa počni da kucaš.",
  },
  dates: {
    difference: "Razlika između datuma",
    from: "Od",
    to: "Do",
    days: "Dana",
    workdays: "Radnih dana",
    workdaysHint: "Vikendi i državni praznici se preskaču.",
    calendar: "Godina, meseci i dana",
    years: "Godine",
    months: "Meseci",
    weeks: "Nedelje",
    adjust: "Dodaj ili oduzmi",
    base: "Datum",
    add: "Dodaj",
    subtract: "Oduzmi",
    result: "Rezultat",
    holidays: "Neradni dani",
    holidaysHint: "Državni i verski praznici, sa zamenom kada državni praznik padne u nedelju.",
    substitute: "Zamena za državni praznik",
    easter: "Vaskrs (pravoslavni)",
    format: "Oblik: GGGG-MM-DD",
    invalid: "Datum nije ispravan.",
  },
  worldclock: {
    home: "Tvoja zona",
    city: "Grad",
    add: "Dodaj grad",
    cities: "Gradovi",
    empty: "Još nema gradova.",
    emptyBody: "Izaberi grad i dodaj ga na sat.",
    local: "Lokalno vreme",
    offset: "Pomeraj",
    dst: "Letnje vreme",
    dayAhead: "Dan napred",
    dayBehind: "Dan nazad",
    meeting: "Sastanak",
    meetingHint: "Radno vreme je 09:00-17:00 po lokalnom vremenu svakog grada.",
    date: "Datum",
    start: "Od",
    end: "Do",
    utc: "UTC",
    window: "Zajednički termin",
    noWindow: "Nema preklapanja u radnom vremenu tog dana.",
    limitError: "Najviše 12 gradova.",
    unknownZone: "Nepoznata vremenska zona.",
  },
  screenlight: {
    cast: "Boja svetla",
    castWhite: "Belo",
    castWarm: "Toplo",
    castRed: "Crveno",
    redHint: "Crveno svetlo čuva noćni vid.",
    brightness: "Jačina",
    levelLow: "Slabo",
    levelMedium: "Srednje",
    levelHigh: "Jako",
    leave: "Izlaz",
    hint: "Pritisni Esc da se vratiš na alatke.",
  },
  qr: {
    file: "Iz slike",
    choose: "Izaberi sliku",
    fileHint: "PNG ili JPEG sa QR kodom.",
    decoding: "Čitam…",
    noCode: "Na slici nema čitljivog QR koda.",
    badImage: "Sliku nije moguće pročitati.",
    tooLarge: "Slika je prevelika za čitanje.",
    text: "Tekst",
    urlHint: "Nexus ne otvara linkove sam - kopiraj ga i otvori u pregledaču.",
    empty: "Još nema rezultata.",
  },
  errors: {
    load: "Nije moguće učitati mini aplikacije.",
    mutate: "Izmena nije sačuvana.",
  },
  cities: {
    beograd: "Beograd",
    zagreb: "Zagreb",
    sarajevo: "Sarajevo",
    podgorica: "Podgorica",
    ljubljana: "Ljubljana",
    bec: "Beč",
    budimpesta: "Budimpešta",
    prag: "Prag",
    berlin: "Berlin",
    pariz: "Pariz",
    amsterdam: "Amsterdam",
    london: "London",
    rim: "Rim",
    madrid: "Madrid",
    atina: "Atina",
    istanbul: "Istanbul",
    moskva: "Moskva",
    kijev: "Kijev",
    njujork: "Njujork",
    cikago: "Čikago",
    losandjeles: "Los Anđeles",
    toronto: "Toronto",
    meksiko: "Meksiko Siti",
    saopaulo: "Sao Paulo",
    buenosajres: "Buenos Ajres",
    kairo: "Kairo",
    najrobi: "Najrobi",
    dubai: "Dubai",
    mumbaj: "Mumbaj",
    singapur: "Singapur",
    hongkong: "Hongkong",
    sangaj: "Šangaj",
    tokio: "Tokio",
    seul: "Seul",
    sidnej: "Sidnej",
    okland: "Okland",
    honolulu: "Honolulu",
  },
  holidays: {
    "nova-godina": "Nova godina",
    bozic: "Božić",
    sretenje: "Sretenje",
    vaskrs: "Vaskrs",
    "praznik-rada": "Praznik rada",
    "dan-pobede": "Dan pobede",
    "dan-primirja": "Dan primirja",
  },
};
