/**
 * CHESS' own copy, in Serbian — the SHAPE every other locale of this module is
 * checked against (ADR-090).
 *
 * The rules this table follows are TOOls' (the timers module's): the module
 * carries its own words so the shell's startup chunk does not, `copy.ts`
 * registers the table with the locale machinery the moment this chunk loads,
 * and English is `copy.en.ts`, typed `typeof sr`, so a sentence left
 * untranslated or a key invented is one compile error each.
 *
 * The register is the app's Operate voice: a sentence says what happened or what
 * to do, never jokes and never shouts. Nothing here names a gender, and nothing
 * here is a number the code does not compute — a level, a clock and a count are
 * formatted at the call site through `Intl`.
 */
export const sr = {
  page: {
    subtitle: "Partija na tabli — protiv računara ili druge osobe, sa satom i arhivom.",
    loading: "Učitavanje…",
  },
  board: {
    title: "Tabla",
    empty: "Nema partije na tabli. Izaberi protivnika ispod i započni novu partiju.",
    flip: "Okreni tablu",
    fenLabel: "Pozicija (FEN)",
    keyboardHint: "Strelice pomeraju kursor po tabli, Enter podiže figuru i spušta je.",
    white: "Beli",
    black: "Crni",
    turn: "Na potezu",
    check: "Šah!",
    checkmate: "Mat",
    stalemate: "Pat — nema legalnih poteza",
    drawInsufficient: "Nerešeno — nedovoljno materijala za mat",
    drawFifty: "Nerešeno — pedeset poteza bez napredovanja",
    drawThreefold: "Nerešeno — pozicija se ponovila tri puta",
    draw: "Nerešeno",
    resultWhite: "Pobeda belih",
    resultBlack: "Pobeda crnih",
    resultUnfinished: "Nedovršena partija",
    review: "Pregled partije",
    toLive: "Na poslednju poziciju",
    thinking: "Računar razmišlja…",
    degraded: "Računar na ovom sistemu ne može da radi u pozadini, pa igra najviše do nivoa 5.",
    engineFailed: "Računar nije odigrao potez.",
    engineMove: "Potez računara",
    depth: "dubina",
    nodes: "čvorova",
    saveFailed: "Partija nije sačuvana.",
    saved: "Partija je sačuvana u arhivi.",
    resign: "Prezigni",
    resignQuestion: "Prezigni partiju? Rezultat ide protivniku.",
    offerDraw: "Ponudi remi",
    drawOffered: "Remi je ponuđen.",
    acceptDraw: "Prihvati remi",
    declineDraw: "Odbij remi",
    drawDeclined: "Remi je odbijen.",
    newGameQuestion: "Partija u toku se čuva kao nedovršena i ostaje u arhivi.",
    moveTarget: "polje za potez",
    picked: "izabrana figura",
    pieces: {
      w: {
        p: "beli pešak",
        n: "beli skakač",
        b: "beli lovac",
        r: "beli top",
        q: "bela dama",
        k: "beli kralj",
      },
      b: {
        p: "crni pešak",
        n: "crni skakač",
        b: "crni lovac",
        r: "crni top",
        q: "crna dama",
        k: "crni kralj",
      },
    },
  },
  setup: {
    title: "Nova partija",
    opponent: "Protivnik",
    opponentEngine: "Računar",
    opponentHuman: "Druga osoba",
    color: "Igraš",
    colorWhite: "Belim",
    colorBlack: "Crnim",
    level: "Nivo",
    clock: "Sat",
    clockNone: "Bez sata",
    clockCustom: "Po meri",
    clockBase: "Minuti",
    clockIncrement: "Sekunde po potezu",
    startFen: "Početna pozicija (FEN)",
    startFenHint: "Ostavi prazno za standardnu početnu poziciju.",
    start: "Započni partiju",
  },
  promotion: {
    title: "Izaberi figuru",
    queen: "Dama",
    rook: "Top",
    bishop: "Lovac",
    knight: "Skakač",
    cancel: "Otkaži",
  },
  moves: {
    title: "Potezi",
    empty: "Još nema odigranih poteza.",
    first: "Na početak",
    previous: "Prethodni potez",
    next: "Sledeći potez",
    last: "Na kraj",
    position: "Pozicija",
  },
  pgn: {
    title: "PGN",
    importLabel: "Nalepi PGN",
    importHint: "Uvezi partiju iz PGN teksta — sa zaglavljima i potezima.",
    import: "Uvezi",
    importError: "To nije PGN partija koju Nexus može da pročita.",
    importLoaded: "Partija je uvezena i postavljena na tablu.",
    export: "Kopiraj PGN",
    exportHint: "PGN nosi zaglavlja (igrači, datum, mesto, rezultat) i sve poteze.",
    copied: "PGN je kopiran.",
    copyFailed: "Kopiranje nije uspelo.",
    event: "Partija u Nexusu",
    site: "Nexus",
    playerYou: "Ti",
  },
  games: {
    title: "Sačuvane partije",
    emptyTitle: "Još nema sačuvanih partija",
    emptyBody: "Završena partija se čuva sama, pa se ovde pojavljuje sa svojim rezultatom.",
    open: "Pregledaj",
    remove: "Obriši",
    removeQuestion: "Partija se trajno briše iz ovog profila.",
    resumeTitle: "Partija u toku",
    resume: "Nastavi partiju",
    moves: "poteza",
  },
  stats: {
    title: "Protiv računara",
    empty: "Još nema završenih partija protiv računara.",
    played: "Partija",
    won: "Pobeda",
    drawn: "Remija",
    lost: "Poraza",
  },
  errors: {
    load: "Nije moguće učitati partije.",
    mutate: "Izmena nije sačuvana.",
    fen: "To nije FEN pozicija.",
    clock: "Sat ide od 1 do 120 minuta, a dodatak od 0 do 300 sekundi.",
  },
  common: {
    cancel: "Otkaži",
  },
  widget: {
    empty: "Nema partije u toku.",
    loading: "Učitavanje…",
    loadError: "Nije moguće učitati partiju u toku.",
  },
};
