import { sr } from "./copy.sr.js";

/**
 * CHESS in English — the same shape as `copy.sr.ts`, checked by the compiler.
 *
 * `typeof sr` is the whole mechanism: a sentence left untranslated, a key
 * invented here, or a nested table that does not match is one compile error
 * each. The register is the app's own English: sentence case, informative, no
 * exclamation marks.
 */
export const en: typeof sr = {
  page: {
    subtitle: "A board game — against the engine or another person, with clocks and an archive.",
    loading: "Loading…",
  },
  board: {
    title: "Board",
    empty: "No game is on the board. Pick an opponent below and start a new game.",
    flip: "Flip the board",
    fenLabel: "Position (FEN)",
    keyboardHint: "The arrow keys move the cursor, Enter picks a piece up and puts it down.",
    white: "White",
    black: "Black",
    turn: "To move",
    check: "Check!",
    checkmate: "Checkmate",
    stalemate: "Stalemate — no legal move",
    drawInsufficient: "Draw — not enough material to mate",
    drawFifty: "Draw — fifty moves without progress",
    drawThreefold: "Draw — the position repeated three times",
    draw: "Draw",
    resultWhite: "White wins",
    resultBlack: "Black wins",
    resultUnfinished: "Unfinished game",
    review: "Reviewing the game",
    toLive: "To the last position",
    thinking: "The engine is thinking…",
    degraded: "On this system the engine cannot run in the background, so it plays at most level 5.",
    engineFailed: "The engine did not play a move.",
    engineMove: "Engine's move",
    depth: "depth",
    nodes: "nodes",
    saveFailed: "The game was not saved.",
    saved: "The game is saved in the archive.",
    resign: "Resign",
    resignQuestion: "Resign the game? The result goes to the opponent.",
    offerDraw: "Offer a draw",
    drawOffered: "A draw has been offered.",
    acceptDraw: "Accept the draw",
    declineDraw: "Decline the draw",
    drawDeclined: "The draw was declined.",
    newGameQuestion: "The game in progress is saved as unfinished and stays in the archive.",
    moveTarget: "a move lands here",
    picked: "picked up",
    pieces: {
      w: {
        p: "white pawn",
        n: "white knight",
        b: "white bishop",
        r: "white rook",
        q: "white queen",
        k: "white king",
      },
      b: {
        p: "black pawn",
        n: "black knight",
        b: "black bishop",
        r: "black rook",
        q: "black queen",
        k: "black king",
      },
    },
  },
  setup: {
    title: "New game",
    opponent: "Opponent",
    opponentEngine: "The engine",
    opponentHuman: "Another person",
    color: "You play",
    colorWhite: "White",
    colorBlack: "Black",
    level: "Level",
    clock: "Clock",
    clockNone: "No clock",
    clockCustom: "Custom",
    clockBase: "Minutes",
    clockIncrement: "Seconds per move",
    startFen: "Starting position (FEN)",
    startFenHint: "Leave empty for the standard starting position.",
    start: "Start the game",
  },
  promotion: {
    title: "Choose a piece",
    queen: "Queen",
    rook: "Rook",
    bishop: "Bishop",
    knight: "Knight",
    cancel: "Cancel",
  },
  moves: {
    title: "Moves",
    empty: "No move has been played yet.",
    first: "To the start",
    previous: "Previous move",
    next: "Next move",
    last: "To the end",
    position: "Position",
  },
  pgn: {
    title: "PGN",
    importLabel: "Paste PGN",
    importHint: "Import a game from PGN text — with its tags and moves.",
    import: "Import",
    importError: "That is not a PGN game this build can read.",
    importLoaded: "The game is imported and set on the board.",
    export: "Copy PGN",
    exportHint: "A PGN carries its tags (players, date, site, result) and every move.",
    copied: "The PGN is copied.",
    copyFailed: "Copying failed.",
    event: "A game in Nexus",
    site: "Nexus",
    playerYou: "You",
  },
  games: {
    title: "Saved games",
    emptyTitle: "No saved game yet",
    emptyBody: "A finished game is saved by itself, so it appears here with its result.",
    open: "Review",
    remove: "Delete",
    removeQuestion: "The game is deleted from this profile for good.",
    resumeTitle: "Game in progress",
    resume: "Continue the game",
    moves: "moves",
  },
  stats: {
    title: "Against the engine",
    empty: "No game against the engine has finished yet.",
    played: "Games",
    won: "Won",
    drawn: "Drawn",
    lost: "Lost",
  },
  errors: {
    load: "The games could not be loaded.",
    mutate: "The change was not saved.",
    fen: "That is not a FEN position.",
    clock: "A clock runs from 1 to 120 minutes, and the increment from 0 to 300 seconds.",
  },
  common: {
    cancel: "Cancel",
  },
  widget: {
    empty: "No game is in progress.",
    loading: "Loading…",
    loadError: "The game in progress could not be loaded.",
  },
};
