import { sr } from "./copy.sr.js";

/**
 * THE LAB in English — the same shape as `copy.sr.ts`, checked by the compiler.
 *
 * `typeof sr` is the whole mechanism: a sentence left untranslated, a key
 * invented here, or a nested table that does not match is one compile error each,
 * so this file cannot drift from the Serbian table the way a second hand-kept
 * table would. The register is the app's own English: sentence case,
 * informative, no exclamation marks.
 */
export const en: typeof sr = {
  page: {
    subtitle: "Serial, battery, tone and light — the instruments in one room.",
    loading: "Loading…",
  },
  errors: {
    load: "The Lab could not be loaded.",
    mutate: "The change was not saved.",
  },
  serial: {
    title: "Serial port",
    unsupported: "This Chromium does not expose Web Serial, so a port cannot be opened.",
    noPort: "No port chosen",
    portGeneric: "Serial port",
    usbDevice: "USB device",
    connected: "Connected",
    disconnected: "Not connected",
    choosePort: "Choose a port",
    disconnect: "Disconnect",
    baud: "Speed (baud)",
    ending: "Line ending",
    endings: {
      crlf: "CRLF (what an Arduino prints)",
      lf: "LF",
      none: "No line ending",
    },
    mode: "Reading",
    modes: {
      terminal: "Terminal",
      nmea: "NMEA GPS",
      csv: "CSV sensors",
    },
    hex: "Hex view",
    refused: "The port was not opened — the choice was cancelled or another program holds it.",
    terminalLabel: "The serial port's output",
    hidden: "The view is trimmed to the newest lines.",
    saveLog: "Save the log",
    clear: "Clear the view",
    savedTo: "Saved to",
    fixTitle: "GPS position",
    fixNone: "No sentence with a position has verified yet.",
    latitude: "Latitude",
    longitude: "Longitude",
    satellites: "Satellites",
    quality: "Quality",
    utcTime: "UTC time",
    gpsDate: "Date",
    qualityNone: "The receiver has not acquired a position yet.",
    qualityNames: {
      none: "None",
      gps: "GPS",
      dgps: "Differential",
      pps: "PPS",
      rtk: "RTK",
      floatRtk: "RTK (float)",
      estimated: "Estimated",
      manual: "Manual",
      simulation: "Simulation",
    },
    useAsLocation: "Use as my location",
    locationIs: "Device location:",
    forgetLocation: "Forget",
    csvTitle: "Sensor log",
    columnsFound: "Columns from the header",
    logName: "Log name",
    createLog: "Create the log",
    logSelect: "Log",
    noLog: "None chosen",
    column: "Column",
    startLogging: "Log it",
    stopLogging: "Stop",
    logging: "Logging",
    written: "Readings written:",
    badLine: "A line was not read:",
    chartDescription: "Readings of the column",
    chartEmpty: "At least two readings are needed to draw a trend.",
    logsEmpty: "No logs yet",
    logsEmptyBody:
      "Switch to the CSV mode and let the device send its header first, then name the log.",
    columnsLabel: "Columns",
    readingsLabel: "Readings",
    newest: "Newest",
    exportCsv: "Export CSV",
    removeLog: "Delete",
  },
  battery: {
    title: "Battery",
    read: "Read the report",
    live: "Now:",
    charging: "charging",
    onBattery: "on battery",
    onMains: "on mains",
    liveUnsupported: "This Chromium does not report the battery's state.",
    timeout: "Reading the report timed out.",
    unavailable: "Windows did not give a battery report this time.",
    none: "This computer reports no battery.",
    design: "Design capacity",
    full: "Full-charge capacity",
    health: "Health",
    cycles: "Cycles",
    scanned: "Report taken",
    healthNote: "The full ÷ design ratio is the battery's own report, not a measurement by Nexus.",
    usageTitle: "Recent usage",
  },
  offgrid: {
    title: "Off grid — the daily budget",
    empty: "Add devices and their draw, and the consumption and how long the battery lasts follow.",
    deviceName: "Device",
    deviceWatts: "Draw (W)",
    deviceHours: "Hours a day",
    addDevice: "Add a device",
    remove: "Remove",
    batteryWh: "Battery (Wh)",
    depth: "Depth of discharge",
    sun: "Hours of sun",
    days: "Days of reserve",
    perDay: "Consumption a day",
    lasts: "Lasts",
    daysUnit: "days",
    bank: "Battery for the reserve",
    panel: "Panel needed",
    panelNote: "The panel figure assumes a charge efficiency of",
    save: "Save the list",
    saved: "Saved.",
  },
  tone: {
    title: "Tone and oscilloscope",
    warning:
      "The tone goes to speakers or headphones. Start quiet and turn it up slowly — loud sound for long enough damages hearing permanently.",
    acknowledge: "I understand that the tone can be loud.",
    kind: "Shape",
    kinds: {
      sine: "Sine",
      square: "Square",
      triangle: "Triangle",
      sawtooth: "Sawtooth",
      white: "White noise",
      pink: "Pink noise",
    },
    frequency: "Frequency (Hz)",
    sweep: "Sweep the range (20 Hz → 20 kHz)",
    play: "Play",
    stop: "Stop",
    playing: "Playing",
    level: "Level",
    micStart: "Turn the microphone on",
    micStop: "Turn the microphone off",
    micProblem: "The microphone was not opened — permission was refused or there is none.",
    timeDiv: "Time per division",
    timeDivisions: {
      "0.5": "0.5 ms",
      "1": "1 ms",
      "2": "2 ms",
      "5": "5 ms",
      "10": "10 ms",
    },
    trigger: "Trigger level",
    frequencyReadout: "Frequency",
    waveLabel: "The waveform from the microphone",
    spectrumLabel: "The microphone's spectrum",
    inputNote:
      "A sound card's input is AC-coupled and its full scale is about 1 V RMS (≈ 2.8 V peak to peak): above that the input clips, so measure a source with a meter first and use a divider.",
  },
  light: {
    title: "Light",
    lampMode: "Surface",
    lampModes: {
      white: "White light",
      red: "Red (night mode)",
    },
    intensity: "Intensity",
    lampOn: "Turn on",
    lampOff: "Turn off",
    lampHint: "The lamp covers the whole window; leave it with its button or with Escape.",
    lampLabel: "A lamp across the whole screen",
    lampClose: "Close",
    lampEscape: "Escape closes the lamp.",
    morseTitle: "Morse lamp",
    morseText: "Text",
    morseWpm: "Speed (words a minute)",
    morseAcknowledge: "I understand that the lamp flashes and that flashing can be unpleasant.",
    morseReduced: "The system asks for reduced motion, so the lamp will not flash.",
    morseStart: "Send",
    morseStop: "Stop",
    morseTransliterated: "Sent as:",
    morseTiming: "The timing is ITU-R M.1677-1 (PARIS): a dash lasts three dits.",
  },
};
