/**
 * What a circuit moves, sounds or switches.
 *
 * Almost every entry here is a current problem waiting to be found, which is why
 * `current.peak` is the column to read rather than `typical`. An SG90 idles at
 * 10 mA and stalls at 700; a 28BYJ-48 holds at 240 mA the whole time it is
 * energised. A board's 5 V regulator supplies a few hundred milliamps in total,
 * so „the servo worked on the bench and browned out with the display attached"
 * is arithmetic, and the numbers to do it with are here.
 *
 * The signal pin of a servo or an ESC is `pwm` — not `digital-out` — because a
 * 50 Hz pulse train is what it takes, and a board pin that cannot produce one is
 * a wire that will look connected and do nothing.
 */

import type { ComponentDef } from "../component.js";
import { gnd, pin, powerIn } from "./pins.js";

export const ACTUATORS: readonly ComponentDef[] = [
  // ── Servos and motors ─────────────────────────────────────────────────────
  {
    id: "servo-sg90",
    kind: "actuator",
    name: "SG90 (mikro servo)",
    nameEn: "SG90 (micro servo)",
    summary: "Devet grama, ugao 0–180°; pri zastoju vuče 700 mA i obara regulator ploče.",
    summaryEn: "Nine grams, 0–180°; stalled it draws 700 mA and drags the board's regulator down.",
    supply: { min: 4.8, max: 6 },
    current: { typical: 10, peak: 700 },
    buses: [],
    pins: [powerIn(), gnd(), pin("SIG", ["digital-in", "pwm"])],
    library: "Servo",
  },
  {
    id: "servo-mg996r",
    kind: "actuator",
    name: "MG996R (servo sa metalnim zupčanicima)",
    nameEn: "MG996R (metal-gear servo)",
    summary: "Obrtni moment 10 kg·cm — traži zasebno napajanje, nikad pin ploče.",
    summaryEn: "10 kg·cm of torque — it needs its own supply, never a board pin.",
    supply: { min: 4.8, max: 7.2 },
    current: { typical: 170, peak: 2500 },
    buses: [],
    pins: [powerIn(), gnd(), pin("SIG", ["digital-in", "pwm"])],
    library: "Servo",
  },
  {
    id: "servo-mg90s",
    kind: "actuator",
    name: "MG90S (metalni mikro servo)",
    nameEn: "MG90S (metal micro servo)",
    summary: "Veličina SG90 sa metalnim prenosom — isti raspored, veći moment.",
    summaryEn: "The size of an SG90 with metal gearing — the same layout, more torque.",
    supply: { min: 4.8, max: 6 },
    current: { typical: 120, peak: 1400 },
    buses: [],
    pins: [powerIn(), gnd(), pin("SIG", ["digital-in", "pwm"])],
    library: "Servo",
  },
  {
    id: "servo-360",
    kind: "actuator",
    name: "Servo sa neprekidnom rotacijom",
    nameEn: "Continuous-rotation servo",
    summary: "Ista veza kao SG90, ali impuls zadaje brzinu i smer, ne ugao.",
    summaryEn: "The same wiring as an SG90, but the pulse sets speed and direction, not an angle.",
    supply: { min: 4.8, max: 6 },
    current: { typical: 10, peak: 700 },
    buses: [],
    pins: [powerIn(), gnd(), pin("SIG", ["digital-in", "pwm"])],
    library: "Servo",
  },
  {
    id: "dc-motor-tt",
    kind: "actuator",
    name: "TT motor sa reduktorom",
    nameEn: "TT gearmotor",
    summary: "Žuti motor iz svakog kompleta za robotska kolica — ide preko drajvera.",
    summaryEn: "The yellow motor from every robot-car kit — it goes through a driver.",
    supply: { min: 3, max: 6 },
    current: { typical: 150, peak: 1200 },
    buses: [],
    // Two bare terminals: polarity decides direction, so neither is „anode".
    pins: [pin("M+", ["passive"]), pin("M-", ["passive"])],
  },
  {
    id: "stepper-28byj48",
    kind: "actuator",
    name: "28BYJ-48 (koračni motor)",
    nameEn: "28BYJ-48 (stepper)",
    summary: "Unipolarni motor sa ULN2003 pločicom; drži 240 mA i kad stoji.",
    summaryEn: "A unipolar motor with a ULN2003 board; it holds 240 mA even while standing still.",
    supply: { min: 5, max: 5 },
    current: { typical: 240, peak: 320 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("IN1", ["digital-in"]),
      pin("IN2", ["digital-in"]),
      pin("IN3", ["digital-in"]),
      pin("IN4", ["digital-in"]),
    ],
    library: "Stepper",
  },
  {
    id: "stepper-nema17",
    kind: "actuator",
    name: "NEMA 17 (koračni motor)",
    nameEn: "NEMA 17 (stepper)",
    summary: "Bipolarni motor za štampače i CNC; traži A4988 ili DRV8825.",
    summaryEn: "A bipolar motor for printers and CNC; it wants an A4988 or a DRV8825.",
    supply: { min: 8, max: 35 },
    current: { typical: 1200, peak: 2000 },
    buses: [],
    pins: [
      pin("A+", ["passive"]),
      pin("A-", ["passive"]),
      pin("B+", ["passive"]),
      pin("B-", ["passive"]),
    ],
  },
  {
    id: "bldc-esc",
    kind: "actuator",
    name: "Brushless motor + ESC",
    nameEn: "Brushless motor + ESC",
    summary: "Regulator prima servo impuls; motor je za dron ili propeler.",
    summaryEn: "The ESC takes a servo pulse; the motor is for a drone or a propeller.",
    supply: { min: 7.4, max: 25 },
    current: { typical: 5000, peak: 30000 },
    buses: [],
    pins: [powerIn("VBAT"), gnd(), pin("SIG", ["digital-in", "pwm"])],
    library: "Servo",
  },

  // ── Switching ─────────────────────────────────────────────────────────────
  {
    id: "relay-1ch",
    kind: "actuator",
    name: "Relej modul 1 kanal",
    nameEn: "1-channel relay module",
    summary: "Optokuplerom odvojen kontakt; kalem vuče 70 mA dok je uključen.",
    summaryEn: "A contact isolated by an optocoupler; the coil draws 70 mA while it is on.",
    supply: { min: 5, max: 5 },
    current: { typical: 5, peak: 75 },
    buses: [],
    pins: [powerIn(), gnd(), pin("IN", ["digital-in"])],
  },
  {
    id: "relay-2ch",
    kind: "actuator",
    name: "Relej modul 2 kanala",
    nameEn: "2-channel relay module",
    summary: "Dva nezavisna kontakta; oba kalema zajedno traže preko 140 mA.",
    summaryEn: "Two independent contacts; both coils together want over 140 mA.",
    supply: { min: 5, max: 5 },
    current: { typical: 8, peak: 150 },
    buses: [],
    pins: [powerIn(), gnd(), pin("IN1", ["digital-in"]), pin("IN2", ["digital-in"])],
  },
  {
    id: "relay-4ch",
    kind: "actuator",
    name: "Relej modul 4 kanala",
    nameEn: "4-channel relay module",
    summary: "Četiri kontakta — sa svima uključenim prelazi ono što USB daje.",
    summaryEn: "Four contacts — with them all on it exceeds what USB can give.",
    supply: { min: 5, max: 5 },
    current: { typical: 15, peak: 300 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("IN1", ["digital-in"]),
      pin("IN2", ["digital-in"]),
      pin("IN3", ["digital-in"]),
      pin("IN4", ["digital-in"]),
    ],
  },
  {
    id: "solenoid-12v",
    kind: "actuator",
    name: "Solenoid 12 V",
    nameEn: "12 V solenoid",
    summary: "Povlači klip; obavezna je zaštitna dioda jer pri isključenju vraća napon.",
    summaryEn: "It pulls a plunger; the flyback diode is mandatory, because switching off returns a voltage.",
    supply: { min: 12, max: 12 },
    current: { typical: 0, peak: 650 },
    buses: [],
    pins: [powerIn("V+"), gnd()],
  },
  {
    id: "solenoid-valve-12v",
    kind: "actuator",
    name: "Elektromagnetni ventil 12 V",
    nameEn: "12 V solenoid valve",
    summary: "Otvara i zatvara protok vode; ide preko releja ili MOSFET modula.",
    summaryEn: "Opens and closes a water flow; it goes through a relay or a MOSFET module.",
    supply: { min: 12, max: 12 },
    current: { typical: 0, peak: 500 },
    buses: [],
    pins: [powerIn("V+"), gnd()],
  },

  // ── Sound and touch ───────────────────────────────────────────────────────
  {
    id: "buzzer-active",
    kind: "actuator",
    name: "Aktivni zujalica",
    nameEn: "Active buzzer",
    summary: "Ima sopstveni oscilator — jedan visok nivo i svira. Samo jedan ton.",
    summaryEn: "It has its own oscillator — one high level and it sounds. A single tone.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 25, peak: 35 },
    buses: [],
    pins: [powerIn(), gnd(), pin("IO", ["digital-in"])],
  },
  {
    id: "buzzer-passive",
    kind: "actuator",
    name: "Pasivna zujalica",
    nameEn: "Passive buzzer",
    summary: "Nema oscilator, pa ton zadaje ploča — otuda i melodije.",
    summaryEn: "No oscillator, so the board sets the tone — which is where the melodies come from.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 25, peak: 35 },
    buses: [],
    pins: [powerIn(), gnd(), pin("IO", ["digital-in", "pwm"])],
  },
  {
    id: "vibration-motor",
    kind: "actuator",
    name: "Vibracioni motor",
    nameEn: "Vibration motor",
    summary: "Pljosnati motor iz telefona; preko tranzistora, ne direktno sa pina.",
    summaryEn: "The flat motor from a phone; through a transistor, never straight off a pin.",
    supply: { min: 3, max: 5 },
    current: { typical: 60, peak: 100 },
    buses: [],
    pins: [powerIn(), gnd(), pin("IN", ["digital-in"])],
  },

  // ── Pumps and air ─────────────────────────────────────────────────────────
  {
    id: "water-pump-5v",
    kind: "actuator",
    name: "Potapajuća pumpa 5 V",
    nameEn: "5 V submersible pump",
    summary: "Za zalivanje saksija; nikada direktno na pin — preko releja ili MOSFET-a.",
    summaryEn: "For watering pots; never straight on a pin — through a relay or a MOSFET.",
    supply: { min: 3, max: 6 },
    current: { typical: 130, peak: 220 },
    buses: [],
    pins: [powerIn("V+"), gnd()],
  },
  {
    id: "peristaltic-pump-12v",
    kind: "actuator",
    name: "Peristaltička pumpa 12 V",
    nameEn: "12 V peristaltic pump",
    summary: "Dozira tečnost kroz crevo — količina se meri vremenom rada.",
    summaryEn: "It doses liquid through a tube — the amount is measured by the running time.",
    supply: { min: 12, max: 12 },
    current: { typical: 200, peak: 400 },
    buses: [],
    pins: [powerIn("V+"), gnd()],
  },
  {
    id: "fan-5v",
    kind: "actuator",
    name: "Ventilator 5 V",
    nameEn: "5 V fan",
    summary: "Hlađenje kutije ili Raspberry Pi-ja; troši malo, ali stalno.",
    summaryEn: "Cools an enclosure or a Raspberry Pi; it draws little, but constantly.",
    supply: { min: 5, max: 5 },
    current: { typical: 120, peak: 180 },
    buses: [],
    pins: [powerIn("V+"), gnd()],
  },
];
