/**
 * The parts that stand between a board pin and something it cannot drive.
 *
 * A driver exists because a GPIO pin gives 20 mA at the board's logic level and
 * the load wants amps, or a different voltage, or more pins than the board has.
 * That is why this group is where the pin-expander and level-shifter entries
 * live alongside the motor drivers: they solve the same problem in a different
 * dimension.
 *
 * None of them is `kind: "power"`, even though several take a motor supply —
 * `power` is reserved for parts whose JOB is to produce a rail, and the
 * validator's `board` rule uses that distinction: only a board or a `power` part
 * may have a `power-out` pin. The L298N is where that boundary bites: its
 * on-board regulator really does put out 5 V, but the part is a motor driver, so
 * it stays here and that pin is left off the entry rather than turned into a
 * rail the current budget would then treat as a supply. Anyone powering a board
 * from it is doing something the catalogue declines to bless.
 */

import type { ComponentDef } from "../component.js";
import { gnd, pin, powerIn } from "./pins.js";

const i2cControl: ComponentDef["pins"] = [
  powerIn(),
  gnd(),
  pin("SDA", ["i2c-sda"]),
  pin("SCL", ["i2c-scl"]),
];

export const DRIVERS: readonly ComponentDef[] = [
  // ── Motor drivers ─────────────────────────────────────────────────────────
  {
    id: "l298n",
    kind: "driver",
    name: "L298N",
    summary: "Dvokanalni H-most za dva DC motora; gubi oko 2 V na sebi i greje se.",
    supply: { min: 5, max: 35 },
    current: { typical: 36, peak: 2000 },
    buses: [],
    pins: [
      powerIn("VMS"),
      gnd(),
      pin("ENA", ["digital-in", "pwm"]),
      pin("IN1", ["digital-in"]),
      pin("IN2", ["digital-in"]),
      pin("IN3", ["digital-in"]),
      pin("IN4", ["digital-in"]),
      pin("ENB", ["digital-in", "pwm"]),
      pin("OUT1", ["passive"]),
      pin("OUT2", ["passive"]),
      pin("OUT3", ["passive"]),
      pin("OUT4", ["passive"]),
    ],
  },
  {
    id: "l293d",
    kind: "driver",
    name: "L293D",
    summary: "Isti posao kao L298N u DIP kućištu, ali samo do 600 mA po kanalu.",
    supply: { min: 4.5, max: 36 },
    current: { typical: 16, peak: 600 },
    buses: [],
    pins: [
      powerIn("VCC1"),
      gnd(),
      pin("VCC2", ["power-in"]),
      pin("EN1", ["digital-in", "pwm"]),
      pin("IN1", ["digital-in"]),
      pin("IN2", ["digital-in"]),
      pin("EN2", ["digital-in", "pwm"]),
      pin("IN3", ["digital-in"]),
      pin("IN4", ["digital-in"]),
      pin("OUT1", ["passive"]),
      pin("OUT2", ["passive"]),
      pin("OUT3", ["passive"]),
      pin("OUT4", ["passive"]),
    ],
  },
  {
    id: "a4988",
    kind: "driver",
    name: "A4988",
    summary: "Drajver koračnog motora sa mikrokoracima; struja se podešava trimerom.",
    supply: { min: 8, max: 35 },
    current: { typical: 8, peak: 2000 },
    buses: [],
    pins: [
      powerIn("VMOT"),
      gnd(),
      pin("VDD", ["power-in"]),
      pin("STEP", ["digital-in"]),
      pin("DIR", ["digital-in"]),
      pin("EN", ["digital-in"]),
      pin("MS1", ["digital-in"]),
      pin("MS2", ["digital-in"]),
      pin("MS3", ["digital-in"]),
      pin("1A", ["passive"]),
      pin("1B", ["passive"]),
      pin("2A", ["passive"]),
      pin("2B", ["passive"]),
    ],
    library: "AccelStepper",
  },
  {
    id: "drv8825",
    kind: "driver",
    name: "DRV8825",
    summary: "Kao A4988, ali do 1/32 koraka i veći napon — tiši i precizniji rad.",
    supply: { min: 8.2, max: 45 },
    current: { typical: 8, peak: 2200 },
    buses: [],
    pins: [
      powerIn("VMOT"),
      gnd(),
      pin("VDD", ["power-in"]),
      pin("STEP", ["digital-in"]),
      pin("DIR", ["digital-in"]),
      pin("EN", ["digital-in"]),
      pin("M0", ["digital-in"]),
      pin("M1", ["digital-in"]),
      pin("M2", ["digital-in"]),
      pin("A1", ["passive"]),
      pin("A2", ["passive"]),
      pin("B1", ["passive"]),
      pin("B2", ["passive"]),
    ],
    library: "AccelStepper",
  },
  {
    id: "tmc2209",
    kind: "driver",
    name: "TMC2209",
    summary: "Praktično nečujan drajver koraka; podešava se preko UART-a, ne trimerom.",
    supply: { min: 4.75, max: 29 },
    current: { typical: 10, peak: 2000 },
    buses: [{ kind: "uart" }],
    pins: [
      powerIn("VM"),
      gnd(),
      pin("VIO", ["power-in"]),
      pin("STEP", ["digital-in"]),
      pin("DIR", ["digital-in"]),
      pin("EN", ["digital-in"]),
      pin("PDN", ["uart-tx", "uart-rx"]),
      pin("M1A", ["passive"]),
      pin("M1B", ["passive"]),
      pin("M2A", ["passive"]),
      pin("M2B", ["passive"]),
    ],
  },
  {
    id: "uln2003",
    kind: "driver",
    name: "ULN2003",
    summary: "Sedam Darlingtonovih izlaza sa zaštitnim diodama — pločica uz 28BYJ-48.",
    supply: { min: 5, max: 12 },
    current: { typical: 1, peak: 500 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("IN1", ["digital-in"]),
      pin("IN2", ["digital-in"]),
      pin("IN3", ["digital-in"]),
      pin("IN4", ["digital-in"]),
      pin("OUT1", ["passive"]),
      pin("OUT2", ["passive"]),
      pin("OUT3", ["passive"]),
      pin("OUT4", ["passive"]),
    ],
  },
  {
    id: "tb6600",
    kind: "driver",
    name: "TB6600",
    summary: "Drajver u kutiji za NEMA 23 — do 4 A, sa optički odvojenim ulazima.",
    supply: { min: 9, max: 42 },
    current: { typical: 20, peak: 4000 },
    buses: [],
    pins: [
      powerIn("VCC"),
      gnd(),
      pin("PUL+", ["digital-in"]),
      pin("PUL-", ["passive"]),
      pin("DIR+", ["digital-in"]),
      pin("DIR-", ["passive"]),
      pin("ENA+", ["digital-in"]),
      pin("ENA-", ["passive"]),
      pin("A+", ["passive"]),
      pin("A-", ["passive"]),
      pin("B+", ["passive"]),
      pin("B-", ["passive"]),
    ],
  },
  {
    id: "irf520-module",
    kind: "driver",
    name: "IRF520 MOSFET modul",
    summary: "Jedan kanal za DC potrošač do 24 V — najjednostavniji način da pin gasi motor.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 1, peak: 5000 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("SIG", ["digital-in", "pwm"]),
      pin("V+", ["passive"]),
      pin("V-", ["passive"]),
    ],
  },

  // ── Expanders, shifters and converters ────────────────────────────────────
  {
    id: "level-shifter-4ch",
    kind: "driver",
    name: "Dvosmerni pretvarač nivoa 4 kanala",
    summary: "Spaja 5 V ploču sa 3.3 V modulom — jedini ispravan način, ne otporni delitelj.",
    supply: { min: 1.8, max: 6 },
    current: { typical: 0.01, peak: 0.1 },
    buses: [],
    pins: [
      powerIn("HV"),
      gnd(),
      pin("LV", ["power-in"]),
      pin("HV1", ["digital-in", "digital-out"]),
      pin("HV2", ["digital-in", "digital-out"]),
      pin("HV3", ["digital-in", "digital-out"]),
      pin("HV4", ["digital-in", "digital-out"]),
      pin("LV1", ["digital-in", "digital-out"]),
      pin("LV2", ["digital-in", "digital-out"]),
      pin("LV3", ["digital-in", "digital-out"]),
      pin("LV4", ["digital-in", "digital-out"]),
    ],
  },
  {
    id: "74hc595",
    kind: "driver",
    name: "74HC595",
    summary: "Tri pina daju osam izlaza; više njih se nadovezuje jedan na drugi.",
    supply: { min: 2, max: 6 },
    current: { typical: 0.08, peak: 70 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("DS", ["digital-in"]),
      pin("SHCP", ["digital-in"]),
      pin("STCP", ["digital-in"]),
      pin("OE", ["digital-in"]),
      pin("MR", ["digital-in", "reset"]),
      pin("Q0", ["digital-out"]),
      pin("Q1", ["digital-out"]),
      pin("Q2", ["digital-out"]),
      pin("Q3", ["digital-out"]),
      pin("Q4", ["digital-out"]),
      pin("Q5", ["digital-out"]),
      pin("Q6", ["digital-out"]),
      pin("Q7", ["digital-out"]),
      pin("Q7S", ["digital-out"]),
    ],
  },
  {
    id: "mcp23017",
    kind: "driver",
    name: "MCP23017",
    summary: "Šesnaest GPIO pinova preko I²C; osam adresa, pa i 128 pinova na dve žice.",
    supply: { min: 1.8, max: 5.5 },
    current: { typical: 1, peak: 125 },
    buses: [{ kind: "i2c", addresses: [0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27] }],
    pins: [
      ...i2cControl,
      pin("INTA", ["digital-out", "interrupt"]),
      pin("INTB", ["digital-out", "interrupt"]),
      pin("RESET", ["digital-in", "reset"]),
    ],
    library: "Adafruit MCP23017 Arduino Library",
  },
  {
    id: "pca9685",
    kind: "driver",
    name: "PCA9685",
    summary: "Šesnaest servo kanala sa sopstvenim PWM-om — ploča više ne broji impulse.",
    supply: { min: 2.3, max: 5.5 },
    current: { typical: 10, peak: 25 },
    buses: [{ kind: "i2c", addresses: [0x40, 0x41, 0x42, 0x43] }],
    pins: [...i2cControl, pin("V+", ["power-in"]), pin("OE", ["digital-in"])],
    library: "Adafruit PWM Servo Driver Library",
  },
  {
    id: "ads1115",
    kind: "driver",
    name: "ADS1115",
    summary: "Šesnaestobitni ADC na I²C — ono što Raspberry Pi nema, a UNO ima samo desetobitno.",
    supply: { min: 2, max: 5.5 },
    current: { typical: 0.15, peak: 0.2 },
    buses: [{ kind: "i2c", addresses: [0x48, 0x49, 0x4a, 0x4b] }],
    pins: [
      ...i2cControl,
      pin("A0", ["analog-in"]),
      pin("A1", ["analog-in"]),
      pin("A2", ["analog-in"]),
      pin("A3", ["analog-in"]),
      pin("ALRT", ["digital-out", "interrupt"]),
    ],
    library: "Adafruit ADS1X15",
  },
  {
    id: "mcp4725",
    kind: "driver",
    name: "MCP4725",
    summary: "Pravi analogni izlaz preko I²C — dvanaest bita, za razliku od PWM-a.",
    supply: { min: 2.7, max: 5.5 },
    current: { typical: 0.21, peak: 0.4 },
    buses: [{ kind: "i2c", addresses: [0x60, 0x61, 0x62, 0x63] }],
    pins: [...i2cControl, pin("OUT", ["analog-out"])],
    library: "Adafruit MCP4725",
  },
];
