/**
 * What a circuit reads from.
 *
 * `supply` is the range of the MODULE as it is sold, not of the bare chip, and
 * the difference is the whole reason this column is worth having. An MPU-6050
 * die runs at 2.375–3.46 V; the GY-521 board everyone actually buys puts a
 * regulator in front of it and runs at 3–5 V. Cataloguing the die would make the
 * rules engine refuse the commonest wiring in the hobby, which is a validator
 * that is right about a part nobody owns.
 *
 * `current.peak` is where the gas sensors earn their place: an MQ-series heater
 * draws around 150 mA continuously, so four of them on an UNO's 5 V rail is over
 * budget before anything moves. That is a finding the user should meet on the
 * canvas rather than as a board that browns out.
 */

import type { ComponentDef } from "../component.js";
import { gnd, pin, powerIn } from "./pins.js";

/** VCC + GND + one signal — the shape most three-pin modules have. */
const threePin = (signal: ComponentDef["pins"][number]): ComponentDef["pins"] => [
  powerIn(),
  gnd(),
  signal,
];

/** VCC + GND + SDA + SCL, the I²C breakout everyone solders the same way. */
const i2cPins: ComponentDef["pins"] = [
  powerIn(),
  gnd(),
  pin("SDA", ["i2c-sda"]),
  pin("SCL", ["i2c-scl"]),
];

export const SENSORS: readonly ComponentDef[] = [
  // ── Temperature and humidity ──────────────────────────────────────────────
  {
    id: "dht11",
    kind: "sensor",
    name: "DHT11",
    summary: "Temperatura i vlažnost vazduha, jeftino i sporo — jedno očitavanje u sekundi.",
    supply: { min: 3, max: 5.5 },
    current: { typical: 0.3, peak: 2.5 },
    // A single-wire PROPRIETARY protocol, not Dallas 1-Wire: the timing is the
    // sensor's own and the library bit-bangs it, so it is an ordinary digital
    // pin as far as the wiring is concerned.
    buses: [],
    pins: threePin(pin("DATA", ["digital-in", "digital-out"])),
    library: "DHT sensor library",
  },
  {
    id: "dht22",
    kind: "sensor",
    name: "DHT22 (AM2302)",
    summary: "Isti raspored kao DHT11, ali tačniji i sa opsegom ispod nule.",
    supply: { min: 3.3, max: 6 },
    current: { typical: 1.5, peak: 2.5 },
    buses: [],
    pins: threePin(pin("DATA", ["digital-in", "digital-out"])),
    library: "DHT sensor library",
  },
  {
    id: "ds18b20",
    kind: "sensor",
    name: "DS18B20",
    summary: "Digitalni termometar na 1-Wire magistrali — više njih deli jedan pin.",
    supply: { min: 3, max: 5.5 },
    current: { typical: 1, peak: 1.5 },
    buses: [{ kind: "onewire" }],
    pins: [powerIn("VDD"), gnd(), pin("DQ", ["onewire"])],
    library: "DallasTemperature",
  },
  {
    id: "lm35",
    kind: "sensor",
    name: "LM35",
    summary: "Analogni termometar — 10 mV po stepenu, bez ijedne biblioteke.",
    supply: { min: 4, max: 30 },
    current: { typical: 0.06, peak: 0.1 },
    buses: [],
    pins: threePin(pin("VOUT", ["analog-out"])),
  },
  {
    id: "tmp36",
    kind: "sensor",
    name: "TMP36",
    summary: "Analogni termometar sa pomerenom nulom, pa meri i temperature ispod nule.",
    supply: { min: 2.7, max: 5.5 },
    current: { typical: 0.05, peak: 0.1 },
    buses: [],
    pins: threePin(pin("VOUT", ["analog-out"])),
  },
  {
    id: "bmp280",
    kind: "sensor",
    name: "BMP280",
    summary: "Barometarski pritisak i temperatura; visinu računa iz pritiska.",
    supply: { min: 1.71, max: 3.6 },
    current: { typical: 0.0027, peak: 0.72 },
    buses: [{ kind: "i2c", addresses: [0x76, 0x77] }],
    pins: i2cPins,
    library: "Adafruit BMP280 Library",
  },
  {
    id: "bme280",
    kind: "sensor",
    name: "BME280",
    summary: "Pritisak, temperatura i vlažnost u jednom kućištu — BMP280 sa higrometrom.",
    supply: { min: 1.71, max: 3.6 },
    current: { typical: 0.0034, peak: 0.714 },
    buses: [{ kind: "i2c", addresses: [0x76, 0x77] }],
    pins: i2cPins,
    library: "Adafruit BME280 Library",
  },
  {
    id: "bmp180",
    kind: "sensor",
    name: "BMP180",
    summary: "Stariji barometar, i dalje čest u kompletima.",
    supply: { min: 1.8, max: 3.6 },
    current: { typical: 0.005, peak: 1 },
    buses: [{ kind: "i2c", addresses: [0x77] }],
    pins: i2cPins,
    library: "Adafruit BMP085 Library",
  },
  {
    id: "sht31",
    kind: "sensor",
    name: "SHT31-D",
    summary: "Precizna vlažnost i temperatura, sa grejačem protiv kondenzacije.",
    supply: { min: 2.4, max: 5.5 },
    current: { typical: 1.5, peak: 33 },
    buses: [{ kind: "i2c", addresses: [0x44, 0x45] }],
    pins: i2cPins,
    library: "Adafruit SHT31 Library",
  },
  {
    id: "aht10",
    kind: "sensor",
    name: "AHT10",
    summary: "Jeftina zamena za DHT22 na I²C magistrali.",
    supply: { min: 1.8, max: 3.6 },
    current: { typical: 0.25, peak: 0.98 },
    buses: [{ kind: "i2c", addresses: [0x38] }],
    pins: i2cPins,
    library: "Adafruit AHTX0",
  },
  {
    id: "mlx90614",
    kind: "sensor",
    name: "MLX90614",
    summary: "Beskontaktni infracrveni termometar — meri temperaturu na daljinu.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 1.3, peak: 2 },
    buses: [{ kind: "i2c", addresses: [0x5a] }],
    pins: i2cPins,
    library: "Adafruit MLX90614 Library",
  },
  {
    id: "max6675",
    kind: "sensor",
    name: "MAX6675 + termopar K",
    summary: "Termopar do 1024 °C — jedini iz ove grupe koji ide u peć.",
    supply: { min: 3, max: 5.5 },
    current: { typical: 0.7, peak: 1.5 },
    buses: [{ kind: "spi" }],
    pins: [
      powerIn("VCC"),
      gnd(),
      pin("SO", ["spi-miso"]),
      pin("CS", ["spi-cs"]),
      pin("SCK", ["spi-sck"]),
    ],
    library: "MAX6675 library",
  },

  // ── Distance, motion and orientation ──────────────────────────────────────
  {
    id: "hc-sr04",
    kind: "sensor",
    name: "HC-SR04",
    summary: "Ultrazvučni daljinomer, 2–400 cm; ECHO vraća 5 V i traži delitelj na 3.3 V pločama.",
    supply: { min: 5, max: 5 },
    current: { typical: 15, peak: 20 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("TRIG", ["digital-in"]),
      pin("ECHO", ["digital-out"], 5),
    ],
  },
  {
    id: "vl53l0x",
    kind: "sensor",
    name: "VL53L0X",
    summary: "Laserski daljinomer na principu vremena leta — tačan i na crnim površinama.",
    supply: { min: 2.6, max: 5.5 },
    current: { typical: 19, peak: 40 },
    buses: [{ kind: "i2c", addresses: [0x29] }],
    pins: i2cPins,
    library: "Adafruit VL53L0X",
  },
  {
    id: "gp2y0a21",
    kind: "sensor",
    name: "Sharp GP2Y0A21YK0F",
    summary: "Infracrveni daljinomer 10–80 cm; izlaz je nelinearan i traži tabelu.",
    supply: { min: 4.5, max: 5.5 },
    current: { typical: 30, peak: 40 },
    buses: [],
    pins: threePin(pin("VOUT", ["analog-out"])),
  },
  {
    id: "hc-sr501",
    kind: "sensor",
    name: "HC-SR501 (PIR)",
    summary: "Detektor pokreta po toploti tela; dva trimera podešavaju domet i trajanje.",
    supply: { min: 4.5, max: 20 },
    current: { typical: 0.05, peak: 1 },
    buses: [],
    pins: threePin(pin("OUT", ["digital-out"])),
  },
  {
    id: "mpu6050",
    kind: "sensor",
    name: "MPU-6050 (GY-521)",
    summary: "Akcelerometar i žiroskop u šest osa — osnova svake stabilizacije.",
    supply: { min: 3, max: 5 },
    current: { typical: 3.9, peak: 4.5 },
    buses: [{ kind: "i2c", addresses: [0x68, 0x69] }],
    pins: [...i2cPins, pin("INT", ["digital-out", "interrupt"])],
    library: "Adafruit MPU6050",
  },
  {
    id: "mpu9250",
    kind: "sensor",
    name: "MPU-9250",
    summary: "MPU-6050 plus magnetometar — devet osa, pa i kurs, ne samo nagib.",
    supply: { min: 3, max: 5 },
    current: { typical: 3.7, peak: 4.8 },
    buses: [{ kind: "i2c", addresses: [0x68, 0x69] }],
    pins: [...i2cPins, pin("INT", ["digital-out", "interrupt"])],
  },
  {
    id: "adxl345",
    kind: "sensor",
    name: "ADXL345",
    summary: "Akcelerometar u tri ose sa prepoznavanjem pada i dvostrukog kucanja.",
    // GY-291, the module this is sold as, carries its own regulator and level
    // shifter — the bare die is 2–3.6 V and wiring THAT to 5 V destroys it.
    supply: { min: 3, max: 5 },
    current: { typical: 0.14, peak: 0.145 },
    buses: [{ kind: "i2c", addresses: [0x53, 0x1d] }],
    pins: i2cPins,
    library: "Adafruit ADXL345",
  },
  {
    id: "hmc5883l",
    kind: "sensor",
    name: "HMC5883L",
    summary: "Magnetometar — kompas, ali samo daleko od motora i zvučnika.",
    supply: { min: 3, max: 5 },
    current: { typical: 0.1, peak: 0.64 },
    buses: [{ kind: "i2c", addresses: [0x1e] }],
    pins: i2cPins,
  },
  {
    id: "sw-520d",
    kind: "sensor",
    name: "SW-520D (senzor nagiba)",
    summary: "Kuglica u cevčici — zatvara kolo kad se nagne. Prekidač, ne merač.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 0.5, peak: 1 },
    buses: [],
    pins: threePin(pin("OUT", ["digital-out"])),
  },
  {
    id: "a3144",
    kind: "sensor",
    name: "A3144 (Holov senzor)",
    summary: "Reaguje na magnet — brojanje obrtaja točka i krajnji položaji.",
    supply: { min: 4.5, max: 24 },
    current: { typical: 4, peak: 9 },
    buses: [],
    pins: threePin(pin("OUT", ["digital-out"])),
  },

  // ── Light and colour ──────────────────────────────────────────────────────
  {
    id: "ldr-module",
    kind: "sensor",
    name: "LDR modul",
    summary: "Fotootpornik sa komparatorom — analogna vrednost i podesiv prag.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 1, peak: 3 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("AO", ["analog-out"]),
      pin("DO", ["digital-out"]),
    ],
  },
  {
    id: "bh1750",
    kind: "sensor",
    name: "BH1750",
    summary: "Meri osvetljenost u luksima — pravi merač, ne relativna vrednost.",
    supply: { min: 3, max: 5 },
    current: { typical: 0.12, peak: 0.19 },
    buses: [{ kind: "i2c", addresses: [0x23, 0x5c] }],
    pins: i2cPins,
    library: "BH1750",
  },
  {
    id: "tcs34725",
    kind: "sensor",
    name: "TCS34725",
    summary: "Senzor boje sa belom LED — prepoznaje boju predmeta ispred sebe.",
    supply: { min: 3, max: 5 },
    current: { typical: 0.235, peak: 65 },
    buses: [{ kind: "i2c", addresses: [0x29] }],
    pins: i2cPins,
    library: "Adafruit TCS34725",
  },
  {
    id: "apds9960",
    kind: "sensor",
    name: "APDS-9960",
    summary: "Pokreti rukom, blizina i boja u jednom — bez dodirivanja uređaja.",
    supply: { min: 3, max: 5 },
    current: { typical: 0.79, peak: 100 },
    buses: [{ kind: "i2c", addresses: [0x39] }],
    pins: [...i2cPins, pin("INT", ["digital-out", "interrupt"])],
    library: "Adafruit APDS9960",
  },
  {
    id: "ml8511",
    kind: "sensor",
    name: "ML8511 (UV)",
    summary: "Meri UV zračenje — analogni izlaz srazmeran intenzitetu.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 0.3, peak: 0.4 },
    buses: [],
    pins: [powerIn(), gnd(), pin("OUT", ["analog-out"]), pin("EN", ["digital-in"])],
  },
  {
    id: "flame-sensor",
    kind: "sensor",
    name: "Senzor plamena (IR 760–1100 nm)",
    summary: "Vidi plamen po infracrvenom zračenju; sunčeva svetlost ga zavarava.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 15, peak: 20 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },

  // ── Gas and air ───────────────────────────────────────────────────────────
  // Every MQ module heats a filament: ~150 mA, continuously, from the moment it
  // is powered. On an UNO's 5 V rail that is most of the budget for one sensor,
  // and it is why these entries matter to the current check more than to anything
  // else in this file.
  {
    id: "mq-2",
    kind: "sensor",
    name: "MQ-2",
    summary: "Zapaljivi gasovi i dim; grejač troši oko 150 mA sve vreme.",
    supply: { min: 5, max: 5 },
    current: { typical: 150, peak: 165 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },
  {
    id: "mq-3",
    kind: "sensor",
    name: "MQ-3",
    summary: "Alkoholne pare — isti grejač i isti račun za struju kao MQ-2.",
    supply: { min: 5, max: 5 },
    current: { typical: 150, peak: 165 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },
  {
    id: "mq-7",
    kind: "sensor",
    name: "MQ-7",
    summary: "Ugljen-monoksid; traži naizmenično grejanje na 5 V i 1.4 V da bi bio tačan.",
    supply: { min: 5, max: 5 },
    current: { typical: 150, peak: 165 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },
  {
    id: "mq-135",
    kind: "sensor",
    name: "MQ-135",
    summary: "Opšti kvalitet vazduha — pokazuje trend, ne ppm bez kalibracije.",
    supply: { min: 5, max: 5 },
    current: { typical: 150, peak: 165 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },
  {
    id: "ccs811",
    kind: "sensor",
    name: "CCS811",
    summary: "eCO₂ i TVOC na I²C — greje se, pa prvih dvadesetak minuta laže.",
    supply: { min: 1.8, max: 3.6 },
    current: { typical: 26, peak: 30 },
    buses: [{ kind: "i2c", addresses: [0x5a, 0x5b] }],
    pins: [...i2cPins, pin("INT", ["digital-out", "interrupt"]), pin("WAK", ["digital-in"])],
    library: "Adafruit CCS811",
  },
  {
    id: "sgp30",
    kind: "sensor",
    name: "SGP30",
    summary: "TVOC i eCO₂ sa ugrađenom kalibracijom koja se čuva između paljenja.",
    supply: { min: 3, max: 5 },
    current: { typical: 48, peak: 60 },
    buses: [{ kind: "i2c", addresses: [0x58] }],
    pins: i2cPins,
    library: "Adafruit SGP30",
  },

  // ── Water, soil and flow ──────────────────────────────────────────────────
  {
    id: "soil-moisture-capacitive",
    kind: "sensor",
    name: "Kapacitivni senzor vlažnosti zemlje",
    summary: "Ne korodira kao otporni — jedini koji preživi sezonu u saksiji.",
    supply: { min: 3.3, max: 5.5 },
    current: { typical: 5, peak: 8 },
    buses: [],
    pins: threePin(pin("AOUT", ["analog-out"])),
  },
  {
    id: "rain-sensor",
    kind: "sensor",
    name: "Senzor kiše",
    summary: "Ploča sa provodnim stazama i komparator; staze s vremenom oksidiraju.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 15, peak: 20 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },
  {
    id: "water-level",
    kind: "sensor",
    name: "Senzor nivoa vode",
    summary: "Meri dokle je potopljen; nije za piću vodu jer otpušta bakar.",
    supply: { min: 3, max: 5 },
    current: { typical: 20, peak: 25 },
    buses: [],
    pins: threePin(pin("S", ["analog-out"])),
  },
  {
    id: "yf-s201",
    kind: "sensor",
    name: "YF-S201 (protokomer)",
    summary: "Turbina sa Holovim senzorom — impulsi se broje, protok se računa.",
    supply: { min: 5, max: 18 },
    current: { typical: 15, peak: 20 },
    buses: [],
    pins: threePin(pin("SIG", ["digital-out", "interrupt"])),
  },
  {
    id: "tds-meter",
    kind: "sensor",
    name: "TDS merač",
    summary: "Ukupne rastvorene materije u vodi; vrednost zavisi od temperature.",
    supply: { min: 3.3, max: 5.5 },
    current: { typical: 3, peak: 6 },
    buses: [],
    pins: threePin(pin("A", ["analog-out"])),
  },

  // ── Input the user touches ────────────────────────────────────────────────
  {
    id: "ttp223",
    kind: "sensor",
    name: "TTP223 (kapacitivni taster)",
    summary: "Dodir kroz staklo ili plastiku — nema pokretnih delova da se pokvare.",
    supply: { min: 2, max: 5.5 },
    current: { typical: 0.0055, peak: 0.5 },
    buses: [],
    pins: threePin(pin("SIG", ["digital-out"])),
  },
  {
    id: "ky-040",
    kind: "sensor",
    name: "KY-040 (rotacioni enkoder)",
    summary: "Okreće se beskonačno i klikće; CLK i DT zajedno daju smer.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 1, peak: 3 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("CLK", ["digital-out", "interrupt"]),
      pin("DT", ["digital-out"]),
      pin("SW", ["digital-out"]),
    ],
  },
  {
    id: "joystick-module",
    kind: "sensor",
    name: "Džojstik modul",
    summary: "Dva potenciometra i taster — dve analogne ose i jedan klik.",
    supply: { min: 3.3, max: 5 },
    current: { typical: 5, peak: 10 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("VRX", ["analog-out"]),
      pin("VRY", ["analog-out"]),
      pin("SW", ["digital-out"]),
    ],
  },
  {
    id: "keypad-4x4",
    kind: "sensor",
    name: "Membranska tastatura 4×4",
    summary: "Osam pinova, bez napajanja — redovi i kolone se skeniraju iz koda.",
    buses: [],
    // No power pin at all: the matrix is passive and the board drives it, so it
    // states neither a supply nor a draw. The ground rule does not fire for the
    // same reason — which is the correct reading rather than an exemption.
    pins: [
      pin("R1", ["digital-in", "digital-out"]),
      pin("R2", ["digital-in", "digital-out"]),
      pin("R3", ["digital-in", "digital-out"]),
      pin("R4", ["digital-in", "digital-out"]),
      pin("C1", ["digital-in", "digital-out"]),
      pin("C2", ["digital-in", "digital-out"]),
      pin("C3", ["digital-in", "digital-out"]),
      pin("C4", ["digital-in", "digital-out"]),
    ],
    library: "Keypad",
  },

  // ── Electrical measurement ────────────────────────────────────────────────
  {
    id: "acs712-20a",
    kind: "sensor",
    name: "ACS712 20 A",
    summary: "Meri struju Holovim efektom, galvanski odvojeno od kola koje meri.",
    supply: { min: 4.5, max: 5.5 },
    current: { typical: 10, peak: 13 },
    buses: [],
    pins: threePin(pin("OUT", ["analog-out"])),
  },
  {
    id: "ina219",
    kind: "sensor",
    name: "INA219",
    summary: "Napon, struja i snaga preko I²C — četiri adrese, do šesnaest na magistrali.",
    supply: { min: 3, max: 5.5 },
    current: { typical: 1, peak: 1 },
    buses: [{ kind: "i2c", addresses: [0x40, 0x41, 0x44, 0x45] }],
    pins: i2cPins,
    library: "Adafruit INA219",
  },

  // ── Sound ─────────────────────────────────────────────────────────────────
  {
    id: "ky-038",
    kind: "sensor",
    name: "KY-038 (senzor zvuka)",
    summary: "Mikrofon sa komparatorom — prag, ne jačina; za „pljesak“ je dovoljan.",
    supply: { min: 4, max: 6 },
    current: { typical: 4, peak: 8 },
    buses: [],
    pins: [powerIn(), gnd(), pin("AO", ["analog-out"]), pin("DO", ["digital-out"])],
  },
  {
    id: "max9814",
    kind: "sensor",
    name: "MAX9814",
    summary: "Mikrofonski pretpojačavač sa automatskim pojačanjem — za merenje jačine.",
    supply: { min: 2.7, max: 5.5 },
    current: { typical: 3, peak: 4 },
    buses: [],
    pins: [powerIn(), gnd(), pin("OUT", ["analog-out"]), pin("GAIN", ["digital-in"])],
  },

  // ── Identification and time ───────────────────────────────────────────────
  {
    id: "hx711",
    kind: "sensor",
    name: "HX711 + merna ćelija",
    summary: "24-bitni pojačavač za vagu; dva pina, ali protokol je sopstveni.",
    supply: { min: 2.6, max: 5.5 },
    current: { typical: 1.5, peak: 1.6 },
    buses: [],
    pins: [
      powerIn(),
      gnd(),
      pin("DT", ["digital-out"]),
      pin("SCK", ["digital-in"]),
    ],
    library: "HX711",
  },
  {
    id: "ds3231",
    kind: "sensor",
    name: "DS3231 (RTC)",
    summary: "Sat sa baterijom i temperaturnom kompenzacijom — vreme preživi nestanak struje.",
    supply: { min: 2.3, max: 5.5 },
    current: { typical: 0.11, peak: 0.65 },
    buses: [{ kind: "i2c", addresses: [0x68] }],
    pins: [...i2cPins, pin("SQW", ["digital-out", "interrupt"])],
    library: "RTClib",
  },
  {
    id: "tsop38238",
    kind: "sensor",
    name: "TSOP38238 (IR prijemnik)",
    summary: "Prima signal daljinskog upravljača na 38 kHz.",
    supply: { min: 2.5, max: 5.5 },
    current: { typical: 0.7, peak: 1.5 },
    buses: [],
    pins: threePin(pin("OUT", ["digital-out"])),
    library: "IRremote",
  },
];
