// Token build: tokens/*.json → dist/css/tokens.css + gen/index.ts.
// Zero-dependency by deliberate deviation from ADR-006's Style Dictionary
// mention — see docs/deviations.md entry DEV-001.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));

const global = read("tokens/global.json");
const themes = [read("tokens/themes/dan.json"), read("tokens/themes/noc.json")];

/** Resolve "{color.gold.600}" references against the global token tree. */
function resolveRef(value) {
  const match = /^\{([\w.]+)\}$/.exec(value);
  if (!match) return value;
  const resolved = match[1]
    .split(".")
    .reduce((node, key) => node?.[key], global);
  if (typeof resolved !== "string") {
    throw new Error(`Unresolvable token reference: ${value}`);
  }
  return resolved;
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Flatten a nested token group into [cssVarName, value] pairs. */
function flatten(node, prefix) {
  return Object.entries(node).flatMap(([key, value]) =>
    typeof value === "object"
      ? flatten(value, `${prefix}-${kebab(key)}`)
      : [[`${prefix}-${kebab(key)}`, value]],
  );
}

// --- CSS ---------------------------------------------------------------
const primitiveGroups = { font: global.font, radius: global.radius, space: global.space, motion: global.motion };
const primitiveVars = Object.entries(primitiveGroups).flatMap(([group, node]) =>
  flatten(node, `--nx-${kebab(group)}`),
);

const block = (selector, vars) =>
  `${selector} {\n${vars.map(([name, v]) => `  ${name}: ${v};`).join("\n")}\n}\n`;

let css = "/* Generated by @nexus/tokens — do not edit. Source: tokens/*.json */\n\n";
css += block(":root", primitiveVars);
for (const { theme, semantic } of themes) {
  const vars = Object.entries(semantic).map(([key, value]) => [
    `--nx-${kebab(key)}`,
    resolveRef(value),
  ]);
  css += "\n" + block(`:root[data-theme="${theme}"], [data-theme="${theme}"]`, vars);
}

mkdirSync(join(root, "dist/css"), { recursive: true });
writeFileSync(join(root, "dist/css/tokens.css"), css);

// --- TypeScript --------------------------------------------------------
const resolvedThemes = Object.fromEntries(
  themes.map(({ theme, semantic }) => [
    theme,
    Object.fromEntries(
      Object.entries(semantic).map(([key, value]) => [key, resolveRef(value)]),
    ),
  ]),
);

const ts = `// Generated by @nexus/tokens build.mjs — do not edit.
export const global = ${JSON.stringify(global, null, 2)} as const;

export const themes = ${JSON.stringify(resolvedThemes, null, 2)} as const;

export type ThemeName = keyof typeof themes;
export type SemanticToken = keyof (typeof themes)["dan"];

/** CSS custom-property name for a semantic token, e.g. cssVar("textMuted") === "--nx-text-muted". */
export function cssVar(token: SemanticToken): string {
  return "--nx-" + token.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}
`;

mkdirSync(join(root, "gen"), { recursive: true });
writeFileSync(join(root, "gen/index.ts"), ts);

console.log(
  `tokens: ${primitiveVars.length} primitives, ${themes.length} themes → dist/css/tokens.css, gen/index.ts`,
);
