// Token build: tokens/*.json → dist/css/tokens.css + gen/index.ts.
// Zero-dependency by deliberate deviation from ADR-006's Style Dictionary
// mention — see docs/deviations.md entry DEV-001.
//
// `node build.mjs` regenerates both artifacts. `node build.mjs --check` compares
// the two already in this tree against what these sources produce and writes
// nothing; the block at the foot of this file says what that is for.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));

const global = read("tokens/global.json");
const themes = [read("tokens/themes/dan.json"), read("tokens/themes/noc.json")];

/** Resolve "{color.gold.600}" references against the global token tree. */
function resolveRef(value) {
  const match = /^\{([\w.]+)\}$/.exec(value);
  if (!match) return value;
  const resolved = match[1]
    .split(".")
    .reduce((node, key) => node?.[key], global);
  if (typeof resolved !== "string") {
    throw new Error(`Unresolvable token reference: ${value}`);
  }
  return resolved;
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Flatten a nested token group into [cssVarName, value] pairs. */
function flatten(node, prefix) {
  return Object.entries(node).flatMap(([key, value]) =>
    typeof value === "object"
      ? flatten(value, `${prefix}-${kebab(key)}`)
      : [[`${prefix}-${kebab(key)}`, value]],
  );
}

// --- Accents -------------------------------------------------------------
// Ids come from dan.json's key order (both themes are required to match it
// exactly) so the picker's fixed order is a single source of truth, not a
// hardcoded list drifting from the JSON.
const accentIds = Object.keys(themes[0].accents);
for (const { theme, accents } of themes) {
  const ids = Object.keys(accents);
  if (ids.length !== accentIds.length || ids.some((id, i) => id !== accentIds[i])) {
    throw new Error(`Theme "${theme}" accent ids [${ids}] do not match dan's [${accentIds}]`);
  }
}

const resolvedAccents = Object.fromEntries(
  themes.map(({ theme, accents }) => [
    theme,
    Object.fromEntries(
      Object.entries(accents).map(([id, slots]) => [
        id,
        Object.fromEntries(Object.entries(slots).map(([slot, value]) => [slot, resolveRef(value)])),
      ]),
    ),
  ]),
);

// "zlato" is the default accent — it must never visually drift from the
// theme's own semantic accent/accentSoft/accentStrong.
for (const { theme, semantic } of themes) {
  const zlato = resolvedAccents[theme].zlato;
  const semanticAccent = ["accent", "accentSoft", "accentStrong"].map((key) => resolveRef(semantic[key]));
  if (JSON.stringify(Object.values(zlato)) !== JSON.stringify(semanticAccent)) {
    throw new Error(
      `Theme "${theme}": "zlato" accent (${JSON.stringify(zlato)}) must equal semantic accent/accentSoft/accentStrong (${JSON.stringify(semanticAccent)})`,
    );
  }
}

// --- CSS ---------------------------------------------------------------
// `layout` joins the primitives for the same reason the others are here: these
// are values the whole app must agree on, and the app had been disagreeing.
// Every rail width, every column floor and every reading measure was written
// inline at its call site, so nothing could state what a pane is ALLOWED to
// shrink to — which is how the notes editor ended up at 75px on the window
// size this app itself enforces as its minimum. See `docs/STATUS.md` §5 B.
//
// `layer` is the same argument about a DIFFERENT axis, and it arrived last
// because a stacking order is invisible until two things collide. The app used
// seven positive z-index values — 1, 2, 3, 4, 5, 20, 50, 60, 70 — every one
// chosen at its own call site, so the only statement of the ladder was prose:
// five comments in `notes.css` alone re-listed it by hand, and one of them
// still cited a layer 40 that no rule in the tree had carried for months.
// Two names may share a number (`figure` and a pinned header are both 1) and
// that is the point: a token is a name for an INTENT, so moving one intent
// later cannot silently drag the other with it.
const primitiveGroups = {
  font: global.font,
  radius: global.radius,
  space: global.space,
  motion: global.motion,
  layout: global.layout,
  layer: global.layer,
};
const primitiveVars = Object.entries(primitiveGroups).flatMap(([group, node]) =>
  flatten(node, `--nx-${kebab(group)}`),
);

const block = (selector, vars) =>
  `${selector} {\n${vars.map(([name, v]) => `  ${name}: ${v};`).join("\n")}\n}\n`;

let css = "/* Generated by @nexus/tokens — do not edit. Source: tokens/*.json */\n\n";
css += block(":root", primitiveVars);
for (const { theme, semantic } of themes) {
  const vars = Object.entries(semantic).map(([key, value]) => [
    `--nx-${kebab(key)}`,
    resolveRef(value),
  ]);
  // Swatch vars let the picker show all 8 dots regardless of the active accent.
  for (const id of accentIds) {
    vars.push([`--nx-swatch-${id}`, resolvedAccents[theme][id].accent]);
  }
  css += "\n" + block(`:root[data-theme="${theme}"], [data-theme="${theme}"]`, vars);

  // One override block per accent (including "zlato", so the attribute value
  // is always valid) — picking an accent just adds [data-accent] to <html>.
  for (const id of accentIds) {
    const { accent, accentSoft, accentStrong } = resolvedAccents[theme][id];
    const overrideVars = [
      ["--nx-accent", accent],
      ["--nx-accent-soft", accentSoft],
      ["--nx-accent-strong", accentStrong],
    ];
    const selector = `:root[data-theme="${theme}"][data-accent="${id}"], [data-theme="${theme}"][data-accent="${id}"]`;
    css += "\n" + block(selector, overrideVars);
  }
}

// --- TypeScript --------------------------------------------------------
const resolvedThemes = Object.fromEntries(
  themes.map(({ theme, semantic }) => [
    theme,
    Object.fromEntries(
      Object.entries(semantic).map(([key, value]) => [key, resolveRef(value)]),
    ),
  ]),
);

const ts = `// Generated by @nexus/tokens build.mjs — do not edit.
export const global = ${JSON.stringify(global, null, 2)} as const;

export const themes = ${JSON.stringify(resolvedThemes, null, 2)} as const;

export type ThemeName = keyof typeof themes;
export type SemanticToken = keyof (typeof themes)["dan"];

/** CSS custom-property name for a semantic token, e.g. cssVar("textMuted") === "--nx-text-muted". */
export function cssVar(token: SemanticToken): string {
  return "--nx-" + token.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

export const ACCENT_IDS = ${JSON.stringify(accentIds, null, 2)} as const;
export type AccentId = (typeof ACCENT_IDS)[number];

/**
 * Every accent's three slots, per theme, resolved to colour strings.
 *
 * The CSS carries the same values as \`--nx-swatch-<id>\`, but only the ACTIVE
 * theme's set is readable from the document at any moment. A consumer that
 * needs a specific theme's palette — the canvas does, because Excalidraw
 * applies its own dark transform and must therefore be fed light-theme colours
 * in both themes — cannot get it from \`getComputedStyle\`. It gets it here.
 */
export const accents = ${JSON.stringify(resolvedAccents, null, 2)} as const;
`;

// --- Emit -----------------------------------------------------------------
// Both artifacts are built in full before either is written, so that `--check`
// below can compare them with no write path reachable from it. A check that ran
// between the two writes would have already repaired half of the staleness it
// was asked to report.
const outputs = [
  { label: "dist/css/tokens.css", file: join(root, "dist/css/tokens.css"), text: css },
  { label: "gen/index.ts", file: join(root, "gen/index.ts"), text: ts },
];

/**
 * `--check` is the freshness half of this build, and until now nothing in this
 * repository asked it. Both artifacts are BUILD OUTPUTS that are committed to
 * nobody — `.gitignore` ignores `packages/tokens/gen/` and `packages/tokens/dist/`
 * — so a stale one is invisible to review, to git and to every other gate in the
 * tree.
 *
 * It is not invisible to the product. `gen/index.ts` is what `tsc` compiles into
 * the `dist/ts` declarations the whole monorepo typechecks against, and
 * `dist/css/tokens.css` is what `apps/desktop`, `apps/web` and `apps/gallery`
 * import as `@nexus/tokens/css`. So in a working tree where somebody edited
 * `tokens/*.json` and then ran neither `pnpm build` nor `pnpm typecheck` — an
 * electron-vite dev server, `pnpm --filter @nexus/desktop shots` and a bare
 * `vitest` run all reach the artifact directly — the app renders, the tests
 * assert and the sweep photographs the OLD tokens, while `check:contrast` and
 * `check:tokens` read the JSON and report on the new ones. Two answers to one
 * question, and the one the user meets is the wrong one.
 *
 * ABSENT IS NOT STALE, which is why an artifact that has never been generated
 * here exits 0: nothing was built, so nothing can be out of date, and a gate
 * that failed there could not run before a build — which is where every static
 * gate in this repository sits in CI. Absence is REPORTED rather than passed
 * over in silence, so "compared two files and agreed" and "compared nothing"
 * never read the same.
 *
 * LINE ENDINGS are compared out. Both artifacts are written here with LF and
 * nothing checks them out, so this guards a future rather than repairing a
 * present: promote either to a committed file and `* text=auto` hands a Windows
 * checkout CRLF, at which point a byte comparison answers "stale" to a file that
 * is exactly current. `generate-licences.mjs` paid for that lesson on a
 * committed artifact; a carriage return is not a token, and the question here is
 * whether the artifact still describes the sources.
 *
 * Determinism is what makes any of this sound: same sources in, byte-identical
 * artifacts out, because nothing below observes the clock, the platform or the
 * filesystem's directory order.
 *
 * `scripts/tokens-build.test.mjs` keeps it falsifiable: it mutates one source in
 * a scratch copy of this package and demands the exact complaint below.
 */
const withoutLineEndings = (text) => text.replaceAll("\r\n", "\n");

/**
 * The first line at which the artifact on disk differs from the one these
 * sources produce, as `{ line, expected, found }` — or `null` when they agree.
 * The FIRST difference and not a diff: the repair is to run the build, and
 * "line 27: expected 12px, found 11px" already tells a reader whether this is
 * the edit they forgot to rebuild or something they did not do at all.
 */
function firstDifference(produced, disk) {
  const mine = withoutLineEndings(produced).split("\n");
  const theirs = withoutLineEndings(disk).split("\n");
  for (let index = 0; index < Math.max(mine.length, theirs.length); index += 1) {
    if (mine[index] === theirs[index]) continue;
    return {
      line: index + 1,
      expected: mine[index] ?? "(end of file)",
      found: theirs[index] ?? "(end of file)",
    };
  }
  return null;
}

if (process.argv.includes("--check")) {
  const compared = [];
  const absent = [];
  const stale = [];
  for (const { label, file, text } of outputs) {
    if (!existsSync(file)) {
      absent.push(label);
    } else {
      const difference = firstDifference(text, readFileSync(file, "utf8"));
      if (difference === null) compared.push(label);
      else stale.push({ label, difference });
    }
  }

  for (const { label, difference } of stale) {
    console.error(`check-tokens-build: ${label} does not match what tokens/*.json produces.`);
    console.error(
      `  line ${difference.line}: expected \`${difference.expected}\`, ` +
        `found \`${difference.found}\``,
    );
  }
  if (stale.length > 0) {
    console.error("  Run `pnpm --filter @nexus/tokens build` and let it rewrite the artifact:");
    console.error("  nothing but this build regenerates it, and it is not a file to edit.");
    process.exit(1);
  }

  if (compared.length > 0) {
    console.log(
      `check-tokens-build: ${compared.join(" and ")} ${compared.length === 1 ? "is" : "are"} what ` +
        `tokens/*.json produces (${primitiveVars.length} primitives, ${themes.length} themes, ` +
        `${accentIds.length} accents).`,
    );
  }
  for (const label of absent) {
    console.log(
      `check-tokens-build: ${label} has not been generated in this tree, so there is nothing to compare.`,
    );
  }
  process.exit(0);
}

for (const { file, text } of outputs) {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
}

console.log(
  `tokens: ${primitiveVars.length} primitives, ${themes.length} themes, ${accentIds.length} accents → dist/css/tokens.css, gen/index.ts`,
);
