// Token build: tokens/*.json → dist/css/tokens.css + gen/index.ts.
// Zero-dependency by deliberate deviation from ADR-006's Style Dictionary
// mention — see docs/deviations.md entry DEV-001.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));

const global = read("tokens/global.json");
const themes = [read("tokens/themes/dan.json"), read("tokens/themes/noc.json")];

/** Resolve "{color.gold.600}" references against the global token tree. */
function resolveRef(value) {
  const match = /^\{([\w.]+)\}$/.exec(value);
  if (!match) return value;
  const resolved = match[1]
    .split(".")
    .reduce((node, key) => node?.[key], global);
  if (typeof resolved !== "string") {
    throw new Error(`Unresolvable token reference: ${value}`);
  }
  return resolved;
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Flatten a nested token group into [cssVarName, value] pairs. */
function flatten(node, prefix) {
  return Object.entries(node).flatMap(([key, value]) =>
    typeof value === "object"
      ? flatten(value, `${prefix}-${kebab(key)}`)
      : [[`${prefix}-${kebab(key)}`, value]],
  );
}

// --- Accents -------------------------------------------------------------
// Ids come from dan.json's key order (both themes are required to match it
// exactly) so the picker's fixed order is a single source of truth, not a
// hardcoded list drifting from the JSON.
const accentIds = Object.keys(themes[0].accents);
for (const { theme, accents } of themes) {
  const ids = Object.keys(accents);
  if (ids.length !== accentIds.length || ids.some((id, i) => id !== accentIds[i])) {
    throw new Error(`Theme "${theme}" accent ids [${ids}] do not match dan's [${accentIds}]`);
  }
}

const resolvedAccents = Object.fromEntries(
  themes.map(({ theme, accents }) => [
    theme,
    Object.fromEntries(
      Object.entries(accents).map(([id, slots]) => [
        id,
        Object.fromEntries(Object.entries(slots).map(([slot, value]) => [slot, resolveRef(value)])),
      ]),
    ),
  ]),
);

// "zlato" is the default accent — it must never visually drift from the
// theme's own semantic accent/accentSoft/accentStrong.
for (const { theme, semantic } of themes) {
  const zlato = resolvedAccents[theme].zlato;
  const semanticAccent = ["accent", "accentSoft", "accentStrong"].map((key) => resolveRef(semantic[key]));
  if (JSON.stringify(Object.values(zlato)) !== JSON.stringify(semanticAccent)) {
    throw new Error(
      `Theme "${theme}": "zlato" accent (${JSON.stringify(zlato)}) must equal semantic accent/accentSoft/accentStrong (${JSON.stringify(semanticAccent)})`,
    );
  }
}

// --- CSS ---------------------------------------------------------------
const primitiveGroups = { font: global.font, radius: global.radius, space: global.space, motion: global.motion };
const primitiveVars = Object.entries(primitiveGroups).flatMap(([group, node]) =>
  flatten(node, `--nx-${kebab(group)}`),
);

const block = (selector, vars) =>
  `${selector} {\n${vars.map(([name, v]) => `  ${name}: ${v};`).join("\n")}\n}\n`;

let css = "/* Generated by @nexus/tokens — do not edit. Source: tokens/*.json */\n\n";
css += block(":root", primitiveVars);
for (const { theme, semantic } of themes) {
  const vars = Object.entries(semantic).map(([key, value]) => [
    `--nx-${kebab(key)}`,
    resolveRef(value),
  ]);
  // Swatch vars let the picker show all 8 dots regardless of the active accent.
  for (const id of accentIds) {
    vars.push([`--nx-swatch-${id}`, resolvedAccents[theme][id].accent]);
  }
  css += "\n" + block(`:root[data-theme="${theme}"], [data-theme="${theme}"]`, vars);

  // One override block per accent (including "zlato", so the attribute value
  // is always valid) — picking an accent just adds [data-accent] to <html>.
  for (const id of accentIds) {
    const { accent, accentSoft, accentStrong } = resolvedAccents[theme][id];
    const overrideVars = [
      ["--nx-accent", accent],
      ["--nx-accent-soft", accentSoft],
      ["--nx-accent-strong", accentStrong],
    ];
    const selector = `:root[data-theme="${theme}"][data-accent="${id}"], [data-theme="${theme}"][data-accent="${id}"]`;
    css += "\n" + block(selector, overrideVars);
  }
}

mkdirSync(join(root, "dist/css"), { recursive: true });
writeFileSync(join(root, "dist/css/tokens.css"), css);

// --- TypeScript --------------------------------------------------------
const resolvedThemes = Object.fromEntries(
  themes.map(({ theme, semantic }) => [
    theme,
    Object.fromEntries(
      Object.entries(semantic).map(([key, value]) => [key, resolveRef(value)]),
    ),
  ]),
);

const ts = `// Generated by @nexus/tokens build.mjs — do not edit.
export const global = ${JSON.stringify(global, null, 2)} as const;

export const themes = ${JSON.stringify(resolvedThemes, null, 2)} as const;

export type ThemeName = keyof typeof themes;
export type SemanticToken = keyof (typeof themes)["dan"];

/** CSS custom-property name for a semantic token, e.g. cssVar("textMuted") === "--nx-text-muted". */
export function cssVar(token: SemanticToken): string {
  return "--nx-" + token.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

export const ACCENT_IDS = ${JSON.stringify(accentIds, null, 2)} as const;
export type AccentId = (typeof ACCENT_IDS)[number];

/**
 * Every accent's three slots, per theme, resolved to colour strings.
 *
 * The CSS carries the same values as \`--nx-swatch-<id>\`, but only the ACTIVE
 * theme's set is readable from the document at any moment. A consumer that
 * needs a specific theme's palette — the canvas does, because Excalidraw
 * applies its own dark transform and must therefore be fed light-theme colours
 * in both themes — cannot get it from \`getComputedStyle\`. It gets it here.
 */
export const accents = ${JSON.stringify(resolvedAccents, null, 2)} as const;
`;

mkdirSync(join(root, "gen"), { recursive: true });
writeFileSync(join(root, "gen/index.ts"), ts);

console.log(
  `tokens: ${primitiveVars.length} primitives, ${themes.length} themes, ${accentIds.length} accents → dist/css/tokens.css, gen/index.ts`,
);
