/**
 * A device's name: what it may contain, and how it is sealed.
 *
 * ─── Why the validator lives here and not in `pairing.ts` ───────────────────
 *
 * It was written there, for the consent screen, and it is the highest-stakes
 * string in the product — a peer-supplied value rendered to a human who is about
 * to authorise a key release. `devices.name_ciphertext` is now written by a
 * second path (the master-key mint), and a rule this careful, copied by hand
 * into a second file, is a rule that will diverge in one of them. So it moved,
 * and `pairing.ts` imports it.
 *
 * ─── What the seal is under, and what it therefore is not ───────────────────
 *
 * A subkey of **MK**, derived by HKDF with its own info label rather than MK
 * itself. Every direct use of a root key is a place where two purposes can meet
 * on one (key, nonce) pair; `wrap.ts` derives subkeys from its KEK for the same
 * reason and this follows it.
 *
 * That choice has a consequence worth stating rather than discovering: **a
 * browser cannot read a device name.** The web app never holds MK — it receives
 * per-profile content keys through pairing, and `key_wraps_desktop_only` refuses
 * it `mk_under_kwrap` outright — so a web device list can show when a device was
 * added and what platform it is, and not what it is called. That is recorded in
 * `docs/STATUS.md`; it is a gap in a feature nobody has built yet, not a defect
 * here, and the alternative (a second account-wide key handed to browsers) is a
 * branch of the key hierarchy that should not be invented speculatively.
 *
 * ─── What the AAD binds, and the one thing it cannot ────────────────────────
 *
 * The account and the platform. Not the device id: `devices.id` is generated by
 * the database in the same statement that stores this ciphertext, so it does not
 * exist when the seal is made. The honest limit that leaves: an operator can
 * permute name ciphertexts among one account's own devices of the same platform,
 * and every client will accept the result. That is a display defect and nothing
 * more — the name a human is shown while authorising a pairing comes through the
 * handshake transcript in `pairing.ts`, which binds it, and never from this
 * column.
 */

import { base64urlToBytes, bytesToBase64url, encodeStruct, utf8, zeroize } from "./bytes.js";
import { SyncCryptoError } from "./errors.js";
import { AEAD_KEY_BYTES, AEAD_NONCE_BYTES, type CryptoPort } from "./port.js";

/**
 * A device name has to fit on a consent screen and must not be a payload.
 *
 * The ceiling also has to keep the sealed form inside `devices_name_len`
 * (17–1024 bytes). `String.length` counts UTF-16 code units, and a code unit is
 * at most three UTF-8 bytes (a surrogate pair is two units for four bytes, so
 * astral characters are cheaper per unit, not dearer), which caps the worst case
 * at 120 × 3 + 16 = 376 bytes. The floor holds at the other end: one character
 * is at least one byte, so 1 + 16 = 17 exactly. A larger bound here would
 * produce a name the client accepts and the database refuses — the arithmetic is
 * pinned in `device-name.test.ts` against both database numbers.
 */
export const MAX_DEVICE_NAME_LENGTH = 120;

/**
 * Every Unicode control (`Cc`: C0, C1, DEL) and every Unicode FORMAT character
 * (`Cf`), which is the category the interesting attacks live in.
 *
 * A device name is rendered to a human who is about to authorise a key release.
 * It is the single highest-stakes string in the product, so what it may contain
 * is worth being exact about rather than approximate.
 *
 * `Cc` alone — a newline, a carriage return — only lets a peer break the layout.
 * `Cf` is the category that lets it change the MEANING:
 *
 *  - U+202E RIGHT-TO-LEFT OVERRIDE and friends (U+202A-U+202E, U+2066-U+2069)
 *    render the remainder of the string backwards, so the reassuring half of a
 *    sentence can be placed where the alarming half will be read.
 *  - U+200B ZERO WIDTH SPACE, U+FEFF and U+2060 WORD JOINER are invisible: they
 *    let two different names look identical, so "the device I recognise" and the
 *    one actually receiving the keys need not be the same device.
 *
 * Written as a Unicode property escape rather than a hand-kept range list,
 * because a hand-kept list is how U+202E was missed the first time: the comment
 * named "a bidi-adjacent control character" and the regex covered only C0, C1
 * and DEL, which is none of them.
 *
 * The known false positive, accepted deliberately: `Cf` also holds the Arabic
 * number signs (U+0600-U+0605) and U+00AD SOFT HYPHEN, so a device name
 * legitimately containing one is refused. Refusing a rare valid name costs a
 * rename; accepting an override on a consent dialog costs the keys.
 */
const UNRENDERABLE_CHARACTERS = /[\p{Cc}\p{Cf}]/u;

/**
 * Bounded, visible, and free of anything unrenderable.
 *
 * The bound is not tidiness. An unbounded string from a peer that ends up in a
 * dialog is how a „device name" becomes a paragraph of instructions telling the
 * user to click Allow.
 *
 * "Visible" is a separate condition from "non-empty", and it is the one that
 * matters: `"   "` is non-empty, carries no control characters, and puts a
 * blank line on the dialog exactly where the identity of the thing receiving
 * the keys is supposed to be. A consent screen that names nobody is worse than
 * no consent screen, because it still collects a click.
 */
export function isAcceptableDeviceName(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length <= MAX_DEVICE_NAME_LENGTH &&
    value.trim().length > 0 &&
    !UNRENDERABLE_CHARACTERS.test(value)
  );
}

export function assertDeviceName(value: string): void {
  if (!isAcceptableDeviceName(value)) {
    throw new TypeError(
      `A device name must be 1–${MAX_DEVICE_NAME_LENGTH} visible characters, with no control ` +
        "or format characters.",
    );
  }
}

/** The two values `devices.platform` admits. */
export type DevicePlatform = "desktop" | "web";

/** Everything the seal is bound to. See the header for what is missing and why. */
export interface DeviceNameContext {
  readonly userId: string;
  readonly platform: DevicePlatform;
}

/** The sealed name, in the shape the `devices` row stores: unpadded base64url. */
export interface SealedDeviceName {
  /** 24 bytes, fresh for every seal. */
  readonly nonce: string;
  /** The name under AEAD, followed by the 16-byte tag. */
  readonly ciphertext: string;
}

const DEVICE_NAME_AAD_LABEL = "nexus/sync/device-name/v1";
const DEVICE_NAME_KEY_INFO = utf8("nexus/sync/device-name/key/v1");

/** HKDF over a full-entropy master key legitimately skips the extract salt. */
const EMPTY_SALT = new Uint8Array(0);

async function deviceNameKey(port: CryptoPort, masterKey: Uint8Array): Promise<Uint8Array> {
  if (masterKey.length !== AEAD_KEY_BYTES) {
    throw new TypeError(`Master key must be ${AEAD_KEY_BYTES} bytes, got ${masterKey.length}`);
  }
  return port.hkdfSha256({
    ikm: masterKey,
    salt: EMPTY_SALT,
    info: DEVICE_NAME_KEY_INFO,
    outputBytes: AEAD_KEY_BYTES,
  });
}

function deviceNameAad(context: DeviceNameContext): Uint8Array {
  if (context.userId.length === 0) {
    throw new TypeError("DeviceNameContext.userId must not be empty.");
  }
  return encodeStruct([
    utf8(DEVICE_NAME_AAD_LABEL),
    utf8(context.userId),
    utf8(context.platform),
  ]);
}

/** Seals a device name for exactly this account and platform. */
export async function sealDeviceName(
  port: CryptoPort,
  masterKey: Uint8Array,
  context: DeviceNameContext,
  name: string,
): Promise<SealedDeviceName> {
  assertDeviceName(name);
  const key = await deviceNameKey(port, masterKey);
  try {
    const nonce = port.randomBytes(AEAD_NONCE_BYTES);
    const ciphertext = await port.aeadSeal({
      key,
      nonce,
      plaintext: utf8(name),
      aad: deviceNameAad(context),
    });
    return { nonce: bytesToBase64url(nonce), ciphertext: bytesToBase64url(ciphertext) };
  } finally {
    zeroize(key);
  }
}

/**
 * Opens a sealed device name, or throws `SyncCryptoError`.
 *
 * `context` must be what the SERVER said about this row, not what the caller
 * wishes it were — rebuilding the AAD from the server's own claim is what makes
 * a moved ciphertext a visible failure instead of a silent success.
 *
 * The result is NOT re-validated against {@link isAcceptableDeviceName}. It
 * authenticated under a key only this account holds, so it is the account's own
 * name for its own machine, and refusing to display a name the account chose —
 * after it decrypted — would be inventing a second, later opinion about a rule
 * that was already applied at the seal. Callers rendering it are still
 * responsible for treating it as text rather than markup.
 */
export async function openDeviceName(
  port: CryptoPort,
  masterKey: Uint8Array,
  context: DeviceNameContext,
  sealed: SealedDeviceName,
): Promise<string> {
  const nonce = base64urlToBytes(sealed.nonce);
  const ciphertext = base64urlToBytes(sealed.ciphertext);
  if (nonce === null || nonce.length !== AEAD_NONCE_BYTES || ciphertext === null) {
    throw new SyncCryptoError(
      "device-name/malformed",
      "A sealed device name must carry a 24-byte nonce and base64url ciphertext.",
    );
  }

  const key = await deviceNameKey(port, masterKey);
  try {
    const plaintext = await port.aeadOpen({
      key,
      nonce,
      ciphertext,
      aad: deviceNameAad(context),
    });
    if (plaintext === null) {
      throw new SyncCryptoError(
        "device-name/aead-failed",
        "This device name did not authenticate: wrong account key, edited bytes, or a row " +
          "the server moved between devices.",
      );
    }
    return new TextDecoder().decode(plaintext);
  } finally {
    zeroize(key);
  }
}
